### ISSUE TITLE
Update AWS deployment docs w details on how to connect pachctl

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1028]
Right now if you follow the guide and do the k8s.io setup script, k8s gets setup fine, but you need to do more to setup pachctl.

We've seen 2 methods. Either you 

a) replace the `NodePort` type on the pachd service with `LoadBalancer` (which spins up an ELB) or you 

b) need to set an ingress rule (new custom TCP rule / allow 30650 / etc) for the security groups for the VMs (I did it on the k8s minions ... maybe you want to do it on the master node?)

And then you can connect by doing:

```
ADDRESS=ec2-35-160-15-48.us-west-2.compute.amazonaws.com:30650 pachctl version
```

Where that hostname is either the public hostname of the ELB or one of the VMs whose sec group you updated. One thing to consider, is this will have to play nice w our new replacement solution for `pachctl port-forward`

**Comment by sjezewski** [comment]
@msteffen and @JoeyZwicker I know you looked at AWS deployment after I ran through it. Have we made these updates to the docs?

**Comment by msteffen** [comment]
We never updated the docs because I never committed the code that got rid of `port-forward`. At the time, that was because I couldn't easily connect to the docker registry we were running, and I didn't think I could push the change until that worked. (and, if you *do* use port-forward, you don't need the ingress rule)

Now that we've gotten rid of the internal docker registry, though, I'll revisit that change. I agree that we need to mention the ingress rule if we want to get rid of port-forward

**Comment by sjezewski** [comment]
Is there an open issue for getting rid of port-forward? I remember we talked about it, but I can't seem to find it.

I'd like to reference this issue in that one (the one about removing port forwarding), and push this issue out of 1.3

**Comment by msteffen** [comment]
There was a PR but no issue. Just created one here: https://github.com/pachyderm/pachyderm/issues/1169

**Comment by sjezewski** [comment]
Closing this, as our AWS deployment method + docs have all changed. Any doc updates from the port forwarding update can be captured in #1169
