### ISSUE TITLE
Update pipeline doesn't work if only the container changed

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1074]
If you change the code in your container image and do `pachctl update-pipeline -f pipeline.json` it should rerun your pipeline. Right now it doesn't because the job's it would create hash to the same thing as jobs from previous runs so they don't get created. The fix should be pretty simple, just use the pipeline's version in the hashing scheme.

**Comment by JonathanFraser** [comment]
We've decided to manage this simply by specify tags on the images, the tag on the image name both forces the hash to change, as well as ensures that you don't have any ambiguity on the what an image name is referencing.

**Comment by derekchiang** [comment]
Yeah, it's not unreasonable to make this non-fix and require the user to explicitly use image tags if they want the pipeline to rerun.

**Comment by jdoliner** [comment]
@JonathanFraser that's a very good practice generally.

I think we should still fix this bug though, the cause is something we didn't intend to have happen and I think it could quite possibly manifest in other ways.

**Comment by JonathanFraser** [comment]
my argument is whether or not it's a bug. It comes down to whether update pipeline should be an idempotent operation. If it is idempotent then every thing must be specified in the manifest, including code versions vis a vis docker tags. If you don't care about idempotence and want the pipeline to be redeployed on every single operation, then ok this need to be changed. I'm more in the idempotence camp. However, if you would like to have a value which forces redeploy but doesn't fiddle with docker tags then perhaps add a  'version' field to the manifest file and include it in the hash.

**Comment by dwhitena** [comment]
+1 for a way to re-run pipelines without having to explicitly specify tags, or at least having a way to do this without having to restart pachyderm.  This would naturally be something I would want as a data scientist iteratively improving/developing an analysis.  It's not so much that I couldn't use tags to solve the problem, but I have to exert extra effort in tagging, and keeping track of tags for something that I just want to rerun with an update to the image.

**Comment by JonathanFraser** [comment]
@dwhitena versioning your data is pointless if you aren't versioning your code

**Comment by dwhitena** [comment]
I think there are two issues at play here:

1. Creating truly reproducible analyses
2. A workflow for developing an analysis

On the first point, @JonathanFraser no doubt code should be versioned.  However, in my opinion, "tags" for images are not sufficient for reproducible analysis.  Tagging is relying on a human to use good tags.  Similar to having to remember the naming of files like `that_analysis_from_last_week_when_it_worked.py`.  Further, tagging does not tie a specific image to a specific run of a pipeline.   For true reproducible analysis, images used during each run of a pipeline should be versioned or tracked with that pipeline run, but I don't think we should rely on humans to do that versioning. 

On the second point, my thought is that, during development (i.e,. before production use), it is reasonable to want to re-run a pipeline with a newly created image, without having to constantly be creating new tags.  

However, good points made by all here.  Just wanted to throw my thoughts into the mix, as this is something that has come up frequently as I work through examples.

**Comment by JonathanFraser** [comment]
I agree leaving humans to name things generally works out poorly, just look at any typical code base :confounded:  .  
Our build system automatically tags images with the git commit so in this case tags do uniquely identify a docker image and you don't have to worry about those pesky humans.
However, if you have a tight iterate,build,test loop that does not involve a git commit then I can see the issues at play.  A specific version field in the pipeline manifest, with a conveinence flag on pachctl  to auto increment version would probably allow for the desired cli semantics without removing the idempotent nature of the underlying api request. 

As an aside, I think it would be neat to try and put a build system into a pachyderm pipeline with your code being revisioned controlled in a pachyderm repo. That way committing too the repo re-runs your build and automatically re-runs affected pipelines.

**Comment by dwhitena** [comment]
@JonathanFraser Yes, that type of tagging system is very nice.  And, yes, the main case I'm thinking about is when you are just trying to get something working with a lot of tweaking to, e.g., a new model.

Maybe @jdoliner @derekchiang could comment about the other ideas.  I think the issue of correlating a specific image with a specific run of a pipeline is important.  Once someone updates the pipeline spec, it seems that confusion could be created around which image was used on which runs of a pipeline.  I know I have talked with @jdoliner and others options for versioning images within Pachyderm, but there are open questions there.

**Comment by JonathanFraser** [comment]
In order match up any two things (such as a pachyderm job and an docker image)  together you need a unique identifier. AFAICT, there are two identifiers for a docker image, the repo:tag and the image ID. Image ID provided the fundamental ground truth because as of, I believe, 1.10 the image ID is a hash of the contents which provides a unique signature of the files. The way I see it the image ID is analogous to a git commit id, while the docker tag is analogous to a git tag, with latest being a rough approximation of master. 

There's a problem here though, in git you can checkout a version based on its commit id so that's sufficient to track but that's not true for docker. There is no way retrieve a docker image by its ID AFAIK. In docker you must pull based on docker name:tag. So if you don't treat that pair as unique you can wind up in some sticky race conditions (which is true not just for pachyderm).

Lets say you have a set of pipelines deployed and they have run some commits, then you push a new image do your docker repo with a tag you used previously. You then push new data and for some reason your node(s) need to re-pull the image (you added a new node or the job didn't run on that node previously, etc). Then you have this new data running with new code and you didn't perform an update-pipeline. Obviously this is not what we want.

So scratch what I previously said about adding a version field, it won't fix the scenario described above.  The way I see it, there are three possible options to avoid this.

1) Pipelines are deployed following best practices using tags which do uniquely identify the image either via commit tags or version numbers (v1.2.4). 

2) your code exists as a pachyderm repo and you never really bump the container for the pipeline. You initiate a code redeploy by making a commit to a pachyderm repo. 

3) Pachyderm manages its own docker repository (which it kind of is, but now it has to be backed up for recovery purposes) and when a user updates a pipeline(s) pachyderm pulls the image(s) down from the remote repo and into its repository. When it does so it name mangles the image to give it a unique name:tag. Then any jobs issues by pachyderm go back to this internal repository using the mangled/unique name. 

Three seems like alot of fuddling and the increased complexity would probably introduce more bugs than it solves. Moreover the added repository starts to create additional maintenance concerns.  Two probably sounds better than it would work in practice given how pachyderm shards and manages files. One, is a known good solution which is already the convention for using docker.

**Comment by dwhitena** [comment]
Great comments @JonathanFraser.  Don't have much to add.  However, I did realize that the `--update-images` flag on `create-pipeline` or `update-pipeline` solves my development workflow issue.  So it seems that this is no longer a problem for me.

**Comment by jdoliner** [comment]
> Pachyderm just needs to cache the digest and submit the jobs with the digest instead of the user provided container tag.

This is something we're going to look into doing in the future. It gets a bit hairy though because you might have an image that can only pulled using some pull secrets that pachd doesn't have access to. We have a fix right now that fixes the worst manifestation of this problem where users will call `update-pipeline` and have archived output and now jobs will run at all which is really confusing. This system should work exactly as expected if you use tags which uniquely identify the images or digests. As you point out there are still some thorny edge cases when using `latest` we'll see what we can do to further harden this system in the next release.

**Comment by JonathanFraser** [comment]
> It gets a bit hairy though because you might have an image that can only pulled using some pull secrets that pachd doesn't have access to. 

This lack of pulling can happen now with new pipelines. I don't see how this is unique to ensuring pipeline have a dedicated providence.

**Comment by jdoliner** [comment]
Alright I think after a lot of discussion we're going to not fix this for now since it's unclear that the proposed fix would be considered an improvement. The biggest source of trouble here was the fact that our content addressed jobs could get deceived into thinking we'd already computed something when we hadn't actually computed it. We'll find a way to address that directly instead.
