### ISSUE TITLE
Fail to collect metrics for big workloads

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1101]
From the logs of a user with ~50GB of data:

```
2016-11-23T01:21:23Z ERROR Error Fetching Metrics:gorethink: Grouped data over size limit `100000`.  Try putting a reduction (like `.reduce` or `.count`) on the end. in: 
r.Object("Repos", r.DB("pachyderm_pfs").Table("Repos").Count(), "Commits", r.DB("pachyderm_pfs").Table("Commits").Count(), "ArchivedCommits", r.DB("pachyderm_pfs").Table("Commits").Filter({Archived=true}).Count(), "CancelledCommits", r.DB("pachyderm_pfs").Table("Commits").Filter({Cancelled=true}).Count(), "Files", r.DB("pachyderm_pfs").Table("Diffs").Group("Path").Ungroup().Count(), "Jobs", r.DB("pachyderm_pps").Table("JobInfos").Count(), "Pipelines", r.DB("pachyderm_pps").Table("PipelineInfos").Count())
```

The culprit seems to be this line: https://github.com/pachyderm/pachyderm/blob/master/src/server/pkg/metrics/metrics.go#L149

Although the lines that use `Filter` have huge performance implications as well, since using `Filter` without using secondary indexes requires a full table scan.

I think we should:

1. Remove/rewrite queries that don't scale well (e.g. `GroupBy`, `Filter`).  For instance, is the number of unique paths necessarily a more interesting metrics than simply the number of diffs (i.e. `Table("Diffs").Count()`)?  Personally I'd actually be more interested in the latter.
2. Make metrics collection interval longer.  The current value is [15 secs](https://github.com/pachyderm/pachyderm/blob/c4cf3c939c1c6de95f2228fb07aa228985921dff/src/server/pkg/metrics/segment.go#L11).  Do we need to collect metrics that frequently?

**Comment by sjezewski** [comment]
I'm happy to make the interval longer.

And I agree -- we don't want to adversely effect memory, esp since that will be a bottleneck for other reasons.

But - the point of metrics is to learn what the state of the system is at scale. So specifically for big workloads, I want as much information as I can to understand how the system is being used and is creaking.

I also think that understanding file counts and diff counts could be valuable. It may be interesting to see that ratio and how that ratio differs across users' clusters.

For now, if this solves an issue, I'm ok w the fix. But please open a new issue to add these metrics back in a more efficient manner.

![image](https://cloud.githubusercontent.com/assets/597953/20684296/1f4d97c2-b564-11e6-8b18-079ed4393a80.png)

**Comment by derekchiang** [comment]
^this comment above was meant for #1104
