### ISSUE TITLE
Design a workflow for continuously pushing append-only files

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1127]
Imagine you have a log file that keeps growing.  You would like to store it in `/pfs`.  You would also like to make a commit every day.  Ideally, each of those commits would include only the new portion of the file that was added in the last day.

Right now there isn't an obvious way to do it.  If you naively use `put-file log.txt` once a day, you end up with the a file in PFS that's the original file repeating many times, because `put-file` simply appends.  You will have to manually keep track of the "diff" between the files and only use `put-file` on the diffs.

So the issue here is that there isn't a good workflow for continuously pushing append-only files into PFS.

**Comment by JoeyZwicker** [comment]
I agree that this could be better, but there are a few options. They could start-commit each day, stream the logs lines to pachyderm as they come in and finish-commit at the end of each day. Alternatively, if you wanted the log file to live in Pachyderm and in the application, having a different log file each day could be ok too. Neither solves exactly this use case though.

**Comment by dwhitena** [comment]
I experienced a similar logical blocker on a workflow.  I want to commit a new state of a JSON file (e.g., the output of an API) where certain fields change each day.  This then should trigger the update of some metrics in a corresponding output file in the output repo.  

This doesn't work (as expected) when you naively `put-file` the file, of the same name, because it simply appends.  My workaround flow for now is to:

1. start commit
2. delete the old file
3. put the new file
4. finish commit.

This along with setting `"overwrite": true` in the pipeline spec producing the behavior I want, I think.  However, this wasn't necessarily intuitive and maybe I'm still doing things that have unfortunate consequences.  Still to be seen.

**Comment by sjezewski** [comment]
There is an analogous use case here w database dumps. A periodic dump can accumulate in size quickly. For database adapters we recommend using a db cursor. These are recommendations in theory. We haven't built one of these ourselves.

Marking as stale until we a use case from a paying user.

**Comment by jdoliner** [comment]
I think this is pretty well supported by `put-file --overwrite` now too.
