### ISSUE TITLE
Rethink/remove input method aliases

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1128]
Right now we have three aliases `map`, `reduce`, and `repo` for input methods.  However, it's usually not immediately clear what they mean.  It's especially confusing if you have used Hadoop MapReduce before since the terms mean somewhat different things here in Pachyderm.

Once we revamped our input partitioning model (which is partially described in #1108 I believe), we should get rid of the aliases.

**Comment by JoeyZwicker** [comment]
Just to clarify, it's that the aliases were incorrect, but they were a bit hard to reason about. I this scenario we had a CSV file with column headers and even though the pipeline operation was multiplying each value in a column by 3, which "felt" like a `map` to the user, we needed to use `reduce`because the header was needed to be scene by each container so the whole file had to be kept together. 

As JD mentioned, this would also be a `reduce` in Hadoop because of the headers. It probably would have been better to omit the headers from the file and retain that information another way.

**Comment by sjezewski** [comment]
I believe this is outdated since the cross/union refactor
