### ISSUE TITLE
'create-pipeline' + 'delete-pipeline' + 'create pipeline' doesn't work by default

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#1220]
I apologize if this is already recorded somewhere, nor am I sure what the expected behavior actually is (or if this is even a bug), but I wanted to write it down before I forgot:

if you run `pachctl create-pipeline foo -f foo.json` and then `pachctl delete-pipeline foo` and then `pachctl create-pipeline foo -f foo.json` (so roughly equivalent to update-pipeline), you get `repo foo exists`.

**Comment by JoeyZwicker** [comment]
Update pipeline isn't exactly the same and create plus delete plus create pipeline again because the initial create also makes an output repo of the same name. The second create then can't create that repo but the current repo foo might contain data from the previous instantiation. We don't want to wipe that data (necessarily) so the create-pipeline fails. This is expected behavior although I think there was a different open issue discussing having delete pipeline automatically remove its output repo, but that's not the current implementation.

**Comment by jdoliner** [comment]
I can't track down the issue you're talking about but I think deleting the output directory as part of `delete-pipeline` seems pretty reasonable to me. Seeing as `delete-pipeline` should be the inverse of `create-pipeline` which is what's creating the repo. This should be super simple to do as well, I'm going to schedule it for 1.4.

**Comment by jdoliner** [comment]
`delete pipeline` now deletes its output repo.
