### ISSUE TITLE
Pulling latest image from Docker Hub not working consistently 

### ISSUE THREAD

**Issue by TimVen** [pachyderm/pachyderm#1274]
We've had an issue where Pachyderm hasn't been pulling the latest image from the docker registry and not updating. We fixed this only by creating a new image and pulling that.

Is there a 'imagePullPolicy'  in Pachyderm to force an update when needed if this happens?

**Comment by JoeyZwicker** [comment]
Hi @TimVen. Pachyderm won't pull a new image from DockerHub if it already has an image with the same name/tag locally. Even though you've updated the image on DockerHub, Pachyderm doesn't actually know that because the name is the same. 

We recommend statically tagging each image with the hash of the image instead of using dynamic tags like "latest". Another important reason to not use dynamic tags is for versioning your images and tracking provenance. If you use a dynamic tag, you won't be able to tell exactly which version of the image (your code) was used to transform a particular piece of data and you lose some reproducibility. 

If you sue Pachyderm's `--push-images` flag with`update pipeline`, we'll automatically push your new locally built image to the registry and update the pipeline spec with the new image hash tag. 

That should solve your problem here, but definitely let us know if that's not what you want. We don't have an `imagePullPolicy`, but would consider adding one if there was a clear use case for it.

**Comment by sjezewski** [comment]
stale
