### ISSUE TITLE
Passing parameters to Pachyderm pipelines example

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1275]
Lots of users ask about this.  What is the best way to pass in parameters?  Should I have a repo just for parameters?  How do I distribute parameters throughout the pipeline?

**Comment by jdoliner** [comment]
I think a Repo for parameters makes the most sense. In my mind parameters are just a different kind of data that pipelines might want to consume so putting it in its own repo makes a lot of sense. Putting it in the same repo as other data would be kind of weird because you might wind up with a pod that only sees parameters which doesn't sound particularly useful.

**Comment by dwhitena** [comment]
I'm going to close this for now.  I think that it's low priority and can already be deduced in many places.
