### ISSUE TITLE
How to troubleshoot tcp i/o timeouts on operations like put-file

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [pachyderm/pachyderm#1286]
Following [this example](http://pachyderm.readthedocs.io/en/stable/getting_started/beginner_tutorial.html), there are a couple commands that reference a remote file from raw.githubusercontent.com, namely `put-file` and `create-pipeline`.  These don't work for me, occasionally showing a UDP i/o timeout hitting the Kube DNS, and occasionally a TCP i/o timeout hitting something else.  There aren't a lot of logs, `-v` for verbose output doesn't show any more than the one line of output, and it seems like the `pachd` and other containers are fairly bare bones and so it's hard to `kubectl exec` and try some commands or start an interactive shell session.

If I download the files locally first, then pass the local path to the file to the `-f` flag of the `put-file` or `create-pipeline` commands, it works fine.

What is the best way to go about debugging this?  I'm running on Kubernetes on AWS, and using t2 instance types so it may be that the instances just don't have good network performance, though I'm able to `curl` the files from other containers deployed to the same Kubernetes.

Here's an example of what the TCP timeouts look like:

```
$ pachctl put-file data master sales -c -f https://raw.githubusercontent.com/pachyderm/pachyderm/v1.3.2/doc/examples/fruit_stand/set2.txt -v
Get https://raw.githubusercontent.com/pachyderm/pachyderm/v1.3.2/doc/examples/fruit_stand/set2.txt: dial tcp: i/o timeout
```

And here's the UDP timeout:

```
$ pachctl put-file data master sales -c -f https://raw.githubusercontent.com/pachyderm/pachyderm/v1.3.2/doc/examples/fruit_stand/set2.txt -v
Get https://raw.githubusercontent.com/pachyderm/pachyderm/v1.3.2/doc/examples/fruit_stand/set2.txt: dial tcp: lookup raw.githubusercontent.com on 100.64.0.10:53: dial udp 100.64.0.10:53: i/o timeout
```

That IP is the `clusterIP` of the `kube-dns` service.

**Comment by jdoliner** [comment]
Hi @Amit-PivotalLabs, sorry you're hitting this.
When I've seen issues like this most of the time it's been due to something being wonky about the cluster's DNS setup. In this case it looks like either pods can't connect to the kube-dns server or when they do connect it's unresponsive. However the fact that you're able to curl the files from other pods that are deployed suggests that it does work in some cases so maybe pachd is doing something different than curl. Could you try execing into the container and using dig to check that the DNS server works? You can do this with:

```
dig raw.githubusercontent.com @100.64.0.10:53
```

Depending on what that returns we'll have an idea of whether or not the cluster DNS is functioning correctly. You may be able to sidestep this issue by bypassing kube-dns and just using a public dns server. This can be done by passing `--cluster_dns=8.8.8.8` (or some other dns server you like) to the kubelet on startup.

**Comment by Amit-PivotalLabs** [comment]
Hi Joe,

Thanks for your response.  Any time I've tried to exec commands like dig,
or interactive shell sessions, inside the pachd container, I get errors
like this:

```
$ kubectl --kubeconfig ~/.kube/config.dev exec pachd-1q744 env
rpc error: code = 2 desc = "oci runtime error: exec failed: exec: \"env\":
executable file not found in $PATH"
```

This is why I mentioned previously that debugging via `kubectl exec` was
difficult.  Am I missing something basic?

**Comment by jdoliner** [comment]
Sorry I didn't explain this better.
That's to be expected from the `pachd` pod because it's built `FROM scratch` so it doesn't have `exec` or anything else in it. It makes for a quick deployment but unfortunately prevents stuff like this. The rethink pod would probably be a good target for this since it's a more standard ubuntu container (you will probably need to `apt-get dig`). We're operating under the assumption that if the `pachd` pod is having trouble talking to DNS then the rethink one probably is as well.

**Comment by Amit-PivotalLabs** [comment]
Thanks @jdoliner 

I had actually noticed `pachd` was built `FROM scratch` and so tried in the rethinkDB container, but didn't have dig, and was having trouble apt-getting.  I got further now. I ran `apt-get update` several times, it got hung resolving DNS, resolved DNS locally, and `echo "IP HOST" >> /etc/hosts` a bunch until it worked.  For the record, here's what I needed:

```
72.14.189.19 download.rethinkdb.com
128.101.240.215 security.debian.org
128.31.0.66 httpredir.debian.org
128.180.2.105 debian.cc.lehigh.edu
128.30.2.26 debian.csail.mit.edu
69.90.151.252 deb.vanvps.com
64.50.233.100 ftp-nyc.osuosl.org
128.112.18.21 mirror.math.princeton.edu
```

Was then able to `apt-get install dnsutils` and I can dig things just fine with `@8.8.8.8` but not with the Kube DNS IP.  Will dig more into why not later.

**Comment by jdoliner** [comment]
> Will dig more into why not later.
I see what you did there...

Overall I'd say this is good news since it's pretty strong confirmation that the issue lies with the DNS server. In terms of fixing the problem, as far as pachyderm is concerned there's no need for `kube-dns`. It's used as a method of service discovery in k8s for some types of services but we don't use it. So if it's easy for you to just pass a different dns server for the cluster (`--cluster_dns`) I'd do that.

If that doesn't work then my best guess is that the dns server is in some way resource starved due to the machine size. What does `kubectl get all --namespace=kube-system` get you?

**Comment by Amit-PivotalLabs** [comment]
`kubectl logs`, `kubectl get all`, ssh'ing and and running `htop` or `free` didn't lead to anything interesting.  I wasn't able to reproduce `wget` working, and

```
kubectl run kill \
  --image=tutum/dnsutils \
  --attach  \
  --command -- dig +notcp pachd.dev.svc.cluster.local @100.64.0.10
```

couldn't even connect to the server.

Gave up and just `kubectl scale`d the Kube DNS RC down to 0 and back up to 2, and now things are working (i.e. I can `put-file` with a remote URL).

Thanks for your help!
