### ISSUE TITLE
Pachyderm client (golang client) does not reconnect if pachd restarts

### ISSUE THREAD

**Issue by Southclaws** [pachyderm/pachyderm#1302]
This is a problem I encountered while `pachd` was crashing, I'm still investigating why `pachd` was crashing and I'll open that in a separate issue once I have enough info.

I have a Go app that uses the Pachyderm Go client API, it's connected to `pachd` and everything's running smoothly. Then, `pachd` crashes for some arbitrary reason and is brought back up by the replication controller - `pachd` now has a different IP in the cluster and thus, the Go client starts logging that it's disconnected:

```
grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.0.0.11:650: i/o timeout"; Reconnecting to {10.0.0.11:650 <nil>}
```
At this point, pachyderm is back up and running fine but my app is still trying to connect to the old IP because - from my understanding and some discussion on Slack - Pachyderm doesn't use the Kubernetes DNS to contact `pachd` it uses the environment variable `PACHD_PORT_650_TCP_ADDR` at [this line](https://github.com/pachyderm/pachyderm/blob/805e63e561a9eab4a9c52216f228f0f421714f3b/src/client/client.go#L80) which, is still pointing to the old IP address.

The main problem here is that my app is just sitting there trying to reconnect to the old Pachyderm IP, and from what I can tell it does this indefinitely until `kubectl delete pod myapp` comes along and triggers the RS to recreate it. This would be even more annoying if `myapp` was replicated 1000 times! What I expect Kubernetes pods to do in situations like this is to terminate with errors and let the RS (or RC) recreate them in the hope that they will initialise successfully and continue doing their job.

There are two ends to this problem and two solutions I can see:

1. Server
   - Once `pachd` goes down, the app is forever trying to connect to the old pod which will never happen. The only solution is to restart the app and receive the new IP to connect to.
   - The solution here would be to use Kubernetes DNS so the client is actually just contacting `pachd.default.svc.cluster.local` and the `pachd` service can handle redirection.
2. Client
   - On the client, the `grpc` error that is logged when the client loses connection isn't really useful outside of debugging. I don't think the app should be allowed to attempt reconnects forever.
   - The solution for this would be to somehow get the client to `panic` however, it is my understanding that `panic`ing inside a library is bad practice for Golang and the library should communicate problems back to the user/host app and let it handle the problem so another method could be to send an error to an error channel which some watchdog in the app can monitor and trigger a `panic` there, either immediately or after `x` retries.
   For now, I've implemented a hacky heartbeat repeating timer that just does a ListRepo to check the connection, if that fails my app does a `panic` and restarts.

I should also mention I'm no Golang expert! So I'm not entirely familiar with best practices of error handling in situations like this, so there's likely much better solutions than the ones I have proposed!

**Comment by jdoliner** [comment]
I actually think our current client should support this pretty well. Afaik we don't need to do anything special to get DNS resolution to work for kubernetes. If DNS is enabled in your cluster then the pachd service should be accessible as `pachd.default.svc.cluster.local` (or whatever namespace you've got it deployed in instead of `default`). Then you can just do:

```
client.NewFromAddress("pachd.default.svc.cluster.local")
```

to connect to the server. We also have a method on the client called `KeepConnected` that basically automates the hacky heartbeat you were doing. You probably want to run it with:

```
go c.KeepConnected(nil)
```

Let me know if this satisfies your needs. One thing we could maybe add would be a `HealthCheck` method to check if a connection is healthy. So you can use it and exit if it errors. That's generally a very sane strategy in distributed systems, if the thing you depend on isn't up just crash. There's no particular need for panics to do this and generally I like to avoid panics since they're pretty unfriendly. The `HealthCheck` method would probably just return a normal error and you could exit when you got that back.

**Comment by Southclaws** [comment]
Ah, I actually completely forgot to use the `NewFromAddress` function, that will solve the problem.

However, I was under the impression that since `NewInCluster` is designed to be used in a Kubernetes cluster, it should internally use the domain method since that's the more robust and reliable solution for when services go down and come back up. Is there any specific reason that `NewInCluster` uses a constant IP address instead of a flexible kube-DNS string?

I didn't notice that `KeepConnected` method in the docs (my bad!) that looks like a super useful solution for this. I think in the future, as the documentation matures and more examples of how to work with the Go client API, things like this should be covered so others don't make the same mistakes I do!

Anyway, that `HealthCheck` idea does sound useful and that would be very useful in future when I can imagine more parts of our system will be interacting with Pachyderm but what you've responded with is good for now and will definitely ensure stability in our system so I suppose you could go ahead and close this, or at least mark it as low priority. Thanks!

**Comment by jdoliner** [comment]
> Is there any specific reason that NewInCluster uses a constant IP address instead of a flexible kube-DNS string?

There's a few reasons I'd prefer not to make this the default behavior.

1. Not all kubernetes clusters have dns servers but all of them support service discovery through environment variables. I'd prefer to optimize for reliability with this method.
2. DNS can be kind of finicky and exhibit some weird behaviors like caching old addresses. Which makes me uneasy about having it be the default.
3. It doesn't really save much typing, `NewInCluster()` vs `NewFromAddress(...)` isn't that big of a change.

We could add a `NewInClusterDNS` method which would just call `NewFromAddress` with the right address. To me that doesn't seem like it's really saving enough typing to be useful and it would be kind of inflexible since it would have to hardcode the namespace which might change.

**Comment by JonathanFraser** [comment]
so the service IP is stable in kubernetes. If you perform a dns lookup in the kube for anything thats not a headless service you get the service IP and the kubernetes fabric load balances automatically in the backend. The IP address of pachd should not change in the kubernetes cluster so long as everything is set up correctly.

**Comment by jdoliner** [comment]
I think we have good support for everything in this issue. As @JonathanFraser pointed out (ages ago) using the IP address is just as stable as using a DNS entry.
