### ISSUE TITLE
Atomically updating multiple pipelines at once

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1305]
This situation was proposed by a user who wants to use one giant pipeline spec for a many of his pipelines and update them all at the same time (since they use the same image). Let me know if I'm misunderstanding what would be going on here. 

If a user does `update-pipeline -f multiple_pipelines.json` (or passes multiple `-f` flags), these are sent as multiple `update-pipeline` requests. Since we don't have multi-document atomic updates (until v1.4 and we move from Rethink to etcd), could this cause some clobbering of commits? The first update would go through, archiving everything downstream and kicking off a bunch of jobs and new commits -- then the second one comes in and everything downstream gets "archived" again including the newly created commits which might be partially done. I assume that first batch of jobs/commits run to completion as opposed to terminating when the 2nd update request comes in. 

This means that if a user updates 10 pipelines at once, their cluster will reprocess every affected commit in the system 10 times, putting a huge amount of load on the cluster, right?

**Comment by jdoliner** [comment]
I don't think this is much of an issue.
There's a very small window when new jobs could get kicked off on the order of milliseconds. It's unlikely that jobs could complete in that time and cause unnecessary processing, you probably can't even launch a container in that time. If they did it would be because the jobs are very, very lightweight in which case it's not such a big deal that we did some extra processing.
