### ISSUE TITLE
Better error handling for pachctl put-file

### ISSUE THREAD

**Issue by Seth-Karlo** [pachyderm/pachyderm#1329]
If a flag is missing from `pachctl put-file`, it will silently hang without any error message. For example, passing the -r flag without -f, or missing the -c flag. Ideally, pachctl should output an error message or usage information.

**Comment by JoeyZwicker** [comment]
@Seth-Karlo yeah good point. We can certainly add ways to help catch those simple errors. @jdoliner what would be the simplest and easiest ones to handle?

**Comment by jdoliner** [comment]
So I'm pretty sure what's happening here is that `put-file` isn't erroring because it's actually a correct usage. The default behavior is to block for input from stdin if there's no `-f` or `-i` flag. We could maybe add a message about this so users know it's blocking on stdin, but I don't think it's a great idea to try to turn all these cases into errors. Trying to figure out if the user actually meant the flags they typed or something different can be really tricky / annoying error prone code to write.

**Comment by sjezewski** [comment]
stale
