### ISSUE TITLE
[1.4] Only run processing on content added in a commit

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#1393]
In talking with @msteffen apparently when a new commit is added, all data present in that commit is reprocessed. Most of the user code work is avoided by checking datum hashes, but this still requires some internal work + an etcd read per datum. It seems this could still take a fair bit of time when, eg, adding 3 rows to a 10M row table. If I'm understanding correctly, this extra work could be avoided altogether by only processing the files added/changed within the commit.

Hope this makes sense?

**Comment by jdoliner** [comment]
This is how 1.3 works. The new system is a more robust replacement for it. It requires more work to check things the way you're describing here because you need to check that a file was present in the previous commit and that, that commit was processed by the pipeline code you're using... which is exactly what the 1.4 system allows you to check quickly.
