### ISSUE TITLE
Better manual job management (rerun, cancel, etc)

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1432]
v1.4 doesn't have rerun-pipeline. @derekchiang proposed actually making it simpler and just creating `rerun-job <job_id>` instead. This also lets us sidestep the fact that specifying a slice of commits using `-x` is incredibly confusing.

**Comment by jdoliner** [comment]
What would the semantics of `rerun-job` be?

**Comment by jdoliner** [comment]
In particular how would it be different from `run-pipeline`?

**Comment by derekchiang** [comment]
Had an offline discussion with @jdoliner and @JoeyZwicker.  Basically the conclusion is that instead of having a retry button, we should just have an infinite retry loop for our jobs, similar to how k8s jobs work.  Meanwhile, a retrying job shouldn't block subsequent jobs from running and finishing.  A retrying job will basically have its output commit open until it succeeds.  In this world, there basically isn't such a thing as "failed" jobs.

Open question: should we support a policy where jobs do *not* infinitely retry?  If so, should there be a way to manually restart jobs that have been marked as "failed".

**Comment by jdoliner** [comment]
This use case is now covered by the job retrying logic that @derekchiang described above and by the new implementation of `run-pipeline` which can be used to effectively rerun a job by creating a new one with the same inputs.
