### ISSUE TITLE
Allow regex in addition to globs

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1488]
It would be nice if glob pattern supports the `|` operator, which is a logical "or".  For instance, to process the subdirectories `foo` and `bar`, one would use the `foo | bar` glob pattern which would match both.

**Comment by jdoliner** [comment]
Rather than adding features to glob patterns maybe it would make sense to also accept regexs? That would give us a lot of higher level functionality, including this, pretty easily.

**Comment by jdoliner** [comment]
Repurposing this issue a bit for regex in place of globs.
I think the original thing @derekchiang posted would be solved #1491

**Comment by sjezewski** [comment]
stale

**Comment by jdoliner** [comment]
Playing with this a bit more and trying out some potential use cases I think we should be thinking about this as an advanced but very not user friendly feature. This is mostly due to the fact that while regexes are a well known format, they're pretty god awful for matching paths though. For example the equivalent of `/*` in regex land would be `^\/[^/]*$`. And it gets even worse if you want to do more complicated things, which is the only real use case we have for regex. So it's tough for me to imagine there's that many usecases where the pain is going to be worth it.

**Comment by ysimonson** [comment]
You could say that the regex must be a full match, in which case it'd instead be `/[^/]*`, which isn't so bad

**Comment by ysimonson** [comment]
The concern I'd have other than ergonomics, though, is performance. With globbing, it's easy to parse the pattern and tell whether you need to recurse into subdirectories; I'm not sure how we'd pull that off with regex. This might not affect PFS anyways (does `GlobFile` recurse into all subdirectories anyways?)
