### ISSUE TITLE
Allow for union inputs, as opposed to joining them

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1491]
Right now, when a pipeline has multiple inputs, it processes the cross product of the inputs, essentially performing a join.  For instance, if one input has datums `{A, B}` and the other has datums `{C, D}`, then the pipeline will process 4 tuples: `[(A, C), (A, D), (B, C), (B, D)]`.

However, sometimes you might want to process the "sum" of the input repos as opposed to the product of them.  For instance, if I have a `word-count` pipeline and I want to perform a word count over two different repos, it'd be nice if I could have my pipeline treat those two repos as one giant repo that contains data from both repos.  That is, if the repos have datums `{A, B}` and `{C, D}`, the pipeline should process 4 datums `{A, B, C, D}`.

**Comment by emk** [comment]
I'd like to add some details on our use case.

Imagine that we have four multi-stage pipelines, each of which does some fairly complex processing.

1. `source_a` → ... `processed_a`
2. `source_b` → ... `processed_b`
3. `source_c` → ... `processed_c`
4. `source_d` → ... `processed_d`

In each of the 4 `processed_*` top-level **repos** (not directories in a mega-repo), the data layout looks like:

```
processed_a/
  000/
    5ff9e947-2065-4821-b1a7-5ef635545aa5.csv.gz
    f1e3ca2b-7267-4e42-95a1-9b7d62fc40e8.csv.gz
    7ea94526-aee2-44c4-82f6-524d45af5a15.csv.gz
    ...
  001/
  002/
  ...
  999/
processed_b/
  000/
    11f7e13e-5dc4-4671-9c57-9608527079dc.csv.gz
    ...
  001/
  002/
  ...
  999/
processed_c/
  000/
    2c554605-b564-4b37-a56e-301c35b0ff6e.csv.gz
    ...
  001/
  002/
  ...
  999/
processed_d/
  000/
    c7b85b69-e107-44f2-9522-9a372176eb8d.csv.gz
    ...
  001/
  002/
  ...
  999/
```

Our desired output looks like:

```
out/
  001.gz
  002.gz
  003.gz
  ...
  999.gz
```

To compute `001.gz`, we need to combine all of:

```
    5ff9e947-2065-4821-b1a7-5ef635545aa5.csv.gz
    f1e3ca2b-7267-4e42-95a1-9b7d62fc40e8.csv.gz
    7ea94526-aee2-44c4-82f6-524d45af5a15.csv.gz
    11f7e13e-5dc4-4671-9c57-9608527079dc.csv.gz
    2c554605-b564-4b37-a56e-301c35b0ff6e.csv.gz
    c7b85b69-e107-44f2-9522-9a372176eb8d.csv.gz
```

...onto a single worker. Then the worker will do a very complex calculation to reconcile all those inputs into a single output file.

So essentially `000`, `001`, etc., are "cross-repo join keys" operating at the file level. This could be implemented in two steps:

1. "Smoosh" `processed_a`, `processed_b`, `processed_c`, `processed_d` into a single unified namespace.
2. Apply the match glob `/*` _to the unified namespace_, so that all the `000/*` files from each input repo wind up assigned to a single node.

It would be OK if this were somehow a two step process.

@jdoliner Does this help explain our use case?

**Comment by emk** [comment]
Thank you for looking into this feature!

I've writen up a test case for union/"smoosh" joins, with sample input and output repositories, and a Python Pandas script that does a simulated join:

https://github.com/faradayio/pachyderm_union_join_test

Obviously, my heart isn't set on exact syntax in the `*.json` file, or how the two inputs get combined for `/pfs`. But ideally, it should be possible to produce that exact output data using the supplied Python script and the two input repositories. (No duplicate CSV headers in the middle of files allowed! 🙂 )

As mentioned in the README, the real join will involve far more records and more than 2 input repositories. But this should give you a more concrete idea about what we're trying to do.

Once again, thank you for looking into this, and please don't hesitate to ask questions!

**Comment by gabrielgrant** [comment]
@derekchiang @jdoliner is this addressed by the Union inputs PR? https://github.com/pachyderm/pachyderm/issues/1491

**Comment by jdoliner** [comment]
Yes, this has been merged.
