### ISSUE TITLE
Reconsider default append only behavior

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1531]
From a discussion on slack:

```
Yuval Kalugny [10:50 AM] 
Another question:
When I commit the same file a few times, the results get appended.
Is there a way for this to not happen? That is, that new files replace old files with the same name?

Daniel Whitenack [10:51 AM] 
@kalugny  in 1.4 or 1.3?

Yuval Kalugny [10:53 AM] 
In 1.3, but looking forward, also in 1.4

[10:54]  
I would love to understand why that is the default behaviour - I think that generally files are not an assortment of independent lines

...

Joey Zwicker [11:36 AM] 
@dwhitena @kalugny  I'm pretty sure in v1.4 you still need to do delete, then putfile to not append. The default behavior for putfile is still appending

[11:37]  
A lot of that comes from the defaults of Hadoop-land I believe but perhaps it's something we can reconsider. Especially in v1.4 where appending to a file isn't as clean of a use case since files are the lowest level datum
```

**Comment by jdoliner** [comment]
This seems to make sense to me, I think we definitely still want the "append" behavior for files that are put with `--split`. I.e. if I put files `foo/1` and `foo/2` with one `put-file` the next one should put `foo/3` and `foo/4` not overwrite `foo/1` and `foo/2` but appending to a single file doesn't seem to make a ton of sense in the new model.

**Comment by dahankzter** [comment]
I don't see how append could ever have been useful? There are versions available if needed why would appending to the file make sense?

Perhaps I am too stuck in the git way but it seems that replacing the file in a new commit is the way to go?

Issuing a delete first also requires finding the latest commit and then do a delete right?

Seems a little counter intuitive and a bit cumbersome to code it. Do I have to traverse all the history and delete the file in every commit it has ever taken place?

**Comment by JoeyZwicker** [comment]
@dahankzter I sounds like most of these questions were already answered in our Slack channel, but I'll comment on a few of them here just to keep the issue complete.

>Issuing a delete first also requires finding the latest commit and then do a delete right?

This is what branches are for in Pachyderm. Branch names are essentially tags or aliases for a particular HEAD commit. So `start-commit <repo> master` will start a new commit with it's parent as the HEAD of master and will then tag this new commit as the new HEAD of master. Finding the latest commit is easy.

>Seems a little counter intuitive and a bit cumbersome to code it. Do I have to traverse all the history and delete the file in every commit it has ever taken place?

Commits are immutable so you never go back and delete files from old commits. To delete a file you simply start a new commit on whatever branch you want and delete the file. Let's talk through an example:

- Commit1 adds file `foo`
- Commit2 adds files `bar` and `buz`
- Commit3 deletes file `foo`
- Commit 4 adds `baz`

If we list files for each commit, here's what is returned:
```
$ pachctl list-file <repo> Commit1
foo
$ pachctl list-file <repo> Commit2
foo
bar
buz
$ pachctl list-file <repo> Commit3
bar
buz
$ pachctl list-file <repo> Commit4
bar
buz
baz
```
Notice that in Commit3 we deleted `foo`. `foo` is no longer there in any future commit we read from, but we can always still go back and get `foo` by reading from Commit1 or Commit2. This works the same way for overwrites. If instead of just deleting `foo` in Commit3, I instead deleted it and added in a new file `foo` with different content (let's call it `foo'` to differentiate), then `foo'` would be available in Commit3 and Commit4 but 'foo` would be Commit1 and Commit2.

**Comment by dahankzter** [comment]
Thanks @JoeyZwicker ! It was a bit of a confusion on my part and it is much clearer now. 

I still think the append by default is weird though. Other than a legacy behaviour is there any reason to maintain it? Having putfile behave as a "replace" would be conveniten but perhaps I have not considered enough ramifications.

**Comment by JoeyZwicker** [comment]
There are a few edge cases where it's still useful, but we opened this issue specifically because we're thinking about changing the default to replace instead of append. In pachyderm v1.3, appending was a very meaningful use case, but in v1.4 and going forward, pachyderm manages/prefers lots of small/separate files instead of appending to one big log file -- which was the common use case.

We'll almost certainly change this behavior, it just hasnt been slated into our dev timeline yet.

**Comment by mlhamel** [comment]
It might be something we would want to keep when you are manipulating files using the `pachctl` but it seems it is also how it is currently working when you are manipulating files inside a pipeline, which was something really weird at first for me.

**Comment by derekchiang** [comment]
I'm tentatively in favor of changing the default to replace as opposed to append.  However, I do think that we need an `--append (or -a)` flag for `put-file` that allows for appending.  Otherwise appending to a file, which we've agreed that is still a reasonable use case, would have to consist of 1) reading the file, 2) manually append to it, then 3) put it back.

I'm also not sure if having `--split` default to append makes sense.  It just doesn't feel very consistent to have two defaults.  I think it's fine if you have to do `--split -a` to append to a split file.

**Comment by derekchiang** [comment]
Chatted with @JoeyZwicker offline.  One open question that occurred to us was what the behavior should be when you are putting the same file twice in an open commit.  Should one put overwrite another?  Or should they append?  The former seems dangerous since you are losing writes.  The latter feels inconsistent with what we are proposing which is to have the default behavior of `put-file` being replace.

**Comment by dahankzter** [comment]
It would be good if we could supply a mode to control if overwrite or
append should be used even in an open commit.

**Comment by JoeyZwicker** [comment]
Talked with @jdoliner last week. I think one of the simplest options that would help users would simply to add a --overwrite (-o) to `put-file` so users can have some sugar instead of having to make two calls for every file they want to add. 

This also puts the control into the users hands for most the above issues without having to actually change the default behavior. 

Just to double check, delete-file shouldn't fail if the file doesn't exist (pretty sure it doesn't).

**Comment by mlhamel** [comment]
i think that would be a great idea and would simplify a lot of things.

**Comment by thedrow** [comment]
This is somewhat related to #1885.
The current file mutation behavior is not documented anywhere leading to confusion of users who haven't participated in our Slack channel or read some of the issues in this repository.
While we resolve this issue, can we please document what happens when writing to a file?
