### ISSUE TITLE
--split fails with `node`-related errors

### ISSUE THREAD

**Issue by abourget** [pachyderm/pachyderm#1532]
Running:

```
$ echo '{}' >> lines.txt
$ echo '{}' >> lines.txt
$ echo '{}' >> lines.txt
$ pachctl put-file mama master -c --split line -f lines.txt 
no node at "/lines.txt"
```

Same with `--split json`.

Not sure what to do there..

**Comment by dwhitena** [comment]
@abourget Thanks for bringing this up.  I wasn't able to reproduce this with a 1.4 cluster in AWS:

```
➔ echo '{}' >> lines.txt
➔ echo '{}' >> lines.txt
➔ echo '{}' >> lines.txt
➔ cat lines.txt 
{}
{}
{}
➔ pachctl create-repo testsplit
➔ pachctl put-file testsplit master -c --split line -f lines.txt
➔ pachctl list-file testsplit master
NAME                TYPE                SIZE                
lines.txt           dir                 9 B                 
➔ 
```

Could you provide a little more detail about anything you did in the deploy different from the default deploy outlines here: http://docs.pachyderm.io/en/latest/deployment/amazon_web_services.html?

Specifically, I think you renamed a couple of things maybe, etc.?  Could be related.  I'm not sure.

**Comment by jdoliner** [comment]
This looks to be an error that's coming from the `hashtree` library, on the call to `finish-commit` (which happens because of the `-c` parameter). Likely the reason @dwhitena can't reproduce this is that it's actually not the `put-file` that's causing the problem but some state that's already in @abourget's  `master` branch. @abourget, if you've still got that data hanging around you could confirm this by doing `pachctl start-commit mama master && pachctl finish-commit mama master`.

I'm not quite sure what would put a `hashtree` in a state where it returns this error though, @msteffen @derekchiang maybe you guys know more?

**Comment by abourget** [comment]
Ok, let's close this.. I'll re-open if I find a better way to repro.. Not a problem for me right now.
