### ISSUE TITLE
`put-file`'s flags are a little confusing when adding directories recursively

### ISSUE THREAD

**Issue by abourget** [pachyderm/pachyderm#1533]
Here are a few confusing things:

* `pachctl put-file sessions master -c -r -f ./2017-03-28` will add the files under `./2017-03-28/files.json` in the commit as `2017-03-28/2017-03-28/files.json`.
* `pachctl put-file sessions master 2017-03-28 -c -r -f ./2017-03-28` will add the files under `./2017-03-28/files.json` in the commit as `2017-03-28/files.json`.
* `pachctl put-file sessions master -c -r 2017-03-28/` just stalls there, I guess awaiting input from stdin. But tihs doesn't make sense for recursively loading directories.

I'd propose a `pachctl put-dir` that would do the recursive thing automatically, and would unclutter the `put-file` command.

```
pachctl put-dir [repo] [branch] localpath [dstpath]
```

so that:

* `pachctl put-dir repo master ./subdir` would copy `./subdir/file.json` to `subdir/file.json` inside the commit.
* `pachctl put-dir repo master ./subdir /` would copy `./subdir/file.json` to `file.json` inside the commit.
* `pachctl put-dir repo master ./subdir .` would copy `./subdir/file.json` to `file.json` inside the commit.
* `pachctl put-dir repo master ./my-subdir subdir` would copy `./my-subdir/file.json` to `subdir/file.json` inside the commit.

This is just a proposition.. but it seems to me that cluttering `put-file` with directory operations makes both more confusing.

**Comment by jdoliner** [comment]
> - pachctl put-file sessions master -c -r -f ./2017-03-28 will add the files under ./2017-03-28/files.json in the commit as 2017-03-28/2017-03-28/files.json.

Ugh, this is a silly bug, we'll fix this. The path should clearly be just: `2017-03-28/files.json` 

> - pachctl put-file sessions master 2017-03-28 -c -r -f ./2017-03-28 will add the files under ./2017-03-28/files.json in the commit as 2017-03-28/files.json.

This one seems  reasonable to me, if you explicitly a file name in a recursive call that gets appended as a prefix to all of the files it finds in the directory.

> - pachctl put-file sessions master -c -r 2017-03-28/ just stalls there, I guess awaiting input from stdin. But tihs doesn't make sense for recursively loading directories.

This one is admittedly a bit confusing, I think it's not too terrible to have a `-r` flag do nothing in the case of putting a single file, recursive linux commands like `du` can also be called on single files and have no effect. I think one easy thing we could do to make this less confusing is print out a message that it's waiting for input from `stdin` so people know what's going on.

---

The idea of having `put-dir` does seem interesting to me. It would make both commands a bit less cluttered and also probably increase the chances that the commands are implemented correctly since we've had several problems caused by how much functionality is packed into `put-file`. What do others think?

**Comment by sjezewski** [comment]
stale
