### ISSUE TITLE
Expose `glob-file` in pachctl

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1552]
We already have `GlobFile` API we use internally to apply a glob pattern to a commit and get a set of paths that match the pattern.  We should also expose it to `pachctl` which would be helpful when you are debugging a job and you want to know what datums the job processed, or when you are designing a pipeline and you want to test your glob pattern on your input.

**Comment by sjezewski** [comment]
This is helpful / necessary for some common debugging workflows.

In particular, we need a way to know which worker pod processed which datum. This is critical when debugging scaling issues (or other breaking builds). I need to know which files (by way of a datum) was processed by which pod, so I can look at the resource usage for that pod and see what happened.

**Comment by jdoliner** [comment]
I don't think `glob-file` will quite work for the use case you're describing here @sjezewski. From my understanding `glob-file` will just give you a way to pass a glob pattern and get all of the files that match it. This is still pretty useful since it allows you to quickly check what your datums will be for a particular pipeline. But it won't tell you which workers processed a given datum, for that I think `get-logs` is the answer. You can already do `get-logs` per datum, to satisfy the use case we just need to add a field to the log message about which worker it comes from.

**Comment by JoeyZwicker** [comment]
@jonand was just asking about this in #users today -- trying to figure out which datums were processed by which pods.

**Comment by jdoliner** [comment]
@JoeyZwicker again, this will not tell you about which datums were processed by which pods. That's #1554
