### ISSUE TITLE
pachyderm_ppsd_1 doesn't start in Vagrant image

### ISSUE THREAD

**Issue by brinman2002** [pachyderm/pachyderm#160]
Trying to run Pachyderm in Vagrant using the Vagrantfile/init.sh in the Github documentation.  The ```pachyderm_ppsd_1``` container doesn't start correctly.

Steps to reproduce:
Execute the following steps from [README.md](https://github.com/pachyderm/pachyderm#vagrant)
```
mkdir -p pachyderm_vagrant
cd pachyderm_vagrant
curl https://raw.githubusercontent.com/pachyderm/pachyderm/master/etc/initdev/Vagrantfile > Vagrantfile
curl https://raw.githubusercontent.com/pachyderm/pachyderm/master/etc/initdev/init.sh > init.sh
vagrant up # starts the vagrant box
vagrant ssh # ssh into the vagrant box

go get github.com/pachyderm/pachyderm/...
cd ~/go/src/github.com/pachyderm/pachyderm

make launch # Not make test
```

See attached logs for command output and docker logs for the container.
[logs.txt](https://github.com/pachyderm/pachyderm/files/45355/logs.txt)

Vagrant version:
```
$ vagrant version
Installed Version: 1.7.2
Latest Version: 1.7.4
 
To upgrade to the latest version, visit the downloads page and
download and install the latest version of Vagrant from the URL
below:

  http://www.vagrantup.com/downloads.html

If you're curious what changed in the latest release, view the
CHANGELOG below:

  https://github.com/mitchellh/vagrant/blob/v1.7.4/CHANGELOG.md
```

**Comment by brinman2002** [comment]
Upgraded to latest docker and it still didn't start, although the error message was just-

```
vagrant@vagrant-ubuntu-vivid-64:~/go/src/github.com/pachyderm/pachyderm$ docker logs pachyderm_ppsd_1 
KUBERNETES_PORT_443_TCP_ADDR not set
```

**Comment by brinman2002** [comment]
Adding this environment under ppsd in the docker-compose.yml seems to fix it but as a complete noob to Pachyderm and docker, I'm not sure if it's exactly the fix needed.

```
  environment:
    - KUBERNETES_PORT_443_TCP_ADDR=127.0.0.1
```

**Comment by jdoliner** [comment]
Hi @brinman2002,

Really sorry you ran in to this, as you basically figured out from the error messages `ppsd` requires a running kubernetes instance to launch jobs. That means that deploying on docker-compose isn't possible anymore, at least you won't get a fully functioning cluster because ppsd won't be able to launch jobs. Pfs should still work fine under docker-compose.

To get a working cluster I'd recommend taking a look at:

[https://github.com/pachyderm/pachyderm/blob/master/QUICKSTART.md](https://github.com/pachyderm/pachyderm/blob/master/QUICKSTART.md)

we're just now rolling out this documentation so it's a bit raw but I believe the steps there will get you a working cluster. And if it doesn't please please let us know what went wrong so we can fix it. :)

---

Action item for this issue:

Remove docker-compose since it's not a viable way to deploy.
Update `make launch` to us Kubernetes.

**Comment by brinman2002** [comment]
@jdoliner good information, thanks.  I was having trouble getting the ```etc/kube/start-kube-docker.sh``` script to execute properly as well.  I should have some time today to reproduce that and I'll log another issue if I'm not able to get it running.

**Comment by jdoliner** [comment]
Docker compose has been removed for deployment along with vagrant so I think this issue doesn't apply anymore. Closing.
