### ISSUE TITLE
ListJob is not using the `InputCommit` argument

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1645]
`ListJobRequest` contains a `InputCommit` argument, which is not currently being used.  I think the idea was that you might want to list only the jobs that have certain commits as inputs.  We should either remove the argument or implement the feature.

**Comment by jdoliner** [comment]
We should implement this, along with an `OutputCommit` field.

**Comment by gabrielgrant** [comment]
This should also probably be renamed output_commit**s** (plural), since it is a repeated field. Not sure whether this should be an AND vs OR operation, and whether all inputs should have to be specified. My inclination is that exact matching makes the most sense (return jobs with exactly this list of input commits)

**Comment by jdoliner** [comment]
Why would it be repeated? Jobs only have `1` output commit.
And yes, I agree that it should be exact match making, i.e. the return job will match all `InputCommits` and `OutputCommit` if specified.

**Comment by gabrielgrant** [comment]
@jdoliner sorry, that was a typo -- i meant "input_commit(s)"

**Comment by sjezewski** [comment]
stale

**Comment by jdoliner** [comment]
This is implemented.
