### ISSUE TITLE
Worker should reclaim disk even when job errs

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1680]
With 1.4.3, if a job tries to download more input than the root volume's size, we see the disk leakage / eviction pattern.

That is:

- a single job fills up a node's disk, errs (or gets evicted)
- it gets rescheduled onto another node
- this repeats until all node disks are full
- the disk pressure then causes pachd/etcd to get evicted as well

How can we prevent or mitigate this?

- Can we detect the size of the incoming datum and the freespace on the disk? If we could detect it'll fill up ... we can err out quickly (Doesn't really help w disk contention ... multiple workers on that node could all 'think' there's enough disk when really there isn't)
- Can we reclaim the disk that was 'orphaned' by an evicted worker?

**Comment by jdoliner** [comment]
This should be pretty simple to fix by using an `emptyDir` instead of a `hostPath`.

However there's an unavoidable problem here that I don't think it's possible to process datums that are larger than the disks the VMs have. You could do it with streaming but you'll still get in trouble with the output dataset being too big.

**Comment by sjezewski** [comment]
Yup. And I want us to have good tooling around that if we can provide it. If your datum > disk size (or disk remaining) if we could output a message to that effect that would help a lot.
