### ISSUE TITLE
pachctl put-file with a gs path only uses one level of directory

### ISSUE THREAD

**Issue by rj3d** [pachyderm/pachyderm#1682]
On 1.4.4 using this load command:

`pachctl put-file kallisto_input master -r -f gs://pici-east/kallisto-data/sampled`

Results in the following directory structure:

```
pachctl list-file kallisto_input master /kallisto-data/sampled
NAME                                   TYPE                SIZE                
/kallisto-data/sampled/sub1.fastq.gz   file                77.75 MiB           
/kallisto-data/sampled/sub2.fastq.gz   file                79.98 MiB  
```

I would expect the sampled folder to be created at root and not having the kallisto-data portion of the path preserved.

**Comment by sjezewski** [comment]
I think a modified version of `put-file` is what you want.

If you do `pachctl put-file -h` you'll see some examples of advanced cases. I believe the one you want is:

```
# Put the data from a URL as repo/branch/path:
pachctl put-file repo branch path -f http://host/path
```

**Comment by jdoliner** [comment]
@sjezewski that's correct and in particular if you want to have them at the root directory you can put `/` or `""` as the `path` argument. So your command would look like:

```
pachctl put-file kallisto_input master / -r -f gs://pici-east/kallisto-data/sampled
```

The reason we don't do this by default is that you can pass multiple urls to `-f` and if they happen to have 2 files under them with the same name then you'll get a very strange result since their data will get concatenated.

Does this work for your purposes @rj3d?

**Comment by rj3d** [comment]
That works for me, thanks for the input and help!
