### ISSUE TITLE
Re-run pipeline

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1686]
@JoeyZwicker suggested adding a command `rerun-pipeline --from` that's a syntactic sugar for `update-pipeline -f the_same_manifest`, where `the_same_manifest` would be the same as the original manifest except that it includes a `from` field given by the `--from` flag.  The idea is that `rerun-pipeline` would re-run your pipeline on a particular set of input data.

**Comment by JoeyZwicker** [comment]
@derekchiang also mentioned being able to pass a `--from` flag that changes the default of HEAD to a specific commit. That commit and child commits will be rerun.

**Comment by jdoliner** [comment]
Looks like you edited this to not include it so you've probably realized this yourself but just to clarify there doesn't seem to be much sense in having `--from` default to `HEAD` since in that case `rerun-pipeline` won't do anything. It'll just process the next commit that comes in with the code it would have used anyways, exactly what it would have done anyways. It seems like by default `rerun-pipeline` should leave `FROM` blank which will cause all commits to rerun, that's what I'd expect from a command called `rerun-pipeline`.

Also worth discussing here is how `--from` is going to work with multiple inputs.

**Comment by sjezewski** [comment]
I believe this is covered w update-pipeline / reprocess flag / from-commit flag
