### ISSUE TITLE
`pachctl port-forward` prints out error messages if dashboard is not deployed

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1728]
Running `pachctl port-forward` on a cluster without the dashboard results in the following message:

```
Pachd port forwarded
Dash websocket port forwarded
Dash UI port forwarded, navigate to localhost:38080
CTRL-C to exitNo resources found.
No resources found.
error: pod name must be specified
See 'kubectl port-forward -h' for help and examples.
error: pod name must be specified
See 'kubectl port-forward -h' for help and examples.
```

It otherwise works fine tho.

**Comment by dwojdak** [comment]
hey @derekchiang, were you by chance trying to pass any extra arguments to `kubectl` using the `-k` option? this problem happened to me when trying to pass a namespace. turns out i needed to quote the argument like this `pachctl port-forward -k '--namespace=donuts'`. not sure if this was your issue, but just in case it helps...

**Comment by sjezewski** [comment]
stale
