### ISSUE TITLE
rename "from" field in pipeline spec

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1737]
There are two possible ways to interpret "from" and users are getting confused. 

`from` can be thought to be inclusive, meaning `from: HEAD` reruns on the HEAD commit.

Or exclusive, as it is now, where to rerun just HEAD you pass the CommitID of `HEAD^`

Exclusive is the correct behavior because otherwise there no way to update-pipeline only on future commits (the equivalent of `no-archive` in v1.3). The problem is `from` as a term is ambiguous and in fact we've had 3-4 prominent users in addition to myself and @gabrielgrant think it meant inclusive when it isn't.

I don't know what it should be called instead, perhaps `after_commit` or `since_commit`? 

as @jdoliner pointed out, this would require a migration so should be slated for v1.5 or whatever next migration release we do. Added label to that effect.

**Comment by jdoliner** [comment]
I'd prefer not to do this, it's very common to have to look up whether bounds are inclusive or exclusive in all walks of programming and I haven't seen many examples where the name of the field alone makes it completely clear. Neither of the names you recommend seem better to me. Do you want to process commits that were added after / since this commit was finished? Or data that was added after / since the commit was started? I'm very dubious that there's a name which conveys exactly what we want short of `latest_commit_not_to_process` or something overly verbose like that.

---

More generally speaking, I'm not a fan of the logic that anytime something confuses a user that means we should change it. It's basically impossible to come up with single word names for all the fields that are going to mean exactly the same thing to everyone, if we change things every time it confuses people then we'll likely wind up with a spec that's not any clearer but is also very unstable.

**Comment by JoeyZwicker** [comment]
I disagree with both of these arguments. 

1) As I mentioned, I'm not strongly sold on a particular rename such as "after", but it's meaningfully better. For example (this is directly from multiple pachyderm-savvy, not beginner users), in repo where you have 5 linear commits:
`Reprocess all commits FROM commit 2` is incredibly ambiguous, if not actually misleadingly wrong.  Whereas `Reprocess all commits AFTER commit 2`, meaning 3, 4, and 5 get processed, is significantly closer to implementation. Certainly its not perfect.

2) I agree that "anytime something confuses a user that means we should change it" is not a good policy and that's not what i'm pushing for here. 
- This is a significant point of confusion that large portion of our most experienced Pachyderm users have hit and were _wrong_ about the expected behavior. That should tell you something.
- This workflow for having to rerun things on only a subset of commits is incredibly common and a path that most production users will hit. This is not an edge case that only effects a small number of users.
- We add new flags/fields all the time and don't put a significant amount of thought into naming them -- which is fine because we're developing very fast. But, I for one expected the implementation of `from` to be inclusive and would have lobbied for a different name if I had known that wasn't the implementation. I now understand why exclusive is the correct implementation, but dictates needing a better name. It's obviously not reasonable for me to be part of any (or most) naming discussions, but we also can't be averse to changing it "just because we don't like change." Yes, this is API-breaking and should be included in an API-breaking release along with other changes that will inevitably need to be done that break compatibility.

**Comment by JoeyZwicker** [comment]
From @abhitopia in #1966 

`from_commit` is counter intuitive as it **excludes** the commit itself as explain in doc-

"input.atom.from_commit specifies the starting point of the input branch. If from_commit is not specified, then the entire input branch will be processed. Otherwise, only commits since the from_commit (not including the commit itself) will be processed."

Proposal: Rename `from_commit` to more intuitive `after_commit`.
Alternatively, add provision for both `from_commit` and `after_commit`
```

**Comment by abhitopia** [comment]
@JoeyZwicker - Further, I think following section adds to the confusion
![image](https://user-images.githubusercontent.com/12864026/27455453-33c20f0c-5795-11e7-8bb9-99d59cd32e19.png)

Is this talking about `from` or `from_commit`, and if branch name ( such `master` is allowed ) then how would that work because I believe that `master` would point to the `head` commit-id, and perhaps, the required functionality is to run only on last commit, ie. including the HEAD commit. Which clearly is not from `from_commit` should do. 

Can someone explain, how `from_commit` works with branch name?

**Comment by JoeyZwicker** [comment]
@abhitopia Yeah good point. That document definitely gives the wrong interpretation in a few ways. @dwhitena we should definitely update this doc and the pipeline spec to be clearer. As @jdoliner mentioned, we're going to get rid of `from_commit` for something that actually works the way users expect in the future, but we haven't gotten there yet

**Comment by dwhitena** [comment]
Yep, will do @JoeyZwicker.  Added here: https://github.com/pachyderm/pachyderm/issues/1869

**Comment by sjezewski** [comment]
stale
