### ISSUE TITLE
Document copy elision

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1792]
We've added support for "copy elision" in #1791.  Now we need to document this feature so people know to use it.  The basic idea is that if you create a symlink in your output directory to a file in an input directory, then Pachyderm is smart enough to know to not upload the data.  Combining this with `lazy`, a pipeline that merely shuffles files can skip both the download and the upload.

**Comment by JoeyZwicker** [comment]
Places it needs to be documented:

Time window cookbook
equi-join cookbook (anywhere where there's a shuffle step honestly)

I think we should also just make something like a "Other minor features" sections. I don't like that name or "misc", but there's lots of little things like this we need to document somewhere with just 1-2 paragraphs so we can point people there when they ask instead of having to re-explain.

@dwhitena thoughts?
