### ISSUE TITLE
Pipeline stalled at restarting when switching to new input spec

### ISSUE THREAD

**Issue by vuc4** [pachyderm/pachyderm#1802]
Pipeline spec stalls with state "restarting":
```json
"input": {
    "atom": {
      "repo": "staging",
      "glob": "/*"
    }
  }  
```

Pipeline runs:
```json
"inputs": [
    {
      "name": "staging",
      "repo": {
        "name": "staging"
      },
      "glob": "/*"
    }
  ]
```

**Comment by jdoliner** [comment]
Hi @vuc4, sorry you're hitting this. Would you mind grabbing logs for us so we can see that the error is? You can do this with `kubectl logs <pachd-pod>`. You should see a line like `error running pipelineManager ...` which will have the error in it.

**Comment by vuc4** [comment]
```
2017-05-08T14:00:51Z INFO  launching job manager for job 30caf766-ca05-4b3a-bbb4-5a5877bd2650
2017-05-08T14:00:51Z ERROR error running jobManager for job 30caf766-ca05-4b3a-bbb4-5a5877bd2650: Operation cannot be fulfilled on replicationcontrollers "pipeline-load-power-db-v5": the object has been modified; please apply your changes to the latest version and try again; retrying in 473.05082ms
```

**Comment by derekchiang** [comment]
@vuc4 could you post the full log on Gist or pastebin or something?  The issue was about pipeline stalling but the error messages you posted are for jobs.

**Comment by vuc4** [comment]
https://gist.github.com/vuc4/90b54a0732aea426c251498578c5a64f

**Comment by derekchiang** [comment]
Hi @vuc4, just to be clear, were you seeing that the **pipeline** getting stuck in `restarting` state, or was it the job?

I'm confused because looking at the logs, it doesn't appear that the pipeline went into the `restarting` state.  Also, while the errors about the job are concerning, from the logs it looks like the job was restarted successfully and only failed due to user-code-related reasons.  Could your code be returning a non-zero exit code for some reason?

Or could you have posted the wrong logs?

**Comment by vuc4** [comment]
When I did list-pipeline it would show the load-power-db pipeline as "restarting." There are errors in the job, but those occurred after I updated the pipeline and reverted to the deprecated inputs format and jobs were able to run.

**Comment by sjezewski** [comment]
stale
