### ISSUE TITLE
Adding Documentation

### ISSUE THREAD

**Issue by mattnenterprise** [pachyderm/pachyderm#182]
After using pachyderm I would like to propose some added documentation that maybe helpful for learning about pachyderm.

* Add a page for pachyderm terminology. You could define the following:
   * Pachyderm File System (pfs)
   * Repository
   * Commit
   * Pachyderm Pipeline System (pps)
   * Pipeline
   * Job

* Generating pachctl documentation using cobra. An example of this would be like what kubectl has [here](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/kubectl/kubectl.md)

* An overview of the design of pachyderm.

**Comment by jdoliner** [comment]
Really like both of these ideas.

What do projects normally call this page? Maybe glossary.md

**Comment by JoeyZwicker** [comment]
I already have a start to this glossary under doc/cli/pfs.

**Comment by jdoliner** [comment]
Number 2 is done. We now have autogenerated docs at [docs/pachctl](docs/pachctl)

**Comment by sjezewski** [comment]
We have a good amount of this covered now on the live site:

http://pachyderm.io/pfs.html
http://pachyderm.io/pps.html

For the next level of granularity we'll be figuring out where to host/put technical docs. Since we've covered most of what's described here, I'll close this issue so that any new doc issues can be specific.
