### ISSUE TITLE
Add option to sort ascending

### ISSUE THREAD

**Issue by vuc4** [pachyderm/pachyderm#1836]
Can the order be sorted to recent jobs at the bottom or a flag to reverse the current sort. When the list gets long, the user has to scroll up to view current jobs.

**Comment by jdoliner** [comment]
Newest at the top is fairly common for unix tools (`ls` for example) so I'm somewhat reluctant to break with that standard. This normally works because you can pipe the output to another command which will give you more control over how you view it. I'd try doing `pachctl list-job | less` that will start you at the top with the new jobs and allow you to scroll down to older jobs. You can also do `pachctl list-job | tac` which will get you the newer jobs at the bottom. One last one that might be useful is `pachctl list-job | head`, that will give you the 10 newest jobs.

Does this seem suitable for your purposes @vuc4 ?

**Comment by vuc4** [comment]
That will work.
