### ISSUE TITLE
1.5 Ergonomic issues

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1880]
Stemmed from a conversation with @JoeyZwicker.  Basically now that we are seeing a lot of production usage, it's a good time to start making a serious effort at making Pachyderm more ergonomic.

A couple issues that were brought up during the conversation:

* `from_commit`: currently it's practically useless as each commit captures the entire state of the repo, so in an append-heavy workload, processing a single HEAD commit is basically equivalent to processing all commits.
* Visibility into open commits.  Currently if you mess up an open commit (e.g. a file upload fails midway through), there's very little you can do about it.
* Save the output of a job that failed.  If you have a job that's been running for days and failed in the last second, you'd ideally be able to save whatever data it's processed.  But right now only successful jobs have output commits.

**Comment by JoeyZwicker** [comment]
Adding to above. 

`from_commit` in its current form still has uses in overwriting workloads. But we'd like to make this much more powerful and actually address what users would ideally like to do -- only process a subset of the files. Perhaps `diff` will enable this in some way? Unclear... but definitely worth discussing how to provide this type of functionality. 

Other ergonomics (some are just suggestions or ideas, not full proposals):
- modified/created timestamps (and commitIDs) for files.
- meta operations such as copying repos or subsets of data
- Addressing @derekchiang's comment in slack about orphaned jobs not really being useful? 
- no manual writes to repos that are "owned" by pipelines
- more info displayed in `inspect-*` fields. This would just be sugar for the CLI. For example, `inspect-commit` should show the jobID, pipeline version, perhaps even the transform that was used to create it. 
- commit aliases instead of UUIDs -- some ideas include: `master`, `master~~1`, `master^2`, etc. This would be nice for the FUSE mount too.

**Comment by derekchiang** [comment]
Update: `delete-commit` has been implemented which allows for deleting open commits.  It's useful when you've messed up your ingress and want to start over.

**Comment by gabrielgrant** [comment]
We get something similar to item number 3 ("Save the output of a job that failed") from the stats commit, but we don't do merging of datum outputs. Would it maybe make sense to create a single, merged output in the stats commit for failed jobs?

**Comment by jdoliner** [comment]
I believe everything in this issue has been implement with the exception of merging the output of failed jobs which I'm not convinced is something we want to do.
