### ISSUE TITLE
Unclear append semantics when appending to binary formats

### ISSUE THREAD

**Issue by thedrow** [pachyderm/pachyderm#1885]
I have a pipeline that writes to Parquet tables. Since writing to a Parquet table requires a client it is unclear how pachyderm will append writes to the same table done in parallel.
With CSV files appending to the same file is easy. Every entry ends with a new line. Consolidating parallel writes is trivial.
The same problem applies for saving SQLite or LevelDB files or any other binary format.

**Comment by jdoliner** [comment]
Pachyderm supports only very dumb append semantics. It just appends the bytes of the different files together, it has no notion of the format of the file or smarter ways to append files. This is ok, and something we're unlikely to change, because you can implement smarter merging semantics as a different pipeline step. For example instead of writing your Parquet files to `/pfs/out/foo` you'd write them to `/pfs/out/foo/1`, `/pfs/out/foo/2`, ... and then chain another step onto them which had a glob pattern of `/*` your code would then see a directory `/pfs/repo/foo` which would contain all of the parquet files and your code could merge them together. The downside of this ofc is that it'll store more data because it has to store the intermediate step. #546 is the best solution that that problem.

**Comment by thedrow** [comment]
But if foo is constantly updated appends will happen right?

**Comment by thedrow** [comment]
I think that there are two issues here:

1. Binary files are essentially immutable in Pachyderm.
2. Append semantics are not documented anywhere and there is no list of formats that support mutation in Pachyderm.

**Comment by thedrow** [comment]
After a discussion with @JoeyZwicker we figured out that binary files are essentially immutable only between different workers of the same job.

**Comment by gabrielgrant** [comment]
This should be fixed as part of #1869

**Comment by sjezewski** [comment]
stale
