### ISSUE TITLE
Collect job stats and store them in PFS

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1891]
There are a number of features we'd like to offer people to give them better insight into the execution of their jobs. However we don't yet have a very consistent way of implementing this, we currently store some basic information in etcd such as datum progress, logs are handled by k8s driver but also might be handled by our logging stack if users want more persistence, @sjezewski has proposed adding a stats service so we can record more in depth stats about the jobs as the execute. I worry about how much deployment overhead we're adding for these features and about the people who aren't going to have access to many of these features due to not wanting to deploy such a complicated stack. This is slightly different approach to implementing these features.

The idea is the leverage pfs which we know is present on every pachyderm installation to store some of this data. We'd add a flag to pipelines and jobs called `Trace` which would output tracing information for jobs when they ran. I'm imagining we'd have a branch on output repos called `trace` which would get update alongside the output branch with tracing information for the job. Each job would be its own commit on the branch. The structure of a commit would look something like this:

```
/<job-id>
  /<datum-hash>
    /pfs
      /input1/...
      /input2/...
      /out/...
    /logs
    /metrics
```

`/pfs/...` would contain the full state of the containers filesystem when it exited. This has been requested a lot since it would allow you to see the data processed as part of a job. Pfs' deduplication means that we're not actually storing an extra copy of the data under the hood.

`/logs` would be a copy of the logs outputted during processing of the datum. And of course they can easily be tied to a particular datum.

`/metrics` would be timing information for the job, how long did downloading data take, how long did user code run for, how long did uploading take, etc.

There are probably other things we'll want to add to this repo, the nice thing is once we have this system built it gives us a pretty generic system we can use to expose various information about the execution of a job.

**Comment by derekchiang** [comment]
I think this design mostly makes sense.  Just a couple comments:

* "Tracing" is probably not the right term to use here since that usually means tracking a request end-to-end, i.e. distributed tracing as in Dapper/Zipkin/OpenTracing.
* While there's not much data storage overhead since PFS de-dups, there's a considerable amount of metadata overhead since we will need to store at least 1 more hashtree for each datum.  This may or may not matter but it's something to think about.

**Comment by sjezewski** [comment]
Woah, this is great ... this gives us job stats. That's big.

The proposed solution would be great at answering a bunch of questions around job stats:

- histogram of datum size (e.g. cases of extremely heterogeneous datum sizes ... this came up for a customer w 400 datums where the last 2 accounted for 50% of the processing time)
- histogram of job run times over commits
- I think this would give us an easy way to record 'data written per commit' ... but I don't think quite gives us repo size? (maybe there's something clever we can do here to make that calculation easy too)
- the ability to list datums per job (which we don't have a first class API for)
- the ability to record where a datum was run (for debugging purposes)
- and perhaps most importantly ... a pretty easy way to add more stats to be measured/collected

Which are things we don't have today but I've felt the need for.

Broadly, this bites a huge chunk out of what I'm looking for w the stats service. It gives us job stats. And this would help us dogfood our own tech, which is great.

The two things I see missing / we'd need to address are:

1) App stats for pachd

I want us to be able to answer questions like:

- How much of each API call are we seeing? (e.g. ListFile, GetFile, PutFile ...)
- Where is the bottleneck in the DAG / where are the API calls slowing down? (we could see where in the DAG this was slowing down by looking at a graph of GetFile / PutFile frequencies or times to start)
- How does pachd handle load? sidecars vs master? Where is the scaling bottleneck for pachd? When do we recommend scaling up pachd nodes? 

And to answer those questions I still think we need to record stats for all the pachd API calls. Again, I haven't looked too much into this, there's a chance we can use what we already have reported in the logs. But I want to be able to search / filter / graph the stats data.

2) The rest of the 'stats service' stack

Using grafana / elastic search / statsd (or a similar stack)  gives us quite a lot of things we need. The ability to store (and rotate) data, search, filter, and graph the data. And present the data in a way that we can use to display stuff in our own UI.

What we're talking about here is basically replacing some of the stats collection (statsd or fluentd) and the indexing/hosting of the data (elastic search). I think we get a lot for free w pfs, but it won't be parity with those services

That's not necessarily a bad thing. We'll start with what works. But I just want to make sure we don't try to build all the features of those other things. Because that's probably not our core intention for our tech. And for the things that it would align with (e.g. data volume, data ingest rates) dogfooding it will only make our tech better. Awesome.

I do think we'd need some graphing utils. I'm sure some of this we'll consume and present in our own UI. But I don't want to reinvent the wheel for UI tools that already exist. So to me the question is how to integrate this with something like grafana. It could be that we have an 'ETL' pipeline running on this repo that massages it into the JSON format that grafana expects (and elastic search serves).

This all feels like we may want to start thinking about namespacing repos/pipelines. This all feels like it would go under the 'pach-system' namespace and user's wouldn't see by default. (And prob shouldn't have write access to directly)

**Comment by gabrielgrant** [comment]
Re: data de-duplication -- if this is storing output files from each input datum that then later get concatenated into larger files, will those be deduped? Are we storing a block per concatenated chunk, or doing the concat and then storing the whole file together?

**Comment by jdoliner** [comment]
This has been implemented and merged into master.
