### ISSUE TITLE
Strange behavior with put-file and multiple -f arguments with GCS paths

### ISSUE THREAD

**Issue by rj3d** [pachyderm/pachyderm#1905]
I have a GCS bucket with the following structure:

```
gs://tesla-data/raw-data
gs://tesla-data/raw-data/pt1
gs://tesla-data/raw-data/pt2
gs://tesla-data/metadata
gs://tesla-data/metadata/intervals/intervals.csv
```

I want to load the contents of raw-data and the contents of intervals into a folder called tesla in my repository. To do this, I used the following put-file command:

```
pachctl start-commit somatic_variant_aligner_input master && \
pachctl put-file somatic_variant_aligner_input master /tesla -r -f gs://tesla-data/raw-data -f gs://tesla-data/metadata/intervals && \
pachctl finish-commit somatic_variant_aligner_input master
```

This resulted in both the folder raw-data and the folder metadata being copied into a folder called tesla in my repository:

```
pachctl list-file somatic_variant_aligner_input master /tesla
NAME                TYPE                SIZE                
/tesla/metadata     dir                 552 B               
/tesla/raw-data     dir                 78.47 GiB       
```

I was expecting to have the data loaded like this:

```
/tesla/p1
/tesla/p2
/tesla/intervals.csv
```

**Comment by rj3d** [comment]
Looking at the logs, I got this WARN:
`2017-06-03T02:22:07Z WARN ambiguous key metadata/intervals/, not creating a directory or putting this entry as a file`

**Comment by jdoliner** [comment]
Hey @rj3d, sorry this isn't doing what you expected the behavior here is a little bit tricky. The reason we don't create the files with the structure that you expected is that it's a little unclear what the correct behavior would be if two of the paths had a common filename. I.e. if you had `gs://tesla-data/raw-data/pt1` and `gs://tesla-data/metadata/intervals/pt1` in that case our options would be:

- concatenate the files
- have 1 file overwrite the other
- error

All of these seem kinda like gotchas so we opted to make the command in this form a little bit harder to get name collisions with. We could consider changing this since maybe name collisions are rare enough that we shouldn't make the decision based on them.

As for the `WARN` you got, that's likely harmless but probably indicates that you have a file in your gcs bucket which is literally called `metadata/intervals/`.

**Comment by rj3d** [comment]
I get where you're coming from, but the current behavior ended up loading an entire folder and set of files that I didn't specify anywhere in my commit. This behavior seems a little confusing, no?

**Comment by sjezewski** [comment]
stale
