### ISSUE TITLE
build fails on 'master' branch due to dependency hell

### ISSUE THREAD

**Issue by tadhunt** [pachyderm/pachyderm#191]
It seems the version of Kubernetes packeged into the vendor deps is not compatible with the version of the docker stuff packaged into the vendor deps.  Looks like running 'make vendor' fixes it, but I'm not sure whether that will introduce other problems.

This problem is against the latest master at the time of writing (993b390427f561e93de0bf1b0bf3e1f9f0ca44cb)
```
[...]
docker-compose run --rm  test sh -c "go test -test.short  ./src/..."
Creating pachyderm_rethink_1
Creating pachyderm_etcd_1
vendor/k8s.io/kubernetes/pkg/util/resource_container_linux.go:25:2: cannot find package "github.com/docker/libcontainer/cgroups/fs" in any of:
	/go/src/github.com/pachyderm/pachyderm/vendor/github.com/docker/libcontainer/cgroups/fs (vendor tree)
	/usr/local/go/src/github.com/docker/libcontainer/cgroups/fs (from $GOROOT)
	/go/src/github.com/docker/libcontainer/cgroups/fs (from $GOPATH)
vendor/k8s.io/kubernetes/pkg/util/resource_container_linux.go:26:2: cannot find package "github.com/docker/libcontainer/configs" in any of:
	/go/src/github.com/pachyderm/pachyderm/vendor/github.com/docker/libcontainer/configs (vendor tree)
	/usr/local/go/src/github.com/docker/libcontainer/configs (from $GOROOT)
	/go/src/github.com/docker/libcontainer/configs (from $GOPATH)
Makefile:177: recipe for target 'go-test' failed
make: *** [go-test] Error 1
vagrant@vagrant-ubuntu-vivid-64:~/go/src/github.com/pachyderm/pachyderm$ 
```

**Comment by jdoliner** [comment]
Ugh, this looks annoying.
So first off we're kind of in a fractured state with tests right now.
`make test` runs the old integration suite which is built on `docker-compose`. We ditched that for kubernetes and added some integration tests that run within k8s as a pod.
I'm thinking we should tear out the old tests along with docker-compose and integrate them into the k8s pod since most of the tests require cluster state to run. Also we should have `make test` run the k8s tests that work instead of the broken ones that don't.

Really sorry for the confusion on this.

**Comment by jdoliner** [comment]
The tl;dr is that I'm not quite sure what's breaking the test compilations, but we're probably better off just sidestepping it by removing the tests.

**Comment by tadhunt** [comment]
Looks like there's been tons of refactoring lately so it makes sense that the tests are unstable.  Even with the vendor extension and the govendor tool, it's disappointing that managing dependencies on a large project like this is so fraught with peril.

**Comment by jdoliner** [comment]
Alright I finally figured out what was wrong here. I was having trouble reproducing this due to some caching issues. Finally reproduced this and got it fixed.

It only required a little bit of hackery to get a functional vendor directory.

It still feels like we're in a fragile place with our vendoring. This is probably due to the number of experimental projects we depend on.

**Comment by jdoliner** [comment]
Feel free to reopen if this is still broken in anyway. But I'm hoping it's fixed.
