### ISSUE TITLE
No BTRFS any more ?

### ISSUE THREAD

**Issue by joeblew99** [pachyderm/pachyderm#194]
Are you transitioning to abstracted this away using the OpenStorage ?
https://github.com/libopenstorage/openstorage

**Comment by jdoliner** [comment]
Pachyderm is now 100% btrfs free!
Pachyderm's containers are now stateless and we use object storage (s3, GCS.. etc) for data and a database (RethinkDB) for metadata.

Openstorage doesn't really make sense for the data since object storage is normally outside the container but it probably will for the database which we also deploy as a container.

**Comment by joeblew99** [comment]
Cool. Check out minio then. Might be useful to you

**Comment by joeblew99** [comment]
It's golang based s3 thingy.
