### ISSUE TITLE
Commit durations for pipeline output commits are practically meaningless

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1951]
Since we only construct an output commit when a job finishes, the output commit's duration is almost always `Less than a second`.

There have been proposals for creating the output commit in the beginning of a job and incrementally build up the commit as the job runs, in which case the commit's duration would be roughly equivalent to the job's duration.

Or, we can just not show commit duration.

**Comment by gabrielgrant** [comment]
It makes sense to me that the commit be created at the beginning of the job. If files can be added incrementally as the individual datums' processing completes, then once @jdoliner 's change to allow reading uncommitted files lands, this could be really useful for inspecting in-flight results, particularly for long-running jobs (I'm pretty sure this isn't nearly as straightforward as I'm making it sound given how output blocks & files are added to PFS, but a guy can dream, right? :))

**Comment by jdoliner** [comment]
I don't see any inherent problem with the commit durations not corresponding to the duration of the job. Jobs record their own durations. As it exists now the duration of the commit indicates the time it took to create the commit within pfs which is likely to be small and not particularly interesting, but that's absolutely fine. Changing our implementation so that we can create a meaning for a field seems pretty silly to me.

That being said there may be some other good arguments for creating commits incrementally such as allowing people to explore the output of a job while it's running.

Similar to this, duration for jobs are a bit wonky. They start counting when the job is scheduled but that means if a bunch of commits come in together then the last commit will start a job that has to wait for all the other jobs to finish and count that time as part of its duration. Ideally job duration would only count actual time spent processing.

**Comment by derekchiang** [comment]
@gg agreed that being able to explore a job's output commit while the job's running could be cool.

@jdoliner the refactor makes it such that a job is only created when it's ready to run, so the problem you brought up will no longer exist.

**Comment by sjezewski** [comment]
stale
