### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by cxxly** [pachyderm/pachyderm#199]
Pachyderm can provide both batch and stream processing, is it better than hadoop/storm? May be we need some benchmarks to compare the performance between pachyderm and hadoop/storm/spark, and publish a testing report.

**Comment by jdoliner** [comment]
Hi @cxxly,

Benchmarks that allow people to easily compare Pachyderm's performance to hadoop/spark are definitely something we would like to make readily available. However doing benchmarks correctly such that they actually help users compare the products in a meaningful way is quite an undertaking so we can't quite commit to a timeline right now. This thread would be a good place to collect our thoughts about what these benchmarks should look like.

It seems like the obvious starting point is terasort. I'd be interested to see how Pachyderm did both in the total throughput section and the cost/gb section.

One thing I think terasort misses is latency which I think should be a part of our benchmarks. The fixed cost of jobs can be just as detrimental to user experience, even more so, because it often slows down development.

**Comment by cxxly** [comment]
Ok, I will make some tests about this step by step, and talk about here.

**Comment by derekchiang** [comment]
Some preliminary benchmarks are reported [here](https://github.com/pachyderm/pachyderm/tree/master/examples/word_count#preliminary-benchmarks).  Keeping this issue open as we plan to add more comprehensive benchmarks.

**Comment by sjezewski** [comment]
We've added some benchmarks to master now. We will open new issues w specifics on new things we want to benchmarks.

**Comment by bderooms** [comment]
Is there a possibility to get some insights on the results of these benchmarks for users? Mainly interested in number crunching benchmarks
