### ISSUE TITLE
Error reporting if pachd dies

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#206]
If it dies, I think we have undefined behavior.

This will probably be easiest to reproduce/fix once we have a chaos monkey as part of any CI/CD

**Comment by jdoliner** [comment]
Not sure quite what this is referencing. If pachd dies it gets rescheduled and brought back up.
There are definitely some bugs in there but I think we have issues open for a lot of them and issues to improve CI to expose more as well.
Closing this one since it seems like it's subsumed by those other issues.
