### ISSUE TITLE
pachctl undeploy should have --force option

### ISSUE THREAD

**Issue by thedrow** [pachyderm/pachyderm#2072]
Currently `pachctl undeploy` requires interaction.
A flag should be added to skip interaction and remove everything without asking.

**Comment by JoeyZwicker** [comment]
do you mean `pachctl delete-all`? I didn't think undeploy requires interaction

**Comment by thedrow** [comment]
It does if you specify `-a` as well.

**Comment by JoeyZwicker** [comment]
Ah true. @jdoliner or @derekchiang may be able to chime in about how easy that would be to add. I think it should be pretty easy so you can automate those commands

**Comment by jdoliner** [comment]
I'm not sure if adding a `--force` flag makes sense for this, especially since `kubectl delete` (which is what `pachctl undeploy` is using under the hood) already has a `--force` flag with a different meaning which we may want to push through at some point. If you're looking for a way to get around the interactive aspect of `undeploy` for the purposes of a script I'd recommend doing:

```sh
yes | pachctl undeploy -a
```

**Comment by thedrow** [comment]
That works as a workaround. Didn't know that the `yes` commandline existed.
Should we at least document this somewhere?

**Comment by thedrow** [comment]
@jdoliner Feel free to close this if we shouldn't document this anywhere.
Otherwise, it's probably best to add this to the documentation website which I can do.
