### ISSUE TITLE
Have a homebrew target for pachctl

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#208]
Right now to install pachctl people need to clone the repo and run `make install`.
It would be much better if we had a make target that created a homebrew package so people could just do `brew install pachctl`.

**Comment by derekchiang** [comment]
Test github integration

**Comment by sjezewski** [comment]
Ok, diving in on this. Making a formula is relatively straightforward once you tag the GH repo w proper versions (GH calls them 'releases'). 

The trick is making sure the version we tag is also reported by the binary. Industry standard here is to have the 'micro' version be the build number. So we'll do that. To do so, we'll have to read from an environment variable -- no way around this since the alternative is to modify the code / re-commit. This is fine (I've also seen it done by passing around a `VERSIONS` text file that contains the full version that the binary just reads and spits out).

So the important part of this task will be establishing versioning. We should also take this opportunity to do the same for pachd. So to be clear, the interface would be:


    # cloned & compiled locally:
    pachctl version
    <= 1.0.0
    
    # installed via homebrew:
    pachctl version
    <= 1.0.345

    # cloned & pachd generated from local files:
    pachd version
    <= 1.0.0

    # pachd deployed via dockerhub:
    pachd version
    <= 1.0.345

For the sake of clarity I presented the interface this way -- I know I'm oversimplifying the interface (pachctl reports both versions).

Versioning this way will enable users to write very easy bug reports & more importantly for us to easily track down the exact commit in question.
