### ISSUE TITLE
Docs for optimizing etcd

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2097]
From a user:

> I just stumbled into this https://jeremyeder.com/2017/07/25/docker-operations-slowing-down-on-aws-this-time-its-not-dns/
> 
> [4:28] 
> It doesn't seem that your AWS guide provides advice for how to optimally configure etcd for pachyderm
> 
> [4:28] 
> I think it should be included

**Comment by jdoliner** [comment]
I'm actually not quite sure what we'd put in these docs, `pachctl deploy` deploys etcd in the best configuration we know of, which doesn't really entail anything fancy. I'm a little unsure what we'd put in this doc that we couldn't just include in `pachctl deploy` so that it happens automatically. Right now there just aren't any special deployment options that we know of that help make etcd work better for pachyderm.

**Comment by dwhitena** [comment]
Closing for now based on @jdoliner's comment.

**Comment by thedrow** [comment]
For any production usage, your users need to use a provisioned IOPS drive for etcd pods.
This is true for any database but it is not common knowledge among data scientists.
I don't think you should provision it yourself as more money is involved when provisioning such drive.

Furthermore, for any high load usage where containers are created and destroyed a lot a provisioned IOPS drive is also required to avoid throttling the system.

**Comment by thedrow** [comment]
The [AWS deployment guide](http://pachyderm.readthedocs.io/en/latest/deployment/amazon_web_services.html) is a good place to document such recommendations.
