### ISSUE TITLE
bug in stats or FlushCommit

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2121]
Occasionally I've seen those stats test fail like:

```
--- FAIL: TestPipelineWithStatsAcrossJobs (89.99s)
    require.go:153: /home/sjezewski/go/src/github.com/pachyderm/pachyderm/src/server/pachyderm_test.go:3760
    require.go:155: No error is expected but got stats not enabled on pipelinec1ffc54ae899
```

Which suggests that something is racy ... the jobInfo that `list-datum` retrieves should have a `statsCommit` on it if the job is finished ... so perhaps there's a bug in stats ... or in `FlushCommit` which should be blocking a few lines above it in the `TestPipelineWithStats` branch.

Additionally, it only happens when all the tests are run. If I just run the stats tests, they're ok. So seems like a race.

**Comment by jdoliner** [comment]
The issue here is that `FlushCommit` when the output commit is finished which happens before the job is completed because one of the ways a job can fail is if `FinishCommit` fails. I can think of a couple of ways to solve this: you could wait for the the job with complete by doing `InspectJob` w/ `block = true` within the test, this would be correct with our current semantics. You could also make it so that if you call `ListDatum` on a job that hasn't completed then it waits for the job to complete before looking for the stats commit.

**Comment by jdoliner** [comment]
Per offline discussion I think I'm going to close this. While this behavior is a bit confusing it is technically in keeping with the semantics we've established at this point and we seem to have a fix for the immediate problems in the test that was failing.
