### ISSUE TITLE
Add commit hash check to release script

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2158]
add an extra check to fail the release if there's a commit hash in there. 

It seems there are a lot of ways we can mess up the release to accidentally include the commit-hash. Unfortunately, this causes a bunch of annoying problems with docs being generated, so we should add a check to fail the release if it's not correct. To be clear, we do occasionally want to do custom builds/releases, but I think that's a slightly different process than a main release.

**Comment by sjezewski** [comment]
I think we have this handled since @msteffen's [refactor](https://github.com/pachyderm/pachyderm/pull/2160/files). Now `make doc` and `make point-release` dont use commit hashes / trailing release suffixes (e.g. `RC1`), and we have analogous `make doc-custom` and `make release-custom` tasks for truly one off releases.
