### ISSUE TITLE
Ambiguity between count of Failed vs Queued Datums

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2199]
`JobInfo`s have three fields with datum counts: `data_processed`, `data_skipped`, and `data_total`.

`data_total` is a static count of all datums to be processed; the other two are live-updated as datums are handled by workers. The difference between `data_total` and (`data_processed + data_skipped`) is generally the number of datums still queued to be processed, but can also include a number of failed datums. It doesn't seem to be possible to distinguish between these at the moment.

**Comment by derekchiang** [comment]
Currently a job immediately fails once a datum has failed, so even if we had a `data_failed` count it would never be more than 1, which would not be helpful.  In other words, if a job is running, there are no failed datums.

**Comment by gabrielgrant** [comment]
I believe this assumption that a job can only have a single failed datum is no longer valid -- my understanding is that as of 1.7 a job will try all datums (was just talking with @sjezewski about this)

**Comment by jdoliner** [comment]
It's still the case that we fail fast after a single datum fails, there isn't a guarantee that only one datum can fail to process, since things are running in parallel, but after a job completes there's always a single datum that gets reported as the reason for the failure in the `Reason` field. I don't think there's going to be a useful way to expose datum failures in the progress section, which is already fairly complicated by a number of different datum states. The way datum failures get exposed in the `Reason` seems like it's a lot more useful and gives people a good idea what's going on.
