### ISSUE TITLE
Add caching

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#225]
Being an immutable data store, PFS is naturally suited for optimizations involving caching, since cache invalidation at the block level is a non-issue (because blocks are immutable).  Currently caching is nonexistent in PFS.

There are three levels of caching that can be considered:
1. Caching at the object store level, in order to minimize disk access.  This one is difficult because PFS is oblivious to the actual implementation of the underlying object store (such as s3), so we probably can't do much here.
2. Caching at pachd, in order to minimize data transfer over the network.  That is, instead of always retrieving data from the potentially remote object store, pachd can maintain a local cache for blocks.  This cache would be used whenever possible.  Which caching algorithm to use is up for design.  The cache can even be managed by the client as is the case in HDFS.  That is, we'd have an API that lets the client specify "I want these blocks/commits/repos cached."
3. Caching at the client, in order to minimize data transfer over the network.  This is probably not the best idea since clients are usually assumed to be memory constrained.

Note that this issue is related to #223 since if data is directly transferred between the client and the object store, then the second bullet point becomes irrelevant.

**Comment by sjezewski** [comment]
WRT 1) -- while its AWS specific, it would be interesting to see if cloudfront (their CDN) improves performance. Since the obj's are immutable, that could provide us an easy win. Especially if this is combined with #223 and the client is directly requesting the data. (Then we really gain from the distributed edge caching of cloudfront)

(FYI - Even within the same aws region, downloading from a bucket in the same region, I've only seen ~4MB/s)

**Comment by jdoliner** [comment]
So we currently do 2, and I think 3 is unlikely to be something we want to do ourselves. It's unclear that 1 is really something we'd "do". It might just be as simple as: turn on cloud front and see what happens. So I'm going to close this.
