### ISSUE TITLE
pachctl enterprise activate --expires formatting 

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2265]
`pachctl enterprise activate`'s  `--expires` flag claims to accept either iso-8601 or rfc-3339 formatted strings, but it actually seems to reject both.

```
$ pachctl enterprise activate $(cat "customerTokens/valid-activation-code.txt") --expires "$(date --rfc-3339=seconds)"
could not parse the timestamp "2017-09-11 14:51:02-07:00": parsing time "2017-09-11 14:51:02-07:00" as "2006-01-02T15:04:05Z07:00": cannot parse " 14:51:02-07:00" as "T"
```
seems to imply it may not like the space (although it does seem to have interpreted it properly). ISO uses the T, but that doesn't work either because of timezone format:
```
$ pachctl enterprise activate $(cat "customerTokens/valid-activation-code.txt") --expires "$(date --iso-8601=seconds)"
could not parse the timestamp "2017-09-11T14:51:02-0700": parsing time "2017-09-11T14:51:02-0700" as "2006-01-02T15:04:05Z07:00": cannot parse "-0700" as "Z07:00"
```
It does seem to take a string with no TZ set (ie UTC):
```
pachctl enterprise activate $(cat "customerTokens/valid-activation-code.txt") --expires "2017-09-11T12:31:15.000Z"
```
But using the `date` util's `--utc` flag still doesn't work:
```
$ pachctl enterprise activate $(cat "customerTokens/valid-activation-code.txt") --expires "$(date --iso-8601=seconds --utc)"
could not parse the timestamp "2017-09-11T21:51:02+0000": parsing time "2017-09-11T21:51:02+0000" as "2006-01-02T15:04:05Z07:00": cannot parse "+0000" as "Z07:00"
$ 
$ pachctl enterprise activate $(cat "customerTokens/valid-activation-code.txt") --expires "$(date --rfc-3339=seconds --utc)"
could not parse the timestamp "2017-09-11 21:51:04+00:00": parsing time "2017-09-11 21:51:04+00:00" as "2006-01-02T15:04:05Z07:00": cannot parse " 21:51:04+00:00" as "T"
```

**Comment by msteffen** [comment]
Per slack, `date -Iseconds` works:
```
$ pc enterprise activate $(cat activation-code.txt) --expires $(date -Iseconds)
Activation succeeded. Your Pachyderm Enterprise token expires 2017-09-11 22:06:58 +0000 UTC
```

Are you using `date` for tests? If so, does the fact that `-Iseconds` seems to work fix the issue?

(For future reference: the go docs for date parsing (https://golang.org/pkg/time/) indicate that when Go tries to parse RFC 3339 timestamps, it expects dates of the form `2006-01-02T15:04:05Z07:00`. I gather that in the examples above, the error was that the time zone was denoted with +/- instead of Z. AFAICT, that notation actually is RFC 3339 compliant, but not ISO 8601 compliant. Go also seems to err in that direction in requiring `T` as the date/time separator, when `RFC 3339` explicitly allows a space while ISO 8601 doesn't. In general, strict ISO 8601 compliance seems to be necessary here, which is kind of annoying, but fortunately `date` supports that)

**Comment by msteffen** [comment]
I'm closing the issue because my impression is that `date -Iseconds` will work, but we should re-open it if not

**Comment by msteffen** [comment]
Re-opening because I didn't read your comment carefully. Your second command, which used `--iso-8601=seconds` totally should've worked

**Comment by msteffen** [comment]
Interestingly, our `date` tools appear to be different. When you set `--iso-8601=seconds`, it emits `2017-09-11T14:51:02-0700` (which doesn't have a colon in the time zone, which breaks the parser) whereas mine emits `2017-09-11T14:51:02-07:00`. Both seem to be 8601-compliant.

I'll update pachd to accept both

**Comment by gabrielgrant** [comment]
Weird that our `date` tools would be producing different formats, but it's also weird that Go clearly does recognize the format and translates it into what it seems to want: `parsing time "2017-09-11T14:51:02-0700" as "2006-01-02T15:04:05Z07:00"`

...but then still for some reason refuses to accept it -_-

**Comment by msteffen** [comment]
This is actually an interesting feature of Go—either totally brilliant or totally stupid depending on who you ask. The way Go handles date formats is by using example dates, rather than %Y %M %m etc tokens (what's the code for two-digit year again?).

Basically, you format the date "January 2, at 3:04 PM and 5 seconds, 2006, in GMT +7 in the format you want, and then Go will render/parse dates in that format. So the date format string "2006-01-02T15:04:05Z07:00" corresponds to YYYY-MM-DD"T"HH:MM:SS[timezone]. Because the timezone component of the string is "Z07:00" rather than "Z0700" it expects a colon, which `date` doesn't always seem to print.

**Comment by JoeyZwicker** [comment]
@msteffen Status?

**Comment by sjezewski** [comment]
stale
