### ISSUE TITLE
Kubernetes DNS doesn't resolve external DNS addresses

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2279]
Just upgraded to current master and login seems to have broken. Getting the same failure from both the APi through the browser and from `pachctl` (which makes sense: this is a pachd issue):

```
$ pachctl auth login
(1) Please paste this link into a browser:

https://github.com/login/oauth/authorize?client_id=d3481e92b4f09ea74ff8&redirect_uri=https%3A%2F%2Fpachyderm.io%2Flogin-hook%2Fdisplay-token.html

(You will be directed to GitHub and asked to authorize Pachyderm's login app on Github. If you accept, you will be given a token to paste here, which will give you an externally verified account in this Pachyderm cluster)

(2) Please paste the token you receive from GitHub here:
<MY_GITHUB_TOKEN>
error authenticating with Pachyderm cluster: rpc error: code = Unknown desc = error getting the authenticated user: Get https://api.github.com/user: dial tcp: lookup api.github.com on 10.0.0.10:53: read udp 172.17.0.5:44888->10.0.0.10:53: i/o timeout
```

**Comment by msteffen** [comment]
It turns out that this login issue is a symptom of a larger issue that we've been struggling with for a while: when we deploy kubernetes in docker on our local machines, it uses its own kuberenetes-internal DNS server, which can resolve domains inside the cluster (e.g. for StatefulSets) but can't resolve domains outside the cluster

**Comment by msteffen** [comment]
One fix: set the `--cluster_dns` flag in `etc/kube/internal.sh` to `8.8.8.8` (Google's public DNS server). The line to modify is: https://github.com/pachyderm/pachyderm/blob/master/etc/kube/internal.sh#L10

**Comment by msteffen** [comment]
One fix that worked for me at about a year ago (I've been using kubernetes in minikube since then, which seems to handle internal and external DNS resolution by default) is to comment out `dns=dnsmasq` in `/etc/NetworkManager/NetworkManager.conf`, and then restart network-manager (`sudo service network-manager restart`), kubernetes, and docker

**Comment by JoeyZwicker** [comment]
What's the status here?

**Comment by sjezewski** [comment]
It's a configuration bug / edge case w k8s. It happens when you run
dockerized k8s locally and are also trying to use enterprise auth features.
So I think our team is probably the only folks in the intersection of those
groups. (This shouldn't be an issue for any cloud deployments w ent auth
login).

I've hit and Matt has hit it. I usually opt for the `8.8.8.8` workaround.
I'm not sure how many users run dockerized k8s locally. And if they do, I'm
not sure how they run it (they might use our make task or not).

I think we can close this.

**Comment by sjezewski** [comment]
Leaving this here as a breadcrumb ... I'm now seeing this on k8s 1.7 w minikube running on my local machine w `--vm` set to `none`.

[The solution posted here](https://github.com/kubernetes/minikube/issues/2027)


Basically ...

```
sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved
```
and edited /etc/resolv.conf to contain only:
```
nameserver 8.8.8.8
```

Worked for me. (I did have to restart minikube).

**Comment by edhemphill** [comment]
@sjezewski  - How were you able to get that to work?  My minikube overwrites all settings on boot, including changes to systemd  (I'm on k8s 1.8 w/ a Hyper-v VM driver)

**Comment by sjezewski** [comment]
I don't have a perfect solution yet ... I'm doing it as needed (I don't reboot that often), though you could add it to a startup script somewhere.
