### ISSUE TITLE
client initialization in pfs/server/driver.go is brittle

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#2295]
Currently, every method of pfs/driver calls initializeClient at the beginning. It turns out that if you forget to make this call, you make get intermittent segfaults (where the code tries `d.pachClient` to make an RPC, and `d.pachClient` is null)

Getting the pach client should be gated on initializing the pach client.

**Comment by JoeyZwicker** [comment]
Any updates to this issue? How important is this?

**Comment by sjezewski** [comment]
This is tech debt. It's importnat.

It can be a nasty gotcha if you don't see / adhere to the convention. I
believe I ran into it recently but asked Matt about it and so I figured it
out. Generally we don't like conventions in the codebase that have bad side
effects ... as its easy to lose track of those, and shoot ourselves in the
foot.

**Comment by jdoliner** [comment]
driver has been substantially refactored since this and now passes the `pachClient` in as an argument (in some cases inside of a `TransactionContext`. I think that should guarantee we don't see issues like this and afaik we haven't seen one in quite a while. Closing this, feel free to reopen if you hit something like this again.
