### ISSUE TITLE
Write papers or architectural documentations about pfs/pps

### ISSUE THREAD

**Issue by cxxly** [pachyderm/pachyderm#230]
I have find a paper about pfs [DataHub: Collaborative Data Science &
Dataset Version Management at Scale](http://arxiv.org/pdf/1409.0798v1.pdf), Is there any paper about pps, I want to make some optimization about this and make some contributions.

**Comment by derekchiang** [comment]
Hi @cxxly, we were not previously aware of this paper that you found, but it's a very interesting read!  The system described in the paper is largely motivated by the same problems that motivated the design of pfs/pps, although their implementation and UI differ a lot from ours (e.g. they use postgres as the backend while we use a block store like s3; they expose datasets through a SQL-like language while we use fuse; etc.).  I can certainly see us draw some inspirations from this paper down the road.

As for your question specifically, we have not written any paper for pfs/pps just yet.  However, we do plan to write some white papers about pfs/pps in the near future.  We will make sure to let you know when that happens!

In the mean time, if you would like to learn about pfs/pps in order to contribute, the best place to look is the code itself.  I suggest starting by playing with the [fruit stand example](https://github.com/pachyderm/pachyderm/tree/master/examples/fruit_stand) in order to learn how Pachyderm works, and then read the [protobuf](https://github.com/pachyderm/pachyderm/blob/master/src/server/pfs/pfs.proto) [files](https://github.com/pachyderm/pachyderm/blob/master/src/server/pps/pps.go) in order to learn the internal protocols.

Do not hesitate to reach out to us if you have more questions!

**Comment by derekchiang** [comment]
1.0 worthy? @jdoliner @sjezewski @JoeyZwicker

**Comment by derekchiang** [comment]
As in, should we put out an architectural document that describes the internals of pfs/pps.  Similar to this page for Hadoop: http://hadoop.apache.org/docs/r2.4.1/hadoop-project-dist/hadoop-hdfs/HdfsDesign.html

**Comment by jdoliner** [comment]
It would be awesome to have this for 1.0, but I don't think we're going to want to hold the release for it. I'm going to put this under the milestone for now in case we do have time but it might get removed later.

**Comment by sjezewski** [comment]
This issue has been open for over a year. I'm closing.

FYI - We still do want to add more docs about our processing model.
