### ISSUE TITLE
Partition input by configurable delimiters

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#232]
Discussed offline with @jdoliner.  Basically, currently input to map jobs (i.e. jobs that don't have the "reduce" flag set) are partitioned using newline as the delimiter.  This works for some data sets but not all of them.  We could alternatively partition whole JSON objects, for instance.

What's needed is a way to specify delimiter at the repo or even directory/file level.  We can even support custom scripts for partitioning at some point.

**Comment by JonathanFraser** [comment]
This is actually starting to bump into our stuff. JSON is a natural serialization format for a lot of our data, however, some of our files can contain NaNs. JSON does not support NaNs and so we are left with looking for a different format. most of the other options are binary formats but of course new lines don't make sense for binary files.  This leaves us with the wonderful option of base64 encoding the binary files to make them work with new lines. This would work, but it's a little clunky and it would be nice if there was a way to split things up a little more nicely.

**Comment by jdoliner** [comment]
@JonathanFraser we hear you on this one, this is going to be among the first things we tackle once 1.0 is shipped later this week, moving this into 1.1 to reflect that.

Looking forward to that I'd love to understand your use case a little bit more and start talking about a potential design for this one. It seems to me that binary files are slightly different from what we're doing with new lines because there's nothing in the actual data that indicates where it's safe to split, instead we need to take that information from the users when they give us the data. I also think this mode should be the default because it's the least magical of the behaviors.

Here's what the behavior would look like in terms of our proto API:

```proto
enum Chunking {
  CHUNKING_NONE = 0;
  CHUNKING_LINE = 1;
  CHUNKING_JSON = 2;
}

message PutFileRequest {
  File file = 1;
  FileType file_type = 2;
  bytes value = 3;
  string handle = 4;
  Chunking chunking = 5;
}
```

`CHUNKING_NONE` would be the behavior you'd use for binaries, with this behavior the `PutFileRequest` would _never_ be broken across multiple blocks. This would give the user complete control over where we chunk.

`CHUNKING_LINE` be our current behavior.

`CHUNKING_JSON` would chunk based on matching `{`s.

**Comment by JonathanFraser** [comment]
I presume with `CHUNKING_NONE` then the shard could grow up to the full object size limit of the backing store? For performance reasons you probably don't want to but it would be nice if that was an option, also how would one decide the chunking behaviour in the fuse layer. Maybe its a property of the entire mount?

**Comment by jdoliner** [comment]
I was thinking that in `CHUNKING_NONE` we'd do exactly as you describe and let the only limit on chunk size be object store, we'd just propagate whatever error the object store gives back to the user.
This does have the downside that now behavior would change with different object stores. We could actually take it a step farther and add a way to spread a single chunk across multiple objects. Similar to what we do with blocks but we'd hash all of these objects as a unit so they'd all wind up in the same container together, that would effectively remove any size limitations.

I could see a couple of ways for fuse layers to work. Doing it per mount does make some sense because that basically turns into a per job granularity for delimiter behavior which could work. I could also see making the delimiter property of the repo as a whole since repos are supposed to contain similar data. Finally we could also do it based on file extensions. For example file with a `.json` suffix would automatically use json chunking.
