### ISSUE TITLE
multiple registrations for /debug/requests when trying to connect with client

### ISSUE THREAD

**Issue by erikreppel** [pachyderm/pachyderm#238]
When trying to interact with the pachyderm client you get `panic: http: multiple registrations for /debug/requests`  when trying to establish a connection.

The code I wrote:
```
package main

import (
    "fmt"
    "github.com/pachyderm/pachyderm/src/client"
)

func main() {
    c, err := client.NewFromAddress("10.0.0.115:650")
    if err != nil{
        fmt.Println("Error:", err)
    }
    fmt.Println("Established client")     
}
```

The full output of running:
```
$ go run pull_data.go 
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
panic(0xa53fa0, 0xc8201b0910)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
net/http.(*ServeMux).Handle(0xc820014f30, 0xce8d80, 0xf, 0x7efdc91e9090, 0xe31e38)
	/usr/local/go/src/net/http/server.go:1926 +0x297
net/http.(*ServeMux).HandleFunc(0xc820014f30, 0xce8d80, 0xf, 0xe31e38)
	/usr/local/go/src/net/http/server.go:1955 +0x6a
net/http.HandleFunc(0xce8d80, 0xf, 0xe31e38)
	/usr/local/go/src/net/http/server.go:1967 +0x41
github.com/pachyderm/pachyderm/src/server/vendor/golang.org/x/net/trace.init.1()
	/home/erikreppel/Dev/go/src/github.com/pachyderm/pachyderm/src/server/vendor/golang.org/x/net/trace/trace.go:118 +0x38
github.com/pachyderm/pachyderm/src/server/vendor/golang.org/x/net/trace.init()
	/home/erikreppel/Dev/go/src/github.com/pachyderm/pachyderm/src/server/vendor/golang.org/x/net/trace/trace.go:898 +0x592
github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc.init()
	/home/erikreppel/Dev/go/src/github.com/pachyderm/pachyderm/src/server/vendor/google.golang.org/grpc/trace.go:120 +0x5b
github.com/pachyderm/pachyderm/src/server/pkg/grpcutil.init()
	/home/erikreppel/Dev/go/src/github.com/pachyderm/pachyderm/src/server/pkg/grpcutil/local.go:39 +0x45
github.com/pachyderm/pachyderm/src/server/pkg/shard.init()
	/home/erikreppel/Dev/go/src/github.com/pachyderm/pachyderm/src/server/pkg/shard/sharder.go:925 +0x4c
github.com/pachyderm/pachyderm/src/client/pfs.init()
	/home/erikreppel/Dev/go/src/github.com/pachyderm/pachyderm/src/client/pfs/pfs.pb.gw.go:121 +0x7d
github.com/pachyderm/pachyderm/src/client.init()
	/home/erikreppel/Dev/go/src/github.com/pachyderm/pachyderm/src/client/client.go:63 +0x4f
main.init()
	/home/erikreppel/Dev/go/src/github.com/erikreppel/pach_playground/pull_data.go:23 +0x40
exit status 2
```

The error is caused because `Dev/go/github.com/pachyderm/pachyderm/src/server/vendor/golang.org/x/net/trace/trace.go` and 
`Dev/go/golang.org/x/net/trace/trace.go` both try to setup endpoints in the same place (`/debug/requests`, `/debug/events`). 

I found I could resolve the issues and connect either by altering the endpoints in the pachyderm copy of `trace.go` or deleting `pachyderm/pachyderm/src/server/vendor`, however when I tried removing my copy of net/trace (`Dev/go/golang.org/x/net/trace`) the client failed with other errors. I haven't tried starting Pachyderm without the vendor folder.

**Comment by sjezewski** [comment]
Hey Erik!

Yup thats exactly whats happening. In short, removing it from the server vendor directory should work O.K. but is not ideal - I'd like to figure out a better solution here.

I've run across a similar error myself. We've recently been working hard to make vendorization work for us and our users. It's challenging. Please make sure you're using the latest code as this is something we've been working the kinks out of.

The `src/server/vendor` folder exists to allow us to lock versions of the dependencies we need to build and run pachd.

But any code that is only using the pachyderm client (anything under `src/client/...`) should not require the server vendorization. 

Basically -- we did a refactor to enable our users to vendorize pachyderm client.

In fact - I've been playing w some sample apps to make sure that we allow our users to only import the client and build successfully. You can look at `github.com/pachyderm/sandbox` to see how I'm using pachyderm/pachyderm as a 'user'. In that app, I'm vendoring as well, and I'm actually vendoring `golang.org/x/net/trace` under my sandbox. So - Its not yet clear to me why I'm able to vendor it under an app but you're getting the conflict.

It would help me to know some sanity checks:

- your version of golang
- any value of GO15VENDOREXPERIMENT in your env

But beyond that, it would help if I could see `pull_data.go` and the repo that contains it. Otherwise, its possible that my version of pachyderm that I've vendored under sandbox is out of date, and this is an issue w the latest code. I can look into that as well.

**Comment by erikreppel** [comment]
Hey Sean,

I'm working off a pull of the master branch from this morning with Go version 1.6, GO15VENDOREXPERIMENT was not set.

I ran into this: https://github.com/pachyderm/pachyderm/blob/master/src/client/pfs/pfs.pb.go looks like the generated pfs file is calling shard from server. There might be a dependency of shard that calls the vendor version of trace.

[Here's](https://github.com/erikreppel/pachyderm-client-examples) the repo of pull_data. The method I used for connecting is the same, although I played with a few other things after I got the connection working.

Totally understandable. Have you guys looked at something like [gopkg.in](http://labix.org/gopkg.in) for taking specific versions?

For now while prototyping I'll keep removing vendor until a better solution comes together.

**Comment by sjezewski** [comment]
Yea, I expect client to import shards which in turn imports other things. We chose to leave that import there because that avenue of code requires fuse and that logic should stay in server. But locally it seemed to be working.

(I wasn't familiar w gopkg.in, but love the idea, I can't wait for golang to adopt some mature versioning tools. In our case though, I think what would be required is each dependency of ours to be versioned in the way gopkg.in requires, which isn't really under our control. Also - its unclear to me what happens in the import paths using gopkg.in --- if you can only specify the version during go get, I'm not sure how we'd make it enforceable ... but I'll do more reading on gopkg.in ... thanks for that lead)

I'll play w your code this morning to see what I learn.

**Comment by sjezewski** [comment]
I can reproduce the error locally. Makes sense.

When I vendorize under the app (see [my code](https://github.com/sjezewski/pachyderm-client-examples/tree/vendor/pull_data) ) the import conflict goes away. Also makes sense.

What I didn't realize is that our method of vendorization basically requires our users to vendorize as well. We want to enable our users to vendorize, but I don't really like the idea of making it a hard requirement. 

I'm thinking about a few ways we could try to keep our vendorization for server (which I do think is a requirement for us) while not requiring vendorization for our users. I'm going to play w one of those ideas, but I'm not super confident there is a way to do both. In which case, we'll have a harder design decision to make here.

**Comment by sjezewski** [comment]
Ok ... I do have a working version locally that allows me to vendor the server and provide the pachyderm repo without those files so that a new user won't have the vendored server files and so won't have the vendorization requirement.

But ... this has some consequences for our internal development process. I'll discuss w the team before we choose an approach here. Will provide more updates once we make a decision.

This has been amazingly helpful! Thanks for the bug report.

**Comment by erikreppel** [comment]
Awesome, sounds good.

**Comment by sjezewski** [comment]
Turns out it was easier (and far more elegant) to eliminate all imports to `src/server`

For some reason I thought that the shard import path took a bunch of server components with it, but turns out it was manageable.

**Comment by sjezewski** [comment]
Should be all set if you pull master now ... it'll play nice vendoring or not :-)
