### ISSUE TITLE
Double-asterisk glob patterns should be documented

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2386]
Double-asterisk glob patterns landed recently in #2330 but haven't been documented. These should probably be added to examples in the [pipeline spec doc](http://docs.pachyderm.io/en/latest/reference/pipeline_spec.html#the-input-glob-pattern) and the [distributed computing doc](http://docs.pachyderm.io/en/latest/fundamentals/distributed_computing.html#defining-datums-via-glob-patterns)

**Comment by nadegepepin** [comment]
This is how `/*/*` is documented today in 1.12.x: https://docs.pachyderm.com/latest/concepts/pipeline-concepts/datum/glob-pattern/#glob-pattern . 
I agree that we could explain the pattern in a more visual way - perhaps by providing a table of all possible outcomes given the example mentioned in the doc rather than a wordy explanation, but overall, I don't think the explanation is unclear. What exactly are we supposed to add/clarify here?
