### ISSUE TITLE
Make Cloudfront reads more robust

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2399]
Reported in users. Jobs fails w/:

```
# cloudfront returned HTTP error code 500 Internal Server Error for url http://drjitb8uzax3c.cloudfront.net/pach/block/aada03b34d444b9e9b950bf6dd2663db?Expires=1507824180&Signature=EKYQ4sE5kqmqfwd4BylQxMgitA1kWhRgIg-vOcMtrlwNGsuT4Ht24DbcpwH~BeGcqHdFA8SUsWkOMn1cNRtfAsFO1DNNS7gVZKEely8K70id~DR-7uG59rIa3U6aja9IEHp3F~QWoyuksrFe0xwxt9ZNKrhG-heLZ0mMQDVH1Z5Vt~c8gcekc7WRoSMp18xuFjBqz1LyXzoFSG2FrjXhRf1hoNI5U1BA4bcP0Wqqvgh0kQMX4rBR~fkcMv7zpPUBdnTEnPEzb2XEX9dm6eLouQBpdF-IMdmze-Q151Ri9FM9lZcY4GKX34H~-bSHSE-U~QWmW~wRPFLt-Csq309LgA__&Key-Pair-Id=APKAJ2SKC3QL6C6K6SHA

[1]+  Exit 1                  pachctl get-file -p 1000 create-vrt-manifest master manifest.txt > /tmp/manifest.txt
```

It might be a good idea to make CloudFront reads more robust such that they retry.

**Comment by JoeyZwicker** [comment]
Is this related to #2438 at all? Or this just adding retry logic for cloudfront request?

**Comment by dwhitena** [comment]
I think this is mainly for the retry logic @JoeyZwicker

**Comment by sjezewski** [comment]
The cloudfront request is already wrapped in retry logic:

https://github.com/pachyderm/pachyderm/blob/master/src/server/pkg/obj/amazon_client.go#L129

I'm pretty confident this isn't related to #2438 since the max backoff elapsed time is 15m (so it shouldn't be possible for us to generate a signed URL that expires before the backoff completed).

I don't think there is a todo here, so I'm closing the issue.
