### ISSUE TITLE
Store raw (text) version of pipeline spec as entered by user

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2402]
In order to allow users to update the pipeline spec, it would be useful if we stored the actual raw text that they entered, in addition to the parsed version that we actually use internally

this would:
- preserve key ordering
- not add additional fields that are contained in a PipelineInfo object, but that shouldn't be included in the pipeline spec (`state`, `recent_error`, `job_counts`, etc.)
- doesn't have default values populated that weren't explicitly set by the user

Somewhat related to #1833

**Comment by jdoliner** [comment]
I'm not sure I see what the benefits of storing this would be. What would it allow us to do that we can't do now?

**Comment by JoeyZwicker** [comment]
Update pipeline in the Pipeline Builder (PB) is one key reason. 

We want a user to be able to click on the DAG, click an "update pipeline" button, and have the PB autofill in the fields that are already set for that pipeline. In the current state, we can't tell the difference between set values and default values populated that weren't explicitly set by the user. And showing the user every field kind of defeats the purpose. 

A second use case is, now that we'll have the PB, users will want a way to get out or download a JSON spec file to save in Git or share otherwise.

**Comment by JoeyZwicker** [comment]
We decided against this for now and will work around it in the UI. May revisit later if a new compelling reason emerges. closing
