### ISSUE TITLE
"failed to deserialize parent hashtree: unsupported HashTreeProto version 0"

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#2411]
The issue seems to stem from this code: https://github.com/pachyderm/pachyderm/blob/master/src/server/worker/api_server.go#L369-L371

Notice how, if an error is encountered, we don't exit and instead proceed with the empty buffer.

**Comment by JoeyZwicker** [comment]
@jdoliner whats the status of this issue? You marked it as 1.7 and it'd be good to have more details about what we want to fix here. There's easy ways to make the error go away, but is there a bigger problem that needs to be figured out too?

**Comment by jdoliner** [comment]
> There's easy ways to make the error go away

Are there?

The status is that this comes up if there's an object that Pachyderm thinks it's written to s3 which turns out not to be there. That type of situation can cause all sorts of bugs, none of which are particularly fixable. It's possible we're doing something dumb which causes this particular issue but it's also possible that it's just a general corruption issue. Perhaps this should be moved out of 1.7 since there's no concrete thing we know of to fix.

**Comment by JoeyZwicker** [comment]
Sounds like I was misunderstanding this issue. 

With regard to Derek's initial submission: 
> Notice how, if an error is encountered, we don't exit and instead proceed with the empty buffer.

Have we changed our code to exit here instead of proceeding? Should we be doing that?

**Comment by jdoliner** [comment]
> Have we changed our code to exit here instead of proceeding? Should we be doing that?
Yes

But all that means is that you'll get a nicer error here.

**Comment by sjezewski** [comment]
stale
