### ISSUE TITLE
403 Forbidden error from cloudfront

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2438]
discussed in slack here: https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1508451843000274

 @homme has a long-running job that, after a couple hours, starts showing 403 Forbidden error from cloudfront:

```
{
  "pipelineName": "vrt-dataset-rasters",
  "jobId": "8800c431-ddc4-45d9-8694-01e52f49522c",
  "workerId": "pipeline-vrt-dataset-rasters-v1-6d9n1",
  "datumId": "93df5614181193411778fc2d6a691c244a8ee79e0c1efc3d98e3a9ece20cb2b8",
  "data": [
    {
      "path": "/datasets",
      "hash": "Cn8vSW06OQoxdbd/b7YWur2fMRIMRUV9jd7AXnb8zVA="
    },
    {
      "path": "/World30DSM/42919e20-b4e8-11e7-a5a5-0a5864642e07.json",
      "hash": "htfI7fzWsXZnKG5HTM1ptd4DvGeNYO/RPUrQvLpzqaA="
    }
  ],
  "ts": "2017-10-19T22:17:04.765990812Z",
  "message": "process call finished - request: job_id:\"8800c431-ddc4-45d9-8694-01e52f49522c\" data:<file_info:<file:<commit:<repo:<name:\"datasets\" > id:\"baefcbaac12746938c39552ff92da39a\" > path:\"/datasets\" > file_type:DIR size_bytes:1941 hash:\"\\n\\177/Im:9\\n1u\\267\\177o\\266\\026\\272\\275\\2371\\022\\014EE}\\215\\336\\300^v\\374\\315P\" > name:\"datasets\" branch:\"master\" > data:<file_info:<file:<commit:<repo:<name:\"list-dataset-contents\" > id:\"d817db67467149b78a0d37717e7d69c3\" > path:\"/World30DSM/42919e20-b4e8-11e7-a5a5-0a5864642e07.json\" > file_type:FILE size_bytes:275 hash:\"\\206\\327\\310\\355\\374\\326\\261vg(nGL\\315i\\265\\336\\003\\274g\\215`\\357\\321=J\\320\\274\\272s\\251\\240\" > name:\"list-dataset-contents\" branch:\"master\" > enable_stats:true , response: <nil>, err cloudfront returned HTTP error code 403 Forbidden for url http://<elided>.cloudfront.net/pach/block/063e6f67d52a4985bfa21a2ffb557ab4?Expires=1508455024&Signature=<elided>, duration: 320.971675ms"
}
```

it seems the `expires` timesamp is in the past (that's 11:17:04 PM GMT/4:17:04 PM Pacific), so my guess is that is the source of the problem -- we probably do the auth at the beginning of the job (or maybe a run?), but don't properly handle the expiry

i'm not sure whether we ever refresh that signature -- we may do it at some point once a datum is rescheduled, in which case the job would complete eventually and only datums in-flight when the expiry happens would have to be retried, but it's also possible that we don't ever refresh, in which case these datums would never complete and the job would fail

If the latter is true, it seems this may be the source of the long-running job failures @homme has been struggling with lately

**Comment by gabrielgrant** [comment]
See discussion on #2437

**Comment by gabrielgrant** [comment]
@homme i'm not 100% sure, but i'd be very surprised if the token were tied to a pipeline rather than a job, so that should work

@sjezewski can you confirm?

**Comment by sjezewski** [comment]
Right now it's tied to the obj client, which gets initialized when the worker starts up. So cycling the pod may help (killing the pod and waiting for a restart).

**Comment by sjezewski** [comment]
That's not quite right.

It looks like a new amazon `Reader` is created every time we get an underlying object from the obj store. (This could happen 1 to many times per file).

So it's weird that you're getting an expired URL ... unless perhaps this is a rather large file that takes longer than 1 hour to download? What is the size of that file?

**Comment by gabrielgrant** [comment]
I'd be surprised if this error occurred due to a single request that took a long time to download -- my understanding is that generally expiry is checked at the beginning of a request, and the request is allowed to complete regardless of how long it takes.

In fact, this almost certainly has to be a request that is initially made after the expiry time: the HTTP error code is returned at the very beginning of the response, so if the token was valid when the request began, but expired while the data was in flight, there's no way to change to 403 response, because the 200 would have already been sent. The only option would be to just abruptly stop the data stream (and even that assumes amazon is actually checking for this, which, as i said above, i seriously doubt they are)

**Comment by gabrielgrant** [comment]
Looking at the log timestamp, we can see that this is just barely timed out -- the log line was recorded ~766ms after the signature expires. So what is possible is that the request was sent _just_ before the expiry time (22:17:03.99, say). If the client did a simple check at that point, the signature would still appear to be valid. But in that case it likely wouldn't be received by amazon until a moment after it expired, due to network latency (say 20ms later, at 22:17:04.019)

If this signature is getting generated immediately before sending, with a 1 hour window, though, it's not clear to my why/how this could be occuring

**Comment by homme** [comment]
@gabrielgrant @sjezewski just to let you know the Pachyderm team is always welcome to have access to our cluster to help in the debugging...

**Comment by gabrielgrant** [comment]
@homme great, thanks -- I'll talk to @sjezewski tomorrow and see if it needs more debugging, or if we can easily identify the fix by just looking at the code

**Comment by homme** [comment]
Thanks @gabrielgrant that's appreciated.  In the meantime I'm going to investigate options for setting up a workaround for that step by hooking up our pipeline docker images to a job queue for the I/O.

**Comment by sjezewski** [comment]
I don't think that's quite right.

The worker master client makes the GRPC `Process()` call to an individual worker. That worker then downloads the input data, which in turn calles `GetFile` which calls `GetObject()`. For each call of `GetObject()` a new amazon client reader is created, and at that time a new signature and new expiry is generated.

So. The fact that the log line's timestamp is just after the expiry makes sense. If you make a call w an expired url, of course the error will bubble up just a bit afterwards.

What is unclear is still exactly why/how the URL could've expired. We generate the signed URL right before we attempt to get that URL. I do think a rather large download could do it. (I would still like to know what the max file size is for all the inputs to this pipeline)

But I have a new hypothesis. @homme -- this workload involves ~1M files, correct?

It's possible that we've hit a rate limit w cloudfront. That seems like it shouldn't happen ... cloudfront is a CDN and should be designed for this. However, this is a large workload, and it could be that they measure the workload differently per key rather than across keys and degrade differently.

This would also account for the small end to end time we see in the log message (~400ms). There's no way it could hang for an hour on a large file if thats the total run time of that call. And this also supports the idea that we've hit a limit, and this just happens to be a symptom of what happens after we hit that limit. We saw similar things once we hit the original S3 rate limiting.

I would like to confirm that this is a large # of files @homme . It would be great if we could get a file count for an individual datum. But barring that, your total file count and glob patterns will suffice.

Then this becomes a matter of confirming this theory and engineering the workaround.

I believe we already have a semaphore for rate limiting our downloads from an obj store. I can try lowering that bandwidth and seeing if that helps. It will make it so that downloads take a bit longer ... but they will eventually succeed if we're right.

@homme -- I'd also like to get access to the cluster (you can ping me the `kubeconfig` file on slack) so that I can poke around a bit. In particular I'm interested in seeing the logs / existing download timing for other datums.

We'll go from there.

Ideally, I don't like solutions that slow us down. One thing I'll be thinking on is if we can configure cloudfront differently to get past this rate limiting. 1M files per datum is a use case we want to support. And we'll get it working. But I'd also like it to be as fast as possible.

**Comment by homme** [comment]
@sjezewski thank you for the detailed insight - that's really interesting. I'll try and reply to your questions:

> I would still like to know what the max file size is for all the inputs to this pipeline

The inputs are small JSON documents that are less than 1KB in size.  They actually reference much larger resources on CloudFront that we consume in the pipeline.

> this workload involves ~1M files, correct?

It actually involves around 4.5 million files.

> It's possible that we've hit a rate limit w cloudfront. That seems like it shouldn't happen ... cloudfront is a CDN and should be designed for this.

I think it's very possible. I have been dealing with similar issues in the pipeline code (yesterday in testing we hit CloudFront with ~30 million requests). CloudFront doesn't like this, and will often return a `503 Service Unavailable` response which I deal with successfully using simple retry logic (it's a bash pipeline ;)). 

> It would be great if we could get a file count for an individual datum. But barring that, your total file count and glob patterns will suffice.

The individual datums for the large pipelines (after fanning out) consist of the single JSON files I mentioned.  A typical glob pattern is `/*/*/*/*.json`.  In an effort to optimise I have set atoms to be `lazy` as I can get the information I need from the directory structure in these cases.  I haven't got an exact figure to hand but as I mentioned total file count is in the order of ~4.5M. 

> I believe we already have a semaphore for rate limiting our downloads from an obj store. I can try lowering that bandwidth and seeing if that helps. It will make it so that downloads take a bit longer ... but they will eventually succeed if we're right.

That sounds good.  Perhaps some kind of exponential backoff that feeds into a variable that is global to a worker so that request rate just hovers on the edge of what CloudFront considers acceptable? Adding some randomness to that in terms of increasing downwards pressure on that limit could ensure that we're being as efficient as possible. The worker could even share that value around so that new workers are seeded with something useful.

> I'd also like to get access to the cluster

I'll happily give you access to the cluster when I've got it up and running again - I tore it down and rebuilt it, but I need to create a new pachyderm bucket as @gabrielgrant and I think the existing one is corrupted.

>1M files per datum is a use case we want to support. 

We're currently dealing with the baby dataset (~2.2TB) - the big one is 10TB :)  I haven't done a calculation of total files for that yet!

**Comment by sjezewski** [comment]
Thanks for the detailed reply @homme 

At the end of the day, we'll look at this more as we can reproduce it. So if you have a case that does, let us know.

---

But, some thoughts:

I'm still not sure how the URL could be expiring in that code. Looking at the max elapsed time in the retry loop, its set at 15m, so that URL shouldn't expire. (Another reason I'd like to see it reproduced in the wild).

If we are in fact hitting cloudfront rate limiting, we have some options to scale appropriately. We might want to specify the semaphore/bandwidth as an advanced pipeline setting. That may allow the job to complete, though at a slower rate. It's a bit tricky to be 'smart' about that setting ... since:

a) its unclear how dynamic/static the throttling is
b) its hard to know over different job runs how many files are in a datum ... and distribute that info to the other workers

Another idea is to be smarter about our distribution of objects on s3. 

(AWS has certain recommendations about key distribution that we could use. At this point, I'm providing breadcrumbs for myself here ... but that basically means distributing the hashes at the top level of the key, e.g. `/asdfdf` objects instead of `/pach/obj/asdfdf` ... the former will route to different s3 app servers and get more evenly distributed and the rate limiting goes into effect per app server for s3).

If we are seeing rate limiting, we would prefer a solution that gets past it, and doesn't slow us down. Thanks for sharing those scale numbers, that's helpful for us to know when designing.

**Comment by sjezewski** [comment]
stale
