### ISSUE TITLE
`scaledownthreshold` should not be reset on pachd restart

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2451]
from #2053: 
`For example, if the node with pachd dies (or pachd get OOM or OOD killed), when pachd restarts, it'll spin up all pipeline workers at once, even those that were previously scaled down via scaledownThreshold, causing cascading resource failures.

We're seeing more production clusters that rely on scaledownThreshold to manage resources so these types of failure cases are also becoming more common.`

**Comment by JoeyZwicker** [comment]
Still an issue for prod clusters.

**Comment by jonandernovella** [comment]
+1

**Comment by sjezewski** [comment]
This happened to me yesterday on a production installation. The cluster eventually did 'recover' since those timeouts were low, and the pods got scaled back down.

Additionally, a failed job that happened before the restart was re-attempted. I see the job multiple times in list job, but the input commits are different ... and come from an upstream failed job that was re-attempted and failed.

**Comment by jdoliner** [comment]
`scaledownthreshold` has been replaced by `standby`, which starts in a standby state by default.
