### ISSUE TITLE
Review PFS provenance

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#2494]
This is a placeholder bug so that I can focus on finishing https://github.com/pachyderm/pachyderm/issues/2380 without getting further sidetracked. I believe the code here doesn't compute the full transitive closure of provenance, it just extends the search one level up the graph (and therefore may be incorrect, but I'm not sure). What if the DAG has diameter > 2?
```go
// src/server/pfs/server/driver.go:253
		// compute the full provenance of this repo
		fullProv := make(map[string]bool)
		for _, prov := range provenance {
			fullProv[prov.Name] = true
			provRepo := new(pfs.RepoInfo)
			if err := repos.Get(prov.Name, provRepo); err != nil {
				return err
			}
			// the provenance of my provenance is my provenance
			for _, prov := range provRepo.Provenance {
				fullProv[prov.Name] = true
			}
		}
```

**Comment by brycemcanally** [comment]
Yeah, this looks like it only gets the provenance from the previous two levels of the DAG. Since the notion of provenance is moving to branches in the new commit invariants design this should be getting removed/changed right?

**Comment by jdoliner** [comment]
Repo provenance is going away soon but I think this is actually computing the full transitive closure. We are only iterating through one level of the DAG but we're iterating through the transitive closure of those nodes, so there's no need to traverse further because we store transitive closures at every node.
