### ISSUE TITLE
`GetLogs` is bursty

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#2501]
While working with a user on their pipeline, we observed behavior where running `pachctl get-logs --job=<job>` stopped displaying new logs for a few minutes, and then suddenly, it would output a large block of new log lines (which stayed static, until the next block of new logs started appearing, etc).

It seems like user logs are being blocked or buffered, but we're not sure where. It might be that if a pipeline enables stats, the user code blocks on writing to stdout while we write to s3, or it might be that k8s is buffering these logs, or something else

**Comment by jdoliner** [comment]
This was probably due to the fact that `GetLogs` worked by spawning a goroutine for each pod it wanted to get logs from, but would return those logs in a static order. So you might dispatch 20 requests for logs, and the `0th` request happens to return last so you won't return any logs for a while. This model was changed as part of #2574 so that we return the logs as we receive them. I think that will mitigate this issue as much as we reasonably can. We'll still be bursty if k8s is bursty getting back to us, which I've observed it to be sometimes. But I think that's the best we can do so I'm closing this. Feel free to reopen if you encounter this again.
