### ISSUE TITLE
travis build caching

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2511]
The builds are around 30m again, when they were recently around 15-20m.

Not entirely sure why.

But, we can do some caching of build artifacts / images / etc on travis that could eliminate some of the overhead.

#2510 could provide another build requirement we could cache

**Comment by jdoliner** [comment]
Part of this might be that I made the test run serially instead of in parallel a while ago, although that didn't seem to increase the runtime by that much at the time. Even if this does prove to be a source of slowness I'm not 100% we should go back to running in parallel, the advantage of running serially is that if a test hangs (which is a fairly common way for errors to manifest) you can easily see which test is hanging.

**Comment by sjezewski** [comment]
It seems like the recent additions of the github input tests adds ~5m+ to the test suite. This is mostly because we're cloning pachyderm as part of the tests (which is a big repo). We should switch that out to a smaller public repo. This is a pretty easy fix, and will knock off a fair bit of time.

**Comment by JoeyZwicker** [comment]
Are we able to clone just a specific commit of the repo instead of the
whole repo to make this faster?

**Comment by sjezewski** [comment]
The immediate need was fixed. I pointed the git tests at a tiny repo and got builds back down to around 20m. However ... passing builds seem to be around 25m again ... so at some point we're going to want to look into the caching to speed up builds.

**Comment by sjezewski** [comment]
This is generic, I'm closing it.

I recently did another pass (https://github.com/pachyderm/pachyderm/pull/2623) that caches what we can. Further improvements lie in specific issues such as: https://github.com/pachyderm/pachyderm/issues/2632
