### ISSUE TITLE
Advanced pipeline triggers

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#252]
Add constraint options for when commits are made. These would a properties of a repo.

Examples:
Finish commit after _10MB_ of data has been added.
Finish a new commit ever _1 hour_ (cron).
Finish a commit if there hasn't been a commit in the last _1 hour_. 
AND / OR combinations:
After _10MB_ OR if there hasn't been a commit in the last _1 hour_. 
More than _10MB_ AND more than _1 hour_ since last commit

There are others too, but for now I can only think of _amount of data _and _time. _

Not sure how we'd want to expose this to users.

**Comment by jdoliner** [comment]
@JoeyZwicker how are you imagining that commits get started here and by whom?

**Comment by JoeyZwicker** [comment]
Not sure honestly. I'm thinking these constraints would be set for both starting and finishing commits. To me this basically seems like letting the user script starting/finishing commits within Pachyderm.

> by whom?

I'm not sure what this means

**Comment by JoeyZwicker** [comment]
My original comment did explicitly say "finish commit". I was kind of living under the git assumption that you'd always have an open commit, but that's not how we want users thinking about it because data "dirty commits" isn't safe and there could be a lot of it. So yes, they've have to specify behavior for both starting and finishing the commits.

**Comment by jdoliner** [comment]
>  > by whom?

> I'm not sure what this means

Basically are users explicitly calling `StartCommit` in your mind, my guess is no we want `StartCommit` to be automatic like `FinishCommit`. But there's a wrinkle with that, if they don't call `StartCommit` then how do they get the name of the commit they should write to? Branches can solve this, and now that I think about it a bit more, this feature might make more sense as a property of branches rather than a property of repos.

**Comment by JoeyZwicker** [comment]
Bringing info over from #235 

Wanted to add a few more details here based on discussions. There are a bunch of ideas here, not all of which probably make sense to implement.

The pipeline should have a trigger struct to let users kick off a pipeline job based on time or other constraints such as amount of data or number of commits. By default, the trigger setting for a pipeline is "new input commit."

Cron/time:
This makes the most sense for pipeline with no inputs such as a scraper. Theoretically, a user could want to trigger a pipeline based on time instead of per commit even when it has an input repo so this should probably override the triggering on each new input commit.

Number of commits:
User may make frequent input commits but only want to trigger the pipeline much less frequently because of expensive "reduce" jobs. This could easily be adding files to a datum over time. Some use cases may make more sense to be expressed as time, but this also seems reasonable.

Amount of data:
Trigger the pipeline when n MB of new data has come in. The use case here is less well-defined, but we had one user ask if they just streamed logs into pachyderm, they could want a pipeline to trigger after 1GB of logs as built up.

Combinations: Would it be possible for users to specify some sort of compound trigger argument? E.g. Every 10th commit OR if it's been 24 hours since the last job. <-- seems pretty contrived, but just a thought.

**Comment by brollb** [comment]
Here's another use case:
Suppose in the [tensorflow example](https://github.com/pachyderm/pachyderm/tree/master/doc/examples/ml/tensorflow), you are streaming training data in but also performing some data augmentation (like reflecting the images or random cropping or something) as well.

Training Data Stream -> Data Augmentation -> Training (Batch) Model

We may want the first two steps to stream the data as fast as it gets it in (so small commits) but the last step should be run only on larger amounts of data. Otherwise, we would end up training a new model one each combination of the data set (ie, trained model on `n` elements, trained model on `n+1`, trained on `n+2`, etc).

I think the challenge is that since the data batch size (streaming = batch size 1) of the entire pipeline is dependent entirely on the size of the inputs. Normally this is no problem but if you want to accumulate data, this can be tough.

**Comment by brollb** [comment]
Suppose we wanted to run it like an anytime algorithm and just stream massive amounts of data in but always have a model ready. In this case, maybe the criteria for running the pipeline would be to start the next training cycle once the current one has finished. That is, always running one and only one training pipeline on the latest data (at least the latest commit when the pipeline started).

**Comment by derekchiang** [comment]
There's a user that wants to add about 10 commits per second (one commit per sensor reading).  Triggering a pipeline in a sub-second basis would be unnecessary and wasteful.  Having a custom policy such as "trigger per this much data" or "trigger per this many commits" would help.

**Comment by gabrielgrant** [comment]
The use-case of having a number of commits added to a single repo before triggering a downstream pipeline is reasonably well-addressed by having another branch that gets manually updated at a slower cadence the branch to which the rapidly-received data is being added. This pattern is described in more detail in #2296

**Comment by nitinjainsj** [comment]
Implemented in 1.12.0
