### ISSUE TITLE
Update GPU docs

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2562]
GPU docs should be updated to include information about:

- deploying on GKE
- resource limits
- resource requests

I have notes I will integrate for GKE and AWS, and I have already updated the pix2pix example to work with the new limits: https://github.com/pachyderm/pachyderm/pull/2561.

**Comment by jdoliner** [comment]
Our docs for this seem pretty good to me: https://docs.pachyderm.io/en/latest/cookbook/gpus.html

They don't discuss deploying on specific providers, but we decided not to do that because it changes frequently and it's better to link to relevant docs than to document a moving target ourselves. They do talk about resource limits and requests.
