### ISSUE TITLE
Schema, Schema-less related docs

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2563]
From users:

> Omer Katz [5:19 AM] 
> @jdoliner I think I mentioned it once beforw. There is a case to allow people to mount a persistent volume so that failed jobs could be retried by users. The user needs to check if the file exists and/or validate it and skip it.
> The volume would need to be cleaned up properly by pachyderm after the job completed successfully.
> It's a throughput versus reliability tradeoff.
> 
> Omer Katz [5:29 AM] 
> The same way you do so on any schema-less data store.
> Either a live migration or in bulk.
> Point the end of all pipelines to a new pipeline that alters the schema. Make sure to commit new data only to the repo the new pipeline commits to and start your processing from there.
> 
> Preston Marshall
> Also curious how people are handling the "schema" changing between points on the graph
> 
> Omer Katz [7 minutes ago] 
> This needs to be documented + an example imo

**Comment by bbhoss** [comment]
My initial thought was to update the code of the pipeline(s) downstream from the pipeline you're changing the schema from to handle both schemas first, then to update the pipeline that you're changing the schema of. This would also facilitate not having to reprocess all datums, since your downstream code can still handle both formats. Also, if you wanted to clean this up you could always force a reprocess and then remove the code for handling the old schema.

**Comment by nitinjainsj** [comment]
Will be subsumed by future product work -- dev/staging/prod
