### ISSUE TITLE
More network-fault-tolerant pachctl put-file for large commits

### ISSUE THREAD

**Issue by olegserov** [pachyderm/pachyderm#2576]
I was uploading 250k files using `pachctl put-file .. ... -r`. Then the network went down. The upload stopped. I had to start it again from scratch.

**Comment by dwhitena** [comment]
Hi @olegserov. Thanks for the feedback. There are a couple of things that you can do here:

- Set ADDRESS directory instead of using port-forward, as forwarding includes some rate limiting.
- utilize the resumable upload functionality: https://github.com/pachyderm/pachyderm/pull/2293
- upload these from an object store or http link

Those things should help in these scenarios. Let us know if you have other ideas, but closing for now as the resumable upload is the primary fix for this, and thanks again!
