### ISSUE TITLE
Handle errors in pipelines properly

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#258]
Currently, pipelines output commits even when some jobs fail, meaning that other downstream pipelines might consume incomplete/corrupted data.

**Comment by jdoliner** [comment]
The problem here is that we do want to finish the commit so that users can explore what data was written, but we want to do so in such a way that it doesn't trigger pipelines that are watching the repo. How would people feel about calling this "cancelling the commit" Cancelling a commit would be done using a `FinishCommit` request, but we'd add a boolean flag, `cancel`. Cancelled commits wouldn't be returned in `ListCommit` by default so they wouldn't cause pipelines to trigger. We could also add a flag to ListCommit `all` which would include cancelled commits. I also think we should prohibit using cancelled commits as parents of new commits.

**Comment by JoeyZwicker** [comment]
What would the parental structure look like with a cancelled commit? Would the next started commit know to trace the tree back until the latest non-cancelled commit and make that it's parent?

**Comment by derekchiang** [comment]
Discussed offline with @jdoliner.  Here is the solution.  For the sake of discussion, say that we have a pipeline whose input repo is A and output repo is B.

Imagine the following sequence of events:

1. A receives 1 commit, the pipeline runs successfully, B receives 1 commit.
2. A receives 1 commit, the pipeline fails.

Now, the following things happen:

1. B receives a "cancelled" commit that contains whatever data that the pipeline had written before it failed.  This commit's parent is the last commit in B.
2. The state of the failed pipeline job is set to "failed", which can be seen through `pachctl list-job`.

Now, let's say that A receives another commit.  The pipeline will run with the last **two** commits in A as its input.  The new commit in B will have the last non-cancelled commit in B as its parent.

Cancelled commits do not trigger downstream pipelines.

If the pipeline is a reduce pipeline, the only difference is that we always run the pipeline with the entire history of the input repo, which is already what we are doing right now.

**Comment by derekchiang** [comment]
Upon further discussion, we discarded the idea of "clumping commits."  Instead, we will not retry a failed job at all; the user will have to fix the pipeline by removing the offending commits or branching.

**Comment by derekchiang** [comment]
Fixed in #321
