### ISSUE TITLE
MVP of Hosted Solution

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2613]
I think we're a few key features away from having a viable hosted solution for a (private) alpha.

## Goal

The MVP should:

1) allow a user to access a pachyderm cluster via pachctl or UI
    - a user should only have access to + be able to see their pipelines (no teams)
    - a user will NOT have access to the cluster at the k8s layer
2) allow a user to deploy N pipelines (where N is preset, or where the user's k8s namespace has quotas to limit resource consumption)

Nice to haves:

3) allow users to self register + signup
4) allow users to pay for access / more resources (stripe integration)

---

## Pre-Requisite

- [A cluster deployed to DO and exposed via custom DNS](https://github.com/pachyderm/pachyderm/issues/2612)
    - This allows us to provide a valid `ADDRESS` variable to the user (delivered via `config.json` as outlined below) ... which eliminates the need for them to have k8s access (for port forwarding)

## Todos

1) ACLs determine what a user can list

- ACLs are updated so that a user without `read` access also cannot see a given object
- This allows us to make sure a given user can only see their Pachyderm objects

2) Create a new user

We will create a script to:

- Add the new user (via github username) to a list of ACLs starting w no access to anything
- Define a custom k8s namespace for that user (could store this in pfs under a `users` repo)
    - This namespace should have tight resource quotas defined on it
    - This namespace ID should be keyed by the users session ID (or even better GH username if we have it)
- A user will then be emailed:
    - a link to the UI
    - a copy of their config `~/.pachyderm/config.json` file to connect to the cluster
    - instructions on how to use this config file

3) Namespace all user actions

- pachd will use the users' session ID (which is always passed by pachctl / the UI) to lookup the appropriate k8s namespace to use when creating / deleting / etc k8s objects
- this will enforce a limit on the number of pipelines / services a user can create

This accomplishes our definition of the MVP above.

**Comment by msteffen** [comment]
Very exciting! A few comments on the auth portion of this:

> ACLs are updated so that a user without read access also cannot see a given object

I thought about doing this for the [commit invarants project](https://github.com/pachyderm/pachyderm/issues/2505), but I decided if companies are going to use auth to separate teams, we probably want something a little more complicated. If you can't see repos that you can't read, then there's no way to ask for access to something that you don't already have access to.

There's an issue for discoverability in Pachyderm here: https://github.com/pachyderm/pachyderm/issues/2434, which I think would be a good place for design ideas

> Define a custom k8s namespace for that user

Yes! This would be good anyway, so that users can e.g. get logs from their pipelines without being able to e.g. read directly from etcd. There's a related issue here: https://github.com/pachyderm/pachyderm/issues/2430, which again would be a good place to write out any ideas anyone has

**Comment by ysimonson** [comment]
Details of this are fairly outdated at this point; closing
