### ISSUE TITLE
Validate file paths

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2614]
We probably only want to allow printable ASCII characters.

[See PR for a bit more discussion why this matters tactially](https://github.com/pachyderm/pachyderm/pull/2599)

**Comment by brycemcanally** [comment]
Is anybody working on this? If not, I can do it.

**Comment by jdoliner** [comment]
@brycemcanally don't believe so, and this would be a great issue to dive in on some of Pachyderm's internals since it's very self contained. `src/server/pfs/server/driver.go` is probably the best place to start looking, that's where the real guys of pfs is. We have a function in there for validating repo names (`ValidateRepoName`) but not paths.

**Comment by brycemcanally** [comment]
Okay, cool. Yeah, I looked into this a little bit already and am thinking I should be making modifications to the checkPath function in the driver that checks for null characters.

**Comment by jdoliner** [comment]
Yup that's totally correct, I was mistaken when I said we don't have a function for validating paths. While you're at it, want to change that function's name to `validatePath`? That seems a bit clearer to me, and a bit more greppable.

**Comment by brycemcanally** [comment]
Sounds good. Do you want it exported like the repo name validation?

**Comment by jdoliner** [comment]
Nah, let's keep it private. Exporting `ValidateRepoName` seems to be vestigial, it's not used outside of that package. If you feel like it unexporting `ValidateRepoName` would be nice bit of cleanup to include with this PR.

**Comment by brycemcanally** [comment]
Okay, I will do that as well.
