### ISSUE TITLE
Allow non-root users in Worker containers

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2635]
> dwhitena [3:01 PM]
> @jdoliner do you need to be root in the container to write to `/pfs/out`?
> 
> [3:01 PM]
> Or is there a workaround for non-root users in a container?
> 
> jdoliner [3:06 PM]
> running as root seems to be a requirement right now, we could in theory fix that though

**Comment by gabrielgrant** [comment]
This seems to be the one issue left to fix for us to be able to work on OpenShift using their default permission model (ie no privileged access). Using this as the meta-issue to track a number of more specific issues related to this

- sidecar tries to create /pach dir; fails without root access (#3404)
- worker fails to exec user code when run as non-root user (#3405)
- (unclear if this really needs to be fixed) pipeline workers fail to run without root, due to cert error when connecting to sidecar (#3394)
- Not sure if this is still an issue, but "Non-root users cannot access /pfs" (#1845) has been open for a couple years

**Comment by gabrielgrant** [comment]
Note that the OpenShift model (worker itself runs as non-root) may not be quite the same as what (I imagine) was originally being asked for here: having pach worker running as root still, but having user code running as non-root. I _think_ the latter is already supported today, though

**Comment by jdoliner** [comment]
The original ask for this issue is now supported and the extended ask that @gabrielgrant added is also supported, we can now run on OpenShift.
