### ISSUE TITLE
Upload step slow when pipeline creates lots of small files

### ISSUE THREAD

**Issue by mightyguava** [pachyderm/pachyderm#2636]
We are attempting to follow the pachyderm word count example to create a pipeline that groups events together (the group ID is part of the event). We have a first pipeline that receives for input csv files, with one event per line. We split them to produce `/<group_id>/<event_id>.txt` per file. 

For a 6k line file, this produces about 6k files each about 3KB in size. According to the pachctl output, the download of the single input file took less than a second, but the _upload of the split files took about a minute_.

I understand that usually with a filesystem, syncing multiple small files is expected to be slower than one big file. But given this is pachyderm's recommended way of doing map => reduce operations, I'd expect significantly better performance. Is there a way to speed this up?

We are using pachyderm 1.6.7 and kubernetes 1.8.4 on AWS. Pachyderm was deployed with default configs, no Cloudfront, using the command from the instructions.

```
pachctl deploy amazon ${BUCKET_NAME} ${AWS_REGION} ${STORAGE_SIZE} --dynamic-etcd-nodes=1 --credentials "${AWS_ACCESS_KEY_ID},${AWS_SECRET_ACCESS_KEY},
```

Kubernetes is deployed on t2.mediums, using Kops, 3 master setup, using Calico networking.

Output of `inspect-job` for the slow job:

```
> pachctl inspect-job 67fff014-8a1d-4887-8d72-134871dfaa51
ID: 67fff014-8a1d-4887-8d72-134871dfaa51
Pipeline: split-events
Parent: a0081590-155c-47ad-9f58-7d256e21db91
Started: 3 days ago
Duration: About a minute
State: success
Reason:
Processed: 1
Failed: 0
Skipped: 1
Total: 2
Data Downloaded: 6.98MiB
Data Uploaded: 7.397MiB
Download Time: Less than a second
Process Time: 2 seconds
Upload Time: About a minute
Datum Timeout: (duration: nil Duration)
Job Timeout: (duration: nil Duration)
Worker Status:
WORKER              JOB                 DATUM               STARTED             QUEUE
Restarts: 0
ParallelismSpec: coefficient:1
ResourceRequests:
  CPU: 0
  Memory: 64M

Input:
{
  "atom": {
    "name": "raw-events",
    "repo": "raw-events",
    "branch": "master",
    "commit": "de4eacc59f3e4d25bcd5b04847fd503e",
    "glob": "/*"
  }
}

Transform:
{
  "image": "localhost:5000/pachy_events",
  "cmd": [
    "python",
    "/app/pachy_events.py",
    "/pfs/raw-events",
    "/pfs/out"
  ]
}
Output Commit: af2136e44c794ce1a3b7f1838fd837b0
```

**Comment by jdoliner** [comment]
Hi @mightyguava sorry you're hitting this. To clarify a bit about the example, wordcount is meant to demonstrate how to do `mapreduce` style workloads in Pachyderm so it opts for the simplest implementation, not the most performant implementation. The simplest way to increase performance in Pachyderm is to crank up parallelism. In this case you have 1 worker per node, but only one of the workers gets used, because you only have 1 file. Splitting that file up into multiple files will allow the workers to all upload at the same time which should reduce the job's runtime to `1/n` what it was before (where `n` is the number of workers.) Note that the reported Upload Time will remain the same, since it's an aggregate, but the time the full job takes to run will be lower. You also will probably want to increase your parallelism coefficient since wordcount is not terribly resource intensive and this will allow you to saturate your connection.

If this doesn't prove sufficient you can further increase performance by grouping things together. Rather than having a file for each word you could have a file that contains counts for all the words with the prefix "a", "b", "c" etc, this will limit you to 26 files which should still be enough to saturate all your workers, ifi t's not then doing 2 character prefixes should.

I suspect you could also speed this up by switching to a different object store, we've observed s3 to be one of the less performant object stores (GCS has generally been the best). I think almost all of the overhead here is in uploading to the object store so it should have a big impact.

Finally there are definitely some things we can do on the backend in Pachyderm to make this more efficient by packing small files into a single large object. We haven't done them yet because it complicates the implementation and most of the workloads we've seen in the wild don't involve such small files, but issues like this help us know what to prioritize so we'll definitely be taking a look at how we can improve the out of the box experience in this instance.

**Comment by mightyguava** [comment]
Thanks for the detailed answer @jdoliner. I think we should be able to split the input file in most cases. Hopefully that'll be fast enough. Doing additional grouping is probably not the best idea for us since we'd much rather rely on pachyderm to handle sharding for us rather than adding another layer on top.

> I suspect you could also speed this up by switching to a different object store, we've observed s3 to be one of the less performant object stores (GCS has generally been the best). I think almost all of the overhead here is in uploading to the object store so it should have a big impact.

We are going to be running pachyderm on AWS for the foreseeable future. If we opted to use a GCS bucket, I assume there's going to be non-trivial network latency. Do you have intuition or concrete numbers on whether this will more performant for us, going across clouds?

**Comment by jdoliner** [comment]
My intuition is that it's unlikely to be worth it from a performance perspective due to the added latency. And even if it wasn't I think there's a lot of added complexity to running across multiple clouds.

**Comment by jdoliner** [comment]
Many small files is now handled much better by Workers because they concatenate them into a single large object and store references into it. There should be only minor performance differences between many small files and few large files of equivalent total size.
