### ISSUE TITLE
Need a call that block on a job completing

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2641]
Right now flush-commit block indefinitely if there's a job failure. In our tests, we poll list-job until it shows up and then inspect-job blocks until the job completes. 

@sjezewski will comment on the issue to add more detail since he's had to do a number of hairy things to hack around our current functionality limitations.

**Comment by jdoliner** [comment]
I'm a little confused by the title of this issue. There's already a way to block on a job completing, although you obviously know that since you reference it in the issue. It sounds more like you're asking for `flush-commit` to report failures which it will in 1.7. If that's the ask I think we should rename this and move it out of backlog since it'll be done as part of 1.7.

**Comment by sjezewski** [comment]
Yea, that's it. If flush commit reports failures, this gets a lot simpler. We can close this.
