### ISSUE TITLE
Generic code run on job failure

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2674]
Allow users to specify code to run if a job errs. This would be a good generic way to support notifications on job failure.

**Comment by sjezewski** [comment]
Discussed this a bit w @jdoliner and @msteffen 

We want to draw a distinction between control flow (and perhaps notifications) versus monitoring.

The latter should be done by a system that is independent of the system being monitored.

**Comment by jdoliner** [comment]
I think error handlers are a good solution to this, since they let you run on the actual data that failed and potentially trap the error. It doesn't give you a way to run code generically on job failures, but I don't know how compelling of a feature that is, I think for notifications you're better off having an external monitoring system, because one of the reasons a job can fail is if the cluster is degraded, in which case the failure code won't run either.
