### ISSUE TITLE
Show hash of file in inspect-file results

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2697]
**Is this a BUG REPORT or FEATURE REQUEST?**:

feature

**What happened?**:

A user is ingesting data into pachyderm. In particular, there is a large file (btw 100-500MBs) that has been uploaded. Since this customer is in the process of developing with pachyderm and re-deploying their cluster, and re-uploading their data, they are not sure the right file got uploaded. 

**What would you like to happen?**:

If `inspect-file` returned a hash (md5 or I believe we use sha256 under the hood in commit trees), we could easily verify that the version of the file in pachyderm matches (or doesn't) the local file they have without having to wait for a long download just to check if they match.

**Comment by jdoliner** [comment]
FileInfos have a hash in them so it'd be very easy to include this in what's showing in `inspect-file`s output. This can be accessed right now by doing `--raw` to see everything as json. I'm not sure if the hash algorithm we're using under the hood is one the user's going to have easy access to though. I'm thinking maybe a better idea would be exposing an ability the do a `sync` similar to what workers do when a datum finishes, which uploads some content only if it's new.

**Comment by jdoliner** [comment]
We still don't list hashes in inspect file, but I think that makes sense because it's a less important detail most of the time, especially because it can't be a well known hashing algorithm like md5 due to how we do distributed hashing. We do use sync now on `put file --overwrite` so the important part of this issue is implemented, users no longer have to start from scratch when putting files.
