### ISSUE TITLE
add edge-case functionality to put-file

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#2772]
@jdoliner Feel free to rename this issue to better capture the idea. 

The specific usecase at hand is a user wants to input a directory of 1 million files into a repo as top-level objects. 

currently, `put-file -r -f dir/files` would input the directory structure too. The challenge here is that if there are multiple files with the same name is subdirectories, you'd get those result appended together and could lead to some data corruption issues.

**Comment by jdoliner** [comment]
Actually, it turns out this is possible with `put-file` today. The way to do it is:

```
pachctl put-file repo master /  -f dir -r -c
```

Notice the `/` there as the third argument, that overrides `dir` so that files wind up in `/<file-name>`. This does have the risk @JoeyZwicker outlined above, I think I'm going to add a warning message about that in `pachctl`. I'll also add an example of this behavior to the doc string for it so this is more discoverable.
