### ISSUE TITLE
using overlayfs?

### ISSUE THREAD

**Issue by philips** [pachyderm/pachyderm#28]
Hey! I just started looking at pfs and noticed it is using btrfs. I was curious what features it uses and if it could possibly use overlayfs instead. Happy to discuss via email too.

**Comment by jdoliner** [comment]
Hi!! Just read a bit more about OverlayFS and it seems like it should be doable.

Here's how we use btrfs:

- read only subvolume snapshots for commits, obvious analog in ofs
- writeable subvolume snapshots for commits, The docs I read didn't explicitly says this but I assume ofs doesn't mind if 2 file systems share a lower fs given that they use it in a read only manner.
- `what changed` - btrfs has a `what changed` command which tells you which files changed between snapshots. If I understand correctly, in ofs we could accomplish the same thing by just looking at the upper filesystem by itself.
- `send` / `receive` are used for data transfer, this should work the same way as `what changed`
- parent info, btrfs records where volumes came from which we use to record our commit history. This seems like the only thing that ofs doesn't have a direct analog for but it wouldn't be too hard to record it on the side.

Do you happen to know much about the performance characteristics of ofs? One thing I would worry about is that under normally usage we expect users to create commits with something like a per minute granularity. Depending on how ofs is implemented lookups on files that haven't changed in a long time could get very costly because it will need to traverse several layers to reach them.

**Comment by philips** [comment]
I agree with your overview. The send/receive thing is something that is left to userspace so you will have to figure out some way to address the contents of lower filesystems (hash or something) to ensure you are talking about the same thing across RPC boundaries.

overlayfs should work fine with a commit workload of minute granularity although I haven't measured it myself. Essentially you would want to set some reasonable policy after measuring of when to flatten the commits again.

Of course the other option would be to just continue using btrfs even on systems that don't have a btrfs root filesystem by using a loopback block device.

**Comment by sjezewski** [comment]
We are now using FUSE in lieu of btrfs, which suits our needs for now
