### ISSUE TITLE
/pfs/inputs directory

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2844]
**What is the ask?**

A `/pfs/inputs` directory

**What is the goal / desired outcome?**

So that I don't have to do `inputs = [d for d in os.listdir('/pfs/') if d is not 'out']` (or some bash equivalent) as the first line of every pipeline

The `/pfs/inputs` directory contains a symlink to each input; For consistency, I'd also like to see `/pfs/output` be a symlink to `/pfs/out`

At some point in the future, I'd like to deprecate the use of inputs directly within `/pfs`

**Comment by jdoliner** [comment]
I don't think I like this. Adding extra paths under `/pfs` to support a particular type of iteration seems like it's not worth the clutter. Furthermore I don't think that this use case is that important to users, it's rare that users want to iterate through all of the inputs, normally each input has a name that's meaningful and so you handle it directly by name rather than needing to find it via iteration. This also would have a big downside in terms of backwards compatibility, users who are doing iteration over their directories would suddenly have these new paths `inputs` and `output` which would probably break their existing code.

**Comment by ztj** [comment]
Personally I’d like to see /pfs/in as the prefix to input data rather than just /pfs. I don’t think that’s an unreasonable request, though, it wouldn’t be symlinks or differ in any way from now except the base directory difference.

However, what I think would be more realistic and actually fit the flexibility of pachyderm far better would simply be to enable specifying where the  input data appears just like we already do for secrets.

**Comment by ysimonson** [comment]
If only for backwards compatibility reasons, we're not going to pursue this.
