### ISSUE TITLE
Insufficient alpha.kubernetes.io/nvidia-gpu when running pipeline using GKE

### ISSUE THREAD

**Issue by dyngts** [pachyderm/pachyderm#2886]
Hi guys,

i'm facing problem when trying to running  [example](https://github.com/pachyderm/pachyderm/tree/master/doc/examples/ml/tensorflow) using GPU. I'm deploying pachy on GKE.The exact problem was occurred when running pipeline for `training_and_export_gpu.json`, specifically for pipeline `checkpoint`.

the problem is the pod always throw like this:  
>0/2 nodes are available: 2 Insufficient alpha.kubernetes.io/nvidia-gpu.

when i checked to the nodes to check the nvidia plugin, it throw like this:
>cloud.google.com/gke-accelerator: nvidia-tesla-k80
     nvidia.com/gpu: "1"
     nvidia.com/gpu: "1"
     - cos-nvidia-installer:fixed

i suspect that the GKE moved out to `nvidia.com/gpu` as the plugin name instead `alpha.kubernetes.io/nvidia-gpu`. is this configuration coming from pachy or what? Thanks in advance

My specs:
>Pachy version: 1.7.1
  GKE version: 1.9.7

**Comment by dwhitena** [comment]
Hi @dyngts, I know GKE and Nvidia recently made updates to GPU support, and I know that Nvidia has patches to fix certain things with GKE. We will investigate this. However, you might also open an issue here to start some discussion: https://github.com/nvidia/k8s-device-plugin.

cc @sjezewski @jdoliner

**Comment by mdaniel** [comment]
So, as you correctly said the nvidia device plugin has chosen `nvidia.com/gpu` but I wanted to point that it is evidently the long-term path forward, since [the kubernetes e2e tests use it](https://github.com/kubernetes/kubernetes/blob/v1.12.2/test/e2e/framework/gpu_util.go#L31). There are no more occurrences of `alpha.kubernetes.io/nvidia-gpu` in the kubernetes/kubernetes nor kubernetes/api repos. I also tried searching for `nvidia-gpu` to see if it had moved out of alpha, and no to that, also.

What is your opinion about extending the [`message ResourceSpec`](https://github.com/pachyderm/pachyderm/blob/v1.7.10/src/client/pps/pps.proto#L185) to include a `map<string, string> custom` to allow side-stepping this? Now that device plugins are out-of-tree (from kubernetes's PoV), it is conceivable every device vendor can make up their own resource namespace -- we certainly wouldn't want to have to wait on a pachyderm release to adjust for them all.

I'm aware that `pod_spec` exists but using it would be extremely annoying, especially since that field is a `string`(!) as well as [currently undocumented](http://docs.pachyderm.io/en/v1.7.10/reference/pipeline_spec.html)

**Comment by JoeyZwicker** [comment]
slotting this in for 1.9.

**Comment by jonandernovella** [comment]
+1. I can reproduce this issue. Is there any workaround on this?

**Comment by JoeyZwicker** [comment]
Workaround:

After you create the pipeline, you can do `kubectl edit` on the RC and just change the config manually to remove  the `alpha` tags that are incorrect. We know this is a bit annoying having to do this for each pipeline, but you should only need to do it once for each RC and we'll get this fixed as soon as possible.

**Comment by jdoliner** [comment]
This has been fixed.
