### ISSUE TITLE
Lack of atomicity in repo operations

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#291]
For instance, in `DeleteRepo`, we remove multiple `diffInfo`s one by one.  Now, if some `diffInfo`s get removed but not the others (because something failed in between), then our cluster will be in an incoherent state.

The fundamental problem here is that unlike operations on files (e.g. `PutFile` and `GetFile`), repo operations are not being done in a transaction (a.k.a. "commit" in our system).

Does this worry you?  @jdoliner

**Comment by jdoliner** [comment]
The lack of atomicity is pretty unavoidable in these operations since the delete is a distributed operation. Thus we'll never be able to completely eliminate the possibility that the cluster is left in an incoherent state so what we need to do instead is try to return sensible results from this state. There are going to be a lot of corner cases there that we need to think through though.

So tl;dr this definitely does worry me, I think we should probably get other stuff right first and then start writing some tests that simulate distributed failures to test / fix these behaviors.

**Comment by sjezewski** [comment]
Rethink is dead! etcd gives us multi-document transactions! 

(╯°□°）╯︵ ┻━┻
