### ISSUE TITLE
Error "cannot read from an open commit"

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2924]
I seem to be seeing these errors returned from pachd when inspecting the contents of an output repo whose auto-opened commits have not yet been filled in by a job.

I'd have thought inspecting these open commits would work the same as inspecting any other open commit (used to?) work (since nothing has been written yet, i'd expect to get back an empty list of files). I can see how this is somewhat different, since the whole tree is constructed at once, and (unlike with new ingestion commits) these commits don't inherit their parent's contents. So maybe an error is the expected behavior, but I found this surprising (given we generally have been able to read from open commits in the past).

If the current behavior is expected, please open an issue on the dash repo to handle this case properly

**Comment by jdoliner** [comment]
Yeah, this has to do with the differences between input and output commits and I think is probably the right behavior. It's too expensive to do an on demand merge to show people the partial progress of a pipeline, and it's also potentially confusing, they might interpret the data as actual final output. For an input commit it's a lot more reasonable because what you see is basically what you'd get if you called finish commit without writing anything else to the commit.
