### ISSUE TITLE
Expose worker image pull errors

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2925]
I'm currently seeing `Failed to pull image "pachyderm/worker:local"` (after deploying with make launch-dev), but presumably a user could see the same issue if they weren't able to pull the worker image from dockerhub.

Is there some way we could be exposing this type of error image pull error in the pipeline status? Right now the status of everything looks fine in pach, but I was seeing commit not causing jobs to be triggered. took a little more of a leap than i'd expect users to make to go from that to figuring out it was a problem with the worker image

**Comment by jdoliner** [comment]
This should leave the pipeline in a failed state. Does it not?

**Comment by gabrielgrant** [comment]
That's what I would expect, but I don't believe it does. I don't have this running anymore, but the I'm quite sure the pipeline was in `RUNNING` state.

**Comment by jdoliner** [comment]
So the pipeline only goes into a failed state for the "user" container, the reason this doesn't trigger it is that it's the "init". I'm not totally sure we want to change this, user container pull failures are often due to the user referencing the container incorrectly, which is common and needs to be surface. Worker container pull failures are probably mostly network issues, in which case failing the pipeline prevents it from recovering once the issues resolve, the case where it does make sense to surface is if the user has messed with what the worker container is and that's why it's failing to pull, that sounds like a fairly rare, power user case, where the user will likely be able to figure out for themselves what went wrong. I'm going to leave this open since there's probably some improvements we can make around this case and we should think about it more.

**Comment by ysimonson** [comment]
Some more details in #4568

**Comment by ysimonson** [comment]
Another case where this might happen is if the user sets a storage secret, but doesn't push the init image to the registry. This is common enough to warrant closer attention to this issue.
