### ISSUE TITLE
Upgrade CI test caching

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2934]
Want:

I had a build where the linter failed (the `MISC` travis job) but all the others worked (`PPS1`, `PPS2`, `PPS3`). I'd love to be able to push a new commit w the one change I need, and the other test results are cached.

---

Travis caches test results per branch

Right now only the PFS suite uses the cache, we've disabled the test cache everywhere else, because all the other test suites require the pach cluster to be up and running, and so the `go build ...` process that gets run as part of the test compilation and execution doesn't capture all the dependencies ... so we could see a cached result even though deps changed, which would be invalid.

But!

I *think* is a way to mark go deps so that this cache is updated at the right time.

**Comment by jdoliner** [comment]
This seems like a very far off CI optimization and likely an unsafe one. Assuming that you can tell that certain tests on a commit are going to pass because they passed on the parent commit and none of the changes affect the outcome of the test seems like it's only possible to do in a tiny fraction of cases. The case mentioned here seems particularly impossible, to fix the linter you have to change code, so you can't really be sure that you fixed the linter without breaking the code in some other way (I mean, normally you're sure of this and right, but CI should be paranoid). I don't think waiting for another CI run when you need to fix actual issues with CI is that big of a burden on engineering, so I'm going to close this.
