### ISSUE TITLE
Pipeline flow control

### ISSUE THREAD

**Issue by vasilak** [pachyderm/pachyderm#2982]
Hi guys.

Is there a way to specify flow control in a pipeline?
I have looked through the documentation but haven't been able to find anything relevant.
To provide more context, what I am interested in is creating a pipeline in which some step(s) would only be executed if a certain condition holds. The condition would have to be dynamic in that it would depend on the output of a previous step. For example, let's say I am running a pipeline in which the first step is to run a model to detect whether the input (which is an image) includes the face of a person and the output would be a cropped area of the image where the face was detected. The next step in the pipeline would only execute if a face was detected (and thus a cropped image was generated), otherwise a different step would execute, and so on.

If there is no way currently to do something like that in the pipeline specification, what would be a best practice to achieve something like this using pachyderm?

Thanks!

**Comment by jdoliner** [comment]
Hi @vasilak,

There are a couple of standard ways of accomplishing this with Pachyderm:

- Build the control flow into your pipeline. Your upstream code would output either its cropped face to `/pfs/out/face` or something else to `/pfs/out/other` then your downstream pipeline would do something different based on whether the file it finds is called `face` or `something_else` these names can be changed to your liking so that multiple faces don't conflict with each other.

- Have separate pipelines consume different directories. Your upstream code would output faces to `/pfs/out/faces/face` and other things to `/pfs/out/others/other`. You could then have 2 downstream pipelines, one with a glob pattern of `/faces/*` that would handle faces and one with `/others/*` that would handle the others.

Which one you use depends on how granular you want control over the 2 operations to be. If you want to be able to update one without updating the other, have different resources requests for them, have one get scaled down while the other is up and running, etc. then 2 different pipelines is the better choice. If those things aren't necessary the simplicity of a single pipeline is probably 

---

Generally speaking you'll get faster responses to support questions like this in our users channel: slack.pachyderm.io. GitHub issues are better used for reporting bugs and feature requests.

**Comment by vasilak** [comment]
Hi @jdoliner and thanks for responding.
About the 2nd option you describe: understanding when the pipeline is done (for a particular input) can still be accomplished using `flush-commit`, right? I am asking since in this case you basically have 2 different "end" steps.

**Comment by gabrielgrant** [comment]
@vasilak sorry for the delay. Yes, it sounds like you should be able to achieve what you're looking for with flush commit -- I believe it waits for all downstream commits by default
