### ISSUE TITLE
Hadoop is the only publicly available option for Big Data

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#3]

**Comment by derekchiang** [comment]
MapReduce is just a particular paradigm for data analytics.  For instance, Spark is not MapReduce.  Pachyderm is not limited to MapReduce either; it's more general and powerful than that.  The issue is that Hadoop as a platform is the only available option for big data analytics.  Updating the title to clarify that.

**Comment by jrockway** [comment]
Pachyderm is now available 🎉
