### ISSUE TITLE
Make generalized Docker image for proto compilation

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#302]
A few of us have run into some funny edge cases here. To make our lives more sane and to encourage contributors, we should have a more generalized Docker image for proto compilation. 

@derekchiang has a version working for his setup, that's probably a good starting point

**Comment by derekchiang** [comment]
The reason that the current `docker-build-proto` target doesn't work on Macs is that in order to compile protobuf files in the docker image, you need to mount the pachyderm repo into the docker image.  However, this requires that the docker daemon is running locally.  For instance, it wouldn't work if the daemon is running in GCE or in boot2docker (which is common for a Mac setup).

I found some issues that might be worth looking into:

https://github.com/boot2docker/boot2docker/issues/413
https://github.com/docker/docker/issues/7249

**Comment by sjezewski** [comment]
Huh, I guess it didn't occur to me that its not easy to run docker natively on mac, but that makes sense.

Another idea would be to have a dedicated kube cluster setup to basically 'build proto files As A Service'. That may be a bit silly ... but if we could automate this, I think it would ultimately help us.

That interface would be something like:

- local task zips up current code into tarball  ... posts it to image
- image accepts tarball, unpacks it, and runs proto compilation steps (probably just using whats already specified in our makefile)
- then the service sends a tarball back
- and locally unpack the new proto files

**Comment by derekchiang** [comment]
Actually it just occurred to me that you can do this: instead of mounting a directory into the docker image which is what we are doing right now, you'd pipe a tarball of the source code into the docker image.  So the docker image will expect to receive a tarball from stdin and will write the compiled source code out as a tarball to stdout too.

So we run the docker image like `cat sourcode.tar.gz | docker run pachyderm/protobuf > compiled.tar.gz`.  Then we extract the output tarball.  That way we don't need a remote service and can still use the docker image in a platform-independent way.

**Comment by jdoliner** [comment]
That tarball could also be just the .proto files might make things a little easier.

**Comment by derekchiang** [comment]
Fixed by #316
