### ISSUE TITLE
Allow for overwriting of data as a commit output

### ISSUE THREAD

**Issue by JonathanFraser** [pachyderm/pachyderm#303]
Currently writing to a new commit merely appends the data to reduced file. It would be nice to be able to overwrite the file rather than just append to it.

**Comment by derekchiang** [comment]
We currently support `delete-file` through `pachctl`.  To overwrite a file, you'd delete the file before you write to it.  However, this currently cannot be done through fuse, which means that you can't delete files in pipelines.

@JonathanFraser does the `pachctl` route satisfy your current need?  Or do you need to be able to delete files in pipelines?

**Comment by jdoliner** [comment]
I think we'll need to expose this through fuse, probably the way to do it would be to catch truncations and propagate those as `delete-file` that way should be able to use standard shell techniques:

```
echo foo > /pfs/out/a # overwrite a
echo foo >> /pfs/out/a # append to a
```

**Comment by JonathanFraser** [comment]
I don't know, I'm think if a case where a pipe line step is monitoring one or more repos and producing a summary. The summary is nearly the same all the time except a few lines may be different and when those lines are different kick off the next stage of the pipeline dealing with those lines.

@jdoliner that's basically what I was thinking as well. Also make sure the latter pipelines are smart enough to detect that the commit has the same data and either not run or run as a NO-OP.

**Comment by jdoliner** [comment]
1 more question is this a behavior you're seeing in reduce steps or map steps? Looking at our code it seems like reduce steps always output to parentless commits so this could be indicative of a bug somewhere else. That won't be true forever though so this issue does still apply to reduce steps and it certainly applies to map steps.

Making the commit a no-op if it's the same content should be pretty easy as well thanks to everything being content addressed.

**Comment by JonathanFraser** [comment]
Correct me if I'm wrong but it appears the reductivness affects the view of the input repos and does not apply to the pipeline itself.

**Comment by jdoliner** [comment]
Reductivness affects both. We check if any of the inputs are being reduced and if they are we remove the parent commit:

https://github.com/pachyderm/pachyderm/blob/master/src/server/pps/server/api_server.go#L131

Now this is probably not what we want to do long term since it removes an option of incrementality.

**Comment by JonathanFraser** [comment]
I guess what I'm saying is that the reduce flags should affect only the input repos and the option whether or not to reduce in the pipeline itself is decided if the code overwrites (>) or appends(>>). In this way a reducing pipeline has it's full commit history for free and indeed you could choose to reduce on a per file basis.

**Comment by jdoliner** [comment]
@JonathanFraser that makes sense to me too. We should implement that behavior as part of fixing this bug.

**Comment by JonathanFraser** [comment]
@jdoliner by this bug I presume you mean #296 and #270. I can appreciate lumping similar bugs together but additional feature maybe we keep separate.

**Comment by jdoliner** [comment]
@JonathanFraser yeah sorry... the threads are all starting to blend together. This should definitely be kept separate.

**Comment by sjezewski** [comment]
Looking at this now / making a failing test case (`TestFileOverwrite`). Logs for osx/linux attached - these are the lines just when trying to overwrite the file.

In each case we see a:

```shell
WriteRequest: Goodbye, world
@0
```

But I think osx always reports writes @ 0 -- so we may not have a way of differentiating an append vs overwrite. Will add a negative test case for append next.

[linux-test-failure.log.txt](https://github.com/pachyderm/pachyderm/files/239121/linux-test-failure.log.txt)
[macosx-test-failure.log.txt](https://github.com/pachyderm/pachyderm/files/239122/macosx-test-failure.log.txt)

**Comment by sjezewski** [comment]
This issue has a lot in common with #358 

There are some big design decisions in here. We've been discussing this a lot. I'll summarize our thoughts below. Our discussion centered around the following questions:

1) Do the Unix semantics make sense? Do they make sense in the world of parallelism?
2) Are we enabling common use cases (e.g. new user / tries to write a file) ?
3) What is a user trying to accomplish?

---

1) Do the unix semantics make sense?

Kind of.

For a single node it makes enough sense. But what about for many nodes? Let's say we have 10 nodes. Then what would you expect this output to be?

```shell
echo 'hi' > foo
```

You probably want it to:

a) overwrite the existing foo (basically delete the file)
b) and append 'hi' once per node
c) so that 'foo' contains 10 'hi's 

But that's not really what the `>` operator normally expresses. So even here, we're not really overwriting, we're deleting and appending.

2) Are we enabling common use cases?

Maybe. Maybe not.

If we support the difference between `>` and `>>`, we need to do so by instrumenting the FUSE callbacks. This would be done by watching for some FUSE callbacks. Unclear if this is possible. If there is a unique `SetAttr` we may be able to make this work. If not, we'd have to watch for a `WriteRequest@0`, in which case doing normal new user things like writing a new file (which would also trigger a `WriteRequest@0`) in a job that you run more than once would have the side effect of overwriting (not appending). This is surprising. 

3) What is a user trying to accomplish with this feature?

Considering the parallel use case above and using the `>` operator ... it became clear that the user probably wanted to delete the file ... and then append some more things. So, we'd prefer to be explicit about this desired behavior.

---

So, we're proposing the following. Instead of:

```shell
echo 'hi' > foo
```

We'd expect a user to do:

```shell
rm foo
echo 'hi' > foo # OR
echo 'hi' >> foo
```

And if a user did:

```shell
echo 'hi' > foo
```

It would work the same as it does today --- simply append to the file.

The idea here is that removing / overwriting a file is probably a less common case. And deleting a file is something you should be explicit about (especially since this will often involve deleting a large section of data).

**Comment by derekchiang** [comment]
Briefly summarizing the FUSE semantics that we are implementing here:

* Writing to a file from **any** offset results in appending to the end of the file.

For instance, if you have N parallel jobs and each of them is writing 100 bytes from offset 0, you end up with N * 100 bytes (as opposed to 100 bytes).

As another example, running `echo foo > /pfs/out/file` in 3 parallel jobs results in `foofoofoo`, as opposed to `foo`.

`>` and `>>` will essentially do the same thing.

* A file (or directory) may be deleted by invoking the `unlink` (or `rmdir`) system call.

As such, linux utilities such as `rm`, `rmdir`, and `unlink` will work as expected.

It's important to note that, while you will be able to `rm /pfs/out/file`, you will **not** be able to actually see the file `/pfs/out/file` (through `ls` or `cat`, for instance).

Also note that removing a file that doesn't exist in any prior commit will result in a `File not found` error, similar to how `rm non-existent-file` will fail on a unix machine.

* To overwrite a file, you'd remove a file before you write to it.

For instance, `rm /pfs/out/file && echo foo > /pfs/out/file` will ensure that the file ends up with `foo`, regardless of its previous content.

@sjezewski @jdoliner @JonathanFraser does the above make sense to you?

**Comment by derekchiang** [comment]
Another very important note: deletion only affects previous commits.  For instance, `echo foo > /pfs/out/file && rm /pfs/out/file` will have **exactly the same effect** as `rm /pfs/out/file && echo foo > /pfs/out/file`: the file will end up with `foo`.  While this may appear unintuitive, consider what happens if you run `echo foo > /pfs/out/file && rm /pfs/out/file` in 3 parallel jobs.  If deletion affects the current commit as well, the file can end up with anything between `foo`, `foofoo`, `foofoofoo`, or be deleted altogether.  Whereas under the current semantics, the file is guaranteed to end up with `foofoofoo`.

**Comment by sjezewski** [comment]
Yes, those changes make sense to me. While the difference between `>` and `>>` could be surprising ... it makes sense in the parallel case.

You make a good point about the order of operations of remove. That is surprising. While deleting is probably a rare use case, overwriting is probably not? We'll have to make sure this is clear in the docs (filed under deleting and overwriting).

**Comment by sjezewski** [comment]
This has been merged:

https://github.com/pachyderm/pachyderm/pull/366
