### ISSUE TITLE
Inconsistent undeploy

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#3037]
**What is the ask?**

Undeploy behaviour is dangerously inconsistent. Option (eg -a, -namespace) deletes parts k8s resources relevant to pachyderm without checking the validating of the cluster and its availability. See below:
```bash
➜  wks git:(master) ✗ pachctl undeploy                                               
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
clusterrole.rbac.authorization.k8s.io "pachyderm" deleted
clusterrolebinding.rbac.authorization.k8s.io "pachyderm" deleted
➜  wks git:(master) ✗ pachctl undeploy -a

By using the --all flag, you are going to delete everything, including the
persistent volumes where metadata is stored.  If your persistent volumes
were dynamically provisioned (i.e. if you used the "--dynamic-etcd-nodes"
flag), the underlying volumes will be removed, making metadata such repos,
commits, pipelines, and jobs unrecoverable. If your persistent volume was
manually provisioned (i.e. if you used the "--static-etcd-volume" flag), the
underlying volume will not be removed.

Are you sure you want to proceed? yN
y
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
storageclass.storage.k8s.io "etcd-storage-class" deleted
No resources found
No resources found
➜  wks git:(master) ✗ pachctl undeploy --namespace datapipes -a 

By using the --all flag, you are going to delete everything, including the
persistent volumes where metadata is stored.  If your persistent volumes
were dynamically provisioned (i.e. if you used the "--dynamic-etcd-nodes"
flag), the underlying volumes will be removed, making metadata such repos,
commits, pipelines, and jobs unrecoverable. If your persistent volume was
manually provisioned (i.e. if you used the "--static-etcd-volume" flag), the
underlying volume will not be removed.

Are you sure you want to proceed? yN
y
service "dash" deleted
service "etcd" deleted
service "etcd-headless" deleted
service "pachd" deleted
No resources found
deployment.extensions "dash" deleted
deployment.extensions "pachd" deleted
serviceaccount "pachyderm" deleted
secret "pachyderm-storage-secret" deleted
statefulset.apps "etcd" deleted
No resources found
No resources found
No resources found
persistentvolumeclaim "etcd-storage-etcd-0" deleted
No resources found
➜  wks git:(master) ✗ 

```

**What is the goal / desired outcome?**

Pachctl undeploy should remove everything or nothing. Removing only parts of it leaves us with really bad experience of having lost RABC resources, ETCD but still maintaining resources that no longer usable. 

**If there is a way to accomplish this today via workaround, what does that require?**
yes, but not error prone

**Environment?**: 
- Kubernetes version (use `kubectl version`): 1.10.4
- Pachyderm CLI version (use `pachctl version`): 1.7.4
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): AWS
- OS (e.g. from /etc/os-release): 
- Others:

**Comment by jdoliner** [comment]
Hi @suneeta-mall `pachctl undeploy` is designed to remove as much of the Pachyderm deployment as possible without doing anything dangerous. The only thing we really consider dangerous though is deleting data since that's irreversible, we gate that behind the `-a` flag and have a big warning message to make sure people understand the consequences. We don't consider it dangerous to do things that will impact the availability of the Pachyderm cluster because we feel the user intent of `pachctl undeploy` is to make the cluster unavailable and that this is pretty clear from the name, furthermore it's easily reversed by rerunning `pachctl deploy`. `pachctl undeploy` also doesn't check the consistency of the cluster for a couple of reasons: 
1. consistency is fairly hard to define in this case, for example not all clusters have RBAC roles
2. `pachctl undeploy` is designed as the tool that people use to get out of inconsistent states so they can have a fresh slate to redeploy to.

What you can do to get the behavior you'd like is to save the command you used to deploy pachyderm and then do:

```
pachctl deploy ... --dry-run | kubectl delete
```

this will delete everything your deploy command created because it knows ahead of time what "everything" is. Unlike `pachctl undeploy` which needs to figure out what was deployed by querying Kubernetes and thus only knows about what it finds.

**Comment by suneeta-mall** [comment]
@jdoliner Thanks for the explanation. Yes I agree that perhaps deploying with raw resource definitions will give me desired behaviour and its cool that `--dry-run` gives me this behaviour. 

I will close it.
