### ISSUE TITLE
Allow disabling of file skipping in pipeline specification

### ISSUE THREAD

**Issue by itssimon** [pachyderm/pachyderm#3040]
**What is the ask?**

I need to be able to define a pipeline that processes files no matter what. I have a pipeline that reads an encrypted Avro file and loads a subset of the data to a data warehouse. The pipeline does not produce any output files.

In some occasions the same file ends up in the pipeline's input repository and based on configuration (read from database) a different subset of it's data should be loaded. Pachyderm however does not process the file at all, because it has seen it before and skips over it.

This could be solved by having a parameter in the pipeline specification that simply disables the file skipping, so that the pipeline always processes files committed to the input repository.

**What is the goal / desired outcome?**

Being able to process files, even if they have been processed before without having to change the files contents.

**If there is a way to accomplish this today via workaround, what does that require?**

A workaround would be to alter the files to have different hashes before committing to the input repository. In my case this would be difficult if not impossible, since the files are binary and encrypted.

**Comment by jdoliner** [comment]
Copy pasting from our users slack:

We've found over time that the best way to model behavior like that isn't with pipeline flags but with data, that tends to be a lot more flexible. In your case I'd model it as a cross of 2 inputs: the first is the one you've already got, the second is a "load identifier" which is just a single datum, that you can change anytime you want to force a complete reload.

This is nice because you now have 3 distinct options:
- write a new avro file, and a new identifier: reload from scratch, your desired behavior
- write (or delete) just a new avro file: don't reprocess everything, nice to have for correcting mistakes
- write just a new identifier: reprocess everything, no need to commit something new, nice for development and debugging

**Comment by gabrielgrant** [comment]
Perhaps even better still would be to have this actual config info stored and versioned in Pach, so the provenance tracking meaningfully captures the whole state that is required to recreate the results

**Comment by jdoliner** [comment]
@gabrielgrant having this as a config in the pipeline doesn't really change the provenance that is tracked. Provenance is a little weird in this use-case generally, because your output commits are empty, so you can know which empty commit came from which input commit... but what does that tell you? This is actually another benefit of having an identifier datum, you can use that to distinguish your different loads so you have a kind of pseudo provenance.
