### ISSUE TITLE
Separate pfs and pps

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#305]
Currently, pfs and pps are bundled into one binary.  One implication is that when a pps instance crashes, a pfs instance has to crash too.

This is problematic because pps depends on pfs to function properly.  When a pps node is experiencing failures, we would sometimes like to restart it.  However, we cannot do this without restarting a pfs node too.  But, the reason that the pps node was failing in the first place is likely that some pfs node was failing (or simply unreachable due to network partitions).

So essentially we might get a cascading failure: pfs node fails -> pps node fails, bringing down another pfs node with it -> some other pps node fails, bringing down yet another pfs node...

Separating pfs and pps into two binaries and therefore two kubernetes services would allow us to avoid the cascading failures scenario described above.

**Comment by jdoliner** [comment]
Minor clarification on this, I think our lives will be a bit easier if we stick with a single binary in a single `pachd` container and just add flags to it like `--pps` `--pfs` to change which services it actually launches. Conceptually this accomplishes the same thing, just with a bit less boilerplate code and fewer images to pull.

**Comment by jdoliner** [comment]
The initially reasoning for this hasn't proven to be much of a problem, the worker sidecar has given us some of the benefits here, since it means that each worker has their own pachd instance without needing to connect to the central one and potentially bringing it down. The worker sidecar also shows that it's easy to add new modes to pachd which only run a subset of the services. I'm going to close this issue, we'll be happy to separate out different pachd run targets for different use cases as the arise. But we can track those in separate issues for the specific reasons that the separation needs to happy.
