### ISSUE TITLE
Pipeline parallelism not always guaranteed ? 

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#3096]
**What happened?**:
I processed about 16K datums in constant parallelism of 3 workers.  When the processing state reaches to just short by 26 datum (26 datum yet to process whilst rest finished processing), then something about parallelism starts to misbehave. 2 of thh 3 workers just sitting there doing nothing but the last one is processing all the remaining 26 datum in now serial sequence.  Pipeline spec still shows parallelism as 3 but the none of the remaining datums were processed in parallelism. 

I cant tell how long the pipeline has been churning into artificial parallelism of 1 but when it was processing about 14K datum then it was fairly parallel.   

**What you expected to happen?**:
Expected it to process all datum in parallelism and utilise max capacity. 

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.10.4
- Pachyderm CLI version (use `pachctl version`): 1.7.4
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): AWS
- OS (e.g. from /etc/os-release): 
- Others:

**Comment by jdoliner** [comment]
This is what's known as a "straggler" in distributed computing. Processing a datum entails a certain amount of overhead, so instead of paying that overhead for each datum we pay it for chunks of datums. This greatly decreases the fixed cost of processing a datum, but has the disadvantage that there can't be parallelism within a single chunk, so at the end when there's only one chunk left it gets processed by a single worker. You can control how we chunk the job using the `chunk_spec` parameter in the pipeline spec. But it's very unlikely that you'll make the job run faster. 26 datums is about .1% of your job that's taking 3 times longer than it needs to, this translates to a very small amount of overall runtime that you could save by making your parallelism perfectly distributed.
