### ISSUE TITLE
Is 1.7.5 Backward incompatible? 

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#3104]
**What happened?**:
I was setting up new cluster so I pulled of hot of the press 1.7.5. But I see some very strange behaviour with this version:

The scenario is:
```
pachctl create-repo y
pachctl create-repo x
pachctl put-file y master -f L1/L2/123.json
pachctl put-file x master -f L1/L2/123.json
pachctl list-file x  master "*"                                         
NAME           TYPE SIZE 
L1/L2/ dir  700B 
pachctl create-pipeline -f pp.json
```

where pp.json is:
```
{
  "input": {
    "union": [
      {
        "atom": {
          "glob": "*",
          "repo": "x"
        }
      },
      {
        "atom": {
          "glob": "*",
          "repo": "y"
        }
      }
    ]
  },
  "pipeline": {
    "name": "x1"
  },
  "transform": {
    "cmd": [
      "/bin/bash"
    ],
    "image": "library/ubuntu",
    "stdin": [
      "files=$(find /pfs  -type f \\( -path '*x/*' -or -path '*y/*' \\))",
      "echo $files > /pfs/out/files",
      "for f in $files; do z=${f#*/}; z=${z#*/}; z=${z#*/}; echo /pfs/out/${z%/*}; mkdir -p /pfs/out/${z%/*};  cp -r $f /pfs/out/$z; done"
    ]
  },
  "enable_stats": true
}
```

### Now on 1.7.5 I see:
```
/pfs/.scratch/665d161e3bbc4560a324eb1ecbcb260f/x/L1/L2/123.json
/pfs/.scratch/13b0bd6ad4454aabb5ceaf83330bfd9d/y/L1/L2/123.json
```

###  But on 1.7.4 it gives me:
```
pachctl get-file x1 master "/files"
/pfs/x/L1/L2/123.json
/pfs/y/L1/L2/123.json
```
As per documentation behaviour of 1.7.4 is correct. What am I missing?
**What you expected to happen?**:

PFS behaviour on 1.7.5 and 1.7.4 to be same.

**How to reproduce it (as minimally and precisely as possible)?**:
Steps above 

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment]
This was changed as part of: https://github.com/pachyderm/pachyderm/pull/3031 it's necessary that the scratch space for `/pfs` be under `/pfs` itself, (previously it was `/scratch`) otherwise we can't use symlinks to put the data into place and have to use bind mounts which require privileged containers.

Sorry this came as a surprise, unfortunately our backward compatibility guarantees can't be strong enough that we guarantee the filesystem that user code sees will always be identical between releases. We can guarantee that the inputs and outputs under `/pfs` will be in the same place but sometimes we need to add some other hidden files or move stuff around to get things to work.

**Comment by jdoliner** [comment]
As workaround here you can have your `find` invocation ignore hidden directories.

**Comment by jdelfino** [comment]
This bit us too, for 2 reasons: the addition of .scratch, and the fact that files under /pfs seem to have changed to symlinks. We use golang's `filepath.Walk` to iterate through input files, and that function does not follow symlinks. 

I think this should at least be noted prominently in the release notes. Ideally this sort of change also wouldn't show up in a point release, since it is not fully backward compatible.

**Comment by jdoliner** [comment]
@suneeta-mall and @jdelfino sorry that this affected you. Going forward we'll make sure not to put changes like this in point releases, which means that there will also be an RC period for changes like this that will give you more of a heads up. I hadn't fully thought through the various access patterns this could break. I was thinking of it as just adding some hidden files that most user code wouldn't even notice, but with things like `find` that's easier to notice than I was counting on. And changing to symlinks from bind-mounts is a much bigger deal than I thought it would be. Apologies again an thanks for bearing with us.
