### ISSUE TITLE
Update pachctl deploy defaults for cloud deployments

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#3137]
**What is the ask?**

Customers often want to connect to the cluster not via an IP. It'd be easy enough to change the default `pachd` service to be of type `LoadBalancer` to accommodate connecting this way.

**Comment by jdoliner** [comment]
I'm not sure a load balancer makes for a good default for deployments. For one it isn't generally supported, it only works on clouds, but it'll fail deployment on-prem, which is a lot of our deployments. But it's also a bit dangerous because it can lead to accidentally publicly exposing the service when you don't want to. I think having to do an extra step to setup the loadbalancer is probably reasonable.
