### ISSUE TITLE
Move egressing into merge process (Add a pipeline state 'egressing').

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#3223]
Currently, if a pipeline has `egress` set, then after a job finishes running it appears to get into a funny state: the job's output commit gets finished, but the job stays in state `running` until egress is finished. This is confusing to users and also potentially lossy, if the master dies while egress is running (which can happen because egress is slow and potentially consumes a lot of memory).

It would be better if we indicated this transition in the JobInfo, so that a) it can be displayed to users, and b) the worker master could detect it and resume egress on failure

**Comment by jdoliner** [comment]
We don't actually want an `egressing` state for jobs, because now that merging is done in parallel it makes sense to do egressing as we merge. This will massively increase the scalability of the egress feature. However it makes more sense to call the state `merging` than egressing, since merging will always happen during this time, but egressing will only happen if it's set.
