### ISSUE TITLE
put-file from s3 in 1.8.0 gets 404

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#3262]
```
$ aws s3 mb --region=us-west-1 s3://pachyderm-test-bucket-12072018-3
make_bucket: pachyderm-test-bucket-12072018-3
$ pachctl create-repo test
$ pachctl put-file -r test master /f -f s3://pachyderm-test-bucket-12072018-3
$ aws s3 cp ./LICENSE s3://pachyderm-test-bucket-12072018-3
$ pachctl put-file -r test master /f -f s3://pachyderm-test-bucket-12072018-3
NoSuchKey: The specified key does not exist.
     status code: 404, request id: CC7300D2D41A076F, host id: 404mewZf2gIJTADKQ48lgbwR/+G5CQAvW5SORwtRc98A/+lejXvUWhe0KBC4vWrZ4FH7wmjk/gs=
```

**Comment by ysimonson** [comment]
This is being caused by interactions with the path reversing logic for S3.

* The Amazon client is configured to reverse by default.
* When reverse is true, the `Walk` method calls its input callback with the key *not* reversed.
* When reverse is true, the `Reader` method *does* reverse its input key.

Should the Amazon client be configured to not reverse by default? Or should the `Walk` method call its callback with the key reversed?
