### ISSUE TITLE
Atomically update multiple pipelines (with transactions?)

### ISSUE THREAD

**Issue by mttwong** [pachyderm/pachyderm#3287]
**What is the goal / desired outcome?**
I want to be able to update all of my pipelines all at once by using `pachctl update-pipeline -f ...` on all of my pipelines.  Right now, I have a script that pulls these pipelines from a storage bucket and then updates them on the cluster.  In general, I don't want this step to reprocess my pipelines.  Then, if my change requires a reprocess, I want to be able to issue a command to just reprocess the pipelines that were affected by my change, without having to download my pipeline json files from cloud storage. 

**If there is a way to accomplish this today via workaround, what does that require?**
Right now, I can do this by downloading my pipeline files and then issuing `pachctl update-pipeline -f <file-from-cloud> --reprocess`, but it requires me to download the file.

**(Optional) What is your proposal for a feature to solve this?**
`pachctl update-pipeline -p <pipeline name> --reprocess` or `pachctl reprocess-pipeline -p <pipeline-name>`

**Comment by gabrielgrant** [comment]
Seems like a very reasonable ask. Internally not sure whether i makes more sense to shoe-horn this into the UpdatePipeline API call vs adding a new endpoint. @jdoliner ?

**Comment by JoeyZwicker** [comment]
right now when you call update-pipeline without the reprocess flag, it'll kick off a job, but that job will skip all datums, assuming they're all successful.  it will still retry failed datums, which I think is the behavior we want. 

My reading of the main requests here are:
- Atomic updates for multiple pipelines simultaneously -- this seems very reasonable
- Having update-pipeline not trigger any job. I'm not sure if we want to do this because it then requires multiple steps for a standard "my code is wrong and I want to push a fix" workflow
- A way to reprocess a pipeline without having to grab the json spec file. This only seems to make sense if the pipeline failed for transient reasons. 

@mttwong If I'm misunderstanding some part of your use case, definitely clarify for us.

**Comment by mttwong** [comment]
> Atomic updates for multiple pipelines simultaneously -- this seems very reasonable

I definitely want this.  Updating my pipelines if very slow because it is done sequentially.  I would really like to deploy all my pipelines at once.

> Having update-pipeline not trigger any job. I'm not sure if we want to do this because it then requires multiple steps for a standard "my code is wrong and I want to push a fix" workflow

Not exactly what I am after, I'll explain after point 3.

> A way to reprocess a pipeline without having to grab the json spec file. This only seems to make sense if the pipeline failed for transient reasons.

The fact that I have to get the json file is just inconvenient.  I want to deploy all of my pipelines at once, then reprocess the pipelines with the changed behavior.  I can do this now, I just have to download the json file even though I am not changing it at all (since I just updated all my pipelines).

**Comment by gabrielgrant** [comment]
Thanks for the clarification, @mttwong -- having a separate `reprocess-pipeline` command makes sense to me

**Comment by gabrielgrant** [comment]
I think the (probably more minor) part about having to manually fetch your pipeline specs can be worked around today by piping `extract-pipeline` to `update-pipeline`, but that does seem like a bit of a kludge and should probably be built in. As for the multi-update part of this request, would that be addressed by what we're talking about in #3267 @mttwong ?

**Comment by JoeyZwicker** [comment]
Renaming this issue to the only feature here that is still regularly asked for -- atomically updating multiple pipelines. We have `transactions` so that's probably the best solution, although not sure if there are other internal complications. 

Being able to update a pipeline without passing the pipeline spec isn't something I've seen asked for very often, but is a possible ergonomics improvement too.

**Comment by JoeyZwicker** [comment]
+1 to this from another user
