### ISSUE TITLE
Volumes in 'pod_spec' should be appended to pipeline volumes, instead of replacing them

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#3319]
Per Kyle Tarplee in our users channel:
```
I want to add a volume so I need to append to "volumes" and to the "user"
container "volumeMounts" list. I do not see how to append to a list.  The code
in question is:
https://github.com/pachyderm/pachyderm/blob/80176efe4eb1a4184a8357773616f819668378cb/src/server/pps/server/worker_rc.go#L189

I do not think json.Unmarshal() is what should be used to properly merge the
"pod_spec" JSON into the newly created podSpec instance.
```

**Comment by ktarplee** [comment]
The volumes element is not the only one that contains a list.  There are many things that someone might want to change in the k8s pod spec.

I would suggest using a more general patching policy.  For example we could use [json-patch](https://github.com/evanphx/json-patch) then pod_spec becomes a formal JSON patch per [RFC 6902](https://tools.ietf.org/html/rfc6902).  Then we would cover every case. This is how `kubectl patch pod valid-pod --type='json' -p='[{"op": "replace", "path": "/spec/containers/0/image", "value":"new image"}]'`.  The -p argument is the JSON patch.  You can add, delete, replace, etc. with a JSON patch.

Another approach would be to use code from [k8s](https://github.com/kubernetes/kubernetes/blob/a3d30dc939c102be2eec3d7d5c7f33f63a1e9893/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go) and support ALL the types of merging and patching that kubernetes supports.  I think that would be overkill at this point.

**Comment by ktarplee** [comment]
I should mention that my use case is two fold.
1. I want to be able to increase shared memory (k8s does not support this directly) with this [hack](https://docs.okd.io/latest/dev_guide/shared_memory.html) to allow my pytorch GPU code to work properly.
2. Add large ("never" changing) mounts to one of the pipelines so that I do not have to take the performance hit of downloading it every time (and unpacking it).  There are around 1 million files that I want to use this for so I tar them up (for now).  I realize this breaks encapsulation, but the use cases are numerous,  such as NLTK data (large, never changing, and should not go in the container).

This is a show stopper for me.  I cannot use my two GPUs with pachyderm until pod_spec is functional in pipelines for adding modules.  I have exhausted all other known options.

**Comment by JoeyZwicker** [comment]
Thanks for the details @ktarplee. We'll work on taking a look at this as soon as possible.

**Comment by gabrielgrant** [comment]
I think what we probably want is to have two pod specs: one to over-ride values in our generated spec (afaiu this is what we do today), and one to be recursively merged (so, for example, lists could be extended)

We _could_ go so far as to allow passing something like an entire `jq` filter (or list of filters) to apply (this would have made the recent OpenShift work way easier, for example), but that's probably overkill

**Comment by gabrielgrant** [comment]
sorry, i should have added some context from an in-person convo:

Overall, I totally get the use-case, and like the gist of using JSON-patch, it's just that I've had some bad experiences with it in practice in the past. Specifically, JSON-patch uses the fairly restrictive [JSON Pointer (IETF RFC 6901) spec](https://tools.ietf.org/html/rfc6901), which requires specifying array indices exactly (compared with something like JSON-path, or jq, both of which have some richer form of "querying")

In some more "traditional" uses of JSON[1], this isn't terrible, but in the way we/K8S (and many modern APIs) use JSON, this is problematic, because "key-value" pairs are often stored in a non-stably/imporantly-ordered array (effectively being used as a set) of JSON objects where each contains some sort of "key" (`name`, generally, in K8S) and value. This means that it's effectively impossible to, say, replace the value of an env var, since the position of the particular env var in the array may change, others may be added, etc.

This is the primary reason I've been using jq in the recent work I've been doing to manipulate `pachctl deploy custom`'s output to work on OpenShift -- I can do things like: 

```
# disable usage of the docker socket (in pachd container template, within pachd Deployment)

jq 'select(.kind == "Deployment" and .metadata.name == "pachd").spec.template.spec.containers[] |= (select(.name == "pachd").env[] |= (select(.name == "NO_EXPOSE_DOCKER_SOCKET").value = "true"))'
```

Far more powerful, if somewhat opaque

As for how it could be used, jq is a full self-contained C implementation, so the options would be either to just ship the binary in the pachd image and shell out to it, or to use libjq through an FFI layer (probably just cgo)

All that being said, I wouldn't be entirely opposed to having a JSON-Patch-based implementation if you think that better addresses the use-case than just having a single "overwrite" and "merge" tree (and especially if you're willing to contribute it!). I am curious, though, which specific cases the flexibility of JSON-Patch actually helps with, over a simpler replace-and-merge (totally believe there may be some, I just don't have examples coming to mind)

[1]: By "traditional", I mean specifically where:
1. mappings are always stored as JSON objects with keys as keys and values as values
2. Array order is stable (and, ideally, relevant)

**Comment by mdaniel** [comment]
> This means that it's effectively impossible to use JSON-Patch to, say, replace the value of an env var, since the position of the particular env var in the array may change, others may be added, etc.

I hear that they _may_ change, but has it been your experience that they _do_ change? Toward that end, AIUI, that's the risk that `{"op": "test"}` is trying to address: bomb rather than applying a patch to the wrong place. I would also be super interested in knowing if `pachd` has influence over the stable ordering of those arrays, since [it appears they are ordered at generation time](https://github.com/pachyderm/pachyderm/blob/master/src/server/pps/server/worker_rc.go#L220) and I would be stunned if kubernetes itself reorders them.

>  I am curious, though, which specific cases the flexibility of JSON-Patch actually helps with, over a simpler replace-and-merge (totally believe there may be some, I just don't have examples coming to mind)

I don't know exactly what "replace and merge" means in your mind, but I would be perfectly fine if the merge keys system used by k8s was actually used, but the situation right now is that `pod_spec:` does not merge `volumes[]` even though it has `name:` merge keys on the existing objects, and (at least in my case) it always has merge keys on input

**Comment by gabrielgrant** [comment]
Basically the point i was trying to make about JSON patch being broader than what's needed for these simpler use-cases is that i have trouble coming up with use-cases for `move` or `copy` operations. But, at the end of the day, I think you're probably right that using a standard is more important than minimizing the API surface. So thinking the best path forward is doing JSON patch for now (which iiuc JD has already started on), then, if we find we're running into cases for which richer querying is needed, we could add a jq (or similar) filter (`pod_spec_jq_filters`?) down the line

**Comment by ktarplee** [comment]
Just for future reference.  I was able to use pod_patch to increase the shared memory.  The formatted patch is
```
[
    {
        "op": "add",
        "path": "/volumes/-",
        "value": {
            "name": "dshm",
            "emptyDir": {
                "medium": "Memory"
            }
        }
    },
    {
        "op": "add",
        "path": "/containers/0/volumeMounts/-",
        "value": {
            "mountPath": "/dev/shm",
            "name": "dshm"
        }
    }
]
```

This can be applied to the pipeline file by adding the line.
```
"pod_patch": "[{\"op\": \"add\", \"path\": \"/volumes/-\", \"value\": {\"name\": \"dshm\", \"emptyDir\": {\"medium\": \"Memory\"}}}, {\"op\": \"add\", \"path\": \"/containers/0/volumeMounts/-\", \"value\": {\"mountPath\": \"/dev/shm\", \"name\": \"dshm\"}}]"
```

**Comment by gabrielgrant** [comment]
@ktarplee glad that worked!

Still makes a me a bit uncomfortable that you have to know that pachyderm already supplies a list of volumes (and that there's no way to insulate yourself from this implementation detail, as afaik there's no way to append to a list if it exists, or create it if it does not). This is one of the issues with JSON patch, but I think it may be addressed by using a [JSON merge patch](https://tools.ietf.org/html/rfc7386), right? @jdoliner I am correct that the `pod_spec` field now assumes the passed value is a merge-patch by default? (as opposed to it's old behavior of just bluntly overwriting)

As an aside: I have to admit I didn't know merge patches existed when I wrote my comments above about applying an "override and a merge operation" (as that seems to be pretty much a better-thought-out version of exactly what I was trying to describe), and had totally missed that @ktarplee had already linked to [k8s' implementation](https://github.com/kubernetes/kubernetes/blob/a3d30dc939c102be2eec3d7d5c7f33f63a1e9893/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go) in [his comment above](https://github.com/pachyderm/pachyderm/issues/3319#issuecomment-450729699)

**Comment by jdoliner** [comment]
@gabrielgrant this is all right except you're mixing up JSON patches and JSON merge patches (I can't imagine why).

`pod_spec` _is_ a JSON merge patch, however this does not allowing appending. For that you need to use `pod_patch` which is a JSON patch (not a _merge_ patch), these do allow appending. So you'll need to use those if you want to append volumes.

**Comment by gabrielgrant** [comment]
Ah, no I was actually confusing the IETF's RFC 7396 (ie the official, standard) JSON Merge Patch with a _third_ spec, the "**Strategic** Merge Patch" (which appears to be a K8S-specific "standard"): https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md

_Strategic_ Merge Patch is the one that is most similar to what I was describing earlier, where there are separate directives for "overrides" (delete/replace) and "merges" (which include "merging" lists by combining elements)

The benefit of that, over requiring the use of JSON Patch appends, is that it seems a JSON Patch append only works if the list already exists in the base document -- an append to a non-existent key is an error.

What would you think of switching to using that "spec" (by just using the K8S implementation)? It's technically non-standard, but is K8S-world-standard (and does seem pretty much strictly better than the alternatives)

**Comment by jdoliner** [comment]
I'd be down for using the k8s strategic merge patch, not sure if we should just add it as a third option or have it become the one option if it covers all the usecases, of course, backwards compatibility will be a concern so we may have to keep the other kinds of patches around for a little while.
