### ISSUE TITLE
Flash-crowd behavior

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#332]
It's been observed in my cluster that the following scenario occurs:

I have a non-reduce pipeline with the degree of parallelism set to N.  An input commit comes in.  The input commit contains a number of large files, each of which contains more than N blocks.

Now, the way we assign inputs to jobs, the n-th job will get the n-th block to every file.  So the first job gets the first block to every file, the second job gets the second block to every file, etc.

Since each file contains more than N blocks, each job essentially sees the same files, i.e. all files.

What happens next is that, each job starts processing the same file, i.e. the first file in the input directory.  Since we shard traffic by file path, all these jobs start reading file from the same server.  So even though we'd ideally want traffic to spread across the cluster, we in fact get a flash-crowd behavior where all jobs talk to the same server.

**Comment by jdoliner** [comment]
Few clarifications here, we assign inputs to jobs just by hashing the name of the block. So I don't think there's any guarantee about the nth block going to the nth job. However this does mean that with large files we can expect each job to see each file. Having each job see a piece of each file is generally a good thing, but doing them all in the same order.

I think this issue ultimately comes down to a question of what order `ListFiles` returns it's `FileInfo`s in. Right now there's no guarantees because it reads them out of a `map` and although golang `map`s aren't guaranteed to be in order they're also not guaranteed to be out of order. In fact they normally iterate in the same order. We should add a randomization step to `ReduceFileInfos` and I think this issue will go away.

**Comment by derekchiang** [comment]
@jdoliner actually, I found that `ListFiles` is already returning files in a random order.  It's just that my jobs, by using golang's `ioutil.ReadDir`, are implicitly sorting files by filename.  So I'm guessing this is a non-issue after all.  Our user just needs to be smart and process files in random order.

I guess the only thing we can do about this issue is to talk about it somewhere in our upcoming documents, so our users know how to avoid this flash-crowd behavior.

**Comment by jdoliner** [comment]
Yeah, not much we can do if the user is lexicographically sorting the filenames after the fact. Documenting is a great idea though.
