### ISSUE TITLE
Pipeline/job persistence

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#338]
Currently pipelines and jobs do not survive cluster failures.  That is, if you blow away your pachyderm cluster and start a new one, you lose all your pipelines and jobs (although data gets persisted as long as you are using a real storage backend such as GCE/S3).

Ideally, we should use [persistent volumes](http://kubernetes.io/docs/user-guide/persistent-volumes/) with RethinkDB (where pipeline/job infos are stored).

@jdoliner 1.0 worthy?

**Comment by jdoliner** [comment]
Losing your jobs when you blow away the cluster is expected I think and we should maybe even see if we can cleanup the bucket. But you can also lose your jobs due to a node failing and the rethinkdb pod being rescheduled which is a problem. Using persistent volumes seems like the right answer to me as well, we should use them for both RethinkDB and etcd. This is definitely 1.0 worthy but we could solve this in a couple of ways, ideally we can just ship a manifest that works out of the box. That may be wishful thinking based on the state of the art with persistence in containers and the fact that we target 2 major cloud platforms. We could also solve this with documentation about how to productionize your cluster on various cloud platforms.

Could you do a bit of research about what the state of the art is here? There must be some other people who have deployed etcd (and possible rethinkdb) on kubernetes using persistent volumes. Would be good to know what they did.

**Comment by derekchiang** [comment]
Quick update on this.  With the help from Daniel Mewes from rethinkdb we were able to clear some roadblocks.  So here is the story of data persistence:

1. For a GCE deployment, we will be using [GCE Persistence Disk](http://kubernetes.io/docs/user-guide/volumes/#gcepersistentdisk).
2. For a AWS deployment, we will be using [Elastic Block Store](http://kubernetes.io/docs/user-guide/volumes/#awselasticblockstore).
2. For a local deployment, we could use [hostPath](http://kubernetes.io/docs/user-guide/volumes/#hostpath), but that's probably unnecessary since we are currently assuming that the local cluster is inconsequential and can be blown away.

So there are two things to do in order to close this issue:

1. Update `pach-deploy` so it's able to generate manifest for GCE Persistence Disk and Elastic Block Store.
2. Update `SETUP.md` so the user knows how to generate the said manifest, and how to create GCE Persistence Disk and Elastic Block Store.

**Comment by derekchiang** [comment]
Fixed in #368
