### ISSUE TITLE
Pachyderm CLI docs is missing its index

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#3382]
The pachyderm CLI docs are missing its TOC tree: https://docs.pachyderm.io/en/latest/pachctl/pachctl.html

**Comment by JoeyZwicker** [comment]
I think it was using the .md file instead of the .rst. This has been a constant headache, but maybe it'll work now. started a new docs build. 

@Nick-Harvey https://github.com/pachyderm/pachyderm/blob/master/doc/pachctl/pachctl.rst needs to be updated to include all pachctl cmds -- i think it's missing quite a few

**Comment by pappasilenus** [comment]
This is kind of a dupe of #2559

**Comment by ysimonson** [comment]
Yeah, you're right. Closing.
