### ISSUE TITLE
pipeline workers fail to run without root, due to cert error when connecting to sidecar

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3394]
After working around #3393 by manually removing the `runAsUser` annotation, we see a problem on the pipeline worker pod (user container) caused by running as a non-root user that results in it getting stuck in a crash loop:

```
$ oc logs pod/pipeline-edges-v1-9nzm4 -c user
time="2019-01-23T22:34:17Z" level=warning msg="skipping "/pach-bin/certs/ca-certificates.crt", could not create output file "/etc/ssl/certs/ca-certificates.crt": open /etc/ssl/certs/ca-certificates.crt: permission denied" 
time="2019-01-23T22:34:17Z" level=warning msg="Errors were encountered while copying /pach-bin/certs to /etc/ssl/certs (see above--might result in subsequent SSL/TLS errors)" 
error constructing pachClient: context deadline exceeded
```

**Comment by ysimonson** [comment]
Possibly fixed by https://github.com/pachyderm/pachyderm/tree/fix-sidecar-port-propagation

**Comment by gabrielgrant** [comment]
it's unclear whether the cert issue is actually blocking. afaict, it doesn't seem to be at the moment, since we're talking to the sidecar over a local port within the pod, which doesn't require a cert

**Comment by ysimonson** [comment]
Holding on this until we verify whether it's blocking or not. If it does end up being blocking with the other fixes in place, let me know and I'll circle back.

**Comment by gabrielgrant** [comment]
It appears to not be blocking. Still seems like setting this up as an emptydir mount could work in most cases, but does run the risk of issues if the base image already has something in `/etc/ssl/certs/`

So probably good to leave this for now

**Comment by ysimonson** [comment]
Did emptydir end up fixing this?

**Comment by ysimonson** [comment]
@gabrielgrant ping

**Comment by gabrielgrant** [comment]
i don't believe any fix was needed for this -- my recollection is that the "error" turned out to actually be benign (and the real issue was actually some of the other port errors you fixed), so i didn't bother overwriting that dir with an emptydir to avoid the possibility of breaking things in the case that an image actually did have some certs in that dir already

**Comment by gabrielgrant** [comment]
I'm still not actually sure why that cert is needed at all, since i'm pretty sure the worker communicates with the sidecar pachd over a private port that doesn't require a cert to connect over. @msteffen do you know why this cert is being written in the first place? is something here going to break if TLS is enabled? any suggestions of possible approaches if we actually want to fix this?

**Comment by msteffen** [comment]
@gabrielgrant The TLS certs that the `worker` binary is copying into `/etc/ssl` aren't related to Pachyderm TLS. We use those for talking to object store from the worker, e.g. for egress and perhaps in other cases. If the cluster where this was failing was able to run all of their pipelines despite the error, then it's not issue. In general, through (Pachyderm running in AWS) this will prevent pachyderm from working in at least some cases.

Basically, the `pachyerm/worker` docker image contains:
- the worker binary
- etc/worker/worker.sh
- Whatever's in `/etc/ssl/certs/ca-certificates.crt` on the machine that's building the `pachyderm/worker` images

Then, when we bring up a new pipeline, we run `pachyderm/worker` as an init container, and whatever's in the `pipeline.image` field as the `user` container. The `pachyderm/worker` container runs first, copies its version of `ca-certificates.crt` and the worker binary into the `user` container, and then runs the worker binary in the user container.

The worker binary starts and copies the version of `ca-certificates.crt` into `/etc/ssl` inside the user container, and thereafter, any time the worker binary makes RPCs to S3, they won't choke (which has always happened when `egress` is enabled, and now may also happen when `PutFile`-ing output data into Pachyderm, post 1.8)

I'm closing this issue because it's several months old, but whoever was hitting this bug may still need to fix it.

**Comment by gabrielgrant** [comment]
@msteffen I'm not sure i follow what the user could do to fix this? it sounds like this process is going to consistently fail whenever the worker binary running in the user container isn't run as root (ie doesn't have write access to `/etc/ssl/certs/ca-certificates.crt`), isn't it?

**Comment by msteffen** [comment]
Uh, sorta. I'd lost track of that piece of context. The main things I wanted to communicate above is:
- This error is unrelated to pachd TLS
- This error *is* related to worker<->object store requests

I mean I think a hacky solution could be that the user always uses a docker image with `/etc/ssl/certs` in it. Then they'll get this error every time they run a pipeline, but it's non-fatal, and because their image still has certs the worker binary will still be able to communicate with object store.

Obviously it would be nice if this could just work a little better. Maybe we could build public certs directly into the worker binary? `/etc/ssl/` is only 800k on my laptop. I'll reopen that as a separate issue
