### ISSUE TITLE
pachctl deploy local says to run port-forward even when implicit port forwarding enabled

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#3459]
**What happened?**:

Ran `pachctl deploy local` and got this output

`beemo:opencv jk$ pachctl deploy local
serviceaccount/pachyderm created
clusterrole.rbac.authorization.k8s.io/pachyderm created
clusterrolebinding.rbac.authorization.k8s.io/pachyderm created
deployment.apps/etcd created
service/etcd created
service/pachd created
deployment.apps/pachd created
service/dash created
deployment.apps/dash created
secret/pachyderm-storage-secret created

Pachyderm is launching. Check its status with "kubectl get all"
*Once launched, access the dashboard by running "pachctl port-forward*`

**What you expected to happen?**:

The last line is confusing.  pachctl should inform me that implicit port is enabled with an appropriate message.  A user should only receive that message when the --no-port-forwarding flag is set. 

**How to reproduce it (as minimally and precisely as possible)?**:

Do a local deploy and see the message.

**Comment by ysimonson** [comment]
This needs a better message, but the reason it's showing up is because the dash is not accessible through implicit port forwarding, which only (transiently) port forwards for pachd and SAML ACS. Explicit port forwarding will enable dash access.

**Comment by pappasilenus** [comment]
But I'm able to see the dash without explicit port forwarding.

**Comment by ysimonson** [comment]
You haven't set PACHD_ADDRESS or ADDRESS env vars either?

**Comment by ysimonson** [comment]
Hmm, I'm actually not sure if we can improve this message much:

* I think it should show up regardless of whether `--no-port-forwarding` is set, because, even if implicit port forwarding is enabled, you still need to use `pachctl port-forward` in order to access the dash.
* We could suggest that they can also connect directly, but we won't know the IP address.

@gabrielgrant would love your thoughts here

**Comment by gabrielgrant** [comment]
Yes, dash is accessible with a local deployment by just visiting the relevant IP (usually 192.168.99.100 with minikube iirc), and that generally seems to work better than going through port-forward. My understanding is the problems with suggesting that are (as @ysimonson pointed out):
1. It's not clear how we find what IP to point people at (in some cases this could maybe come from parsing the kubectl config?)
2. Even if we find the address of the minikube cluster, if this is a non-local deploy, there is not necessarily a host we can point to that will have the relevant port open (I'm actually not sure if this is generally true -- the dash is exposed with `NodePort`s; if we can reach the k8s API node to do a port-forward, in practice, does this not expose the `NodePorts` as well as the API endpoint?)

Where 2. is _definitely_ a problem is if people have removed the NodePort declarations (since those are a cluster-global resource, this is likely in prod environments or where they're trying to run multiple instances of pach). But in those cases, people hopefully know what they're doing and can set up their own ingress path.

Also note, this is all what is hopefully going to be a lot easier once we have a gateway

**Comment by ysimonson** [comment]
Oh (2) is a good point. I'll dig around. It'd be awesome if we could tell the user the exact env var value to set to directly connect!

**Comment by ysimonson** [comment]
Okay, we could expose the cluster IP to directly connect to, but as you mentioned, for most cloud-deployed instances it won't be possible to directly connect. How do we want to proceed?

**Comment by JoeyZwicker** [comment]
@pappasilenus Unless you are connecting to the dash directly, I don't think you should be able to access the dash via localhost without explicit port-forward, so that's what that message is for. 

There are so many permutations for connecting that IMO, even though port-forward is one of the least "good" ones, it's also one that is available in every setup and therefore I don't thin we need to immediately change anything here. 

Most of the other info contained in this issue is already captured in our other ingress and connecting to pachyderm thread, so should we close this?

**Comment by ysimonson** [comment]
I'm going to close this for now, but @pappasilenus let me know if you disagree
