### ISSUE TITLE
Dynamically adjust the number of shards

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#349]
Currently the number of shards is [hardcoded in the kubernetes manifest file](https://github.com/pachyderm/pachyderm/blob/a1c450fb8223c92783fb002ff843ebe51b9bd7d0/etc/kube/pachyderm.json#L381).  And since the hardcoded number is 32, having more than 32 servers won't do us any good.

We should instead dynamically set the number of shards to something like the number of servers * 5.

@jdoliner 1.0 worthy?

**Comment by derekchiang** [comment]
I realize that this is a little more complicated than I initially thought.  Since each `DiffInfo` is tied to a shard on creation, we need to ensure that, by dynamically adjusting the number of shards, we don't accidentally create dangling `DiffInfo`s that belong to shards that no longer exist.

@jdoliner am I right in understanding that there is no fundamental reason why a `DiffInfo` has to be tied to a certain shard?  As in, we could just as well hash a `DiffInfo` and modulo it to a certain shard.

**Comment by jdoliner** [comment]
This would be very complicated to change and I'm not sure I understand the reasoning for wanting to change it. Having a static number of shards known throughout the cluster makes a number of things easy and there are a lot of difficulties which switching this number dynamically. For example, suppose we double our shard count, the `DiffInfo` for shard `0` now needs to be split in half because half of the files it has info for are now supposed to be stored in another shard. Doing this safely using object storage semantics is going to be really tough because you need to overwrite the old version of the `DiffInfo` with a new version. If that write fails then you don't have a way to recover the data that was there. So you'll need to do something like write a copy of the file somewhere else just in case the write fails and then delete it. There are a bunch of issues of this sort and I'm fairly convinced that keeping a dead simple access pattern to obj storage is going to be an asset for us long term.

So what can we do here?

First we should identify the actual issues that we're trying to solve:
The first issue is that we can only use 32 nodes with the current setup. That first order problem is pretty easily solved by upping the number of shards, but then we start to hit some other issues. They are:

1. each shard requires 8 bytes per shard every time roles are assigned, this is particularly bad when there are many more shards than nodes
2. each commit will write a `DiffInfo` per shard, even if they're empty, this can lead to a write explosion

1 could probably be substantially aided by assigning ranges of shards rather than single shards.
2 is trickier though.

In terms of actions on this issue, I think for the time being we should table this. The issues here are definitely performance and for 1.0 I just want to focus on correctness. After 1.0 ships we'll start doing more performance testing and we'll hopefully hit some of these issues through use and will then have a better idea how to fix them.

**Comment by jdoliner** [comment]
I think we're going to do away with shards in the pfs refactor so this no longer applies. Closing.
