### ISSUE TITLE
Pachctl inspect-commit should include branch information

### ISSUE THREAD

**Issue by Nick-Harvey** [pachyderm/pachyderm#3529]
**What is the goal / desired outcome?**
When running `pachctl inspect-commit <repo> <commitid>` the output should include a field to display branch information. 

**If there is a way to accomplish this today via workaround, what does that require?**
not to my knowledge

**(Optional) What is your proposal for a feature to solve this?**
just include a field in the output stating the branch that commit was created 

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI version (use `pachctl version`): pachctl 1.8.5
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): minikube
- OS (e.g. from /etc/os-release): Mac Mojave
- Others:

**Comment by gabrielgrant** [comment]
This is actually a bit of a tricky problem, since a commit can be part of multiple branches (or be part of no branch at all). We have an algorithm for this to pick a "primary branch" for a given commit in the dash, but it's not an exact science. One option would be to just show a list of all the branches that a commit is part of, another option (used by `git`) would be to show which commit a branch current points at (ie HEAD), but not to show branch info for non-HEAD commits
