### ISSUE TITLE
Document S3 Gateway Feature

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#3616]
API-style docs are added in #3508 , but broader explanatory docs that are more user friendly need to be included. See PR thread for some examples of the missing pieces.

**Comment by JoeyZwicker** [comment]
we're starting to push this feature more so time to get this out of backlog

**Comment by svekars** [comment]
@JoeyZwicker do you have suggestions about user scenarios that need to be covered in the S3 Gateway doc?

**Comment by JoeyZwicker** [comment]
High level usage docs that go slightly deeper than the API docs

- explain that buckets in the API are repos in pachyderm (even tho all the data is technically in the same bucket)
- Can S3 gateway only read from the HEAD commit of a branch? Or can it read from any commit?
- There are some weird nuances with S3 gateway that we might need to solve on the eng side or at least document. For example, repos can have underscores in their names, but S3 buckets can't. How do users deal with this?

There are likely also cookbooks/examples:

1. TFJob, Spark, or other computation frameworks reading data out of pach s3gateway (and writing results back with provenance tracking --> we may or may not support this last part that well yet)

2. Having outside application that is used to reading data from an S3 bucket getting data from pach instead. That way users can confidently put all their data in pachyderm and not having to worry about major changes to other applications.

**Comment by ysimonson** [comment]
Agreed that the examples would be really helpful. Otherwise, for the first three points:

- An s3gateway bucket is a repo/branch combination. This is documented in the [s3gateway (non-API) docs](http://docs.pachyderm.io/en/latest/enterprise/s3gateway.html), but could be more clearly outlined.
- The HEAD commit limitation is pretty clearly outlined in that same doc.
- I think underscores actually are allowed; at least, I don't see anywhere in the code that doesn't allow them. I'm not aware of any other differences between acceptable names (though wouldn't be surprised if they exist.) More generally, there are a lot of gotchas with s3gateway, though they're almost always on a per-endpoint basis, and are slight discrepancies from s3 itself. Given that, I'm not sure if there's a cleaner way than to put it on the API docs.

**Comment by svekars** [comment]
#3931
