### ISSUE TITLE
Global Setting for Parallelization

### ISSUE THREAD

**Issue by erikreppel** [pachyderm/pachyderm#362]
I'm not sure if this is expected behaviour or not but when I attempt to run a pipeline that is a map (say with `"parallelism": 3`) on a repo that is produced by a reduce, the pipeline fails because the data from the reduced repo is only available to one of the shards.

[Full code](https://github.com/erikreppel/pachyderm-test-pipelines)
[log of code output](https://github.com/erikreppel/pachyderm-test-pipelines/blob/master/logs/reading_from_reduce_issue.log)

The pipelines created are basically:

square (map) ---> sum (reduce) ---> scale (map)

Is there a way to get around this? The implication to me would be that once a reduce is performed any job or pipeline that has that repo as an input cannot be parallelized. I have yet to attempt running a pipeline in parallel off the repo produced by scale, but either way this presents a fair bit of a bottleneck if there isn't a way of circumventing the issue.

**Comment by sjezewski** [comment]
Hi Erik - sorry you ran into this.

From my understanding this is not expected behavior. We want to enable composing pipelines together in many ways, and performing a reduce should not prohibit performing any maps downstream.

We'll look into this.

**Comment by jdoliner** [comment]
Alright I did some investigating and I think I understand what's going on. The problem here is that our behavior for pipelines that take `2` inputs doesn't quite match up with your expectation. Right now what we implement is the following: if a job takes 2 inputs then we'll make sure that every datum in those repos is seen by exactly 1 container. The `sum` repo in your example contains a single file which means that only 1 of the containers sees it and the other 2 don't. If the `sum` repo were the only input then pachyderm would cull the other 2 containers because they're won't see any data and we don't start empty containers. However they're actually not empty, because you have another input `square` and it has enough data for each container so some containers get started with data from `square` but no data from `sum` which leads to the crash.

I think the behavior you were expecting was basically a cross product, you want every line in `square` to be seen by a container with the file in `sum` present so that you can use it. @erikreppel does that describe the behavior you were expecting?

**Comment by erikreppel** [comment]
Yeah exactly.
The purpose of this was to see the case of a single number has been produced as the result of prior calculations and stored in a repo and we want to scale every point of data from a file in a different repo by that number since a really common thing we do.

Any ideas on how to efficiently do this?

As an aside I noticed the other day that if you specify `"shard": 3` on a reduce pipeline in the logs it appeared spin up 3 containers, all of them seeing files, but only one of the containers having files with actual data in them which kind of surprised me. Is that expected? I assumed it wouldn't happen since you don't spin up empty containers.

**Comment by jdoliner** [comment]
@erikreppel thanks, that all makes sense this is a behavior we've talked about a bunch but wanted to understand how users perceived this issue before we started implementing things. Based on this and other conversations we've had I think that the cross product behavior is going to be what the average user expects so I think we'll make that the default.

> Any ideas on how to efficiently do this?

Right now I think your best bet would be to just scale down to a parallelism factor of `1` so that you can get unblocked. We're going to look into getting the cross product implemented for you ASAP and then your old code should just work.

1 more question: does the behavior as it stands now seem useful to you? and if so how would you expect it to be exposed to you?

**Comment by erikreppel** [comment]
Its useful from an efficiency standpoint but those kinds of cross product operations are pretty common. For us at least I think cross product type of operations would be the most common thing we do from a processing standpoint.

The ideal behavior to me would be that I can set a flag for an input to a pipeline to be globally available so it appears in every container spun up by the pipeline.

**Comment by jdoliner** [comment]
Alright, we just had a big discussion of this offline here's what we came to for a direction on this feature. Here's what it's going to look like:

- The default for parallelism is going to switch from union to cross product, meaning that when a pipeline takes 2 inputs we guarantee that the each _pair_ of datums will be seen by exactly 1 container. This means a single datum might be seen more than once.
- Inputs will have a boolean `global` flag on them. This flag indicates that this input repo should be seen by every container run in the job.

**Comment by JonathanFraser** [comment]
@erikreppel and I were discussing this offline a bit. The need for this may be related to the unavailability of more typical map/reduce semantics. In a conventional map-reduce you assign your keys in the map phase and then the reduce operation can be shared per key. In the case of pachyderm, there is only one shard level in reduce (all).  One way to get more typical map-reduce sematics would be to allow for finer sharding in the reduce stage, say per file. That way one can shard their reduce while still having an atomicity guarantee.

**Comment by jdoliner** [comment]
@JonathanFraser what you're saying makes total sense, I think what we have is already pretty close to what you're describing. In our system a `map` shards over blocks, meaning that a single file may be split over several different containers. In `reduce` jobs we shard over files, so each file will be seen by exactly one container but any 2 files could wind up in separate containers and not be seen together. I believe those are the semantics you're describing but correct me if I'm wrong. With this issue we'd be adding a 3rd mode of input `global` which would specify an input that every container in a job sees all the files of no matter what.

**Comment by JonathanFraser** [comment]
@jdoliner ahh, this could just be misunderstanding of what pachyderm is doing under the hood.  If you are saying reduces are parallelized on a per file basis already then ignore my tom foolery. But yes having a flag which allows for a complete view of a repo is useful.

**Comment by sjezewski** [comment]
Updated the title to reflect the action needed. Was formerly 'Map job performed on a repo produced by a reduce cannot be parallelized'

**Comment by derekchiang** [comment]
#393 added a way to have a complete view of a repo in a job.  Refer to the updated [pipeline spec](https://github.com/pachyderm/pachyderm/blob/master/doc/pipeline_spec.md) for details.  Feel free to reach out to us if anything is unclear!
