### ISSUE TITLE
Design: Rerun Pipelines

### ISSUE THREAD

**Issue by adelelopez** [pachyderm/pachyderm#3622]
## The problem 

Say you have a job that failed for some transient reason, and you want to rerun it. Or that you want to experiment with running it on different pieces of data, but don't want to have the job subscribed to new commits -- just something you trigger manually. 

Right now, you can re-run a failed job by making an empty commit. I don't believe there is a way to have a job run on specific commits, or to have a job that doesn't subscribe to new commits.

It would be nice to have a clear, simple way to allow users to perform these operations. 

### Rerun pipeline
Since users don't create jobs directly, instead specifying a pipeline, I think it makes the most sense to present this to the user as a command to manually run a pipeline.

The basic command would be `pachctl run pipeline <pipeline> [commits...]`. This would create a new commit on the `master` branch of the `<pipeline-name>` repo. This commit would be provenant on the `commits` (if any), and otherwise would be empty. The job-spawner is subscribed to this repo, and will run a new job on the new commit. This command could also take the pipeline and commits in as a json file with an `-f` flag.

The commit's branch provenance would be set to use the commit's Branch implemented here: pachyderm/pachyderm#3583 I don't believe it would be necessary or useful to allow the user to specify a different branch here.

**Comment by adelelopez** [comment]
One issue with the no-job commits proposal is that these commits would break the commit invariants. If we didn't consider these commits as part of the invariant, that might work -- but it seems like it ultimately might just be a more complicated way of doing this.

On the other hand, no-job commits which are allowed to break invariants might be useful when implementing pipeline loops and conditionals.

**Comment by JoeyZwicker** [comment]
Thoughts on non-triggering:

IMO the general notion of triggering information being a property of the data (commit) instead of the pipeline seems like a weird and brittle situation. I might have two pipelines subscribed to the same branch, one which I want to trigger and another that I dont. Having the adding of data into a repo being so intricately tied to how I want to process it forces the user to have an unreasonably complete view of the whole system. 

In a reasonable size org, the data team that is ingesting info into repos might be totally separate than the data science team writing pipelines that consume that data. If we want to support Pachyderm as a "data lake" usage better, we need to make it easier for teams to add data to repos without even knowing exactly what processing is going to be done on it. 

Also, how does this work for output repos? The non-triggering need might be for a downstream pipeline. Will the upstream pipeline need to somehow understand how to add this info to output commits?

**Comment by adelelopez** [comment]
Those are some good points, I think that the one-off pipeline approach will probably work better now.

**Comment by jdoliner** [comment]
Agree with @JoeyZwicker's comments, I think with that tweak this design is in a pretty good place to start work on it.

A few more thoughts and clarifications:

> I don't believe there is a way to have a job run on specific commits

You can kind of accomplish this right now by doing a `create-branch` to move the head of a branch, then another one to put it back to the previous head. It's definitely not pretty, but I figured I'd mention that both for anyone who's following this issue but is looking for a workaround right now, and because inspect that code path may help you with this implementation.

Another interesting question to me is whether or not the output commit should go on the master branch. I think for a first pass we should definitely do that, because if we didn't pipelines would need to be extended to watch other branches for commits they need to fill in. However I think we it's worth asking ourselves what we're conveying to users from the fact that output is a continuous chain from a pipeline. And if a one-off job fits into that. A similar question that came up recently was about why when you do `update-pipeline` it breaks the output chain by starting a new branch.

**Comment by ysimonson** [comment]
Related: https://github.com/pachyderm/pachyderm/issues/3287

**Comment by jdoliner** [comment]
I believe everything we're planning to do for this has been implemented and shipped in 1.9. Feel free to reopen if this is still tracking something.
