### ISSUE TITLE
pachctl --raw does not return proper json in the case of a list

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#3625]
**What happened?**:

using pachctl with raw flag does not return proper json in case of a list. For instance when running `pachctl list-file xxx master /yyy --raw` returns:
```
{
  "file": {
    "commit": {
      "repo": {
        "name": "assembly_seqprep_1_2"
      },
      "id": "7ea82bf731fc473e96071ccd9bf991d5"
    },
    "path": "/metapipe/user1/3pXD9RMccN/merged.fastq.gz"
  },
  "fileType": "FILE",
  "sizeBytes": "5450",
  "committed": "2019-04-04T10:45:19.807117206Z",
  "hash": "nh3WS42MdE8LwpUfyRuNsIVHBjE3pLDzlipb712SmYcJ+dxSlmQWxjyIvif0bvNMBlQeYIe9zC+41V8bh/iSOQ=="
}{
  "file": {
    "commit": {
      "repo": {
        "name": "assembly_seqprep_1_2"
      },
      "id": "7ea82bf731fc473e96071ccd9bf991d5"
    },
    "path": "/metapipe/user1/3pXD9RMccN/paired"
  },
  "fileType": "DIR",
  "sizeBytes": "2624",
  "committed": "2019-04-04T10:45:19.807117206Z",
  "hash": "Ibzjqb1EHwpUXJSqDvJAbWd+2vJV/6MxP/is1oW45H0="
}
```
This makes the outputs needlessly difficult to parse.
Please return proper json for all pachctl commands!

**Possible solution**
To preserve backward compatibility, leave --raw as it is now and add a --json flag which outputs proper json.

**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI version (use `pachctl version`):
COMPONENT           VERSION             
pachctl             1.8.6               
pachd               1.8.6

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): minikube

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Others:

**Comment by marcadella** [comment]
In addition, the --raw output sometimes contains "sizeByte" field, some times not. For instance I got this output:
```
{
  "file": {
    "commit": {
      "repo": {
        "name": "assembly_rrnapred_3_1b2"
      },
      "id": "4e54b7f0a7454376baf3d4b8ef3cbe2f"
    },
    "path": "/metapipe/user1/2i5kzYgDqj/forward_paired/filtered.fastq"
  },
  "fileType": "FILE",
  "sizeBytes": "1987",
  "committed": "2019-04-05T06:39:55.298706386Z",
  "hash": "G2tb39xwkARmnhHWe/5KIbigy7wSI0KYZyZ0ZUcf0kIxWtxgSLAKJvv7CqIvi52yIwr3maXjq9+jvNXzLKwp2g=="
}{
  "file": {
    "commit": {
      "repo": {
        "name": "assembly_rrnapred_3_1b2"
      },
      "id": "4e54b7f0a7454376baf3d4b8ef3cbe2f"
    },
    "path": "/metapipe/user1/2i5kzYgDqj/forward_paired/predicted16s.fasta"
  },
  "fileType": "FILE",
  "committed": "2019-04-05T06:39:55.298706386Z",
  "hash": "z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg=="
}
```

Note how the 1st file as sizeByte but the second hasn't. Why??

**Comment by jdoliner** [comment]
Pachyderm outputs concatenated json with one object per record. This is a widely supported format with parsing support in most languages and lots of tools like `jq` designed for manipulating it. Putting all of the objects into a single json array would mean storing all of the objects in memory and only spitting them out at the end, which could require a lot of memory for large numbers of objects, and would prevent downstream tools from working on earlier objects while later objects are being fetched.

In general our json serialization omits values that are the default value, for size that's `0`, admittedly size is a case where seeing an explicit `0` might be nice, but in general this works well as a default because it strips away a lot of extraneous default values, pipeline specs are an example where this is particularly nice.

I'm afraid I don't think it makes sense to rethink either of these decisions right now.
