### ISSUE TITLE
Remove commit information from `pachctl list-file` 

### ISSUE THREAD

**Issue by Nick-Harvey** [pachyderm/pachyderm#3651]
**What is the goal / desired outcome?**
When users run `pachctl list-file <repo> <branch>` the first field in the return output is commit information: 

```
$ pachctl list-file flower_photos master
COMMIT                           NAME        TYPE COMMITTED      SIZE
c3475cb15c8a4f2484f7235776089ad6 /.DS_Store  file 18 minutes ago 8.004KiB
c3475cb15c8a4f2484f7235776089ad6 /daisy      dir  18 minutes ago 32.73MiB
c3475cb15c8a4f2484f7235776089ad6 /orchids    dir  18 minutes ago 52.56MiB
c3475cb15c8a4f2484f7235776089ad6 /sunflowers dir  18 minutes ago 52.4MiB
``` 

Having the commit information displayed here seems unnecessary for two reasons: 1. the commit id is always going to be the same (the parent commit) 2. I'm just trying to get a list of files, if I want commit information I would run `pachctl list-commit`. 

**If there is a way to accomplish this today via workaround, what does that require?**
nope

**(Optional) What is your proposal for a feature to solve this?**
Couple of ideas to tackle this one:  
1. Remove the commit information from list-file by default
2. Rearrange it so that files come first and commit information comes 2nd,3rd,4th, etc. 
3. Remove it by default but make the information available via a flag. TBH not sure this is needed since `--history` does the same kind of thing, but I added it here as an option just in case Im missing something about why the commit information is displayed in the first place. 

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment]
This was added when we added the `--history` flag because when you do that the commit field will tell you about which version of the file it's reporting on. The `--history` flag isn't very useful if we don't report this information. I considered having that column only show up when you pass `--history` but I'm not sure I like the idea of the pretty printer changing based on flags, it seems like it might potentially confuse people.

**Comment by jdoliner** [comment]
I'm going to close this since I think based on above this isn't something we want to change. Feel free to reopen if you disagree.

**Comment by JoeyZwicker** [comment]
@jdoliner given some internal conversation and multiple questions that have come up in the last week or two from users, I think

>  I considered having that column only show up when you pass --history but I'm not sure I like the idea of the pretty printer changing based on flags, it seems like it might potentially confuse people.

is worth reconsidering. It's much more confusing to have that info there on list-file IMO, and experience so far, rather than having it show up based on the history flag. 

In addition, I think renaming the pretty-printed "commit" field to `commit modified`or something along those lines would be ideal, along with the above change. This would reinforce for users what they're actually seeing and prevent the common misinterpretation that files "live" in past commits.

**Comment by jdoliner** [comment]
This is already fixed in master.

In terms of renaming I don't want to go down the path of having different names for fields in the API and the cli. And I think the field is plenty clear as `commit` now that it only shows up with `--history`.
