### ISSUE TITLE
Documentation for cross and union should list glob patterns

### ISSUE THREAD

**Issue by kanzure** [pachyderm/pachyderm#3665]
I would describe the documentation about cross and union as somewhat ambiguous. In particular, the examples seem to be showing (and my interpretation might be wrong) the result of a star glob pattern, and not the result of a non-star glob pattern. I think it would be helpful to show both, or explain what's going on there.

These two sections in particular:

* http://docs.pachyderm.io/en/latest/reference/pipeline_spec.html#union-input
* http://docs.pachyderm.io/en/latest/reference/pipeline_spec.html#cross-input

Which currently show these examples:

    Union inputs take the union of other inputs. For example:

    | inputA | inputB | inputA ∪ inputB |
    | ------ | ------ | --------------- |
    | foo    | fizz   | foo             |
    | bar    | buzz   | fizz            |
    |        |        | bar             |
    |        |        | buzz            |

and:

    Cross inputs take the cross product of other inputs, in other words it creates tuples of the datums in the inputs. For example:

    | inputA | inputB | inputA ⨯ inputB |
    | ------ | ------ | --------------- |
    | foo    | fizz   | (foo, fizz)     |
    | bar    | buzz   | (foo, buzz)     |
    |        |        | (bar, fizz)     |
    |        |        | (bar, buzz)     |

Using a star glob pattern produces a very different result regarding which datums are available to the worker during processing. For example, without the star glob, a union will produce a union of the repositories' files available to each process, instead of separately providing datums from the union's two repositories.

**Comment by JoeyZwicker** [comment]
Thanks @kanzure, you're definitely right that the "assumed" glob there is `/*`, which should absolutely be documented better. We have more in-depth docs on globs here, but can also make some updates to this one.

**Comment by kanzure** [comment]
Yeah I think the source of my confusion is that the diagram doesn't show what I would expect a union to look like. In fact, the behavior of a union seems to be different for unions of datums and unions of ... well, I guess it depends on what you're identifying a datum as (folder/repository or individual file).

**Comment by jdoliner** [comment]
We can definitely make these a lot more clear. To clarify, and to hopefully get an idea of what language we can use to make this more clear, let me describe what's going on here.

The docs on this don't mention glob patterns because they don't affect the semantics of `union` and `cross`, all that really matters is what the datums of the crossed or unioned inputs are, so in the example above, `InputA` could be a single `pfs` input with a `glob` of `/*` on a repo that has 2 files `foo` and `bar` in the root directory. Or it could be a union (union of unions is allowed) of two `pfs` inputs that have no glob, and one of them has a file `foo` in the root directory while the other has `bar` in the root directory. These two inputs are the same as far as the `union` operator is concerned.

The only thing that the `/*` changes is how the filesystem gets split up into datums, if it's not present then that means the filesystem is treated as 1 big datum, i.e. the root directory `/` is the datum.

**Comment by svekars** [comment]
https://github.com/pachyderm/pachyderm/pull/3821
