### ISSUE TITLE
Beginner tutorial fails parsing pipeline def

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#3769]
**What happened?**:

Beginner [tutorial fails](https://docs.pachyderm.io/en/latest/getting_started/beginner_tutorial.html#create-a-pipeline) due to parsing pipeline def error: `malformed pipeline spec: invalid character '#' looking for beginning of value`.

**Comment by JoeyZwicker** [comment]
@marcadella I assume you copy/pasted the spec from the tutorial snippet into your own file instead of using the create-pipeline command in the tutorial or using edges.json spec we provide on Github: https://github.com/pachyderm/pachyderm/blob/master/examples/opencv/edges.json?

The actual snippet in the docs has an invalid comment at the top: `#edges.json` which is there for clarity. We can remove that if it's too confusing, but if you use the create-pipeline command in the tutorial, or use the spec on GH, or simply remove the comment which isn't valid json, everything should work fine. Please let us know if you have any other issues.
