### ISSUE TITLE
Document the pfs net protocol

### ISSUE THREAD

**Issue by cemeyer** [pachyderm/pachyderm#38]
One of the more annoying issues in working with HDFS in the early days was that the net protocol was entirely undocumented. Things improved a little bit with Hadoop 2, when the protocol was switched over to Protobuf objects, but protocol semantics are still mostly only documented by code.

It would be great if pfs documented the client<->server network protocol and semantics early on. Thanks!

**Comment by jdoliner** [comment]
This is a really good point, thanks for opening this issue. I'll make sure to get it in to the next release (meaning v0.5, v0.4 is technically the next release but the dev cycle for that has basically ended.) Does anyone know if there are really good tools for documenting http apis written in go? Since our server code has such a common structure there might be some nice way to autogenerate the docs and make sure they stay in sync with the actual code.

**Comment by cemeyer** [comment]
Even a really rough sketch of verbs, endpoints, and that the protocol uses HTTP would be great. It doesn't have to be the best documentation you've ever seen. Thanks!

**Comment by peter-edge** [comment]
Hey @cemeyer, we're redoing the PFS API with protocol buffers v3 and grpc, the current API is here https://github.com/pachyderm/pachyderm/blob/master/src/pfs/pfs.proto, there will be generated HTTP endpoints as well. Would this cover your concerns? Should one of us look into generating documentation based on this if not?

**Comment by cemeyer** [comment]
That looks ok. It's really up to you, though :).

**Comment by peter-edge** [comment]
I think we will just close this issue for now (I'm all about the
unachievable 0 issues 0 PRs active) and when things are more settled, we
may decide to document this further with some documentation generation
tool. Thanks for the input :)
