### ISSUE TITLE
Forcing a scheduled CRON pipeline

### ISSUE THREAD

**Issue by svekars** [pachyderm/pachyderm#3843]
I have a pipeline that's currently set to "daily" and I want to force it to trigger ad-hoc.

**What is the goal / desired outcome?**
Enable forcing of a scheduled pipeline
**If there is a way to accomplish this today via workaround, what does that require?**
update them to have a timestamp that triggers right now, you can also call run pipeline on a previous commit, but unfortunately there's not quite a good way to trigger it now
**(Optional) What is your proposal for a feature to solve this?**

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`): 1.9.3
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): N/A
- OS (e.g. from /etc/os-release): N/A
- Others:

**Comment by JoeyZwicker** [comment]
Are users able to manually create a tick file to do an ad-hoc trigger or do we prevent writing to the cron repo? They'd have to be careful to maintain the file format and either overwrite (or not) to match the semantics of the cron input.

**Comment by jdoliner** [comment]
We do not restrict users from writing to the cron repo, so that will work as a way to manually trigger the pipeline, it's not super friendly though, because you have to correctly format the file name or the cron pipeline will break in a fairly confusing way. It'll actually trigger regardless of what you name the file, but it will then try to parse this file to figure out the next time it should trigger, which is where things will break.

I think a user friendly solution to this would be to fold this functionality into `run pipeline`, it could just as easily be its own command (`trigger pipeline` maybe?), but I think whatever we name it would get conflated with `run pipeline`, and they're conceptually very similar even though what's going on behind the scenes is a bit different. I'm thinking something like this would be nice:

```sh
$ pachctl run-pipeline <pipeline-name> --trigger-cron [other commits...]
```

This would error when called on pipelines that don't have `cron` inputs, when called on those that do it'll create a new commit on each of the `cron` inputs (having multiple `cron` inputs is pretty uncommon but technically supported) with the current time as the time stamp. It would also have the existing semantics for the specified commits, specifying a commit from the `cron` input and passing `--trigger-cron` should error, if there are multiple `cron` inputs I think it works so long as one of them isn't specified.

**Comment by LaurentGoderre** [comment]
I am facing the same issue. Since crons have name couldn't it just be:

```
$ pachctl run-cron <cron-name>
```
