### ISSUE TITLE
Add an option to pipline spec for handling datum file name conflicts

### ISSUE THREAD

**Issue by benwbooth** [pachyderm/pachyderm#3898]
**What is the goal / desired outcome?**

Provide an option in the pipeline spec that explicitly describes how to handle when multiple datums write to the same file path in their `/pfs/out`. Currently the default seems to be to concatenate the contents of both files together in random order.

**If there is a way to accomplish this today via workaround, what does that require?**

The only workaround is to completely avoid datums writing to the same path.

**(Optional) What is your proposal for a feature to solve this?**

Add a `fileConfict` key to the pachyderm pipeline spec that allows specifying one of the following options:

`fail` - Fail the datum(s) if conflicting files are found. This should IMO be the default behavior.
`overwrite` - Overwrite the file, so that the last datum to write to the path gets priority.
`overwriteFirst` - Overwrite the file, so that the first datum to write to the path gets priority.
`directory` - Create a directory with the same name as the conflicting file. Then put the output of each datum to that path as a separate file inside the created directory, with the datum hash as the file name.
`concatenate` - The current behavior. Concatenate the conflicting files together in random order.

**Comment by benwbooth** [comment]
I think the current behavior is very surprising. I accidentally had a script that was saving the same path in multiple datums, and ended up concatenating a binary file together with itself, corrupting the file! I think at the very least the default behavior should be changed to simply fail the datum(s).

**Comment by jdoliner** [comment]
The current behavior is a core part of how Pachyderm pipelines work that's designed to be analogous to how MapReduce works, wherein identical keys from mappers get passed to the same reducer. I can definitely see how these semantics would come as a surprise though. However I think gating this behavior behind a flag is going to make it more confusing without adding much value, and we certainly can't change the default, for one thing it would be a huge compatibility issue for our existing users, but it also doesn't make sense for a feature that's required to implement a lot of workloads to error unless you pass the right flag.

In general we try to avoid adding things to the pipeline spec that  implement things that can be implemented in user space, because it litters pipeline specs with a lot of arcane flags and we feel makes understanding pipelines more confusing. We're particularly resistant to doing it in cases where the behavior can be implemented in user space, which all of these behaviors can with the exceptions of `fail`.  I can see how having that `flag` could help in debugging, but since it can't be the default it's unlikely to save anyone from initial confusion and once you understand the concatenating behavior (which you'll have to if you're passing `fail`) I don't think it adds much.

**Comment by gabrielgrant** [comment]
@jdoliner at one point i believe we had talked about adding a "pass-through/map-only" mode, that could simplify processing by skipping the merge step. not sure how much that still makes sense in the context of the new storage layer stuff, but broadly the idea of saying "datums can be fully processed independently, and no shuffling behavior is expected" does seem like a pretty common use-case, and useful both semantically as well as as a performance optimization.
