### ISSUE TITLE
Add parallel job processing to workers and refactor worker code

### ISSUE THREAD

**Issue by Tryneus** [pachyderm/pachyderm#3963]
**What is the goal / desired outcome?**

Too much of the worker/master code operates in the same scope with way more variables than necessary, making it hard to reason about the code.  There is a fair amount of repeated code that should probably be combined, and in particular, error handling in the master feels very precarious.

In general, there are three main goals of this project:
* Run multiple jobs in parallel in the workers
* Better organize the code in the worker package
* Reduce code duplication in the worker package

**If there is a way to accomplish this today via workaround, what does that require?**

No

**(Optional) What is your proposal for a feature to solve this?**

These proposals focus mainly on the `master` code.  The `worker` code feels like more of a mess, but at the same time, it should not need many changes to support the main targeted feature: parallel jobs.

* Split out master and worker implementations off of the `worker.APIServer` struct.
* Split out each of the spawners into their own struct and file with a well-defined interface to the rest of the worker code.
* Consolidate job and output commit updates in `jobSpawner` and `waitJob` so this is only performed in one or two places, and is always done transactionally through an STM.
* Ability for `jobSpawner` to run multiple jobs in parallel
* Rename `chunk` to `datumSet` everywhere to avoid the terminology conflict with the new storage layer.
* Unify stats code path with data code path.

**Wishlist**

* Shard on hashspace rather than a constant in the pipeline spec so we can scale merges dynamically.  I'm not sure how much of an issue this is, but it seems like it's awkward expect users to specify this.
* Change `DatumFactory`/`DatumIterator` so that we don't need to load the entire filetree into memory. This will need some new ideas on how to guarantee the workers and master agree on the datum sets, as this currently uses `pfs.GlobFileStream` internally.
* Move as much worker-related data as possible into postgres.  This is a bit complicated because so many places rely on the guarantees we get from etcd, and it is harder to watch data in postgres.  We would need to build a new package to make this as simple as our `collections` package, which is heavily used in the worker.

## Separate master/worker structs

Both the master and worker are defined as a collection of functions on the `worker.APIServer` struct, which makes it hard to see where one ends and the other begins.  Leave the common functionality on the `worker.APIServer` struct and add new `worker.worker` (Name TBD) and `worker.master` structs to encapsulate their specific behaviors.

## Separate spawner structs

The spawners `jobSpawner`, `spoutSpawner`, and `serviceSpawner` all have similar roles but are never active concurrently.  For readability and organization, having these as separate structs in their own files should improve the code.  These should be constructed with as much configuration as possible explicitly, rather than pulling from the APIServer (such as setting the logger, and client), to make it a bit easier to reason about, free from side-effects.

A good chunk of the code in `master.go` is used exclusively by `jobSpawner`, but `waitJob` is also monolithically large and should be broken up into smaller pieces.  This will also be done as a part of refactoring `jobSpawner` for running multiple jobs in parallel.

I spent some time trying to design the interfaces for this here, but I think it would be best to figure these out during implementation, as it's easy to miss details in a design document.

It may be useful to break out a lot of common code into a `utils` subpackage.  For example, the code to provision a node (unlinkData, downloadData, MkdirAll, linkData) is repeated in every spawner, and we should be able to abstract this into a single call.

## Consolidate job and commit updates

When a job fails, the output commit is made empty and the job status is set to 'failed'.  There are various places that do this in different orders for various reasons, and it has caused some confusion.  Since both job and commit metadata are stored in etcd, we can do this transactionally in an STM and drop this extra complexity.

The functionality to do this already exists since `ppsutil.UpdateJobState` already runs within an `stm.STM` transaction, and we have `pfs.APIServer.FinishCommitInTransaction which works similarly.  We can wrap these up into a helper function that will provide this in a clean manner.

This helper function will likely need to be an RPC in the pachd PPS server, as the workers do not run a `pfs.APIServer` that we can use to call `FinishCommitInTransaction`, and it seems a little overkill to add that to the worker.  If there are other uses for accessing PFS transactionally inside a worker, we can revisit this.

This change may also affect `StopJob`, which interacts with the worker by finishing a job's output commit early.

## Multiple jobs in parallel

If we model jobs instead of blocking on commits to blocking on _datums_, we can run jobs in parallel.  Internally, the job-supervisor logic in `jobSpawner` will need to be broken up into its own struct.  In this way we can instantiate multiple supervisors in parallel.  The spawner should use a semaphore to ensure that the number of available tasks is matched to the number of workers, or that there are no new jobs that can be started.  Jobs will have dependencies on each other in order to perform merges and finish commits, so the spawner will need to determine and manage these dependencies by analyzing the inputs from the `DatumFactory`.

We _may_ need to break Jobs up into explicit tasks in order to make this simpler to reason about.  I'm not excited about changing the interface between master and worker, or changing the data stored in etcd, but this should just be ephemeral data, so no migration would be necessary.

The worker itself should require minimal changes to support this.  I don't see any particular places that need to change, but I'm also not fully familiar with the code and I expect something to come up during implementation.  In general, though, its job remains nearly identical - the only new requirement is that it will execute tasks from a new job even if a previous job exists but all tasks there are claimed.  We will need to make sure that workers do not block waiting on inputs when they could be working on other jobs.  This is probably easiest to implement in the master by not creating a task until its inputs are ready.

## Unify stats

Currently stats are done in a separate code path from data, which means several times we have encountered bugs where stats commits were not being output. Consolidate the code to write out stats (in success and failure cases) and make it foolproof.

**Comment by jdoliner** [comment]
I think this proposal basically makes sense, I just have a few small tweaks on prioritization of the various goals. I think the main goal needs to be paying down the technical debt in this code, I'm worried that if you pursue the goal of running multiple jobs in parallel as the main goal we'll wind up taking on more debt. We already have a system that at times fails to run 1 job in parallel, and I have trouble believing we'll be able to get to a system that can run multiple jobs in parallel before we get to a system that doesn't get choked up on a single job, which I think is going to require a fairly big refactor of this code. I'm hoping after the refactor it should be pretty straightforward to make the jobs run in parallel. Also, I think one thing that would be really good would be some fuzz/chaos tests that can get the code as it exists today into stuck states.  That's proven to be one of our best tools for ironing out kinks like these.

> Change DatumFactory/DatumIterator so that we don't need to load the entire filetree into memory. This will need some new ideas on how to guarantee the workers and master agree on the datum sets, as this currently uses pfs.GlobFileStream internally.

This is something that we do have an idea of how to do, we were thinking of representing the Datums as a fileset themselves (much like we do when stats is turned on) and then using that file set to efficiently page / iterate / chunk the datums. Not sure if it's going to fit into this project, but if it does definitely chat with @adelelopez about it, since she might start implementing this around the same time.

**Comment by brycemcanally** [comment]
> In general, there are three main goals of this project:
> - Run multiple jobs in parallel in the workers
> - Better organize the code in the worker package
> - Reduce code duplication in the worker package

I agree with @jdoliner  that the scope of this project should be limited to 2 & 3.

> Shard on hashspace rather than a constant in the pipeline spec so we can scale merges dynamically. I'm not sure how much of an issue this is, but it seems like it's awkward expect users to specify this.

I don't think we want this because it magnifies the small insert problem because it, in general, will spread new files evenly across the shards and also this means we have to read from many places for sequential accesses (the most common access pattern for our system). I discuss how the merge could be dynamically distributed based on file path ranges in https://github.com/pachyderm/pachyderm/issues/3522. Some of the details have changed, but the basic idea still stands and the cheap copy in particular makes this a lot easier to manage and performant. How this would be exposed to users is up for grabs, but it would be dynamically configurable (file sizes, number of files, etc.).

> Change DatumFactory/DatumIterator so that we don't need to load the entire filetree into memory. This will need some new ideas on how to guarantee the workers and master agree on the datum sets, as this currently uses pfs.GlobFileStream internally.

https://github.com/pachyderm/pachyderm/issues/3703 addresses this pretty extensively. 

> This helper function will likely need to be an RPC in the pachd PPS server, as the workers do not run a pfs.APIServer that we can use to call FinishCommitInTransaction, and it seems a little overkill to add that to the worker. If there are other uses for accessing PFS transactionally inside a worker, we can revisit this.

I'm not sure I understand what you mean here? We have the pachd sidecar in each worker pod that exposes a pfs api. I assume if you were to make this a pps rpc then it would just be talking to the sidecar pps api server which would make a call to the sidecar pfs api server? 

> If we model jobs instead of blocking on commits to blocking on datums, we can run jobs in parallel. Internally, the job-supervisor logic in jobSpawner will need to be broken up into its own struct. In this way we can instantiate multiple supervisors in parallel. The spawner should use a semaphore to ensure that the number of available tasks is matched to the number of workers, or that there are no new jobs that can be started. Jobs will have dependencies on each other in order to perform merges and finish commits, so the spawner will need to determine and manage these dependencies by analyzing the inputs from the DatumFactory.

I think there are a lot of scalability/performance questions if we go with this model. I'm not going to spend too much time thinking about it in the short term because I think it adds a ton of complexity that we really don't have the resources to support before we successfully deliver the new storage layer. I think scoping this project down to just refactoring the worker master and overall code quality improvements is a large enough project with very high leverage that does not introduce a lot of new variables that we have to take into account.

> Currently stats are done in a separate code path from data, which means several times we have encountered bugs where stats commits were not being output. Consolidate the code to write out stats (in success and failure cases) and make it foolproof.

The datum file sets in https://github.com/pachyderm/pachyderm/issues/3703 are essentially what @jdoliner and I think the next iteration of stats could be. Also, I think it is going to be tricky to try and clean up stats without messing with the worker code, but you might be able to consolidate some of the finalization (merge, finish commit).


I more or less agree with the stuff I did not comment on, although I am getting a sense that this may be leaning a little too much into object-oriented-like territory, specifically the spawners, but I will wait and see what you come up with before commenting on that more.

**Comment by jdoliner** [comment]
Changing assignee to @Tryneus since he's actively working on this right now.

**Comment by pappasilenus** [comment]
There's a use case for providing the option to turn off the processing of multiple jobs in parallel for a pipeline where the processing flow depends on state outside of Pachyderm.

And example: A pipeline clusters data and  queries an external database for a cluster identifier to see if the data has been marked as "done".  If not, it records that cluster ID in the external database as a "candidate".  The data associated with the cluster is put into the output repo, and downstream pipelines collect additional context for data around the cluster.  A "grading" pipeline further downstream queries that database for the clusterid to determine if the "candidate" cluster is worth working on. If it is, it records the cluster as "done".  If the cluster is "done", other, additional processing may be done to add more value to it.

It is conceivable that two sequential jobs in the "grading" pipeline could determine that a "candidate" cluster is "done".  If they're allowed to be processed in parallel, the external state could result in a race condition where a "candidate" cluster is marked as "done" incorrectly by 2 sequential jobs.

Thus, it would be good to have a way to turn off parallel job processing for a particular pipeline where state external to Pachyderm is used to move the data from one state to another.

**Comment by JoeyZwicker** [comment]
@pappasilenus I think your explanation is close, but might as well add some more color from end. 

The pipelines:
PipelineA: clusters groups of genomes, assigned them a unique ID and writes that ID to external database along with the list of cluster members. If a cluster is "similar enough" (their business logic) to a previously "done" cluster, it will mark the new clusterID as "done" as well.

PipelineB: Reads clustersID's from the DB. If they are _not_ "done", then process them and once processing is complete, mark as "done" in the DB. 

The main issue here is that this is not strictly a DAG. It has a cycle in that pipeline B reads from the DB and writes to the DB. This currently works totally fine because jobs are sequential so job2 of pipelineB doesn't run until job1 of pipelineB has completed.

**Comment by Tryneus** [comment]
Fixed in #4572
