### ISSUE TITLE
[REQ] garbage collection progress

### ISSUE THREAD

**Issue by danielefranceschi** [pachyderm/pachyderm#3966]
**What is the goal / desired outcome?**
To check the status of the garbage collection process.

**What is your proposal for a feature to solve this?**
Make the GC process asynchronous (and its status pollable) or add a "tail" flag to `pachctl garbage-collect`.

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.15.1
- Pachyderm CLI version (use `pachctl version`): 1.9.2

**Comment by JoeyZwicker** [comment]
We're working on a bunch of improvements to GC that'll address these concerns. Namely, GC will run automatically in the background instead of requiring the cluster to the paused. 

I also like the idea of making GC a bit more transparent about what it's doing, regardless

**Comment by jdoliner** [comment]
This is a fine idea for our current implementation of GC, but it won't make sense in our new implementation. It makes more sense for us to focus resources on getting the new implementation out, which will run in the background rather than being user triggered, in which case progress doesn't really make sense. There will probably be stats of some sort for visibility, but we'll probably design / implement that after the new gc is shipped.

**Comment by marcadella** [comment]
Is there any plan for this new background gc? Don't see anything about that in 1.10 milestone.

**Comment by JoeyZwicker** [comment]
the new GC implementation is part of a much broader storage layer overhaul that is part of 1.11/2.0 and also include massive storage layer improvement. I can point you at the PR, but it's not going to be released as part of 1.10 unfortunately. 

Joey Zwicker
Founder, Pachyderm
