### ISSUE TITLE
pfs not being refreshed after new commits

### ISSUE THREAD

**Issue by jkhelil** [pachyderm/pachyderm#4011]
it is related to https://github.com/pachyderm/pachyderm/issues/3781 ‑ 
I am opening the issue to see if there is a workaround about it

**What happened?**:
pfs not being refreshed after new commits
**What you expected to happen?**:

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by JoeyZwicker** [comment]
@jkhelil when using `pachctl mount` it purposely does not refresh for reasons described in #3781 as we have not found any way to make it reliable. You can of course unmount and remount to get updated data. 

Can you tell us more about your use case and how you're using the mount? There are some instances where using a Pachyderm Service can work well too (e.g. Jupyter notebook) and Services do automatically restart/refresh after each new commit. 

I'm going to close this issue for now because there are no immediate plan to change `mount` in this way, but is something we could take another look at in the future.
