### ISSUE TITLE
pach list job has weird output since 1.9.1

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4036]
**What happened?**:

Before 1.9.1, `pachctl list job` would simply print the list of jobs.
Since 1.9.1 (included), I guess it kind of emulate linux `watch` but with a blue line in the middle of the terminal and it does not even update properly new data.
Please revert to the normal print. If one needs to, one can just use `watch pachctl list job`.

**Environment?**:
- Kubernetes version (use `kubectl version`):
1.5.2
- Pachyderm CLI and pachd server version (use `pachctl version`):
1.9.1
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
minikube
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by OliverEvans96** [comment]
I agree, this is annoying. It seems like the output is just being piped to `less` on my system, which does not happen for other similar `pachctl` commands.

**Comment by jdoliner** [comment]
Sorry this is annoying you guys. List job was changed in 1.9.1 to use a pager because the output is often longer than a single screen, similar to the behavior of `git log`. It's not attempting to be a watch. I'm not sure why you're getting a blue line in the middle of the terminal, could we see a screenshot of it? If you'd like to disable the behavior you can pass `--no-pager` to the command, I'm hesitant to remove this as the default since I think it's generally more useful than annoying when there are more than a handful of jobs.

**Comment by OliverEvans96** [comment]
Ah, cool - that makes sense. The `--no-pager` option is fine for me.

Thanks!
Oliver

**Comment by marcadella** [comment]
To not surprise users I would rather add "--pager" tag and leave the default outpour as it was before?

**Comment by JoeyZwicker** [comment]
I don't think it's something we plan to change back right now. 

You can also use `export PAGER=cat` in your terminal to switch it back to the previous view so you don't need to type the flag every time if that makes things easier. 

I'm closing the issue for now, but if you're getting a blue line or some other weird rendering, please post a screenshot so we can try to debug that further.
