### ISSUE TITLE
Pipelines that generate a commit for each datum

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#4057]
**Example scenario:**
I have a scenario where the first repo is a list of jsons for pachyderm to query a db to download a bunch of data. Each json in the first repo produces a bunch of jsons for a "/*" download pipeline.

Each download can take quite a while. Some might stall. In the current implementation in Pachyderm, the overall pipeline throughput is limited until all the downloads complete.

**What is the goal / desired outcome?**
The above scenario executes with optimal throughput and is responsive to the user while maintaining the declarative nature of the pipeline.

**If there is a way to accomplish this today via workaround, what does that require?**
- In the above scenario: Have 2 pachyderm clusters. The first executes the first pipeline and pushes the output to the second cluster. This would create a commit for each download but would be highly inefficient infrastructure wise.
- Batch the pipeline into many small jobs so only a few downloads trigger at a time by having a human constantly tinker with the query. This delegates the bottleneck to a human which is never a good thing.
- Implement first part of the pipeline outside of pachyderm and pushes the results into pachyderm. This loses the benefits of the pipeline being simple and declarative, version controlled etc.

**(Optional) What is your proposal for a feature to solve this?**
- Add a non-default flag in the pipeline spec which allows a pipeline to generate a commit for each datum.
- This would not be optimal for use cases with many small files as it would generate many commits but to my understanding it is ideal for the above.

**Comment by pappasilenus** [comment]
I believe the problem you are trying to solve is addressed by this issue, which is currently in design: https://github.com/pachyderm/pachyderm/issues/3963

Datums themselves can be merged into final output files, which adds much complexity to this implementation.  I'm not sure what this design would buy us that 3963 doesn't address, at a cost of added complexity to both the feature set and internal workings of Pachyderm.

**Comment by jdoliner** [comment]
This is at odds with the Pachyderm processing model in a number of ways so isn't something we'll be implementing. Commits are designed as the atomic unit of work and a lot of things will fall apart if that stops being the case. This also introduces the massive footgun that if you have a pipeline that creates a commit per datum and it has a lot of datums you can easily ddos the entire cluster. There are a couple of simple things you can do to increase the throughput of this workload:

- make smaller commits, a steady stream of smaller commits rather than a single large commit will allow both pipelines to be running all the time.
- merge the pipelines, since the datums from the second pipeline are all contained within a single datum in the first pipeline you can just run the code for the second pipeline after the first pipeline (all in the same container / pipeline). This makes it trickier to get the parallelism you want for the second chunk of code, but if you can split up the datums in the first pipeline more, then this should work well.

**Comment by jdoliner** [comment]
@pappasilenus is also correct that #3963 will help with this a lot, especially if you make your input commits smaller.
