### ISSUE TITLE
Allow ErrCmd to add files to /pfs/out

### ISSUE THREAD

**Issue by adelelopez** [pachyderm/pachyderm#4062]
https://github.com/pachyderm/pachyderm/blob/master/src/server/worker/api_server.go#L2059

**Comment by JoeyZwicker** [comment]
Also note, things written to pfs/out in err_cmd should also be egressed.

**Comment by jdoliner** [comment]
Filling in a few details here from chatting about this offline. The use case here is that a user has a pipeline in which datums can fail in such a way that he doesn't want the datum to fail the pipeline, but does want it to be retried in future jobs, this is exactly the use case that `err_cmd` solves. However, the user also wants to create an when the `err_cmd` is run on these datums, his alerting stack is setup to watch in an s3 bucket for files showing up there, so he's hoping to have pachyderm egress the content in `pfs/out` from the `err_cmd` to trigger his alerting.

I don't think this is something we want to do, at least in the short-term. Having `err_cmd` able to write output begs the question of what happens with that output when the datum is run again and succeeds, writing real output. Or if it fails again, and `err_cmd` runs again and outputs more. I also don't think this is a super valuable use case to address, because it only applies when your alerting/monitoring system is based on s3, which isn't really the norm.

The recommended way to solve this is to trigger your alerting directly from within the `err_cmd` in this case that would mean writing files directly to s3. But could also include whatever other alerting / monitoring systems are in place.
