### ISSUE TITLE
Being abble to download files located on PFS directly from the object store using a stitcher

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4063]
As far as I understood, one pfs file is represented by a series of files stored in the object store. I guess pachyderm does a diff of all those files when one uses `pachctl get file xxx`. This means that I cannot access an output file directly from the object store.
Of course I could simply:
  - egress this output file but this means doubling the disk usage
  - download the output file on my server using `pachctl get file xxx` then transferring it back to the the client app that requested it, but this means a high amount of load on my server in addition to needless data transfer
  - implement direct access to pachd using a javascript client for instance, but I do not want to expose pachyderm to the outside world for my application.

Instead, what if `pachd inspect file xxx` returned the list of those files along with the necessary metadata to stitch them together? It would then be possible to implement a "stitcher" in javascript and make possible the downloading of output files directly from the client, thus saving huge amount of bandwidth, CPU and disc.

**Comment by pappasilenus** [comment]
This is the problem the S3 gateway is designed to solve: providing access to files in Pachyderm through a standard API. I believe we will be allowing use of the S3 gateway, unauthenticated access only, with the open source product. (You’ll need an enterprise license to add auth to S3.) 

Is that a good solution?

**Comment by jdoliner** [comment]
s3 gateway is probably the nicer solution here. However `inspect file` does also expose this information in the `Objects` and `BlockRefs` fields. Those are a fairly internal part of the api, but you can use those to stitch together content in object storage.

Closing this, since I think we've got everything implemented that we would do for this issue. Feel free to ping us in the slack channel if you want some help using those fields.
