### ISSUE TITLE
add state tracking to spouts

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4070]
**What is the goal / desired outcome?**

Provide a mechanism for spouts to keep track of the work they've done that persists between spout restarts.

**If there is a way to accomplish this today via workaround, what does that require?**'

Customers can roll their own, but that can be error prone. 

**(Optional) What is your proposal for a feature to solve this?**

A persistent datastore  or transaction log that allows a spout to keep track of what it's done.

(See https://pachyderm-users.slack.com/archives/C3UN0S0Q0/p1567762926253800)

**Comment by jdoliner** [comment]
The tricky part with this, as with most stuff with spouts is what the API will look like. I think the simplest way to expose the past state to the user code is as a file. The user only needs to see this file when the code starts up for the first time, there's no need to update the file while the spout is running, because it's only needed on restarts. There is, of course, the question of what the file should be named, I'm just going to call it the `marker` file for now (it marks where you are in the stream of data). User code could then output the `marker` file in their tar streams (literally as a file called `marker`). Then this file would be present as `/pfs/marker` when the code starts up, allowing it to pick up where it left off.

We probably also want to consider defacing the file name a little bit to prevent it being accidentally emitted.

**Comment by JoeyZwicker** [comment]
Most users who've asked about this use the term `offset` which I think comes from kakfa instead of `marker`, but I have no actual opinion on what it's named.

**Comment by jdoliner** [comment]
`offset` seems little too specific to me, also seems like an offset is an example of a marker, but not the other way around. I'd imagine the other common use case for this would be a timestamp that records when the last chunk of data was from, so you can, for example, start reading records in the data base that are newer than this timestamp. `marker` still seems like a fairly reasonable name in that case, but offset doesn't.

I'm wondering if maybe we want to go another direction, and simply expose it as a `meta` directory for metadata about the stream that you can get back, and then you could have `meta/offset`, `meta/timestamp`, whatever you wanted.

**Comment by jdoliner** [comment]
This has been implemented as spout markers.
