### ISSUE TITLE
Allow pachyderm to use a database such as Dynamo for metadata storage

### ISSUE THREAD

**Issue by andy-han** [pachyderm/pachyderm#4090]
**What is the goal / desired outcome?**

To use a database to store pachyderm metadata

**If there is a way to accomplish this today via workaround, what does that require?**

No workaround. I'm using the helm chart and all Amazon EBS implementations are locked to a single availability zone

**(Optional) What is your proposal for a feature to solve this?**

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment]
Pachyderm uses etcd to store metadata which works well for us as a database because it's designed for metadata, and fits in with the container / kubernetes ecosystem. We have long term plans to move off it onto Postgres, although there's a good chance that etcd will still be required, because it provides some consenus semantics that Postgres doesn't. It's unlikely that we'll ever consider using Dynamo because, afaik it doesn't support a standard query language, it's SQL based but it looks like it only supports a small subset of the language and is "schema free," so we'd have to write support specifically for dynamo, and it doesn't make sense for us to do that for a solution that's tied to a single cloud provider.
