### ISSUE TITLE
Include Commit messages in List Commit

### ISSUE THREAD

**Issue by samlmichel** [pachyderm/pachyderm#4108]
**What is the goal / desired outcome?**
It would be great to be able to see commit messages at a glance when listing all commits from a repo, rather than needing to inspect each individual commit.

**If there is a way to accomplish this today via workaround, what does that require?**
Yes, one could write a simple bash/python script to list all commits in a repo then inspect them all and print out the relationship of commits:messages, obviously that is somewhat tedious/obtuse for a solution.

**(Optional) What is your proposal for a feature to solve this?**
I propose to add an additional flag to the "list commit" command that will allow the user to tell the method to include messages in the returned list, so multiple commit messages can be more easily browsed.

**Comment by jdoliner** [comment]
For a much nicer workaround try passing the `--raw` flag, that will give you commits as a json blobs that will include the commit message, coupled with `jq` this will allow you to extract all the information you need from them.

Adding this to standard `list commit` would be quite easy, I'm not sure if it makes for a great default, since I think most commits don't have commit messages so we won't want to eat up terminal space with a mostly empty field, but a flag that turns it on would totally make sense.
