### ISSUE TITLE
pull docker image for pachyderm deploy

### ISSUE THREAD

**Issue by hh1985** [pachyderm/pachyderm#4125]
It is very slow to deploy pachyderm with kops on AWS in China.
```
Normal   Created    32m                kubelet, ip-10-0-78-253.cn-northwest-1.compute.internal  Created container
  Normal   Started    32m                kubelet, ip-10-0-78-253.cn-northwest-1.compute.internal  Started container
  Warning  Failed     48s                kubelet, ip-10-0-78-253.cn-northwest-1.compute.internal  Failed to pull image "pachyderm/grpc-proxy:0.4.6": rpc error: code = Unknown desc = context canceled
  Warning  Failed     48s                kubelet, ip-10-0-78-253.cn-northwest-1.compute.internal  Error: ErrImagePull
  Normal   BackOff    48s                kubelet, ip-10-0-78-253.cn-northwest-1.compute.internal  Back-off pulling image "pachyderm/grpc-proxy:0.4.6"
  Warning  Failed     48s                kubelet, ip-10-0-78-253.cn-northwest-1.compute.internal  Error: ImagePullBackOff
  Normal   Pulling    33s (x2 over 32m)  kubelet, ip-10-0-78-253.cn-northwest-1.compute.internal  pulling image "pachyderm/grpc-proxy:0.4.6"
```
Just wonder if there is way to specify alternative docker image url to speed up the procedure.

In minikube, I can start with --vm-driver=none, and pull the docker images needed and then rename them. Not sure if there is similar way in kops or pachyderm.

Thanks a lot!

**Comment by JoeyZwicker** [comment]
@hh1985 if you check out `pachctl deploy --help` there are --registry and --image-pull-secrets flags to pull from a private registry instead of dockerhub. You'll still need to get the images into your private registry first but either pulling them somehow or building from source, but that can be done separately to simplify and speed up the deployment steps. 

Let us know if you have any issues/questions. You can also join our [public slack channel](slack.pachyderm.io) and ask there.
