### ISSUE TITLE
[DOC] Describe Pachctl system cert

### ISSUE THREAD

**Issue by svekars** [pachyderm/pachyderm#4143]
Create documentation based on https://github.com/pachyderm/pachyderm/pull/4093

**Comment by svekars** [comment]
@kevindelgado @msteffen Can you please provide a summary of what needs to be documented?

**Comment by kevindelgado** [comment]
This change modifies how pachyderm API clients are created such that if the pachd address supplied has the prefix `grpcs`, the client creation function knows that SSL is being used, and thus it adds system root certificates to the dial options of the grpc connection, so that they can be used to encrypt data sent via the api client to the pachd server.
