### ISSUE TITLE
Changing HEAD to the same branch breaks pachyderm

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4178]
**What happened?**:

When changing the HEAD of a branch to another commit on the same branch, the pipeline will not process any new data committed to its inputs. If that is not a valid operation, please throw an error when attempting to do so.

**What you expected to happen?**:

I'm not sure, I was just trying out.

**How to reproduce it (as minimally and precisely as possible)?**:

`pachctl create pipeline p  -f ...`, then run `pachctl create branch p@master master^1`. After that any new commit on `p`'s input repo do not trigger new job on `p`.

Running `pachctl create branch p@master master^-1` did not fix the issue.

**Environment?**:
- Pachyderm CLI and pachd server version (use `pachctl version`):
1.9.6
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
minikube

**Comment by marcadella** [comment]
Even running `pachctl create branch p@master` yield the same issue.

**Comment by pappasilenus** [comment]
Hi, @marcadella, I'm a little confused because it looks here like you deliberately broke provenance on a pipeline by resetting its master branch.  That is, what you did was create a floating "master" branch on a _pipeline_, not on its _input repo_, as your text seems to say you intended.  That is, I *believe* you wanted to move the HEAD commit on the *input* repo, not on the *pipeline*.

Here's what you did to get into that state, using our opencv example as the pipeline:
```
$ pachctl create repo images
$ pachctl create pipeline -f opencv/edges.json
$ pachctl create pipeline -f opencv/montage.json
$ pachctl put file images@master -i opencv/images.txt
$ pachctl put file images@master -i opencv/images2.txt
$ pachctl create branch edges@master
# uh-oh, we're broken
$ pachctl put file images@master -i opencv/images3.txt 
# this results in no output in edges or montage.
```
To recover from the state you got in here, you could do something like the following. 
```
$  pachctl list commit edges
REPO  BRANCH COMMIT                           PARENT                           STARTED            DURATION   SIZE     
edges master e3b646032cab4997b27f5771768f963d b7b7d0608c0046da9fcd71a245662c89 About a minute ago 10 seconds 133.6KiB 
edges master b7b7d0608c0046da9fcd71a245662c89 <none>                           About a minute ago 8 seconds  22.22KiB 
$ pachctl create branch edges@master --head e3b646032cab4997b27f5771768f963d
$ pachctl update pipeline -f opencv/edges.json 
```
Admittedly, allowing branch operations on a pipeline's output repo is a very sharp tool, but we do have some design issues around how those may be used in the future.

If you run into trouble like this in the future we're happy to help you out in slack.pachyderm.com!

**Comment by marcadella** [comment]
Thanks fr the answer. But it might be  good idea to throw an exception instead of letting the user do something that yields nothing good.
