### ISSUE TITLE
pachctl run pipeline commits to <none> branch

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4179]
**What happened?**:

After running `pachctl run pipeline ...` I can see that there is a new commit on my pipeline repo, but contrarily to what the [doc](https://docs.pachyderm.io/en/latest/how-tos/run_pipeline.html#run-a-pipeline-on-a-specific-commit) says, it is on the `none` branch instead of `master` (which is the output branch of my repo).

**What you expected to happen?**:

The commit should have happened on the output banch of the pipeline.

**How to reproduce it (as minimally and precisely as possible)?**:
```
pachctl create repo inputs
pachctl create pipeline p -f xxx.json #A pipeline using inputs as input
pachctl run pipeline p inputs@master
```
then after running `pachctl list commit p` you should see something like:
```
p    <none> 17f45c2052d9441295eee4893fa8d90c <none>                           5 minutes ago 22 seconds         18B
p    master 1843ae95d27b4ccaa99aa370809ab83b <none>                           7 minutes ago 8 seconds          16B
```

**Environment?**:
- Pachyderm CLI and pachd server version (use `pachctl version`):
1.9.6
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
minikube

**Comment by pappasilenus** [comment]
I've reproduced this bug.

Should be linked to #3985

**Comment by jdoliner** [comment]
This is actually the intended behavior, we should update the docs. The head of the output branch is supposed to represent the result of processing the heads of all of the input branches, not the result of the most chronologically recent job. In your case you happen to be calling `run pipeline` on the heads of the input branches, in which case it would be a lot more reasonable for the output commit to be put on the output branch. But in general it's not a good policy because it can be confusing, particularly because when you do update the heads of the input commits, and have a normally triggered job run, it won't take into account the results from the `run pipeline` commit, and it can appear as if results are disappearing. We may want to think about special casing `run pipeline` calls that take the heads of branches as inputs, since I don't think there's any risks with that behavior and I think it would match up better with users expectations.

**Comment by marcadella** [comment]
I use `run pipeline` in a context where pipelines tend to fail often.
Ideally the commit would happen on the same branch (let's say master) and
the trigger the next pipeline. No data is lost since the next pipeline did
not run in the first place (since the previous pipeline failed). Even if
the next pipeline had run and created an output commit O1, I don't see why
data would be lost because the new output commit O2 would just be a child
of O1.
But anyway, the issue with `<none>` is that I cannot move master to it
(using `pachctl create branch xxx@master --head ???`). So basically
re-running the failed pipeline was useless since it produces a commit I
cannot re-inject in master to trigger the rest of the workflow.

ons. 9. okt. 2019 kl. 02:37 skrev Joe Doliner <notifications@github.com>:

**Comment by jdoliner** [comment]
Data would be "lost" in the case where the commit you trigger on isn't the head of the input branch, which isn't what you're doing here. `run pipeline` was designed with the use case where you want to do ad-hoc runs of the pipeline on past datasets, it wasn't really intended as a retry mechanism like this. The general expectation is that the most likely response to a failed pipeline is an update to the pipeline with new code that fixes the issue. In this case I'm guessing the issue is something transient so you don't want to make any changes to the code. I think `update pipeline` has all the semantics you want though, it will cause the pipeline to run again on the heads of the input branches, and the result will be outputted to the output branch. I realize it's a little awkward, but I think just doing a no-op update to your pipeline rather than a `run-pipeline` is likely what you want.

> the issue with `<none>` is that I cannot move master to it (using `pachctl create branch xxx@master --head ???`)

the `--head` flag for `create branch` takes a commit, not a branch, so you can pass the commit id directly in there. This is only going to work if the branch isn't the output branch of a pipeline though, the head of an output branch is kept in sync with the heads of the input branches, so you're going to get an error if you try to move it. However, you can have the downstream pipeline take a different branch as input and then you're free to move it however you'd like.

In addition you can call `run pipeline` on the downstream pipelines to trigger them on the newly created, not on `master` commits. I don't think this is correct for your workflow right now, but just figured I'd mention it.

**Comment by lbliii** [comment]
https://pachyderm.atlassian.net/browse/DOC-138
