### ISSUE TITLE
list-job should output the inputs of the jobs as well

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#418]
Currently `list-job` only includes the output commits of the jobs, but not the input commits.

**Comment by jdoliner** [comment]
It actually used to do this but I removed it because it made the output lines too long and basically unreadable. One idea, what if we made `inspect-job` and other inspect commands return extended information about the objects. Basically `list-*` would return a small enough amount of info that it fits in one line. While `inspect-*` would span multiple lines and tell you everything you might want to know about the object.
