### ISSUE TITLE
Persist logs

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4321]
Currently logs are lost when a pod is deleted. In my use case, this is an issue since I heavily rely on `standby` to re-schedule my pods after each run. Would it be an idea to write the logs to pfs (for instance /pfs/logs.txt) and this special file would be accessible even when a datum failed?

**Comment by jdoliner** [comment]
This is the behavior you'll get if you set `EnableStats: true` in your pipeline spec. Logs for each datum will be persisted to pfs in a branch called `stats` in the output repo. You can access those logs through `pachctl logs` as you normally do.

Closing this because I think we already have the feature that's being asked for. Please feel free to reopen if it doesn't work for your needs.

**Comment by marcadella** [comment]
Awesome thanks!

tir. 12. nov. 2019, 02:52 skrev Joe Doliner <notifications@github.com>:
