### ISSUE TITLE
Smarter standby mode

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4345]
**What is the goal / desired outcome?**

Currently, in standby mode, a pipeline will be up and process all the jobs available before shutting down. Now imagine a workflow constituted of 2 pipelines `A` and `B` and the resource requests are such that either `A` or `B` can run. Using standby mode, kubernetes can run `A` (while `B` is pending) process all the jobs, then shut down `A` and run `B`. This works but assuming that one submits at least as much jobs to the workflow `A` can process, this means that `B` will never run (hence the throughput of the workflow is 0).
Could it be possible that Pachyderm finds out points in the workflow where jobs ready to be processed are accumulating and switch RC accordingly? For instance, taking 5 as a threshold: `A` executes 5 jobs, this means that 5 jobs are ready at `B`'s input. Pachyderm detects this, change RC config to shutdown `A` (which makes k8s able to run `B`) until the number of jobs waiting decreases to less than 5 (which will make `A` pending again until `B` has processed all the jobs). This way ensures a throughput > 0.

This is related to #4344

**Comment by jdoliner** [comment]
Making standby smarter is definitely something we'd like to do. However with scheduling decisions like this we have to be careful because it's easy for optimizations like this to wind up having unintended effects that are very undesirable. Taking your situation specifically, you have two pipelines `A` and `B`, enough resources to run one of them, and enough data to keep both of them busy at all times. So you have half the compute that's needed to do the work you want to do. The current implementation of `standby` makes it so that pipeline `B` never runs, because pipeline `A` got the resources first and is always running, which is clearly undesirable because you never get end to end results. However, if we implemented what you're suggesting and `A` ceded the resources to `B` even though it had work left to do you would get end-to-end results, but each of the pipelines would only have half as much compute time as it needed to process the incoming data, so the pipelines would get progressively more behind. I.e. after 10 days of running the pipelines it would take you 5 days to get end-to-end results, after 100 days it would take 50 days to get end-to-end results. This also doesn't seem like a desirable result, and I think the reality is that there's no scheduling system that's going to get a desirable result in this situation, because there's half as much compute as is needed to run the workload. This is a situation that we intentionally didn't consider when we were designing `standby`, we only considered situations where there're not enough resources to run all pipelines at the same time, but there *are* enough resources to keep up with the overall flow of data. I think there are still several situations like that where we have sub-optimal behavior, and those are the ones we're going to want to focus on addressing. I don't think it makes sense to try to focus on improving situations like the one described here with improvements to `standby` because there really isn't a good solution to them other than adding enough capacity to run the workload.

**Comment by marcadella** [comment]
Ok, I understand your view, but the fact is that my workflow will not have enough resources to run all the pipelines in parallel, and it will receive more inputs than it can process. And yet I still need to get some outputs (even if the queue of inputs keeps increasing day after day). Of course I could use  staging branch and commit inputs whenever the pipeline is ready to process them.
But Overall I think you guys tend to only consider perfect case scenario (enough resources, jobs that do not fail, etc...) forcing users to find workarounds to make pachyderm fit their needs instead of providing out-of-the-box solution to users. That being said, this policy makes Pachyderm design cleaner and easier to use, so it is a perfectly valid standpoint as well.
