### ISSUE TITLE
Running multiple jobs in parallel for the same pipeline

### ISSUE THREAD

**Issue by Tryneus** [pachyderm/pachyderm#4354]
This issue proposes a design to allow pipelines to process datums and merges
from multiple jobs simultaneously when the pipeline has sufficient workers.

Currently, certain workloads result in unused worker resources in a pipeline.
If the user code for a pipeline is relatively long-running, but only
processes one datum per commit, users cannot get any benefit from adding more
workers, they are bottlenecked on a single worker. In order to fully utilize
available resources, we should be able to process datums from other jobs in
the same pipeline on idle workers.

# Overview

Terminology:
* "spawner" refers to the process run by the worker node which has acquired the master lock on a transform pipeline
* "worker" refers to the process run by all worker nodes which runs user code and performs merges

The spawner will maintain (within etcd) a priority queue of tasks to run,
with the oldest output commit having the highest priority. Inside the
spawner, each output commit (until enough outstanding tasks are present) is
supervised by a goroutine which will append tasks to the queue when they can
be performed. A task can either be a datum set or a merge.

As a departure from how jobs are currently divided, workers will no longer
evaluate datums to skip. This work will instead be done by the spawner node
and included in the task structures. The spawner will generate temporary
datum set files in object storage for the set of datums to be evaluated as
part of the job. This will allow the spawner to coordinate datums between
jobs without duplicating work. Once the parent commit of a given output
commit has been finished, the spawner can determine if all datums are
accounted for and create new chunk tasks accordingly (to handle any failed
datums from previous jobs). If all chunk tasks have been run for a commit,
the goroutine will move on to merge tasks.

The worker loop will claim tasks from the highest priority queue available,
perform the work, then update the task and release it. The way work is
performed will not significantly change in this feature, the main difference
is in determining which work to perform.

## Data Structure Changes

The `Plans`, `Chunks`, and `Merges` etcd collections will become obsolete.
These are the current representation of the 'tasks' needed by a given job,
but are used in conjunction to deal with claims and results. Instead we will
have a unified `Tasks` collection that will provide a single place to
organize work to be claimed and performed by workers. This will also make it
easier to extend the system with new types of work in the future. A `Task`
protobuf must provide:

* An ordering that can be used to determine the task's priority relative to other tasks.
  * The collection must be sortable based on this.
  * Tasks from the same job may have the same priority, but tasks from earlier jobs in the output commit hierarchy must be higher priority.
* A `Params` field for each task type (i.e. datums and merge) that contains all the data needed by the worker to start work
* A `State` field for each task type that will be filled in by the worker based on the results of the task
* A `Type` enum that will be used to determine which `Params` and `State` fields to use
* A `Job` field that refers to the job this task represents work for

The `State` fields can reuse the existing `ChunkState` and `MergeState`
protobufs with no anticipated changes. `ChunkState` may be renamed to avoid
the ambiguity between storage-layer chunks.

The `Params` field for a datum set shall include the hash range for which
datums in the datum set the worker shall process.  It will load the datum
set from a PFS Object, referenced in the `EtcdJobInfo`.

The `Params` field for a merge shall include the shard identifier for the
merge.

### Spawner

The spawner code for a transform pipeline is mostly contained within two
rather monolithic functions: `runTransform` and `waitJob`, representing about
500 lines of code. These will likely be completely rewritten, although many
components of these functions will remain the same.

#### Parallelization

The spawner will need parallelization at the top level, through
`forEachCommit`, that will:
* Block if enough tasks are already present in the `Tasks` collection, or enough pending jobs are running
* Spawn a goroutine to oversee the job and related tasks until the job is in a terminal state

#### Datum coordination

To coordinate datums between jobs, the spawner will need to maintain a
registry of datums being processed by each job. This needs to be cognizant of
the relation each job has (essentially a linked list), and provide
notifications to subsequent jobs when its set of datums changes. This
registry should be the only code path for finishing an output commit so that
the logic can be centralized. The interface for this registry may look
something like:

```go
type pendingJob struct {
  // The jobInfo for the job, this is to be considered stale and any decisions
  // based on job state should be done in an STM.
  job *pps.JobInfo

  // The datum iterator for this job
  dit *datum.Iterator

  // Objects in object storage that contain the inputs for each datum to
  // process. If the next-oldest pending job fails, its datumSets will be
  // appended here
  datumSets []*pfs.Object

  // Hashed datums that should be processed in this job
  filter map[string]struct{}
}

// processDatums will create tasks for datums in the datumSets and block until
// all parent jobs and all tasks have completed.
func (je *jobEntry) processDatums() error {...}

// processMerges will create tasks for all merges in the job and block until
// the tasks have been completed.
func (je *jobEntry) processMerges() error {...}

type registry struct {
  // Hashed datums that exist in the most recent successful commit, this is used
  // as the 'skip' filter to skip processing datums that are already present in
  // the version history.
  filter map[string]struct{}

  // An entry per job that is currently being processed (and supervised within a
  // registry.superviseJob call)
  jobs []pendingJob

  // A channel to control the number of outstanding tasks at any given time,
  // this has a very small buffer size and is used to put pressure back on the
  // job goroutines.  Note that merges should never be blocked from reaching
  // etcd, since that will unnecessarily increase the latency of a job.
  taskQueue <-chan Task
}

// Creates the job, and ensures that the job and commit are cleaned up correctly
// on return of the inner callback. This will also handle canceling if the job
// times out, or if the output commit is deleted or otherwise fails.
func (reg *registry) superviseJob(
  outputCommit *pfs.CommitInfo,
  cb func(job *pendingJob) error,
) error
```

The state of the registry must be reconstructible from etcd and object
storage data at any time, it should be thought as like a cache rather than an
authoritative source of truth. In general, the spawner process may be
expected to shut down at any point in time if an error occurs so that another
worker can be elected master.

The design of this is attempting to accomplish a few things (and why):

* Use hash sharding rather than iterator range sharding (which workers currently use)
  * PFS datum iterators are sorted by file size, which may result in heavily unbalanced jobs
* Remove the need for workers to iterate over the entire datum iterator for every job
  * This adds significant overhead to switching jobs
  * Switching jobs will be more common with job parallelization
* Use interfaces and functions that are easily unit-testable
  * The current design is still rather monolithic and testing specific behaviors is difficult
* Reduce repetition in code and constrain the scope of variables
  * The current code has many places that duplicate logic in very slightly different ways, like finishing a job or dealing with stats
  * This impacts the maintainability of the code and makes bugs more likely when changing things

The basic flow of a job in this system will be:

* Call `registry.superviseJob`, which will append the job into its pending jobs list and upload its set of datums to object storage
  * The set of datums is determined by iterating over the job's datum iterator and filtering out the datums from the registry's `filter` map and the `filter` on any parent jobs.
  * Within the `superviseJob` callback:
    * Call `job.processDatums` to split up datum sets into tasks and wait for all tasks to complete
      * `processDatums` will determine the number of datums per task based on the parallelism factor and the total size of a datum set
      * `processDatums` cannot return until all parent jobs have completed so that we can be sure our set of datums is not missing any failed datums from previous jobs
    * Call `job.processMerges` to create merge tasks for the job and wait for them to complete
  * If the output commit is failed, pass down the job's datum sets to its next-youngest child job that is still pending
    * This will require re-intersection with the child job's datum iterator in case any of the inputs were deleted in the new commit chain
  * If the job succeeds, overwrite the registry's `filter` map with the hashes from the Datums field of the output commit

### Worker

Changes to the worker code should mostly be localized at the outer loop.
There are significant changes to how a worker obtains work to do, but very
little should change in how the worker performs that work. This is mainly the
function `worker.APIServer.worker`, which is currently roughly 100 lines of
code.

This must be completely rewritten to deal with the new way of claiming tasks,
and several supporting functions may become obsolete and need to be
rewritten: `getCommitDatums`, `acquireDatums`. The interfaces for
`processDatums` and `mergeDatums` may need to change as well, though the
changes there should be more localized. That said, most of the
responsibilities of `worker.APIServer.worker` remain the same, and
error-handling and cancel behavior should be carried over where possible.

## Compatibility

This design implies some changes to the `EtcdJobInfo` structure, to track the
temporary datum set Objects. This should only be needed while a job has not
reached a terminal state, though, so compatibility problems should be
minimal.

In addition, several collections in etcd are being removed/added, but these
seem to also be used only temporarily, so I don't foresee any problems here.

There is one behavior change that is not entirely intended, but might not be
unwelcome. Currently in Pachyderm, if a set of inputs is deleted upstream
then readded in a later commit, it will be reprocessed for the new output
commit. With the design in this proposal, the spawner may 'shortcut' these
datums because it has kept track of them and knows that an earlier job has
processed it. This can only happen if that job was run in the same instance
of the spawner, the information is not rebuilt for jobs that were terminal
before the spawner started.<br><br><i>(related to <a href='https://pachyderm.zendesk.com/agent/tickets/24'>Zendesk ticket #24</a>)<br>gz#24</i>

**Comment by jdoliner** [comment]
Overall this all seems really good to me. Below are a few random thoughts and things I think you should consider. There's not really anything that I feel needs to be changed here though.

The `Tasks` collection sounds like exactly the right approach to me. We actually have a [recently added task queue implementation](https://github.com/pachyderm/pachyderm/blob/master/src/server/pkg/work/work.go) from @brycemcanally's storage changes here. I think it'd be great if we could reuse / extend that for the purposes of this project. Especially because it's currently being used for the merge process in the new storage layer, which is one of the things you'll be using it for here.

I really like that this is making it so datums get layed out ahead of time in object storage, that's a change we've been wanting for a while. I think one of the most interesting questions is how you lay out the datums to be processed in object storage. The simple answer is to just have one big object with the datumIDs serialized into it. It looks you're already thinking about doing something fancier and having them broken up into datum sets. Another idea in this vein that we've talked about is repurposing the stats commit for this. The stats commit already contains all of the information about datums being processed, since it has a top level directory for each datum to be processed, it also will have information about already processed datums, since that gets filled in when a job completes. To make this work I think we'd probably want to remove the option to turn stats off, which I think would simplify things, and not add much overhead, especially if a lot of the information is stuff we need to compute no matter what. We can chat more about this if you think it fits in well with what you're doing, I don't want to add more constraints to this project though if it doesn't fit well so feel free to ignore this idea.

> The Params field for a datum set shall include the hash range for which
datums in the datum set the worker shall process.

How are you envisioning hash ranges being defined? I generally have a preference for defining them using a common prefix, rather than explicit start and end points. Feels a bit more elegant and it's easy to see if one overlaps another.

It seems possible that this work could either set us up well for or include #3065, again I don't want to expand the scope of this work by adding more requirements but I think this would be a good thing to at least keep in mind as you're implementing this. Since it's something we know we'll want soon and it should be possible to set ourselves up well for it.

Similarly take a look at #3773, I think you actually might have to do some work in this refactor to maintain our current reprocessing semantics when it'd be easier to implement the ones described in that issue, in which case you might as well implement that issue while you're at it. Again if it feels like it's expanding the scope feel free to ignore that issue.

Lastly one thing that I'd like to see some clarifications on is what happens when a datum fails. Are you planning to preserve our fast fail behavior on jobs? (I.e. when a datum fails do we fail the job immediately or is there a lag time.) And will you be maintaining the retry semantics, ie. a failed datum gets retried in the next job? I suspect the answer to both of these is just a simple yes, but it seems like there might be some things that subtly change.

**Comment by brycemcanally** [comment]
I figured it would make sense for me to read over this to get a feel for how these changes will play into the new storage layer. Overall, I think this makes sense. The only thing I don't think I fully grasp yet is how updating the work for a job plays out when the prior job failed. I do have some feedback on one particular decision:

> Use hash sharding rather than iterator range sharding (which workers currently use)

Is the benefit of this over file path range sharding just that we get a better guarantee on new work being distributed among workers (like time series data)? If that is it, then I don't think this is the right approach or at least the way we should be thinking about it. Sharding by file path range will give us good performance on workloads that are Pachyderm bound (how fast Pachyderm can move data into the user container and out) and sharding by hash will not. The main difference is that there is no way for the user to improve the performance in the sharding by hash model in this case because the new storage layer will not, and cannot, work as well on point queries. With sharding by file path range they can decrease the sharding threshold (number of datums per shard for example) to get better distribution of the work for those workloads that add a bunch of new stuff in a range.

Also, I think it might be a good idea to read over (and potentially give some feedback on) https://github.com/pachyderm/pachyderm/issues/3703. The datum file set is basically going to be supported out of the box with the new storage layer. It is just another file set that can be used. I think we will probably want to merge the datum file set concept with this work.

**Comment by Tryneus** [comment]
>a recently added task queue implementation from @brycemcanally's storage changes

Yep, this is almost exactly what I was thinking of.  I'll use this, although it may need a few changes for my requirements.

> Another idea in this vein that we've talked about is repurposing the stats commit for this. The stats commit already contains all of the information about datums being processed, since it has a top level directory for each datum to be processed, it also will have information about already processed datums, since that gets filled in when a job completes.

I think this could be very effective.  If we go with this, we'd be changing the stats commit to be more of a "datum metadata" commit, which sounds really useful.  Here are the changes I'm thinking after talking this over:

* Drop the concept of datum indexes into the iterator
  * We shouldn't be relying on datum offset in the iterator any more than ephemerally
  * I think we can get rid of it entirely if we iterate once in the master process and leverage the stats commit for distributing task data.
  * Iterator indexes of datums are currently written into stats commits for some reason.
* Leave the existing structure of stats commits the same to avoid compatibility issues.
  * If stats are disabled, this will not be populated past the minimal data needed for workers to start processing datums.
* Add the concept of a secondary index into the stats commit hashtree
  * This is a top-level directory containing mappings from some key to the datum's inputs and hash.
  * This will allow us to shard on things that are not based on datum index or datum hash.
* When constructing the hashtree in the master, build a secondary index based on concatenated input filepaths (with some delimiter).
  * Use this keyspace when sharding the work so that we can leverage range scans in the new storage layer (when available).
  * Allows for input reuse in the workers when we cache it between datums.
* This system will make it easier to shard work differently if we want to add a new secondary index later

> How are you envisioning hash ranges being defined?

Having thought about it more, I'm currently considering just doing a second pass of the generated filepath index in the output stats commit.  Since the master already knows the number of datums present, it can easily divide this up into even chunks.

Note that grouping datums by contiguous input filepaths seems to run counter to the existing behavior of putting the largest datums in the first tasks.  We could still look at total input size and total unique input size for a task and order them based on that, but based on our talk today we aren't too concerned about preserving this behavior.

> It seems possible that this work could either set us up well for or include #3065,

#3065 seems to be about dynamically scaling parallelism when the datum latency grows.  This feels a bit orthogonal to what we're solving here, but I don't see any major blockers in implementing it on top of this.  We would mainly need to build a system for tracking datum latency and idle resources over time.

> Similarly take a look at #3773, I think you actually might have to do some work in this refactor to maintain our current reprocessing semantics when it'd be easier to implement the ones described in that issue, in which case you might as well implement that issue while you're at it.

I could see a way of marking a commit (or datums) as invalid and propagating the invalidation to subvenant commits.  It should be almost trivial to generate a new job to process these datums based on the output stats commits of the invalidated commit.

> Are you planning to preserve our fast fail behavior on jobs? (I.e. when a datum fails do we fail the job immediately or is there a lag time.)

I am not positive what the lag time will be, but it should be comparable to the current system.  Specifically, the work queue implementation mentioned will cancel a running task's context if the task fails, so this should be fairly straightforward.

> And will you be maintaining the retry semantics, ie. a failed datum gets retried in the next job?

Yes, we are using the same concept of 'skipping' datums from the most recent successful output commit, so any datums that have not been processed since then will be retried.

> Also, I think it might be a good idea to read over (and potentially give some feedback on) #3703. 

I think what we arrived at here is basically the same concept as datum sets, however I don't want to go through the work of breaking backwards compatibility yet for this feature.  Having a worker and master that operates on these concepts on the existing hashtree implementation seems like a good first step towards bringing in the new storage layer, though.

**Comment by JoeyZwicker** [comment]
We can close this now, right?

**Comment by jdoliner** [comment]
Yes!!

**Comment by sinonkt** [comment]
Can't wait to see these features in action!, on next 1.11.0-beta

**Comment by Tryneus** [comment]
How could you @jdoliner

**Comment by jdoliner** [comment]
Apologies @Tryneus you should have the glory on closing this.

**Comment by Tryneus** [comment]
Skadoosh

**Comment by sinonkt** [comment]
@Tryneus Hi, I've try v1.11.1. In my understanding if i've 3 consecutive single datum commits and i configure parrallism_spec to 3. they should utilze those 3 workers as commit come in. not waiting for the first commit to finished right?.
but as i try it's not what we expected. Could you please clarify a bit how to use these features do i need to set more flag or something. thank you in advance

**Comment by JoeyZwicker** [comment]
@sinonkt If you are adding one datum in each commit (e.g. the 3rd commit has 3 datums), all the datums across commits will be processed at the same time -- so that will be much faster. But since the commits are _cumulative_, the first output commit will still need to be closed before it can close the 2nd and 3rd output commit. 

If your 3 commits have no datums in common (e.g. you overwrite the datum each time), it will fully finish the 3rd commit even if the 1st or 2nd are still running. Here's a video demonstrating this feature: https://www.youtube.com/watch?v=lr8FD-i_6M4&feature=youtu.be

Note that in this video though, the commits are _**not**_ cumulative.

**Comment by sinonkt** [comment]
@Tryneus @JoeyZwicker @pappasilenus That's help a lot. it's much clearer now, i'll keep in mind about cumulative and non-cumulative nature, Thank you so much. :))
