### ISSUE TITLE
pachctl delete all doesn't delete anything in the object store

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4375]
I expect `pachctl delete all` to delete all the pachyderm data in the object store (Minio in my case). But it turns out that all of it is still there after I run the command.

**Environment?**:
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.8

**Comment by JoeyZwicker** [comment]
Delete all by design deletes the Pachyderm objects, but not the underlying data in object store, garbage collection does that. Or you can just wipe the bucket yourself. This works the same as deleting commits or repos doesn't delete the data without GC running too. 

I can understand that this might be slightly unexpected though, but we see a lot of uses where users delete everything because some of their pachyderm setup is in an unwanted spot, but then end up adding much of the same data back into their next environment and this saves them writing that data twice. 

I dont think there are any plans to change this setting. That said, we have upcoming plans to make GC run automatically in the background. Once that feature is added, any old data left around in the bucket that is no longer referenced by the new cluster will get removed over time.
