### ISSUE TITLE
Use one sidecar container per pipeline

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4417]
The sidecar containers require at least 1 CPU or the merging step takes forever. This is an issue when deploying pipelines utilizing parallelism. If Parallelism=10, the sidecar containers will consume 10CPU which seems wasting a lot of CPUs. (I'm not even talking about the crazy memory usage: #4337 ).
- Could it be possible to have a mode not using sidecar containers?
- If not, could it be possible to merge all the "parallel pods" into one pod having only one sidecar container?

**Comment by jdoliner** [comment]
The sidecar exists so that workers can proceed as independently as possible from one another and make use of the given resources. If we removed the sidecars then that 10 CPU worth of traffic is going to have to go through the main pachd, which means that it either needs an additional 10 CPU to work with, or more likely that it will get swamped and start to slow down, which means the pipelines will go a lot slower, and more importantly that user commands will slow down and even get blocked out, making the cluster unresponsive.

Merging all the pods into one pod would have a similar problem (minus the part about user commands getting blocked out), it would also mean that you could only use one machine's worth of resources in running a pipeline, which would be undesirable.

Neither of these are things I think we want to do. Overall I think the current system is good, prior to its introduction we had the issue mentioned above of large pipelines swamping pachd and preventing pachctl from working which was really bad because there was basically nothing you could do, we haven't seen that issue since its introduction. Working on the CPU usage of the sidecar (which is just a pachd instance, so really pachd CPU usage) is something we can do, although that's going to be a fairly incremental solution to this problem.
