### ISSUE TITLE
documentation commands include an extra '$' character

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#4426]
**Provide a link to the page with an issue:**
most of the docs containing commands. for example:
https://docs.pachyderm.com/latest/getting_started/local_installation/
**Describe what is wrong:**
When clicking the copy to clipboard button, the extra '$' character gets copied as well and causes the command to be invalid.
for example:
"$ curl -o /tmp/pachctl.deb -L https://github.com/pachyderm/pachyderm/releases/download/v1.9.9/pachctl_1.9.9_amd64.deb && sudo dpkg -i /tmp/pachctl.deb" gets copied.

This forces the user to manually delete the extra character which breaks the flow of using the docs for the user.

**Describe the suggested changes:**
either remove the extra '$' character or make it so that copying it does not copy that character into memory.

**Anything else we need to know?**
nope.

**Comment by JoeyZwicker** [comment]
This totally makes sense and shouldn't a hard fix. Thanks for filing!

**Comment by jdoliner** [comment]
I think having the `$` is a good thing because it distinguishes commands from their output. Not copying it when the copy button is clicked makes a lot of sense though, and similarly not copying the output of the command.

**Comment by JoeyZwicker** [comment]
Agreed, but we're using a built-in plug-in for the copy functionality and that's meaningfully harder to edit to just not copy the `$`. @svekars can comment further.

**Comment by svekars** [comment]
Many known and respected documentation websites omit it. Examples: [AWS](https://docs.aws.amazon.com/eks/latest/userguide/getting-started-eksctl.html), [Kubernetes docs](https://kubernetes.io/docs/tutorials/hello-minikube/). I agree that in some cases omitting the `$` sign might be confusing. For these cases, we should ensure that we describe how to run these commands in more detail. But as @jdoliner and I have discussed, the multi-line commands that we have in the docs at the moment are not copypastable either with the $ in them.  These commands in their turn might be used in scripts, where the $ sign is not relevant. We can add a `$` as a background image in code blocks in the future.

Here are my suggestions:

1. Not to use the `$` sign in commands. 
1. Separate input and output so that one-line commands are copypastable (will update the PR).
1. In situations with setting up env variables where we want to copy multiple lines, add `\` where needed.

There is probably another way of achieving this by modifying `clipboard.js` to avoid copying the first symbol in a code block if it's a dollar sign. I vaguely imagine how this would work and most likely need engineering help to implement this. 

Thoughts?

**Comment by JoeyZwicker** [comment]
@jdoliner I agree with @svekars on this one. Changing the clipboard.js plugin seems like a bigger project than we want this to be and will need eng help that doesn't seem worth it. 

Svetlana's suggestion of breaking up input & output into separate code blocks when output is important seems totally reasonable. There's plenty of places where we have it and it's not really needed.  

If we decide breaking input/output into different code blocks worsens the docs meaningfully, then still removing the `$` from all single-line commands (and making more of them single-line cmds where reasonable) still has some value gained there. Right now, nothing is copy/paste. If we only remove for single-line commands with no output, then at least those work and the multi-line/output ones still wont, so we're not really any worse off.
