### ISSUE TITLE
Make pachctl syntax more consistent with kubectl

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#4427]
**What is the goal / desired outcome?**
Make pachctl and kubectl have more consistent syntax, reducing learning curve and confusion to the user coming from a k8s background.

two common examples I personally see all the time:
1. pachctl config and kubectl config. They achieve something very similar but have slightly different syntaxes ergo:
'pachctl config list context' vs 'kubectl config get-contexts'
and all the other CRUD operations in the config subfamily are different.
2.  pachctl inspect vs kubectl describe will inspect/describe a resource. I'd rather have 'pachctl describe'.

**If there is a way to accomplish this today via workaround, what does that require?**
have the user learn 2 similar syntaxes.

**(Optional) What is your proposal for a feature to solve this?**
implement a syntax change in pachctl. probably apply this in pachyderm 2.x as this is a usage shift to the user. Preferably keep the older syntax still working with a warning before deprecation. 

Don't get me wrong, pachyderm might have a slightly cleaner syntax with a bracket missing here or there. But achieving the same syntax where possible with k8s would reduce the learning curve and make the usage more streamlined.

**Comment by JoeyZwicker** [comment]
@RaananHadar the `config` being different is definitely one that messes with me from time to time so I agree there. 

I can see how `inspect` vs `describe` is a bit annoying too, but I think the vast majority of our cmd are similar to kubectl already. Do you have any others that stand out to you?

**Comment by RaananHadar** [comment]
inspect and describe are minor. 
config, **being a part of a longer command** is more of an issue since the user has a greater chance of inputting an invalid command when they confuse things up.

These are the main ones i see. I will note if I see anything else.

**Comment by ysimonson** [comment]
As a counter-argument: while `kubectl` is generally consistent, their `config` commands are not -- it's the one place I'm aware of that doesn't use a verb-based syntax. Our current `pachctl config`-related commands are more consistent with other `pachctl` commands, as well as (non-config) `kubectl` commands. Due to this, I instead tend to get tripped up when running `kubectl config` commands rather than `pachctl config` commands.

For context, here's the PR that introduced config-related commands: https://github.com/pachyderm/pachyderm/pull/3786

**Comment by JoeyZwicker** [comment]
I think I agree with Yusuf here. It's unclear if we should try to copy inconsistencies within kubectl just to be similar to them or try to do things better ourselves while staying mostly consistent where possible. 

@RaananHadar your point in well made, but I think we're going to close this for now as it seems like a minor inconvenience and the kubectl syntax was taken into account when we added the feature and specifically decided we wanted to be more internally consistent.

**Comment by jdoliner** [comment]
Agree with closing this, a few things to add:

- we intentionally chose to be inconsistent with `kubectl config` for all of the reasons @ysimonson described above, I still think that was the right choice.
- `inspect` was originally chosen over `describe` because that's what Docker uses and consistency with Docker was seen as a bit more important at the time, these days consistency with `kubectl` is more important, so if I could go back I think I'd make the opposite choice, however I don't think it's worth the disruption to switch over now.
- the other glaring inconsistency is that we use `list` where `kubectl` uses `get`, this one never comes up because I think `list` just makes a lot more sense to most people. Needless to say, I don't think it would make sense for us to switch all of our `list` commands over to `get` commands.

**Comment by RaananHadar** [comment]
i'm ok with that. Its always good to see how openly you handle issues.
