### ISSUE TITLE
error thrown when trying to delete file

### ISSUE THREAD

**Issue by erikreppel** [pachyderm/pachyderm#453]
Getting the error 
```rpc error: code = 2 desc = commit test/887b35b7a14c4078abf12c05776674cb has already been finished```
When I'm trying to use `DeleteFile`. That commit is finished so maybe I'm misunderstanding how `DeleteFile` is suppose to work? Should I be able to delete a file from a closed commit? I saw that you guys don't yet support deleting a commit.

Heres the code block that causes the issue:
```
err = pach.DeleteFile(oldInfo.RepoName, oldInfo.CommitId, oldInfo.FileName)
if err != nil {
        ctx.WithError(err).Error("Failed to delete file")
        return err
}
```

**Comment by erikreppel** [comment]
Never mind, can't operate on closed commits, have to open a new commit then delete the file.

**Comment by jdoliner** [comment]
Deleting a file in a finished commit is disallowed along with other write operations like `PutFile`. Commits need to be immutable once they're finished so that downstream jobs can safely consume them and not worry about them changing during execution.

What you can do though is start a new commit with the commit you want to delete the file from as the parent, this commit will allow you to call `DeleteFile` while it's open and once you finish the commit it will look like the old commit with the file deleted.
