### ISSUE TITLE
Delete pipeline doesn't trigger an error when the pipeline doesn't exist

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4570]
**What happened?**: Calling `pachctl delete pipeline <some-non-existent-pipeline>` does not print an error, and exits with code 0.

**What you expected to happen?**: An error should be returned if the pipeline doesn't exist.

**Comment by jdoliner** [comment]
I think we added this intentionally, because it makes it easier to write reset scripts like:

```
delete repo ...
create repo ...
put file repo@master ...
...
```

and have them work no matter what. Without this you need to do something at the start of the script to check if the repo exists, and only delete it if it does. We thought about gating this behind a flag, but it doesn't seem super dangerous to me so we didn't bother.
