### ISSUE TITLE
add a way for PutFileURL to reference a set of credentials for accessing the storage

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4582]
**What is the goal / desired outcome?**

As a data scientist, I would like to ingress data into Pachyderm from storage using a different set of credentials than in the pachyderm-storage-secret, so that I can use a different storage mechanism for data ingress than Pachyderm uses for its object store.

**If there is a way to accomplish this today via workaround, what does that require?**

Ingressing directly from storage other than the object store Pachyderm is configured with is not possible, if the storage requires authentication.    You must download the data to  location accessible to Pachyderm that either doesn't require authentication, or is accessible using the credentials encoded in `pachyderm-storage-secret`. 

**(Optional) What is your proposal for a feature to solve this?**

Optional parameter(s) to PutFileURL, accessible from `pachctl put file`, which will allow a way to reference credentials and authentication mechanism for accessing the URL specified in the command.  Not sure what the UX should be, I'll leave that to discussion below.  

I do believe that making this work with the new facility for Pachyderm to upload secrets would be acceptable.  Requiring the secret to contain the authentication parameters in a particular format, perhaps S3 access credentials that can be used with S3 stores that can use the Go s3 driver.

**Comment by jdoliner** [comment]
From what I know about Kubernetes secrets this isn't possible without introducing some fairly serious security holes. Pods need to declare the secrets that they have access to ahead of time, which is when Kubernetes checks to make sure they have access to the secret, they can't request them during runtime without really permissive RBAC settings that Pachyderm shouldn't be given.

I think the way Pachyderm's credentialing system currently works is the way we want it to, it can store a credential for each cloud provider in the storage-secret, this credential should be for a role that's specific to Pachyderm and can then have whatever access controls are appropriate for Pachyderm attached to it, or revoked through it. Adding multiple credentials for the same cloud introduces a lot of complexity, such as having to specify which credential is should be used for different requests. That's in theory solvable, but I suspect will have a few negative effects on UX. There's also the UX question of what combining credentials looks like in Pachyderm, all the clouds have UIs specifically designed for making credentials, and assigning them different access controls, these are the interfaces people should be using to add access to new things for their Pachyderm credentials, and they're a lot better UX than our own homegrown solution is going to be, so I think we'd be doing people a disservicing by trying to implement this ourselves, rather than guiding them to use the existing solutions. It also guides people toward bad security practices, having a single credential for Pachyderm (or anything) is a really good idea because you have one place to look if you want to see what you've given Pachyderm access to, and one place to  go if you want to revoke that access. When you start adding multiple credentials it gets really easy to revoke access through one credential but leave it on through the another, at which point you can leak sensitive data.

I'm going to close this because I don't think we want to do this. Feel free to reopen if you feel like I'm missing something here.

**Comment by pappasilenus** [comment]
I hear you on the complexity of credential management.  What I'm hearing from users is that they often want to ingest from systems that are separate from the object store used to run Pachyderm.  

For example, on hub, are we only going to allow ingestion from gcs buckets?  Or whatever provider it's currently running on?

I can see a couple of ways this could be implemented with low complexity, similar to the way curl and wget use it.

1. Allow a single set of alternate credentials used for file ingestion only.
2. Allow PutFileURL to have, as a parameter, a reference to a either a secret or a set of inline credentials that's used for that operation only.
