### ISSUE TITLE
Run a specific commit instructions aren't really about that

### ISSUE THREAD

**Issue by szeitlin** [pachyderm/pachyderm#4583]
**Provide a link to the page with an issue:**
https://docs.pachyderm.com/latest/how-tos/run_pipeline/

**Describe what is wrong:**
This page talks about how to do this with `cross-pipe` but it's unclear that this is also supposed to be used with commit IDs or how that would work. 

**Describe the suggested changes:**
Give an example that is not a cross join. 

**Anything else we need to know?**
nope.
**Environment:**
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS:
- Other:

**Comment by JoeyZwicker** [comment]
We can add a super simple example of this with only 1 input to demonstrate the basic concept, then include the more powerful/complicated cross example. 

Also, these example commands should use actual pachctl formatting instead of A, B, C for commits. e.g. Should it be repo@commitID, etc. 

The majority of the edits would simple include updating this doc to follow our pachctl cmd guidelines more closely

**Comment by lbliii** [comment]
https://pachyderm.atlassian.net/browse/DOC-131
