### ISSUE TITLE
Expose S3 Gateway to web based clients

### ISSUE THREAD

**Issue by chainlink** [pachyderm/pachyderm#4589]
**What is the goal / desired outcome?**
Allow web based s3 clients to connect to the pachyderm s3 server implementation. For this to work in browser, we should need to handle CORS pre-flight `OPTIONS` requests. This would unlock additional S3 compatible tooling

In general, i think the s3 gateway could eventually replace our (aging) http api and allow us to consolidate support on one option.

**Proposal**
Add a `S3_ALLOWED_DOMAINS` flag for CORS domain support.

**Comment by chainlink** [comment]
@ysimonson I get the sense you have some reservations about this approach? Can we capture them here?

**Comment by ysimonson** [comment]
Chatted with @Connor-Wallace about this offline. I don't think we're going to be able to use s3 gateway, because it's not feasible to browse non-head commits on PFS.

**Comment by jdoliner** [comment]
I have some reservations about this too. It sounds like there's a decent amount that would have to be added to s3g to make it viable for this, which expands its scope from a shim layer that does just what's necessary to allow other software that's designed around s3 apis to interface with data in pfs, to something that's got to expose everything in pfs that we might want to expose in the UI. Moreover I'm worried there will be things that just can't be exposed this way because our filesystem model doesn't totally map to an object store model, at the very least I think we'll have to shoehorn a bunch of things in.

To me it makes more sense to base the filesystem browser on an API that we have full control that unfortunately probably means we can't grab something off the shelf to base the filebrowser on.

**Comment by chainlink** [comment]
Thanks all! Was hoping this approach would be a quick win, but it's looking like we'll need to go back to the drawing board.
