### ISSUE TITLE
stopped pipeline looses processed datums

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4618]
When killing a pipeline (by upgrading it for instance) while a job is running on that pipeline, the datums that were already processed are skipped when resuming the pipeline. This is the expected behavior.
Now when stopping a pipeline while a job is running, the processed datum are lost (i.e. reprocessed when restarting the pipeline).

**Environment?**:
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.9

**Comment by jdoliner** [comment]
This isn't the expected behavior, and isn't one that we've observed internally. This behavior is possible if you stop a pipeline while a datum is still processing or uploading to object storage, and there's no particular indication of when the datum has actually been checkpointed in. Most likely you're stopping the pipeline before the objects have been written to object storage.

I'm going to close this, but feel free to reopen with reproduction steps if can find a consistent way to reproduce it.
