### ISSUE TITLE
Worker pods should be a minimum resilient against state inconsistency

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4621]
It happens quite often that workers and pachd do not agree about the state of the system. This is an example:
My pipeline `xxx` seems to be stuck in state `RUNNING` (or sometimes `MERGING`). I look at the pod logs and I see: `{"pipelineName":"xxx","workerId":"xxx-v2-hb2pz","ts":"2020-02-19T10:52:09.649866770Z","message":"blocking on parent commit \"559dba0ae69a4ac1ad59fc8ea9c7c1d2\" before writing to output commit \"2d0eaff55fd742c480ff6469c4daf660\""}
`
`pachctl list commit xxx` returns:
```
REPO                     BRANCH COMMIT                           FINISHED    SIZE PROGRESS DESCRIPTION
xxx stats  f28f55673db74d6688d34278e5b08e54 -           -    -
xxx master 2d0eaff55fd742c480ff6469c4daf660 -           -    ▇▇▇▇▇▇▇▇
xxx stats  f3d948b9bfd7477e9b718823508677ed -           -    -
xxx master 559dba0ae69a4ac1ad59fc8ea9c7c1d2 2 hours ago 0B   ▇▇▇▇▇▇▇▇
```
To confirm that the commit is finished: `pachctl finish commit xxx@559dba0ae69a4ac1ad59fc8ea9c7c1d2`, which returns: `commit 559dba0ae69a4ac1ad59fc8ea9c7c1d2 in repo xxx has already finished`
This is what I call a state inconsistency: one worker is not aware of this commit being finished while the others are.

Now this happens way too often and I don't know the reason. Is it etcd (I do have a few `read-only range request xyz took too long to execute`)? But whatever the cause is, pachyderm **must** to be able to maintain a consistent state **almost** all the time. I say **almost** because unexpected stuff will always happen (transient network issue, longer response time, ...). But pachyderm should recover from a state inconsistency, fairly quickly and automatically. If not, then Pachyderm is virtually unusable in a production environment where stuff do happen.

**Environment?**:
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.x
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
minikube & openshift

**Comment by jdoliner** [comment]
@marcadella logs aren't state they're events emitted by the server, in some cases they might give you a snapshot of state at a given time, in this case it's not even giving you that. The worker just prints out that message before it blocks on the commit finishing, it has no idea what the state of the commit is when it prints that message (it's about to check that information), it frequently returns a few milliseconds later, but the log message has already been printed at that point and there's no way to modify it, that's not how logs work, and it would defeat their purpose if it was. The fact that they're immutable and represent events emitted by the program, rather than state that gets updated is what makes them useful for debugging.

**Comment by marcadella** [comment]
Alright, thanks for the clarification. I wasn't asking to change the log, I was trying to understand why my pipeline were stuck and thought it was because of an inconsistent state. But now I understand that this was just another manifestation of #4622 .

**Comment by jdoliner** [comment]
Jobs getting stuff is definitely a bug. I think it's probably covered by other issues but if it's not feel free to reopen this with more details.
