### ISSUE TITLE
setting resource requests for worker pod doesn't set them for worker sidecar 

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4668]
**What happened?**:

In a locked-down k8s environment where explicit resource requests are required on each container (see https://kubernetes.io/docs/concepts/policy/resource-quotas/#requests-vs-limits), pipeline creation fails because there are no explicit resource requests for the worker or sidecar. 

To work around it, we made an explicit resource request in the worker using `resource_request` in the pipeline spec.  The pipeline still failed because there was no explicit request for the sidecar.

This can be worked around by editing the RC for the worker, but that needs to be updated manually every time the pipeline is updated.

**What you expected to happen?**:

We expected the pipeline to run.

**How to reproduce it (as minimally and precisely as possible)?**:

1. Create a k8s namespace with a hard resource request value (see https://kubernetes.io/docs/concepts/policy/resource-quotas/#requests-vs-limits)
2. Deploy pachyderm to that namespace 
3. Create one-stage DAG using a pipeline spec without a resource request.  Watch it fail, logs will indicate reason is no resource requests in user and storage containers for worker.
4. Set a resource request in the pipeline spec and update it
5. It will  still fail because only the user container will have an explicit resource request. The storage container will not have one.

**Anything else we need to know?**:

IT departments can be inflexible in enforcing these constraints, as they're trying to keep costs under control and wish users to create well-defined pods.

**Environment?**:
- Kubernetes version (use `kubectl version`): OpenShift 4.X, I believe (will update), but this should be a problem on an k8s
- Pachyderm CLI and pachd server version (use `pachctl version`): pachctl 1.9.12
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): on-prem
- OS (e.g. from /etc/os-release):
- Others:

**Comment by Tryneus** [comment]
So, attempting to reproduce this locally - it appears we _do_ set default requests for the `storage` and `user` containers.  If you don't specify anything, it will do `cpu: 0` and `memory: 64M`.  The 64M comes from the default cache size setting, which ends up getting used for both containers (which is kind of confusing because the cache is only in the sidecar).

I think the problem actually arises because there are no resource requests on the `init` container.  I was having trouble launching the pod until I added defaults there.

Here's what I'm thinking of doing in my branch:

* Get rid of the default behavior for `pipelineInfo.ResourceRequests` - this was spread out over like three files and still had (what I considered) surprising behavior.  We will leave the `ResourceRequests` exactly as defined in the pipeline spec.
* Leave the `CacheSize` default value in the pipeline spec (`64M`)
* When instantiating the pod spec:
  * `init` container: use the `user` container resource settings
  * `user` container: provide a default cpu request of `0` and mem request of `64M`.  This will be over overwritten by any values from the `pipelineInfo.ResourceRequests`
  * `storage` container: provide a default cpu request of `0` and mem request equal to the `pipelineInfo.CacheSize` value

There are a few things to consider here, but we can look at these individually:
* `init` container:
  * I don't think the values here are very important, especially because this container runs _before_ the other containers, we don't have to worry about resource contention.  It also doesn't do any heavy lifting.
  * Using values identical to the `user` container should be fine as those resources should be available to the pod.
* `user` container:
  * The default value of `64M` should be fine as it's the existing default, we've just moved where this gets determined to be in one place.
  * This is a user-visible change in that the `user` container used to request `CacheSize` memory here, but now it will be `64M`.  On the other hand, we used to be requesting the `CacheSize` twice, which was obviously wrong.
  * The user has full control over these values via the pipeline spec.
* `storage` container:
  * Using the `pipelineInfo.CacheSize` for memory here is obviously correct.
  * The cpu request is not configurable, but I'm not sure this is a problem - if the sidecar slows down, that should put backpressure on the `user` container which should reach an equilibrium.
  * Disk and gpu requests aren't configurable either - the sidecar has no use for gpu, but I could see disk being a problem as that is also used for caching hashtrees - not sure how big of a deal this is for the `storage` container.
* The one breaking change I see here is if people have been relying on the behavior that `CacheSize` double-dips and applies to both the `user` and `storage` containers.  After this change, the `user` container will only request 64M.  Given that these are requests and not limits, I think it _should_ be fine, but I'm not sure.

@pappasilenus @jdoliner - any opinions here?

**Comment by pappasilenus** [comment]
@Tryneus I'm sorry I haven't responded.  This looks good to me.  Not having the storage requests configurable is OK in the short term, but I think we'll want those available via pod_patch or another mechanism in the future.

**Comment by pappasilenus** [comment]
duplicates https://github.com/pachyderm/pachyderm/issues/4907
