### ISSUE TITLE
Glob characters in file paths

### ISSUE THREAD

**Issue by brycemcanally** [pachyderm/pachyderm#4750]
Should the characters we use for globbing (`[*?[\]{}!()@+^]`) be allowed in file paths? 

The approaches discussed up to this point are:
- Prevent users from uploading files with glob characters in the path.
- Allow users to upload files with glob characters in the path (they will need to escape them to retrieve them).
- Allow users to upload files with glob characters in the path when they explicitly enable it (potentially a global flag for this?)

I am leaning towards preventing users from uploading files with our glob characters in the path because that avoids potential user access issues in the future and is just a simpler model. I think the latter approaches only make sense if there is a strong argument for why those reserved characters are needed by users.

**Comment by JoeyZwicker** [comment]
@svekars For whatever is decided above, we should probably add a small note/section to one of the docs (maybe the files section or maybe globs, I'm not sure) to capture this for users. Adding docs label too

**Comment by jdoliner** [comment]
The argument for why those reserved characters are needed is that sometimes users are mirroring existing filesystems into pfs, they can sanitize the names but it's awkward and runs the risk that two sanitized names might collide.
An alternative that's not mentioned here that might work well is allowing users to submit paths with glob characters if they escape them. I.e. if they want to put a file as `foo+bar` it has to be `foo\+bar`. This has the advantage that it forces you to go through the work you're going to need to go through to access the file up front, so it's not a surprise. And it means that your accesses will look fairly sane:

```
pachctl put file repo@master:foo\+bar
pachctl get file repo@master:foo\+bar
```

If you wind up needing to do this programmatically then the same function you use to escape the string for ingress is the one you should use to request it for egress.

I think I prefer this to a global flag, because it doesn't force you to redeploy when you need it, and because it guides you through using glob characters in filenames a bit better imo.

**Comment by svekars** [comment]
@jdoliner  @brycemcanally  were any decisions made on this and what's the status of the issue?

**Comment by jdoliner** [comment]
We haven't made a decision / scoped this yet. I'm going to tentatively milestone this for 1.12. But I'm not 100% sure it's something we'll get to. It's only come up a few times, so I don't see a burning need. We should definitely make a decision on this before 2.0 though, since then it becomes a backward compat issue.

**Comment by mindthevirt** [comment]
@jdoliner is this still targeted for 1.12?

**Comment by jdoliner** [comment]
1.12 has shipped already and this is probably too big a change to do in a point release. So I think this is going to have to wait until 2.0 unfortunately. Have you seen other users needing this support?

**Comment by PFedak** [comment]
Just saw an instance of confusion due to this: #5774

**Comment by BOsterbuhr** [comment]
This has been decided to not get implemented. However, `pachctl put file` as well as `get file` throw appropriate error message.
