### ISSUE TITLE
Optional inputs

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4754]
For flexibility purpose, it would be awesome if some inputs could be marked as 'optional'. The outcome would be that the path for that input (`/pfs/myOptionalInput/`) simply would be empty, but the stage, even if that input is crossed with another one, would execute anyway.

**Comment by jdoliner** [comment]
The semantics of an optional input in a cross seem a little weird to me. Particularly the fact that when you add a datum to an empty optional input the data produce by running the empty version will go away and be replaced with the data created by running with the none empty version. I can totally believe there are some use cases where this behavior is desirable, but I think it's also going to be confusing to people, because data is being remove due to other data being added. It'd be the only case in Pachyderm so far where you can lose the output of one datum by adding in another datum.

These semantics are also fairly easy to accomplish in other ways, simply add an empty directory that matches your glob pattern for that input and it will act as optional, then when you add real data to the input delete that empty directory. This requires a little more implementation work, but it has the advantage of being explicit. It shouldn't be confusing at all that some data is added to the output while other data is deleted, because in the new input commit you added some data and deleted some other data. It also gives you more alternatives, for example if you want to keep the old data around you just don't delete the empty directory and it'll stick around.

**Comment by marcadella** [comment]
Thanks for your answer, however using a directory as glob pattern doesn't fit my use-case. I can give some more details:
In my workflow, a user may or may not submit a file as input. If he does, on pipeline X will execute, otherwise not since this file is the only input. In any case, other pipelines will run in parallel of X. Lets call them Y. Following X and Y comes Z which crosses them. Z can handle the case where the outputs of X are missing but if X ran, then Z needs to process X's outputs along with Y's outputs. That's why Z crosses X with Y. Now the issue is that since X doesn't run, Z won't run either.
I found a hack which is to make X run anyway by submitting a dummy input file, but that's rather ugly...

**Comment by jdoliner** [comment]
A dummy input file is more or less what I'm suggesting with the empty directory.

If you don't want to pass a dummy file through the pipeline though you can union `X` with another repo that you use to input dummy files directly. That way you can directly control what they look like and delete them / readd them as needed.

**Comment by marcadella** [comment]
Yes that would delay the introduction of dummy files only where it is messed instead of everywhere. I'll do that. Thanks for the tips.
