### ISSUE TITLE
Provide guidelines on `pach-disk`

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#4761]
We need documentation on the `pach-disk` volume.

1) What is it's purpose?

It's where we cache PFS hashtrees for better performance.

2) Why is there no quota?

While there is no kubernetes-level quota, we limit the number of hashtrees that can be cached. Aggregate disk usage should be quite small.

3) What might have been done in pachyderm to cause an explosion in # of files/file size?

Cached hashtrees are evicted asynchronously. If the number of files/file sizes explodes, it implies that the eviction is failing.

**Comment by chainlink** [comment]
Agree we need more clarity here. Interestingly, in local deployment, it's mapped to `hostPath` (presumably for debugging purposes) but in non local deployments these use `emptyDir` instead of a PVC. 

From the [Docs](https://kubernetes.io/docs/concepts/storage/volumes/)
> By default, emptyDir volumes are stored on whatever medium is backing the node - that might be disk or SSD or network storage, depending on your environment. However, you can set the emptyDir.medium field to "Memory" to tell Kubernetes to mount a tmpfs (RAM-backed filesystem) for you instead. While tmpfs is very fast, be aware that unlike disks, tmpfs is cleared on node reboot and any files you write will count against your Container’s memory limit.


So, a few things here:
- In cloud deployments, we could either use a PVC with a storage class to speed up this scratch space by ensuring it uses an SSD. This also unlocks more control over provisioning (size, etc)
- If we continue to use `emptyDir` we should probably be recommending the use of SSD backed nodes for performance.

**Comment by jdoliner** [comment]
So `pach-disk` actually serves two purposes, which makes it confusing.

1. it's used as a place to cache hashtress in workers, this is true in both local and non-local deployments. This cache seems to be the thing that can cause the empty disk to fill up in production deployments.
2. In local deployments it's used to "fake" an object store, we just store the things we would store as objects as files in the filesystem. This is why we use a `hostPath` in local deployments rather than an `emptyDir` because we need workers to be able to access the same volume so that objects created by pachd can be seen by the worker, and vice versa.

We should document this, but we also might want to consider changing a few aspects of this:
1. We should probably switch to using an `ephemeral-storage` request instead of the `emptyDir`. I haven't used `ephemeral-storage` in k8s yet but it seems strictly better suited to our needs.
2. We may want to separate out these two uses of `pach-disk` that way we can give them both more descriptive names, and have the cache always be `ephemeral-storage` and fake object store disk always be a `hostPath` and that way it can just not exist in `non-local` deployments.

**Comment by chainlink** [comment]
Agree with separating out the two uses of `pach-disk` into different names. I've hit that before and I took a while to parse through the difference.

**Comment by svekars** [comment]
@jdoliner thank you for clarifying this. Is there a plan for renaming `pach-disk` for separate uses and should the docs wait until that happens?

**Comment by jdoliner** [comment]
There's a plan to do that, it's not a high priority thing and config changes like this can be disruptive, so I'd hold off on docs.

**Comment by mindthevirt** [comment]
@jdoliner given recent performance tests by @dgeorg42 , I believe we should document the importance of having a performant disk backing `pach-disk`. Any objections?

**Comment by jdoliner** [comment]
Nope that sounds good.

**Comment by nadegepepin** [comment]
KB item will be created for this.

**Comment by claytonlemons** [comment]
@jdoliner Could you elaborate on the PFS hashtrees (i.e. what are the keys and values) and how they affect performance?

**Comment by jdoliner** [comment]
Sure thing @claytonlemons. Hashtrees (similar to Merkle trees) are the main structure that backs pfs. The keys are filenames and the values are filecontent and metadata. The hashing of these trees is what gives pfs its versioning semantics. They're also the main usage of storage and bandwidth within the system, so caching them can allow things to run much much faster. Especially when you high levels of the tree since those get accessed again and again to read different files.
