### ISSUE TITLE
large parallelism specs make k8s hit a queries-per-second (qps) limit

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4815]
Hi all - my pipeline killed in the middle with error - `Reason: pull QPS exceeded`

tried to rerun it - fail with the same error.

it do runs for several hours and then fail.

any Idea ?

---

Ticket created from a Slack message by John Karabaic (he/him) in #users. gz#29

**Comment by pappasilenus** [comment]
Agent comment from John Karabaic in <a href='https://pachyderm.zendesk.com/agent/tickets/29'>Zendesk ticket #29</a>:  
  
Parallelism spec will definitely increase the amount of requests which can cause it to hit that limit. Pachyderm has special handling of ImagePull errors because those generally aren't recoverable (mostly they come from a bad image name) so we surface them to the user and fail the pipeline. We hadn't seen this error before so we handle it like the other image pull errors and fail the pipeline.

**Comment by jdoliner** [comment]
The thing to do here is that this error shouldn't be treated like other `ErrImagePull` errors, we generally treat those as meaning the pipeline will never succeed, which we do so that when you reference an image that doesn't exist you get an error back that tells you what's going on. Unfortunately this is the same error as the one we're getting here so we're going to need to look at more detailed things from the error to distinguish them.

**Comment by pappasilenus** [comment]
Agent comment from John Karabaic in <a href='https://pachyderm.zendesk.com/agent/tickets/29'>Zendesk ticket #29</a>:<br><br>This should have been fixed in 1.10.5.
