### ISSUE TITLE
Error : failed to negotiate an api version;

### ISSUE THREAD

**Issue by ChaiBapchya** [pachyderm/pachyderm#498]
Trying to deploy Pachyderm on AWS, steps followed

On Local machine (Fedora 23)

1. Go installed (go version 1.6 , GOPATH,GOROOT,PATH set )
2. Pachyderm repo cloned using (go get)
3. kubectl ,pachctl, pach-deploy working
4. AWSCLI installed (checked with aws command)
5. Environment variables for cluster set
6. Amazon cluster made
7. Session token received, manifest file made

Error - 
make MANIFEST=manifest launch
# GOPATH/bin must be on your PATH to access these binaries:
GO15VENDOREXPERIMENT=1 go install ./src/server/cmd/pachctl ./src/server/cmd/pach-deploy
kubectl -s 52.37.153.65 create -f manifest
error: failed to negotiate an api version; server supports: map[], client supports: map[metrics/v1alpha1:{} extensions/v1beta1:{} componentconfig/v1alpha1:{} batch/v1:{} autoscaling/v1:{} authorization.k8s.io/v1beta1:{} v1:{}]
Makefile:119: recipe for target 'launch' failed
make: *** [launch] Error 1

**Comment by ChaiBapchya** [comment]
On the server side, at 52.37.153.65
Docker image for ubuntu builds a container
Apache installed on the Ubuntu container
(Basically htttp port 80 opened)
And hence during 

[root@localhost pachyderm]# make MANIFEST=manifest launch
# GOPATH/bin must be on your PATH to access these binaries:
GO15VENDOREXPERIMENT=1 go install ./src/server/cmd/pachctl ./src/server/cmd/pach-deploy ./src/server/cmd/pachctl-doc
kubectl -s 52.34.196.247 create -f manifest
**Unable to connect to the server: dial tcp 52.34.196.247:80: i/o timeout
Makefile:107: recipe for target 'launch' failed**
make: *** [launch] Error 1

**Comment by jdoliner** [comment]
The issue with failing to negotiate an API version with is a new one for me. What version of kubernetes were you using?

The second one looks like a connection problem. You should check port forwarding etc. to make sure kubectl can talk to kubernetes.

Neither of these issues could be fixed by code added to this repo though so I'm going to close this. I think the kubernetes folks will be able to tell you more, you should try running this issue by them.
