### ISSUE TITLE
Error from CreatePipeline

### ISSUE THREAD

**Issue by ChaiBapchya** [pachyderm/pachyderm#503]
```
#pachctl create-pipeline -f examples/fruit_stand/pipeline.json
Error from CreatePipeline: rpc error: code = 2 desc = proto: bad wiretype for field pps.PipelineInput.Reduce: got wiretype 2, want 0

#2016/06/13 12:52:38 transport: http2Client.notifyError got notified that the client transport was broken read tcp 192.168.1.21:35954-> w.x.y.z.:30650: read: connection reset by peer.
```
Context - 
1. Cluster up and running on GCS
2. Repo created on GCS
3. Finish commit
4. Error while creating the pipeline

**Comment by jdoliner** [comment]
Hmm, this looks like it's probably a mismatch between the pachctl version and the server version.
What happens if you try rebuilding both of them?

**Comment by ChaiBapchya** [comment]
pachctl version
COMPONENT           VERSION             
pachctl             1.0.0(dirty)        
pachd               1.0.0(849)          

pachctl version - returns version (of the server on which pachyderm is deployed right?)
By server version, do you refer to the pachyderm github repo version or kubectl version?
My kubectl version is 

 kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}

Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}

**Comment by sjezewski** [comment]
Hi there -

That's helpful. FYI - when we refer to server version we're asking for the `pachd` version string reported from the first command you ran. That command reports the version of `pachctl` (the client) and `pachd` (the server).

Since you're using a build of the client from source, its a bit hard to tell if its mismatched. Please try the following:

- pull the latest pachyderm code (`git pull origin master`)
- rebuild the client (`make install`)
- retry making the pipeline
- if that doesn't work, report the current commit you're on (`git log | head -n 1`)

**Comment by jdoliner** [comment]
Pretty sure this was just a version mismatch. Closing.
