### ISSUE TITLE
Document Pipeline build steps 

### ISSUE THREAD

**Issue by svekars** [pachyderm/pachyderm#5075]
Document #5064

**Comment by fakela** [comment]
@svekars @JoeyZwicker I would love to work on this

**Comment by JoeyZwicker** [comment]
Thats great @fakela! #5064 includes at the top pretty solid starting point for the docs. The main thing that it needs is for us to run through and test it, ask questions of @ysimonson and the document any gotchas and other little details. That makes this a not-so-tiny project unfortunately. 

If you're still up for it, you can join our public slack channel (slack.pachyderm.io) and we'd be happy to work with you there and iterate on the PR further. If it's too big of a project to do since it's a pretty complicated feature, we can work with you to find other docs issues that might be an easier place to start.

**Comment by JimmyWhitaker** [comment]
I believe this is closed with #5184
