### ISSUE TITLE
pachctl list job should show progress on a human timescale

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#5151]
**What happened?**:

A user started a job with 50K datums in it, each of which took 30-40 seconds to process, with a parallelism of 15.  With this number of datums, pachctl list job wouldn't show any progress until 3-4 hours into the running job.  Here's  a snapshot of the output at 2h in:

```
D                               PIPELINE STARTED     DURATION RESTART PROGRESS  DL UL STATE
1c6c707a8251461dbcb6ba2bb401a250 gentle   2 hours ago -        0       0 + 0 / 0 0B 0B running
```

**What you expected to happen?**:

Some progress indication should be available from list job on a normal human timescale, as opposed to the first indication of progress appearing when 10% of an arbitrarily sized job is done.

**How to reproduce it (as minimally and precisely as possible)?**:

Start a job with lots of datums and wait for the progress indicator to show some progress.  

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:
<br><br><i>(related to <a href='https://pachyderm.zendesk.com/agent/tickets/102'>Zendesk ticket #102</a>)<br>gz#102</i>

**Comment by jdoliner** [comment]
I think we should be able to set the denominator of the progress counter at the same time we create the job due to the new structure of the worker code. Updating the actual count with a higher granularity is trickier though. To clarify how this works, the progress counter gets updated when a chunk is completed, this works really nicely because at chunk completion time we need to talk to etcd anyways to mark the chunk as completed and we can do this in a single transaction. This also ensures that we don't get any weird effects like the progress going backwards when a chunk fails mid way through or going over the total number of datums. I don't think it's a good idea to change how we do progress because we had a lot of those weird effects in the past and they made progress a lot worse than slow updates do. We could increase the granularity on our chunking, I think right now it defaults to two chunks per worker, which wasn't a value that had a lot of thought going into it, so we could increase that, or maybe scale it by number of datums to get better progress results.

For monitoring a job another good tool is calling `inspect job` on it. This gives you a live view of what each worker is doing, and how long they've been doing it. I like to pass that command to watch when I'm running a job with a lot of datums.
