### ISSUE TITLE
Delete-Repo of a running pipeline which cant be deleted(pipeline)

### ISSUE THREAD

**Issue by bedekarsarvesh** [pachyderm/pachyderm#517]
Trying to delete pipe-line created repo's .. the pipeline didnt finish successfully .. Any way to force delete repo's by any shorthand flags . 
```

root@sb-HP-Pavilion-g6-Notebook-PC:/home/sb/work/src/github.com/pachyderm/pachyderm# pachctl delete-repo filter101
rpc error: code = 5 desc = remove /pach/diff/filter101/0/someID: no such file or directory
root@sb-HP-Pavilion-g6-Notebook-PC:/home/sb/work/src/github.com/pachyderm/pachyderm# 

```

**Comment by ChaiBapchya** [comment]
In my pc, 
pachctl list-repo lists all the repositories associated with GCS
When I try to delete the repo using
pachctl delete-repo <repo-name>
*No error*
pachctl list-repo - lists the repositories but the repositort still exists

This is possibly because our pipeline is running despite **deleting it**
pachctl delete-pipeline filter102
[root@chai /]# pachctl list-pipeline
NAME                INPUT               OUTPUT              STATE               
filter102           data1               filter102           starting

**Comment by jdoliner** [comment]
I've hit this bug a few times too. I think this one basically comes down to local block store issues. There's some pachd node that's assigned a shard that it wasn't assigned when the commit was finished so it doesn't have the necessary file to delete. @derekchiang's hostpath fixes should fix this issue as well.

**Comment by sjezewski** [comment]
Accounted for by refactor
