### ISSUE TITLE
why all the data is save in one folder : minio:bucker/pach/block/ ?

### ISSUE THREAD

**Issue by goodskillprogramer** [pachyderm/pachyderm#5266]
**What is the goal / desired outcome?**

**If there is a way to accomplish this today via workaround, what does that require?**

**(Optional) What is your proposal for a feature to solve this?**

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

I use minio to store the data for pachyderm . I see all the data is saved  in minio:bucker/pach/block/ folder.
If I have lots of file or update, whether these files affect the query performance? Thanks.

**Comment by JoeyZwicker** [comment]
@goodskillprogramer Users may have a number of other things in Minio other than pachyderm data and we want to keep these separate. I don't believe we've seen any meaningful performance issues come from this fact. Are you hitting performance problems of some kind, or just an open question?

**Comment by goodskillprogramer** [comment]
I dont have performance problems  now. It is just a concern, because I will do frequent update for my data .

**Comment by jdoliner** [comment]
Storing all data in one folder shouldn't have negative performance effects on modern object stores. Object stores generally do not have a concept of folders (aka directories) they kind of fake it by offering some convenience functions for objects with a common prefix ending in `/` but there's isn't a directory object that needs to be updated for each of the children. There are some exceptions to this, we've heard that Dell ECS does have a notion of directories that can lead to slowness with our current scheme. More commonly there are issues with a keys having a long common prefix, which is generally what you have with a directory. This used to be an issue with s3, but however it was recently fixed. We do have some recourse for both of these issues which is that you can turn on reversed paths which means that there won't be common prefixes or large directories. This has some other negative performance impacts around listing of objects, so I wouldn't turn it on unless you're hitting performance issues without it.

I'm going to close this issue since I don't think there's anything we plan to change based on it. As @JoeyZwicker explained there's value to keeping all of our data in a common directory that we don't want to lose. Feel free to reopen if you're experiencing performance issues you need help with, or swing by our Slack channel to chat live about them.
