### ISSUE TITLE
setting datum_tries in the pipeline spec to 0 should report an invalid value

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#5268]
**What happened?**:
I've tried setting datum_tries in the pipeline spec to 0 as I've mistaken datum_tries for datum retries.

**What you expected to happen?**:
I've expected the pipeline to not retry because this was not extremely clear in the docs. On failing, Pachyderm ran the datum 3 times which confused me further, thinking this is a bug in Pachyderm. I think adding a warning that using 0 is an invalid value for datum_tries can be useful here besides improving the docs.

**How to reproduce it (as minimally and precisely as possible)?**:
as described above.

**Anything else we need to know?**:
nope.

**Environment?**:
Pachyderm hub 1.11.3

**Comment by JimmyWhitaker** [comment]
Adding this comment here for transparency (from a slack discussion): 

From @JoeyZwicker : "The field is called datum tries (not retries) because using a value of 1 will make sure it does not try a 2nd time"

From @jdoliner : "It's a little confusing but comes from the fact that default values need to be 0 values in protobuf / golang so if the field was "retries" there'd be no way to set 0 and have a default that wasn't 0."

I'll have a PR up for the docs on this shortly.
