### ISSUE TITLE
Glob patterns ending in '/' work differently inside and outside joins

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#5365]
Via slack:
"If I run `pachctl glob file A@master:/(*)` and then pachctl glob file `A@master:/(*)/`, though, they both return the same thing, which implies that `/(*)` and `/(*)/` are equivalent."

However, when using `/(*)/` as a capture pattern to join two inputs, we see the cross of the two repos rather than the inner join.

**Comment by PFedak** [comment]
It's probably out of scope for the current PR, but I was curious about how users can debug joins. Their description of the bug was that a cross happened instead of a join, which was really a join on the empty string. It seems like both the key being the empty string and multiple data (do we say datums?) from one input having the same key could be clues to something being broken - could it make sense to validate/warn on one of these conditions, or expose some way (unless there already is one) to see the capture results, like an extra `--joinOn` argument` to glob?

**Comment by abkfenris** [comment]
I was the one who raised this in Slack.

I couldn't tell what seemed to be going on until I ran `pachctl inspect job` and saw the datums that were getting worked on and did some math to figure out where it may have got the total number of datums.

Being able to use `pachctl glob` and see just one datum instead of all files matched would help for debugging issues like this. 

Possibly something like `pachctl glob file --random-datum "iccat_by_date@master:/(*)/:$1" "hycom_sst@master:/(*)/:$1"` for debugging joins.

**Comment by JoeyZwicker** [comment]
@jdoliner I believe you and I discussed expanding `list datum` to include functionality like what @abkfenris is talking about above. Not sure if this would replace glob completely or not.  I see a note in #3709, but don't see any issue/rfc that came from it.
