### ISSUE TITLE
Force a pipeline to standy

### ISSUE THREAD

**Issue by panfeng-hover** [pachyderm/pachyderm#5472]
As said in [standby pipeline not removed after run](https://github.com/pachyderm/pachyderm/issues/4371), the old `pachctl` version's `standby` might not work.

I cannot re-deploy the pachyderm, I am wondering is there any easy way to force the pipeline state to `standby` instead of `running` after finishing the job.

**Comment by panfeng-hover** [comment]
The `pachctl delete pipeline --keep-repo <pipeline>` would still delete the repo with flag `--keep-repo`.

**Comment by mindthevirt** [comment]
Hey @panfeng-hover could you give us some details of what version of pachd and pachctl you're running? The output of `pachctl version` will provide both. The latest 1.11.7 is now known to have any standby issues.

**Comment by panfeng-hover** [comment]
Hi @mindthevirt 

```
$ pachctl version
COMPONENT           VERSION
pachctl             1.11.7
pachd               1.9.12
```

I cannot update my `pachd` version as I am not able to delete and redeploy the pachyderm.

In order to let the finished pipelines not occupy any resourses, I also tried `pachctl delete pipeline --keep-repo <pipeline>`, but which results in my repo got deleted too.

**Comment by mindthevirt** [comment]
I'm not sure if 1.9.12 has `pachctl extract` yet. This would allow you to back up everything including your commits, files etc.. Then you could restore it on a later version. However, I'm not sure if this will work since your version of pachd is fairly old. If you try the above and it doesn't work, then I'll need to see if our engineering team may have an idea.

**Comment by JoeyZwicker** [comment]
Hi @panfeng-hover. A few things to note:

1. using mismatched pachtl and pachd version, particularly across different minor releases is not recommended.
2. the keep-repo flag didn't exist in 1.9.12 which is why it's not working for you. 
3. I think you can use `stop pipeline` to have pachd spin down all the resources for the given pipeline. This puts your pipeline in a paused state where it wont trigger any new jobs. You'll need to use `start pipeline` again to turn it back on when a new job needs to trigger.
4. 
> It costs too much for me to re-deploy the pachyderm

Can you describe this further? Costs too much in terms of time and effort? There shouldn't be any major $$ cost with upgrading. Upgrading does not lose your data or make your pipeline reprocess much work.

**Comment by panfeng-hover** [comment]
Hi @JoeyZwicker Thanks for your reply! Yeah, I think the best choice here is to upgrade the pachd.

**Comment by JoeyZwicker** [comment]
@panfeng-hover I think stop pipeline will change it to `stopped` or `paused` not standby. It wouldn't be doing the same thing as standby at all -- but would give you a short term workaround to spin down the unused resources. 

Do you still plan to upgrade to 1.11.x? That would still be our strong recommendation and we can help you with the upgrade process if you need. It should not require a complex migration, but there are a few steps to make sure all the manifests are updated correctly. Please let us know if we can offer some office hours and set up a call to discuss.

**Comment by mindthevirt** [comment]
Just following up on here. Did you happen to upgrade and did this resolve this issue?

**Comment by panfeng-hover** [comment]
@mindthevirt Thanks for your follow-up, I upgraded the `pachd` to 1.11 and it is solved now.
