### ISSUE TITLE
Expose  join_on and group_by match to the pipeline's job 

### ISSUE THREAD

**Issue by nadegepepin** [pachyderm/pachyderm#5546]
**What is the goal / desired outcome?**
Direct access to the captured join or group in the execution of the pipeline's job. 

**If there is a way to accomplish this today via workaround, what does that require?**
[In the group example](https://github.com/pachyderm/pachyderm/blob/master/examples/group/lab_group_by_hospital.json), we want to create a directory for each group. The workaround involves parsing the file names from each datum, using the same regex as the glob expression.

**(Optional) What is your proposal for a feature to solve this?**
The value could be exposed as an environment variable.

**Comment by JimmyWhitaker** [comment]
I definitely agree that we need something here - a non-trivial portion of my time is spent debugging pipeline inputs, usually through regular expressions or walking the file tree. These can not only have performance impacts, but can also introduce very low-level bugs if the parsing is done in a questionable way. 

Here are a couple of ideas I've heard discussed or considered: 

1. **Environment variable** inside the container that has the datums from `/pfs`. 
2. **Client library** standardizing and optimizing common read patterns. This is pretty heavy weight in the realm of support. Much of the time, I am walking the file system to understand the data that's been provided since I want my code to be loosely coupled to Pachyderm to decrease duplication and make it easier to test locally. For [example](https://github.com/JimmyWhitaker/videoproc/blob/master/extract_frames.py#L159-L165). Having a python library or api that provides this basic functionality could be useful. 
3. Having the **pipeline spec support mapping** the inputs to specific locations or file paths, much like being able to name the input differently from the repo name.

**Comment by RaananHadar** [comment]
Just to expand on this interesting but non-trivial feature... 
I think this enables some really powerful behavior when exposing **multiple capture groups**. 

To give an example, suppose you perform a group_by, by using one capture group and following with another capture group as an argument to the transform. For example, look at this mock pipeline spec:
```
 {
   "pipeline": {
     "name": "group"
   },
   "input": {
     "group": [
      {
        "pfs": {
          "repo": "labresults",
          "branch": "master",
          "glob": "/(*)-(*)-lab*.txt",
          "group_by": "$2"
        }
      }
    ]
  },
   "transform": {
      "cmd": [ "bash" ],
      "stdin": [ "python main.py /pfs/labresults $1" ]
      }
  }
 }
```
You can really simplify pipeline development and readability by exposing additional capture groups and using them as arguments. This has an interesting property: similar to how Pachyderm abstracts away getting the data to the transform, it makes it extra easy to abstract away parsing the metadata and allowing the developer to write code that focuses on the transform and less on parsing metadata. Overall this makes easier development with Pachyderm.
