### ISSUE TITLE
job ids not unique

### ISSUE THREAD

**Issue by JonathanFraser** [pachyderm/pachyderm#580]
if some one creates a pipeline, then deletes that pipeline and it's output repo and then creates a new pipeline with the same name but different manifest, the output job IDs are the same as with the original pipeline. This is a problem as get-logs keeps pointing at the old jobs.

**Comment by jdoliner** [comment]
Hey @JonathanFraser sorry you ran into this there's what's going on:
Job ID's for pipelines are generated in a deterministic way, this is convenient because it makes job creation idempotent which means that we can service pipelines in a distributed setting without having to worry about some of the nastier corner cases that pop up. Unfortunately the IDs are created by hashing the pipeline name, transform and input commits which means if you recreate the pipeline it creates jobs with the same name. I can think of a few of ways that we can solve this:

1. just use unique job ids and handle corner cases
2. delete pods when we delete a job
3. change how we compute job ids for pipelines so that it'll be unique across different runs of the pipeline

I'm leaning toward 2 since it seems like it's the easiest to write and it feels clean that deleting a pipeline deletes of the objects that it created.

**Comment by JonathanFraser** [comment]
So in this instance I was changing the container image each run, I suspect it would have been find if that was also included in the job id.

**Comment by jdoliner** [comment]
Fixed via #584.
