### ISSUE TITLE
job-shim should come with common build environments

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#592]
Currently, for a custom Docker image to run on Pachyderm, it has to inherit from job-shim.  However, job-shim is basically just a thin wrapper around vanilla Ubuntu 14.04.  Therefore, to put a custom binary into the Docker image, the user has to:
1. Either compile the binary somewhere else and add it to the Docker image, while having to ensure that the binary is binary-compatible with Ubuntu 14.04,
2. Or compile the binary in job-shim.

But the problem with 2 is that job-shim doesn't come with common build tools.  So the user has to install the tools herself, which is annoying.  So I thought it'd be nice if job-shim comes with common build environments such as those for Go, C, Java, etc.

An alternative (and probably better) solution is to make it easy to add job-shim the binary to a custom Docker image.  After all, all we need in a custom image is job-shim the binary and FUSE support.  For instance, we can ask the user to add:

``` Dockerfile
RUN go get github.com/pachyderm/pachyderm/src/server/cmd/job-shim
```

to their Dockerfile.

**Comment by jdoliner** [comment]
The file `etc/user-job/Dockerfile` is meant to document what a user needs to add to their container to make it work with the job-shim. It's definitely a lot more verbose than we would like though.

Probably the best solution to this problem is to figure out how to separate the job-shim code and the user code into separate containers. I'm not sure kuberenetes has all the features we need yet. But I think it's getting close.

**Comment by derekchiang** [comment]
@jdoliner Interesting.  I was not aware that `etc/user-job/Dockerfile` exists.  We should probably refer to it somewhere in our documentation.

**Comment by jdoliner** [comment]
> We should probably refer to it somewhere in our documentation.

That seems like a very sound idea.
