### ISSUE TITLE
2.0.0-alpha.10 - Auth - `pachctl auth deactivate` then reactivate leaves cluster in inconsistent state

### ISSUE THREAD

**Issue by nadegepepin** [pachyderm/pachyderm#5929]
**What happened?**:
$ **pachctl auth  deactivate**
Are you sure you want to delete ALL auth information (ACLs, tokens, and admins) in this cluster, and expose ALL data? yN
y
$ **pachctl auth activate**
WARNING: DO NOT LOSE THE AUTH TOKEN BELOW. STORE IT SECURELY FOR THE LIFE OF THE CLUSTER.THIS TOKEN WILL ALWAYS HAVE ADMIN ACCESS TO FIX THE CLUSTER CONFIGURATION.
Pachyderm root token:
b508ba28d01345af8137049bc473506e
**failed to configure OIDC client ID: OIDC client with id "pachd" already exists**

It looks like the `pachctl auth deactivate` did not clean the auth properly.

**Comment by actgardner** [comment]
The issue here is that "auth" and "identity" are two separate services, and disabling auth doesn't delete all the data from the identity service. So the pachd OIDC client continues to exist after auth is disabled and re-enabled.

I think the right behaviour here is to delete everything from the identity server when auth is disabled.
