### ISSUE TITLE
Job Failure commit data exposed via the mount

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#615]
Reported via @dwhitena 

He has a [pipeline](https://github.com/dwhitena/gofordatascience/blob/master/pipelines/pipeline.json) he's running and the `compile16` step is marked as failure:

```shell
dwhitena@dirac:gofordatascience$ pachctl list-job
ID                                 OUTPUT                                       STARTED             DURATION            STATE               
6ae3c275a6e957ac7bc972be34d6ec6a   compile16/e4949b2057a343fd896dd5c1d59f0621   29 minutes ago      6 minutes           failure    
735ea3b47af3ea7aa3d73f78da6493c3   filter/af8fe4c650564006a57bad449a80ddd4      30 minutes ago      24 seconds          success    
```

You can see the `e4949b2057a343fd896dd5c1d59f0621` commit when listing the commits for `compile16` w the all flag set (and not otherwise). So the commit is definitely flagged as a cancelled commit.

However, the data is exposed via the mount:

```shell
dwhitena@dirac:gofordatascience$ ls /tmp/pfs/compile16/e4949b2057a343fd896dd5c1d59f0621/*
/tmp/pfs/compile16/e4949b2057a343fd896dd5c1d59f0621/0
/tmp/pfs/compile16/e4949b2057a343fd896dd5c1d59f0621/1
/tmp/pfs/compile16/e4949b2057a343fd896dd5c1d59f0621/10
/tmp/pfs/compile16/e4949b2057a343fd896dd5c1d59f0621/11
/tmp/pfs/compile16/e4949b2057a343fd896dd5c1d59f0621/12
/tmp/pfs/compile16/e4949b2057a343fd896dd5c1d59f0621/13
...
```

This is true even after unmounting and remounting.

While we've discussed exposing cancelled commit data via the mount (and perhaps by default), I don't think this is the expected behavior of the [current code](https://github.com/pachyderm/pachyderm/blob/master/src/server/pfs/fuse/filesystem.go#L628) ... (the fuse FS never calls list commit w anything but `false` for the `all` argument)

**Comment by jdoliner** [comment]
Possible fixes I could see for this:

1. show cancelled commits by default, this is the easiest solution the downside is that users may not realize the commit is cancelled
2. mark the commits as cancelled somehow (maybe by prepending `cancelled_` to the front
3. add a flag to `mount`, maybe `mount -a` which would include the cancelled commits

Of these I think I like 1 the best since it's simplest and users have other ways to know that the commit was cancelled. In most cases we've seen people seem to be mounting to view a specific commit that they already know about from `list-commit` so they'll know it was cancelled.
