### ISSUE TITLE
Permission issues with directories copied from /pfs

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#643]
## Steps to reproduce
1. Mount PFS as a normal user: `pachctl mount ./mount`
2. Copy a commit directory to somewhere: `cp -r ./mount/test/06fe02bf248343bdae794a93e399d58c/ ~/Desktop`
3. Remove the copied directory: `rm -rf ~/Desktop/06fe02bf248343bdae794a93e399d58c`

You should see a `Permission denied` error.
## Expected result

No `Permission denied` error.

**Comment by jdoliner** [comment]
Oh interesting, this is probably because we mark the directories as read only right?
Assuming that's true I'm not sure what we should do about this. Marking the directories as read-only makes sense while they're under the mount since you actually can't write / delete them. I didn't realize that would be carried over with cp though.

**Comment by jdoliner** [comment]
Closing this since I don't think there's much we can do here, marking mounted files as read only seems correct, since they are read only and attempts to perform writes on them will fail. But this necessarily means that when they're copied they take those permissions with them, so users will have to change the permissions if they want to copy them and modify them. I think this is fine for what should be a pretty rare use case, in general if you want to copy data out of pfs into a file structure then `get file --recursive` is a better way to do it that won't have these issues.
