### ISSUE TITLE
pachd enters a temporary crashloopbackoff

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#6510]
**What happened?**:
When deploying the Pachyderm 2 beta, it seems like pachd does not wait for postgres pod to start. This results in pachd entering a crashloopbackoff state. Once the other pods are up, pachd starts normally. But it restarted multiple times before coming up.

**What you expected to happen?**:
pachd should wait for the other pods to start and only fail if they don't start.

**How to reproduce it (as minimally and precisely as possible)?**:
deploy the beta.

**Environment?**:
- Kubernetes version (use `kubectl version`):
AKS 1.20.7
- Pachyderm CLI and pachd server version (use `pachctl version`):
Pachyderm 2.0.0 beta1
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
Azure

[AB#26](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/26)

**Comment by mindthevirt** [comment]
Did you deploy via Helm or via pachctl deploy @RaananHadar ?

**Comment by RaananHadar** [comment]
pachctl

**Comment by jrockway** [comment]
I think helm will have the same issue.  Postgres takes longer to start than pachd, so it's not going to be ready when pachd tries to connect.  It will then back off to wait for postgres to be ready.  That's kind of the kubernetes way -- you apply the manifests and it eventually becomes consistent.

@chainlink agrees that the backoff is a bad experience here.  For local deployment, the latency introduced by waiting for pachd to awake from the crash loop is annoying.  I would be inclined to handle this at the pachd level -- add an environment variable WAIT_FOR_POSTGRES, set it only for local deployments, and then try to connect to the database in a loop.  (You want the crash in production -- you're probably using your cloud provider's managed Postgres, and you want to be alerted to misconfigurations as soon as possible.  I think a crash at startup is better than being stuck in an infinite loop because you mistyped the name of the database server in your configuration.)

**Comment by chainlink** [comment]
I think I've come up with a good compromise here: In cases where we deploy our own PG, we can add the init check via helm, if PG is disabled (ie external postgres in use) we can disable the corresponding init check and let pachd crash if that DB isn't around.

**Comment by nitinjainsj** [comment]
@chainlink Who is implementing the compromise?

**Comment by chainlink** [comment]
it's on my plate

**Comment by chainlink** [comment]
Implementation note: This should consider PG bouncer as well
