### ISSUE TITLE
Improve Message When Repo Not Found

### ISSUE THREAD

**Issue by dgeorg42** [pachyderm/pachyderm#6544]
If I try to create a pipeline when the input repo does not exist, I get a message like the following:

`repos test.user not found`

First, it should be "repo" not "repos".  Second, including the ".user" as part of the repo name will be confusing to customers because it implies that they need to explicitly create a repo a called "test.user", which isn't the case. (And if they do try to create "test.user" they (correctly) get an error message saying that "test.user" isn't a valid repo name, and that will only contribute even more to their confusion.) Third, we should provide simple guidance to the customer on what they actually need to do to fix the issue.

I would suggest re-wording the message as follows:

`ERROR: The input repo "test" required by this pipeline does not exist. Please run "pachctl create repo test" to create it before you create the pipeline.`

Even better would be if we just created the repo if it didn't already exist. ;)

**Comment by jdoliner** [comment]
This seems fairly easy to improve. I'm assuming the error message is plural because it can return multiple repos. In which case I think it's fine to do the easy thing and just change the message to "repo(s)". Agree with @dgeorg42  about the rest of the message.

I'm a little less sure about creating the repo if it doesn't exist, we do that for branches which I think makes sense. But with a repo if they were to typo the name of a repo that would create a repo with that typoed named and not have any input. Which might be confusing. Theoretically the same thing can happen with a branch but since that's mostly used for the `master` branch that doesn't exist yet I think it makes sense overall.

@acohen4 giving this one to you since you're oncall this week.

**Comment by PFedak** [comment]
It's actually plural because we print out the collection name, I don't think we support multiple repos in that error. Also just to double check, what version was this on? We shouldn't be showing `.user` suffixes anywhere anymore.

**Comment by dgeorg42** [comment]
@PFedak - I originally saw this on Beta 1, but the behavior is the same in Beta 2.
