### ISSUE TITLE
Document how to send pachd traffic through an HTTP load balancer

### ISSUE THREAD

**Issue by jrockway** [pachyderm/pachyderm#6574]
Something that is potentially confusing is that, by default, we configure pachd to listen on a LoadBalancer, and auth and dash to listen with an Ingress rule.  I get the feeling that people would like pachd's grpc traffic to go through their HTTP load balancer, so they can just run it on port 443 and multiplex by hostname.  This workflow is well-supported by many Ingress Controller implementations, and by HTTP proxies in general, but it's not how we currently set it up in Helm.

To set this up, we probably have to know the ingress controller by name, and generate a configuration specific to that ingress controller.  Worth looking into are ingress-nginx, nginx-ingress (a different project!), Traefik, Ambassador, Contour, AWS ALB, GCP HTTP Load Balancer, and the Azure Application Gateway.  Obviously writing the same configuration 8 times is a pain, but that's the state of Kubernetes ingress.

(Personally, I don't use or recommend Ingress controllers, but the world ignores my opinion there.  I just have an Envoy configuration that does exactly what I want, and it handles gRPC just fine.  I have heard in the past that Envoy breaks Pachyderm, but I honestly don't believe it.  We don't abuse the protocol in any way, and it's designed to work with gRPC.)

**Comment by jrockway** [comment]
While I'm here, something I've been thinking about is just running all the services (pachd, console) in one pod, and having a sidecar that handles all the URL rewriting and sending requests to the right backend.  I use that pattern a lot when I have a setup that involves a frontend and a backend.  I run the frontend, backend, and envoy in the same k8s pod; envoy accepts requests to both containers on one port and routes them to the right place; then you just have one http port that you expose to the ingress controller or load balancer, and things work without any k8s-Ingress-level configuration.  Example: https://github.com/jrockway/jrock.us/blob/master/production/jsso2/envoy.yaml (and the deployment https://github.com/jrockway/jrock.us/blob/master/production/jsso2/deployment.yaml)

**Comment by chainlink** [comment]
Using a load balancer for GRPC is more of a historical remnant since we've never really gotten grpc to play nicely with any reverse proxy we've thrown at it. IIRC envoy (via istio) cached requests, which is sensible for most http requests, but definitely got real sad with a large put file. This is configurable I imagine, but given the configuration surface of istio/envoy we chose to simply move away from it at the time.

Using two ports (and potentially two load balancers) definitely isn't ideal, but I'd like to collect more data on client setups before making a call here (Do they have an existing ingress controller at all? which one? etc) Using ingress as we are now in a vanilla fashion (host/path based routing) should be compatible with ingress controllers that confirm to the default spec.

I do like the elegance of adding our own proxy solution, but this should be balanced against the complexity of adding another component we need to support. Traditionally this would have gotten built into pach (ie. dex) but that's another discussion entirely.

We also need to consider existing services on a given cluster. ie if Istio exists on a customer cluster (a seemingly popular requirement for other data science products) our bespoke envoy configuration needs to work in concert with that.

Not trying to throw up a ton of roadblocks here, but I hope this context is helpful for the discussion. I agree our ingress (as in getting traffic into pach, not kubernetes ingress) story definitely needs work.
