### ISSUE TITLE
Restructure Docs

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#676]
@sjezewski  When we recently moved around the docs stuff — all (or most of) the links on GH broke. I've been thinking about reorganizing them a little too as I've been collecting feedback from users and have a few ideas. 

Let's talk about this in person too because you'll have to show me how to get it all working with readthedocs. 

Notes to self:
- See Ang Li email questions (and other dev@ user questions/responses)

**Comment by sjezewski** [comment]
Fixing #670 will make most of this better. The confusing thing is viewing the docs on GH - those docs won't work. So we need to remove the readme under `/docs` so that people don't do that. We should probably update the readme under docs to point users at read the docs. 

So, I'm going to re-appropriate the title from "Broken links on GH docs" to "Restructure Docs". I'm sure they could use more organization :-)

**Comment by dwhitena** [comment]
Already restructured.  New structure and updates tracked here: https://github.com/pachyderm/pachyderm/issues/1869
