### ISSUE TITLE
Pipeline reads from spout can't list dirs in spout repo 

### ISSUE THREAD

**Issue by oosugi84** [pachyderm/pachyderm#6792]
**What happened?**:
Hi, right now I have 3 pipelines which is like       
MQ　-------->　Spout　------------------------->　pipeline A     
　　　　　　`/2021-08-25/sourceA/*.png`
　　　　　　`/2021-08-25/sourceB/*.png`
　　　　　　`/2021-08-24/sourceA/*.png`
　　　　　　`/2021-08-24/sourceB/*.png`

Spout saves MQ data to repo every day, the dir is like above. The spout and pipeline A is modified from spout101 example.
Pipeline A's config is:     
```
{
    "pipeline": {
      "name": "comparer"
    },
    "description": "compare snapshots",
    "input": {
      "pfs": {
        "glob": "/*",
        "repo": "spout"
      }
    },
    "transform": {
      "cmd": [ "python", "/usr/src/app/compare.py" ],
      "image": "harbor.base.dc/comparer:latest"
    }
}
```
I can see the files spout had saved to the repo.
```
context:(local) >>> list file spout@master
NAME             TYPE SIZE     
/2021-08-24 dir  386.7KiB 
/2021-08-25 dir  390.3KiB 
```
```
context:(local) >>> list file spout@master:/2021-08-25/5626245945cedb339863d513
NAME                                                    TYPE SIZE     
/2021-08-25/5626245945cedb339863d513/avatar.png  file 79.35KiB 
```

But when I use `os.listdir` in pipelineA, it just list the last committed dir.
```
if __name__ == '__main__':
    dirs = os.listdir('/pfs/spout')
    print('list dirs:')
    print(dirs)
```
The output is:    
```
list dirs:
['2021-08-24']
list dirs:
['2021-08-25']
```
And I can't get into the dir using `os.walk`. When I tried to `os.listdir('/pfs/spout/2021-08-24')`
The program raised an exception
`FileNotFoundError: [Errno 2] No such file or directory: '/pfs/spout/2021-08-24'`
**What you expected to happen?**:
1. List the previous output dirs.
2. Can get into the output path.

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.21.2
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.13.4
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- If you deployed with helm, the values you used (`helm get values pachyderm`):
- OS (e.g. from /etc/os-release):
- Others:

[AB#122](https://dev.azure.com/PachydermCompany/92b98a32-88e5-46cb-a28f-5d064712e03b/_workitems/edit/122)

**Comment by PFedak** [comment]
The behavior you are seeing is intentional, due to the way that pachyderm handles datums. The glob specification you chose for `pipelineA`, `/*`, means that each new folder is a single datum. While a worker for `pipelineA` is processing a datum, only the files for that datum are present, which in your case means only the latest folder.

The right way to structure this depends a lot on what exactly you want `pipelineA` to do. It's possible you just want to use `/` as a glob pattern, which will include every file. It's worth keeping in mind that pachyderm expects pipeline outputs to be functions only of their inputs, so if you go this route you may need to write pipelineA's logic so that it outputs the same data produced earlier as well as the new values.

If you have a more involved use case, it's probably best to reach out in our [public slack channel](https://www.pachyderm.com/slack/).
