### ISSUE TITLE
Robust pipeline error detection

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#762]
Currently, when something goes wrong in a pod, we rely on the pod itself to report that it has failed, at which point we mark the job as failed as well.  However, if a pod for whatever reason fails to contact PPS, we don't have any mechanism in place that would proactively check on the pod, so the job will just forever be stuck in the "RUNNING" state, even though it's not actually making progress.

**Comment by jdoliner** [comment]
Here's a proposal for how to fix this and probably a few other issues with job execution.
Right now the way a job gets executed is that we create a k8s job, which in term creates a set of workers running the user's code. These workers each make a call to `StartJob` which gives them back some work to do (input data to mount and a cmd to run), when the cmd finishes they call `FinishJob` and report success or failure. If any of them fail we report the job as failed. Instead of this model I think we should start think in terms of leases, that is when we give a pod some data to work on we can at a later point declare that pod as failed, take back the work and give it to another pod. Here's a sketch of the implementation:

Pod:
- On startup pods behave much the same, they boot up, they call `StartJob` and pachd responds with some work to do, at this point the work has been leased to the pod.
- Unlike the current implementation, while the pod is running it sends periodic heartbeats to pachd so it knows the work is still being done. Let's call those `ContinueJob`.
- The response to `ContinueJob` will normally be empty which means the pod should keep doing what it's doing.
- The response to `ContinueJob` might contain a new lease, in which case the pod abandons its old lease and starts working on the new one.
- When the pod finishes a piece of work it still calls `FinishJob`. The response will either contain a new lease, in which case it starts processing it, or be empty in which case the pod exits with return code 0.

Server:
- The server now needs to keep track of the leases that it has handed out and who's currently working on them.
- If a pod hasn't pulsed us with `ContinueJob` for too long then we reclaim the lease and give it to the next available pod.

I think this will give us a good way to solve a few other issues we've had. For example straggler detection: In this system straggler detection, from the perspective of the server, looks like a single pod that's still processing (sending `ContinueJob`s) while all the other pods have called `FinishJob`. We could solve it by timing out a lease when it's been running for too long and splitting the work between the idle pods.
