### ISSUE TITLE
JSON logging

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#775]
Make a helper to unmarshal objects into JSON. We do this so often. Should be easy.

**Comment by sjezewski** [comment]
Would also be helpful for nested objects in logs:

```
2016-09-01T23:18:56Z INFO  protorpclog.Call 
{
    "duration": "0.000s",
    "method": "CreatePipeline",
    "request": "pipeline:<name:\"pipeline22893edd24b05\" > transform:<cmd:\"cp\" cmd:\"/pfs/pipelinea160108d7723/file\" cmd:\"/pfs/out/file\" > parallelism:1 inputs:<repo:<name:\"pipelinea160108d7723\" > > ",
    "service": "pachyderm.ppsclient.API"
}
```

**Comment by jdoliner** [comment]
I don't think there's a ton of value in doing this, our workers output logs in a json format that can be parsed and filter using `pachctl logs`. We don't have a compelling reason to do this for pachd logs, since they're mostly just mean to be consumed as text. Closing, feel free to open if you have a need for this.
