### ISSUE TITLE
Prefetch job input data

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#777]
Discussed offline with @msteffen and @JoeyZwicker .

Currently, jobs read data lazily.  That is, a file is not actually downloaded to the machine on which the job runs, until the job attempts to read that file.  This makes sense because given a job and a set of input files, we don't actually know which subset of the input files the job will actually need to read over the course of its execution.  For instance, if we have a 1TB dataset and the job only needs to read one file, it'd be really dumb to download the entire dataset to the machine.

On the other hand, there is a large class of jobs that do need to read all or most of its input data, so it might make sense for there to be a way to prefetch these data before the job actually reads them.  To see the benefit of prefetching input data, consider this execution pattern:
1. Read (download) a small file.
2. Do a long computation.
3. Read (download) a huge file.
4. Do another computation.

If we don't prefetch input data, then the total execution time will be the sum of all these individual steps.  If we do prefetch input data, however, step 2 and 3 can be done in parallel (i.e. we'd be downloading the huge file when the long computation is running), therefore reducing the total execution time of this job.

The most obvious way to expose this functionality would be to have a `prefetch` flag in the pipeline spec.  So if you know that your pipeline will need to read all or most of the input data, then you might want to set the `prefetch` flag to true to enable the optimization.

**Comment by jdoliner** [comment]
Definitely like this idea. Here's how I'd imagine implementing this.

Step 1, add a cache to our fuse implementation. It should be able to cache actual files (the results of `GetFile`) and also the results of meta queries (`ListFile` et al). The latter is probably much more important since reading a file normally requires several meta ops followed by a single `GetFile`.

Step 2, make it so that the fuse layer proactively tries to fill the cache using whatever information it has handy to try to fill it with things the user is likely to request next. A couple of thoughts on this algorithm.

- I'd prefer not to have a `prefetch` flag if we can avoid it but instead make this happen transparently for users. I'm worried about having too many performance nobs for users to turn making it too confusing. In this case I think an oblivious algorithm should work really well if it follows the simple rule that as long as the job is still running, the cache isn't and there's data the job could read that isn't cached it should attempt to read whatever data it thinks the job is likely to need in the future. If the job winds up finishing without needing that data then we wasted some bandwidth and memory which seems fine.

- Likely this algorithm should start by requesting all of the meta ops, listing out all the files in the commits the job is processing since those add a lot of round trips. Actually it would be even better if we could start computing this information in `CreateJob` and have it ready for the worker pods once they come online.

**Comment by derekchiang** [comment]
Another thought on this.  If we ever decide to prefetch all input data for a given job, then we don't even need FUSE anymore.  `/pfs` can just be a normal file system.  We can skip a lot of overhead/bugs that way.

**Comment by jdoliner** [comment]
Jobs now download, process and upload data concurrently. Some of the details in this issue have changed but as much as is makes sense in the current system, this is implemented.
