### ISSUE TITLE
The speculation about the performance bottleneck

### ISSUE THREAD

**Issue by ShengjieLuo** [pachyderm/pachyderm#780]
## Possible reason for performance bottleneck

Please refer to #755 #701. These two issues have did a performance test about Pachyderm. To explain the bottleneck , I have read the source code and give some speculations about it. This discussion use the `wordcount-reduce` in `wordcount` example as the test object.

![image](https://cloud.githubusercontent.com/assets/20234415/18240612/6314819a-737f-11e6-808d-8d725220bb17.png)
## Procedure Analysis about the Pachyderm Code

To certify the last reason,  I analyze the procedure of Pachyderm.
![image](https://cloud.githubusercontent.com/assets/20234415/18240655/a706f176-737f-11e6-8a28-98a47a02dd5c.png)
![image](https://cloud.githubusercontent.com/assets/20234415/18240707/f5c6987a-737f-11e6-8268-171d4809485b.png)
![image](https://cloud.githubusercontent.com/assets/20234415/18240715/0308ae10-7380-11e6-9c02-96456710c2a5.png)
## Is FUSE the bottleneck?

After the analysis, I speculate the file operation as the performance bottleneck. The file operation is based on FUSE system according to the source code. See the following code to verify it.

```
#src/server/cmd/job-shim/main.go
#mount the file system
mounter := fuse.NewMounter(appEnv.PachydermAddress, c.PfsAPIClient)
go func() {
    if err := mounter.MountAndCreate(
        "/pfs",
        nil,
        response.CommitMounts,
        ready,
        response.Transform.Debug,
    ); err != nil {
        errCh <- err
    }
}()
... ...
#execute the command given to the image
cmd := exec.Command(response.Transform.Cmd[0], response.Transform.Cmd[1:]...)
cmd.Stdin = io.MultiReader(readers...)
cmd.Stdout = os.Stdout
cmd.Stderr = os.Stderr
success := true
if err := cmd.Run(); 
          ... ...
```

If my speculation is correct, FUSE is a remote file system and the actual data file is stored in the docker `Pachd` as a data volume. The bottleneck can be attributed that the data storage locate in the `pachd` container (I call it center container). The pipeline docker get the data file from the center container and write the revised data back into the center container. This kind of data transportation and file operation lead to the low performance in the test.
![image](https://cloud.githubusercontent.com/assets/20234415/18241306/f2b8ef54-7382-11e6-9d38-08bb560be39c.png)
## Possible FUSE structure

Then I think the FUSE mechanism would be one of the following two plan.
![image](https://cloud.githubusercontent.com/assets/20234415/18241187/6398517a-7382-11e6-9a37-51fea6c9c595.png)
![image](https://cloud.githubusercontent.com/assets/20234415/18241205/76cb388e-7382-11e6-9397-d9b356224c94.png)

**Comment by ChaiBapchya** [comment]
Having gone through this detailed analysis of possible performance issue, I, as a user of Pachyderm, understand that Question is being raised not about FUSE file system per se
But the implementation of FUSE with the Unconventional I/O mechanism in Pachyderm File System
Of the 2 suggested plans, from Network security and feasibility POV, I believe Plan B shouldn't be the encouraged one due to Remote R/W. Instead the 3 tier structure seems more realistic. 
@ShengjieLuo Even I agree there exists a need to better understand Pachyderm implementation from the creators/contributors/users

**Comment by jdoliner** [comment]
I think you guys are almost certainly right that the bottle neck is the fuse filesystem layer (and all the stuff behind it). It'd be hard for it to be anything else since the only other thing is the process running in a container which I'm pretty confident shouldn't be any slower than in your tests. #777 should do a lot to ameliorate this.

**Comment by derekchiang** [comment]
@ShengjieLuo currently Plan B is how it is.  Every read/write involves a roundtrip over the network.  See #777 for some ideas about how we might optimize this.

**Comment by sjezewski** [comment]
Thanks for the detailed debugging.

FUSE has been ripped out of PPS, and the job processing model has been updated in 1.4
