### ISSUE TITLE
Process data with a rolling time window and cumulatively collect downstream data

### ISSUE THREAD

**Issue by willguxy** [pachyderm/pachyderm#809]
Hi I understand that creating a pipeline with `"incremental": false` allows the job to see all data files, then the output should be a parentless commit because conceptually this job keeps doing the same thing to the whole data set. 

But what if the job actually does some calculation with a rolling time window? which means it's supposed to have access to the whole data history but the output should also be collected in a cumulative way. In this case, a commit with parent id would be more appropriate.

Any suggestions on how to tackle this problem? Thank you in advance.

**Comment by ShengjieLuo** [comment]
@willguxy I am not sure whether I understand your problems. Do you mean that you need the pipeline pods to deal with whole data, and then, add the results to one old repo? If you do this, you would get duplication data. Please give me an example about this issue to help me understand it. Thanks.

**Comment by willguxy** [comment]
@ShengjieLuo Thanks for your prompt reply and sorry for the confusion. To your question, yes and conceptually I could get duplicated data, but not necessarily. One simple example would be a job that takes the whole data set and compute the average when new data comes in. So the ideal output would be a time series consisting of timestamps and average up to each timestamp.

**Comment by jdoliner** [comment]
This is an interesting question that will probably require extending our pipeline semantics a bit to support. There are a few things I'd like some clarification on so I can better understand the use case.

- You mention that to compute a rolling time window you'd want to have access to the whole data history, this would mean that the job logic would have to filter out some of the data that it's shown right? Would it possibly be simpler if pachyderm only showed the job data that's part of the sliding window?
- You mention wanting output commits from successive runs of the sliding window computation to be parented on each other. Parenting makes sense for datasets that are built incrementally. That is if results from the first run of the job could still be relevant output for the 10th run of the job. Is that true of sliding window computations? My impression was that the output of each run is distinct since it considers a distinct "slice" of the input?

**Comment by willguxy** [comment]
@jdoliner First of all, thanks for being so active in reposing to questions and issues.

Re your question,
- My original thought was about some data transformation with a sliding time window, but in my example to @ShengjieLuo, I mentioned using the whole data history. I guess essentially the problem is similar, except the sliding window case has this extra layer of complexity if the requirement is for pachyderm to only show the job data that's part of the sliding window. In summary, the base case is access to the whole data history (although just exposing the data of certain time window would be more efficient in reading and writing files).

- I think the outputs are relevant in the sense that they are results of the same data transformation method and are somewhat convoluted. Say computing the average stock price with 1 month lookback window everyday with new intraday data coming in. The output series is consistent and does not contain duplicates. So I don't know if it makes sense make output data commit isolated/parentless.

I'm not sure how much this would affect the implementation though. So more of a conceptual discussion here rather than request a feature :)

**Comment by sjezewski** [comment]
@JoeyZwicker discussed this very issue today. There are some good methods for this in v1.4

We opened an issue about this here: https://github.com/pachyderm/pachyderm/issues/1558
