### ISSUE TITLE
Best practice for structuring projects

### ISSUE THREAD

**Issue by rexmortus** [pachyderm/pachyderm#811]
Thanks for your hard work, everyone!

In the fruit stand example, we create a pipeline by pulling in a JSON configuration file from the examples folder with the `-f` flag. :ok: 

However, in a real setting, where is the recommended place to store these pipeline configurations? Should they be under version control?

Any advice about how you structure your `pachyderm` projects?

**Comment by jdoliner** [comment]
Storing them under version control is definitely a good pattern, that was a big part of our rational for having a simple text format for pipelines. I like to structure things like this:

```
project/
   pipeline.json # pipeline file
   Dockerfile
   <other things the Dockerfile uses>
```

If I need more than one docker image I put each of them in top level directories.

**Comment by rexmortus** [comment]
Thanks @jdoliner.

I'm not sure I fully understand.

What does `/project` correspond to? A git repository?

If yes, where would you subsequently mount the pachyderm filesystem?

So for example, if I have a project like this:

```
/project
   pipeline.json
   Dockerfile
```

Where would you mount the pachyderm filesystem? In a different folder?

Also, would there be a one->one mapping of pachyderm repos to git repos containing the pipelines?

Or would you have one git repo of pipeline files for `n` pachyderm repos?

**Comment by jdoliner** [comment]
Yeah, `project` would correspond to a git repo, and have a name that makes sense to you. So for example if I'm working on analyzing political speeches my git repo might be called `speech-analysis`.

I like to mount the pachyderm filesystem on `~/pfs`, so in a different folder.

Having many pipelines / pachyderm repo in the same git-repo is probably the way to go. You normally need several pachyderm repos and pipelines to do something interesting and keeping them all in separate repos would quickly get unwieldy. Especially because the pipelines need to match, in the sense that what one pipeline outputs others must be able to consume. That could get tricky if things are spread across multiple repos.

**Comment by ShengjieLuo** [comment]
A little supplement for Jdoliner's statement. I think that @rexmortus wonders where the data file is stored, or where the file system is mount, in Pachyderm. I recommend you to read my issue #780 to help understand the structure of Pachyderm if it is necessary. A refactor would be finished in v1.2.0 to correct the problem.  A small advice that you can divide you issue into several parts, and each part can be related to one specific topic with some running results. It would be helpful for us to understand your problem.
