### ISSUE TITLE
Feature request: safely un-mount pfs

### ISSUE THREAD

**Issue by rexmortus** [pachyderm/pachyderm#815]
Hello again gentlefolk! :heart: 

Presently, `pachctl` provides `mount` which mounts the pachyderm filesystem. :ok: 

When you're ready to un-mount pfs, it might be a nice feature (in particular, for those less-experienced with *nix) for `pachctl` to provide a "safely" `un-mount` pfs command.

Of course we can use `fusermount -z` or `umount`, but I imagine that some undefined slice of potential users won't know much about mounting/unmounting filesystems, let alone how to interpret such messages as:

```
ls: cannot access pfs: Transport endpoint is not connected
```

**Comment by JoeyZwicker** [comment]
+1 I even struggled with this a bit last week and I work here.

**Comment by rexmortus** [comment]
Also, a secondary :question:

What would happen if you mounted `pfs` to multiple locations?

Even if there wasn't a particular problem with it, should `pachctl` allow it (for reasons of it being ultimately un-necessary and potentially confusing)?

**Comment by jdoliner** [comment]
I think there's 2 things worth doing here.

- The best pattern for unmounting is to just CTRL-C the mounting process. In 1.1 `pachctl mount` would just silently block, what if in 1.2 we made it print out "Filesystem mounted, CTRL-C to unmount." This would nudge people toward what I think is the most intuitive control scheme.

- We could also add a command `pachctl unmount` (maybe `umount` will be an alias) which unmounts existing pfs mounts. It seems like between these 2 things most users will be able to figure out how to unmount.

Do people feel like that would address the concerns in this issue?

Mounting pfs to multiple locations is currently possible and I think it's reasonable to allow that because not all pfs mounts are necessarily the same. `pachctl mount` accepts a variety of flags and it's possible to have 2 different pfs mounts that include completely different data sets, have different caching properties etc.

**Comment by jdoliner** [comment]
Also for a little history on where the term `umount` comes from check here: http://unix.stackexchange.com/questions/9832/why-is-umount-not-spelled-unmount. Kind of fun read.

**Comment by rexmortus** [comment]
@jdoliner I like those suggestions! :+1: 

Additionally, if you wanted to background the process perhaps you could do so with a flag `--daemonize` or some shit, which prints a message like:

```
running in the background - use pachctl unmount to un-mount
```

Thanks for clarifying about multiple pfs mounts. I imagine that I'll need that before long.

**Comment by jdoliner** [comment]
I'm down with a `--daemonize` flag in theory. However from what I understand it's actually nontrivial to do this in go (fork doesn't work). So we'll need to see what our options are, it looks like there is some hope though: https://github.com/sevlyar/go-daemon

**Comment by sjezewski** [comment]
stale
