### ISSUE TITLE
Tech support!

### ISSUE THREAD

**Issue by rexmortus** [pachyderm/pachyderm#817]
Sorry for the noob tech support question. I'm just confused:

A simple grep should... work?

```
{
  "pipeline": {
    "name": "landmarks_and_places_of_interest_filtered"
  },
  "transform": {
    "cmd": [ "sh" ],
    "stdin": [
      "grep \"Places of Worship\" /pfs/landmarks_and_places_of_interest/data > /pfs/out/places_of_worship"
    ]
  },
  "parallelism": "1",
  "inputs": [
    {
      "repo": {
        "name": "landmarks_and_places_of_interest"
      },
      "method": "map"
    }
  ]
}
```

Produces this result:

```
ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"landmarks_and_places_of_interest_filtered"},"id":"0c14c57f44844a7b9f4dcde9aab4d782"}},"repoAlias":"out","write":true},"name":"places_of_worship","err":"no such file or directory"}
0 | Error from exec: exit status 1
```

It seems like `write: true` and `no such file or directory` are at odds.

What is going on here? :tongue:

**Comment by JoeyZwicker** [comment]
hey @rexmortus I'm also going to add you our users slack channel so you can reach us more directly there for help.

**Comment by jdoliner** [comment]
This all looks reasonable to me. That "error" is actually total benign. Before the OS attempts to write a file it checks to see if the file exists to make sure it's not a directory or something that would cause the write to fail. NotFound gets logged as an error but in this context that "error" means you can proceed with the write. In 1.2 we've silenced this particular error because it confuses people.

So that's probably not why it's failing, let's see if we can figure out why that is. Grep has the somewhat annoying behavior that if it doesn't find any matches it returns with error code `1` is it possible that, that's what's happening here?

**Comment by rexmortus** [comment]
Thanks @jdoliner I'll check it out a bit later on.

Quite possible. But... it really shouldn't be returning 1. Locally this produces the desired outcome.

If my `pfs` looks like this:
```
~/pfs/landmarks_and_places_of_interest/569c644fef224bef86fc81aedab4cfef/data
```

And my job looks like this:

```
"grep \"Places of Worship\" /pfs/landmarks_and_places_of_interest/data > /pfs/out/places_of_worship"
```

Am I doing it right?

**Comment by jdoliner** [comment]
Looking at grep's docs [here](https://www.gnu.org/software/grep/manual/html_node/Exit-Status.html) it seems a return code of `1` means that no lines were found. You probably just want to silently swallow this error since outputting nothing is a reasonable thing to do in that case. You can do this by adding `"acceptReturnCode": [1]` to your transform.

If that grep command finds stuff on your local setup but not in the cluster then maybe there's a parsing issue that's going on. What happens if you run a pipeline with:

```
  "transform": {
    "cmd": [ "grep", "Places of Worship", "/pfs/landmarks_and_places_of_interest/data" ],
  },
```

Or maybe just try:

```
  "transform": {
    "cmd": [ "cat", "/pfs/landmarks_and_places_of_interest/data" ],
  },
```

as a sanity check.

Neither of these commands will output anything since they don't write to /pfs/out. But their logs should help you with debugging.

**Comment by rexmortus** [comment]
Excellent suggestions @jdoliner, about to step out for Saturday's shopping but let me say I appreciate the lengths you're going to.

I'll report back later.

**Comment by rexmortus** [comment]
Another question.

When a pipeline fails like this, what is your procedure for "pushing a fix"?

Right now, I'm just deleting the pipeline and associated repo and starting again. Which seems kinda noob.

**Comment by jdoliner** [comment]
Thanks! We appreciate your patience with our rough edges.

We have `pachctl update-pipeline` for that, it works just like `create-pipeline` but the pipeline can already exist :). It's not present in 1.1 but it's in master and is going to ship in 1.2 in a week or so.

**Comment by rexmortus** [comment]
@jdoliner yep, it definitely a parsing issue. At some point I'll look into the code and see what's happening under the hood... I imagine that infracoder-type people are used to writing shell scripts inside JSON configs... but not me. :stuck_out_tongue: 

FWIW, this is what worked for me in the end:

```
{
  "pipeline": {
    "name": "places_of_worship"
  },
  "transform": {
    "cmd": [ "sh" ],
    "stdin": ["grep \"Place of Worship\" /pfs/landmarks_and_places_of_interest/data > /pfs/out/places_of_worship"],
    "acceptReturnCode": [1]
  },
  "parallelism": "1",
  "inputs": [
    {
      "repo": {
        "name": "landmarks_and_places_of_interest"
      },
      "method": "map"
    }
  ]
}
```

The job succeeds and I can read the resultant data. :heart:  

I just now realized that the idea is for my to define multiple transforms in a single pipeline file.

Now that I've cracked writing pipeline configs, shit is about to get interesting. :raised_hands: 

God this is exciting.
