### ISSUE TITLE
Run production workload before releases

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#892]
There have been instances where seemingly obvious bugs were discovered in production after a release.  There are several reasons why this happens:
- Certain parts of our code are simply not covered by any tests.  Notably they include: pachctl, GCS storage backend, AWS stroage backend.
- Integration tests still pale in comparison to production workloads in terms of scale and complexity.

I propose that, before each minor/major release, we run a real production workload against pachyderm in a real cluster (GCS/AWS).  That should catch most of the bugs that would otherwise be discovered by users in production.

**Comment by jdoliner** [comment]
I agree, although I think this should be an automated part of tests rather than something that we do manually.

**Comment by derekchiang** [comment]
Yeah the reason I don't want it to be part of CI is that it can take a while to run a production workload and I don't want that to slow down our dev process.  But I do very much agree that it should be as automated as possible.  It can also run asynchronously with regard to CI.

**Comment by sjezewski** [comment]
I think 

- [the CLI test harness](https://github.com/pachyderm/pachyderm/issues/710)
- and [the object store test harness](https://github.com/pachyderm/pachyderm/issues/648)

will take some real big bites out of what you're looking for.

So lets figure out what remains to be tested that we'd like to see. It sounds like what you want to see is some real amount of load on the system. 

I think the simplest approach would be getting in the habit of writing tests like [this one](https://github.com/pachyderm/pachyderm/blob/master/src/server/pfs/fuse/filesystem_test.go#L746)

- As written, as a 'failing test' it's scaled in such a way that it overloads the server's capabilities. Specifically, so much so that we cause a test to timeout.
- Once fixed however, the system can handle the amount of scale supplied in the test with no problems.

What's interesting though, is how that scale changes. For this test (I think ... it may have been `TestBigWrite` or `TestATonOfPuts`) we ended up throttling the test down so that the refactor wouldn't hang. That information isn't really captured anywhere!

This starts to matter once we care about the degree of scale, and the tradeoffs we're making. I can see how it would be helpful to have a benchmark suite to test many aspects of the system (e.g. Read speeds, Write speeds, Deletion speeds, best / average / worst case workloads, jobs that require resources that are correlated to data input size, jobs that don't, etc) to be able to get a snapshot of the system.

But I'm wary of building that without clear goals. I think that would be a great tool for us to:

- understand the system's ability to scale and the 'shape' of that scale
- internally make design decisions about scaling and tradeoffs
- be rigorous about our performance at scale release over release

**Comment by sjezewski** [comment]
duplicate
