### ISSUE TITLE
More ways to specify images

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#896]
Right now there's a couple of ways that you can get your container image into Pachyderm. You can host it on a public registry ,and kubernetes will automatically pull in the image when a pod gets scheduled, or you can have the image already be present on the docker host. The latter being mostly used by us for development.

I think we can make this simpler with a few things:
- run a registry within the k8s cluster, this allows us to build images within the cluster and have them available on every node without having to worry about creds or anything. It should also be quite easy, [this guide](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry) seems like a good starting point.
- Extend our api to allow specifying images in more ways, building directly from a git repo is one idea, embedding Dockerfiles directly might be another although it remains to be seen how you'd actually get your code inside an image like that.

**Comment by derekchiang** [comment]
I think this issue was fixed and then subsequently unfixed.  We added an in-cluster registry and a way to push images to the said registry (via `create-pipeline --push-image`), then we decided that it's not as useful as we thought, so we removed it.

Am I summarizing this correctly?  @jdoliner 

Feel free to reopen if it's still an issue someone wanna fix.

**Comment by JoeyZwicker** [comment]
I dont think it was because an internal registry wasn't useful, but that
security for it is annoying enough right now that it's not really a viable
option. Anyway, the reason doesn't matter, just wanted to clarify the info
in this issue for when we come back to this later because an internal
registry is probably something we may eventually want.

**Comment by jdoliner** [comment]
This issue is a lot more about the second part than the first. Being able to specify your images directly from a git repo. That's a feature I'd still like to find a way to implement if possible although it's unlikely to make 1.3 so I'm going to reopen this and move it out of the milestone. The fact that internal registries aren't usable makes this tough. Likely we'll have to give users a way to specify which registry they want to use in the cluster and specify credentials for it.

> I dont think it was because an internal registry wasn't useful, but that
security for it is annoying enough right now that it's not really a viable
option.

This is nonsensical it wasn't viable precisely because it wasn't useful. If it'd been useful then more or less by definition it would have been viable.

**Comment by jdoliner** [comment]
Closing for the same reasons as #835 was closed. A registry within a cluster is probably just untenable from a security perspective, and most users already have an existing workflow for deploying images that we shouldn't get in the way of.
