### ISSUE TITLE
Benchmark infrastructure

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#899]
See #898 for background.

We want to be able to run benchmarks as easily as possible, so it's easier for developers to keep track of the performance variance caused by their code.  That entails some form of automation: ideally, it will just be a button click or a script to run.

We also want the benchmarks to run in a realistic environment, i.e. GCE with GCS buckets, or AWS with S3 buckets.  That means that we don't want to naively use CI (which just runs in a single under-powered VM) to run the benchmarks directly.

**Comment by jdoliner** [comment]
Moving this to 1.3 milestone.

**Comment by jdoliner** [comment]
@derekchiang you're actively working on this right? I'm adding you as the assignee assuming that's true.

**Comment by derekchiang** [comment]
Here is a proposal for how the infrastructure might look like:

First, we create a GCE or/and AWS cluster that's shared among Pachyderm committers.

Second, we write a script that does the following in order:

1. Check if there's already a benchmark running on the cluster.  If so, prompt the user to see if they want to kill the running benchmark.  We only want one benchmark to be running at a time because we don't want multiple benchmarks to interfere with each other.
2. Build the pachd and job-shim images locally.
3. Push the images to some personal/private repos on docker hub.  The specific repos will be specified via environment variables.  For instance, I might push them to `derekchiang/pachd:latest` and `derekchiang/job-shim:latest`.
4. Generate a manifest that refers to the private images.
5. `make launch`: launches Pachyderm on the cluster
6. `make bench`:  creates a kubernetes job that runs the benchmark.
7. Report benchmark numbers.
8. `make clean-launch`: removes Pachyderm from the cluster.

The script assumes that your kubectl has been authorized to talk to the GCE/AWS cluster, and that your docker has been authorized to push to the private repos of your choice.

So, ideally, a developer will just need to run the script to benchmark Pachyderm in a real cluster.

**Comment by jdoliner** [comment]
I agree with most of this but I don't like the idea of having a single cluster for the company that needs to be maintained. It seems too much like a big pet and it's a serious pain to have to check with others before running your benchmarks. How hard would it be to make it so that cluster turn up and turn down is automated to the point where people can just create a new cluster when they want to start benchmarking? It seems like that would make things easier. Limiting ourselves to GCE for now will probably make this a bit easier since they have GKE which should make spinning up a cluster pretty painless.

**Comment by sjezewski** [comment]
That sounds good, but I have a request:

I want a way to record the results of the benchmark

So that in the future when we say "We ran a benchmark testing heavy writes ... and it performed well" we know exactly what was tested, and what 'well' means, so that it's repeatable. It would be super great if we could use this information to configure and re-run a benchmark. But at the very least, we should record enough information so that we can manually re-create it. Maybe this 'benchmark report' isn't done every time you run a benchmark. Maybe its a totally manual process. But I think getting most of this info is pretty easy to automate and would make the benchmark results salient in the short term and long term.

I think the following information is necessary:
  - the images being used (great that you're already setting up a registry / private DH acct ... can just be an image hash)
  - the pipeline(s) manifests (if any) being used ... and if they're not ... any pachyderm specific config (e.g. # nodes, size of storage for rethink, etc)
  - if pipeline(s) aren't used directly, then a reference to the exact code being run (maybe its an image, maybe just a commit hash and golang benchmark name a la `BenchmarkManyWrites` (which refers to the `BenchmarkManyWrites(b *testing.B){}` function in the code)
  - the state and scale of the cluster
    - AWS vs GCE
    - k8s version
    - docker version
    - number of VMs
    - shape of VMs (esp if they're heterogeneous)
    - any other relevant config (e.g. k8s auto-scaling flag)
  - the results of the benchmark
    - total run time?
    - the metric may depend on the thing we're measuring. E.g. for heavy writes we probably care about writes per second
    - we may also want to record other health stats (as soon as we have them) about performance. Things like:
      - CPU used per VM (cpu graph over the timespan of the benchmark)
      - mem usage (again over timespan of benchmark)
      - I/O (local disk and network)
      - other pachyderm specific stats we're going to add

**Comment by jdoliner** [comment]
@sean recording this stuff is definitely important but I think most of this stuff should be recorded by git rather than another system. Given a commit hash that a benchmark was run at I should be reconstruct:

- the images, by running `make docker-build` and seeing what I get
- the pipeline manifests, since all the assets for running benchmarks should be under version control. Or other code needed for the benchmark.
- The benchmark cluster, since the scripts used for cluster turn up and turn down should all be under version control as well.

Recording the results of the metrics does make sense, I think we could write a simple reporting tool that just gave you plain text output with the runtime and other metrics we care about. These reports would provide all the context one needs to understand them and would be pretty easy to send to each other over slack, store in git or on the web if we wanted a record of them. Etc.

**Comment by sjezewski** [comment]
That makes sense, and I think text and git are adequate output and storage mediums.

I'm assuming in that case the amount that we scale the VMs in the cluster we generate is hardcoded into the script (and you commit each change you make). I think there will be cases where we want different size and shaped clusters. But we can cross that bridge once we get there.

**Comment by msteffen** [comment]
SGTM. I mostly agree with JD's response, that ideally we shouldn't have to check in with each other before running benchmarks. We should maybe also agree on where we want to keep results (just checked into git? A spreadsheet?) to make tracking our progress and comparing changes easier.

One thing that might be good (depending on how long the benchmark takes) would be to run the benchmarks several times and record a distribution of runtime. Benchmarks can often be very uneven, and knowing that e.g. our average benchmark time is X but 5% of the time is 10X (because e.g. fuse really cares about the order that certain events happen) seems potentially valuable me.

We should maybe also be aware of the cost of running these benchmarks? I don't know how expensive GKE CPUs are, but maybe that'll add up?

**Comment by jdoliner** [comment]
Yeah, I think what we'll want to do is develop a standard set of benchmarks and a standard set of environments. So our benchmarks might be 10G-wordcount, 100G-wordcount and 1TB-wordcount and our environments might be 10Node-n1-standard-16, 100Node-n1-standard-16 and 1000Node-n1-standard-16. Then we could talk about the performance of 100G-wordcount on 10Node-n1-standard-16 and everyone would be on the same page pretty quickly.

**Comment by jdoliner** [comment]
Also cost is worth keeping in mind, right now we still have quite a few GCP credits so you can just go nuts. But those are going to run out soon and then we'll need to start thinking about managing our compute instances because it can add up quite quickly. That's probably another argument for making cluster turn up and turn down as painless as possible. It'll give people less reason to keep clusters running over night when they're not using them.

**Comment by derekchiang** [comment]
I think everyone brought up some good points.  Taking these points into consideration, how does this sound:

The script takes the following parameters:

* A regex expression that specifies the benchmarks you want to run.  This regex expression will just be passed to `go test` verbatim.  Defaults to `*`, meaning running all benchmarks.
* The cloud provider to use.  Defaults to GCE.
* The number of nodes to spawn up.  Defaults to 4.  Each node will also default to some reasonable specs such as 4 vCPUs and 16GB memory.
* The number of times the benchmark should be run.  Defaults to 1.
* Names of the private repos to use, e.g. `derekchiang/pachd:latest`.  No default.

Then, the script does the following:
 
1. Build the pachd and job-shim images locally.
2. Push the images to the specified private repos on dockerhub.
3. Generate a manifest that refers to the private images.
4. Launch a GCS/AWS cluster.
5. Launch Pachyderm on the cluster.
6. Create a kubernetes job that runs the benchmark.
7. Record the performance numbers.
8. Delete the cluster (including the bucket).
9. Repeat step 4 to 8 N times, where N is the number of times the user wants to run the benchmarks.  By relaunching the cluster, we ensure that the benchmarks always start from a clean state, e.g. no pre-existing blocks, etc.
10. Generate the final report.  This report should include not only the performance numbers, but also the parameters that the script started with, e.g. number of nodes, node specs, etc.

**Comment by jdoliner** [comment]
Sounds pretty reasonable.

Go benchmarks actually have built in iterations exposed on the [`testing.B`](https://golang.org/pkg/testing/#B) object as a field called `N`. You should look into how that works before implementing stuff for yourself.
