### ISSUE TITLE
Most links in this document seem to be broken

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#913]
The document: https://github.com/pachyderm/pachyderm/blob/master/doc/pachyderm_pipeline_system.md

Curiously, the links on the corresponding readthedocs page are not broken: http://pachyderm.readthedocs.io/en/latest/pachyderm_pipeline_system.html

On a cursory look, seems like the reason the links are broken on Github, is that the links use the `.html` suffixes, while the documents are actually of `.md` or `.rst` format.  I'm not familiar with our readthedocs infrastructure, but surely there's a way to have working links on both Github and readthedocs?

Might be worth looking into if other pages have similar problems.

@JoeyZwicker @sjezewski

**Comment by JoeyZwicker** [comment]
This is actually a bit tricky and a solution isn't immediately obvious to me. These docs are not technically meant to be read on Github as all the links [here on the docs portal](http://pachyderm.readthedocs.io/en/latest/pachyderm_pipeline_system.html) work fine.  

One solution would be to hardcode in the urls instead of having them be relative links. We'd lose RTD's link-checking if we did that. Also, our other docs on GH have links that don't really work too, we just "intercept" users with a README sending them to our docs portal before the navigate there. We can hide the PFS/PPS docs in a folder and do that same if that'd be better. What do you think @derekchiang ?

**Comment by jdoliner** [comment]
A good stop gap measure might be to just put a header at the top of each doc with a link to the doc on RTD saying: "This documentation is meant to be read at: ____."

**Comment by JoeyZwicker** [comment]
But than that header shows up on the RTD site, which looks kinda dumb. But
yeah, it's an easy stopgap.

**Comment by derekchiang** [comment]
@JoeyZwicker I agree that if the docs are not meant to be read on Github, then they should probably be less discover-able.  When I try to find the docs for a Github project, the first place I look at is usually the `doc/` directory.  I'm not really sure where we should hide it though.

**Comment by JoeyZwicker** [comment]
I think we have a plan for this. We're going to add a new folder to contain those top-level docs and a readme for each directory that pushes people off of GH to RTD instead.

**Comment by dwhitena** [comment]
Not relevant at the time being until PPS and PFS docs are re-done.  Tracked here: https://github.com/pachyderm/pachyderm/issues/1869

**Comment by JoeyZwicker** [comment]
We accidentally still link to them on the getting_started page -- we should fix that since the docs aren't done yet.

**Comment by dwhitena** [comment]
@JoeyZwicker adding to the 1.5 check list.
