### ISSUE TITLE
Expose Garbage Collection / Total Block Annihilation of Object Stores 

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#914]
We saw a user in #users channel have a good use case around this.

He was unable to run pachd / pipelines because he ran out of disk space. The symptom was pods stuck in 'pulling' state and upon describing reported `no nodes available to schedule pods`. This was because the disk was full and k8s couldn't schedule any more pods.

He had a 40GB disk. Pachyderm images could account for a few gigs.

However, he had some big files. And he was running `pachctl delete-file` between launches while trying to get this working. Because we don't garbage collect the raw blocks (on any object store), his disk filled up between launches / runs.

It would be helpful to have something like `pachctl garbage-collect-blocks`. The local use case is obvious - delete the local files. Not sure what happens when you're connected to a real object store. We know that S3 rate limits, and since there could be quite a lot of data there, this could take a long time. Maybe after you enter the command you see a prompt like:

```shell
$ pachctl garbage-collect-blocks
There are 34.GB of block data that can be garbage collected. This task may take a while. Do you want to proceed? Y/n
```

As well as reporting some percentage value so the user gets _some_ feedback about the progress.

**Comment by jdoliner** [comment]
I don't think I agree with this approach to garbage collection.
Garbage collection should be something that happens transparently when things are deleted, not something that the user has to initiate for themselves.
This issue also doesn't contain much in the way of details about what the semantics of `pachctl garbage-collect-blocks` would be. The local use case isn't so obvious to me. Does it just delete all local blocks regardless of if they're referenced or not or only unreferenced blocks?

I'm going to close this because we already have #626 and that has more details. Feel free to weigh in on that one.
