### ISSUE TITLE
The size of log files becomes gigantic after a few days

### ISSUE THREAD

**Issue by willguxy** [pachyderm/pachyderm#957]
Hi,

I have Pachyderm set up and running for about two days on a AWS machine. This machine has about 40G in space. When it started in the first place, the usage ratio of disk space is < 20%. But when I check the space again, it's almost full after two days of running. During the past 2 days, I only ran some small job and have generated a couple of hundred MB of data. This has happened in the past and I noticed that when space is drained up, the services would enter into a weird state and the only way to solve that problem is to blow away the whole cluster and redeploy.

Here are some details,

```
-rw-r----- 1 root root 14G Oct  7 15:27 /var/lib/docker/containers/f642f59852b1bd56a839f369b73ae55b4cd98ef1a6a6d8520d050a062eadd13c/f642f59852b1bd56a839f369b73ae55b4cd98ef1a6a6d8520d050a062eadd13c-json.log
-rw-r----- 1 root root 14G Oct  7 15:27 /var/lib/docker/containers/e292b786902ab30fd6066cc2b46875a1a3e3ce30f7951fb5c697051d7c66318d/e292b786902ab30fd6066cc2b46875a1a3e3ce30f7951fb5c697051d7c66318d-json.log
```

I believe the above logs belong to the following docker containers `pachd` and `hyperkube`

```
CONTAINER ID        IMAGE                                                        COMMAND                  CREATED             STATUS              PORTS               NAMES
f642f59852b1        pachyderm/pachd:local                                        "/pachd"                 2 days ago          Up 2 days                               k8s_pachd.e8916dab_pachd-z5zaq_default_3fc491fc-8a59-11e6-b890-0e84a6c9a22d_bc75b660
e292b786902a        gcr.io/google_containers/hyperkube:v1.3.5                    "/hyperkube kubelet -"   2 days ago          Up 2 days                               pedantic_shannon
```

I understand that more verbose logs help with debugging your code. But would it be possible to let user change the verbosity? I'm not sure if the logs are rotating at this point (or at what frequency), but tens of gigs of log files isn't very useful in my current case.

Please advise. Thank you.

**Comment by willguxy** [comment]
After some digging, I realized that this issue is probably because k8s couldn't clean up the orphaned pods, and it just keeps trying infinitely. The log of `hyderkube` contains all the things like `Failed cleaning pods` and 
```
Failed to remove orphaned pod "a99fc0eb-8699-11e6-b9ea-0e84a6c9a22d" dir; err: remove /var/lib/kubelet/pods/a99fc0eb-8699-11e6-b9ea-0e84a6c9a22d/volumes/kubernetes.io~secret/default-token-64z4a: device or resource busy
```
Previously when parallelized pachyderm job fails partially, I deleted the pipeline and tried to delete the pods, too. I ran `kubectl delete pod/<pod-id>` but it didn't work. I added `--grace-period=0` to it and it worked. But the `job-shim <job-id>` docker containers was still running, and I couldn't stop them. So I had to restart docker service and remove afterwards. 

I think at some point my behavior caused orphaned pods.

**Comment by sjezewski** [comment]
An update from our triaging late last week --

@willguxy was able to show me some logs during which time he was not initiating any requests to the cluster.

Those logs indicated that pipelines were trying to create jobs, failing, and backing off. The other API calls (e.g. `ListCommit` and `InspectRepo`) were symptoms of this pattern. The pipelines will back off when attempting to start a job, but eventually this would fill the disk.

We do see an error a la:

```
error from InspectJob: gorethink: dial tcp 10.0.0.148:28015: getsockopt: connection refused
```

Which suggests that we cannot connect to rethinkdb. At this point, we suspect this as the root cause. If we cannot connect, job creation will never work, and logs will pile up and accumulate. This will exhaust resources in this deployment.

In general, that shouldn't be the case. I know k8s / GCP integrate nicely to do log rotation, aggregation, etc to report to a UI on the GCP console. I'm not as familiar w the AWS config, but I'd bet that they have some similar configuration options.

**Comment by sjezewski** [comment]
We now have a 'make launch-logging` task that will spin up the EFK stack (fluentd aggregator, elastic search backend + index + serving, kibana frontend) for log aggregation. If your logs are taking up a lot of space, we recommend spinning up that service.
