### ISSUE TITLE
Use Kubernetes anti-affinity feature to spread pods across nodes

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#971]
If I understand [this feature](http://kubernetes.io/docs/user-guide/node-selection/#inter-pod-affinity-and-anti-affinity-alpha-feature) (added in Kubernetes 1.4, currently in alpha) correctly, it's possible to have Kubernetes try to schedule pods across nodes as evenly as possible, which sounds like what we want for PPS jobs.

Like right now, even if you have parallelism N and you have M nodes, and M > N, there's no guarantee that you actually get one pod per node.

**Comment by derekchiang** [comment]
That's a good point.  Also can confirm that you can force Kubernetes to schedule one pod per node by messing with CPU/MEM quotas.  Although this approach can get tricky if you have a heterogeneous cluster.

I was also looking into [Daemon Sets](http://kubernetes.io/docs/admin/daemons/) which runs one pod per node for long-running services.  If PPS ever moves into a model where we have "worker" pods requesting work (as opposed to PPS scheduling jobs directly), then it will be pretty easy to run the workers as a daemon set, and we will be able to enforce that jobs are spread across nodes as well.

**Comment by jdoliner** [comment]
> Although this approach can get tricky if you have a heterogeneous cluster.

I actually think that's one of the advantages of using CPU/MEM quotas. Kubernetes detects how many CPUs and how much memory each node has and uses it to make scheduling decisions. So heterogeneous clusters should work well. Daemon Sets, on the other hand do not seem well suited to a heterogeneous cluster.

**Comment by derekchiang** [comment]
I thought by using CPU/MEM quotas you meant something like, if all your nodes have 4 CPUs, then you can ensure that each node gets at most 1 pod by requesting 4CPUs for each pod.  How would that work when you have a heterogeneous cluster?  Like if you have 1 node with 2 CPUs and another with 4CPUs, how would you use CPU quota to deploy 1 pod per node?

**Comment by jdoliner** [comment]
It'd be tricky to get 1 pod per node in that case but I'd argue that's because 1 pod per node isn't the right goal in a heterogenous cluster. If every job were to schedule 1 pod per node then the 2 cpu node would become the bottle neck for every job. Performance wise your cluster would effectively be a cluster of 2 CPU nodes.
I'm not advising that we use CPU quotas as a way to force pod spreading, we should have users set their CPU quotas to accurately reflect how many cores their job can utilize and then let k8s make scheduling decisions based on that. There will be times when this doesn't translate into 1 pod per node and that's fine because in many real cases that'll be more efficient.

**Comment by sjezewski** [comment]
We have cpu/mem requests in place now, so I think this accomplishes what we wanted here.
