### ISSUE TITLE
Run pachd as a daemon set

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#972]
Right now we run pachd using a [replication controller](http://kubernetes.io/docs/user-guide/replication-controller/), which requires us to specify a replica number.  Users with big clusters are expected to change this replica number to a higher value by modifying the kubernetes manifest.

Is there any reason why we don't want to run pachd as a [daemon set](http://kubernetes.io/docs/admin/daemons/), which ensures that one copy of pachd is running on each node?  Especially considering that PFS and PPS are both horizontally scalable.

Here's a problem I see with running pachd using a replication controller.  Let's say we have 2 nodes and we are running 1 replica of pachd.  Now, let's say that my `pachctl` is connected to the node that **does not** have the replica running.  Now, the node I'm talking to will basically serve as a proxy; the traffic needs to flow from the actual pachd replica to this node I'm talking to before it can reach me.  If we run pachd as a daemon set, this won't be a problem.

Actually now that I think about it, could this be related to #930?  @msteffen

**Comment by jdoliner** [comment]
There are a bunch of reasons not to run pachd as a daemon set:

- Daemon sets are less flexible than rcs, they cannot be updated.
- They're much more unwieldy, if a user has a 1000 node cluster and they just want to try pachyderm they'll wind up deploying 1000 containers. That takes longer, consumes more resources and will probably annoy people.
- if it's a heterogeneous cluster or, if one of the nodes is oversaturated users might randomly get very bad performance. That's because by using a daemon set, we force k8s to schedule pachd even in places that it otherwise wouldn't due to cpu/mem constraints. Any clients that connect to those pods will get really bad performance.
- Replication controllers support [horizontal auto-scaling](http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/) which scales the number of replicas based cpu metrics from the pods. That sounds like a dream setup for an ops team to me.

Also I'm not sure if I agree with the premise here, the path of least resistance for connecting to pachd is to type `pachctl port-forward &` which will automatically connect you to a node that does have a pod running. Furthermore k8s can be made to deploy load-balancers for Services which I think give pretty good performance if users need to do more serious ingress traffic.

Look into horizontal pod autoscaling. That is a newer k8s feature that I think could help us. Also checkout [replica sets](http://kubernetes.io/docs/user-guide/replicasets/), and [deployments](http://kubernetes.io/docs/user-guide/deployments/) those are the new primitives that caught my eye as a potential improvement to how we deploy pachd.

**Comment by derekchiang** [comment]
Good points!  The third point especially sounds like a deal breaker.

Gonna close this issue for now.
