### ISSUE TITLE
FlushCommit should return successfully finished commits even when some commits are cancelled

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#985]
Imagine the following provenance structure:

```
A -> B -> C -> D
```

Currently if C is cancelled, when you `FlushCommit(A)`, you get an error saying that C is cancelled.  Ideally, you should also be notified that A and B have been successfully finished.

Or this structure (fan-out):

```
  A
/ | \
B C D
```

Again, if C is cancelled and you `FlushCommit(A)`, you are only told that C is cancelled.  Ideally you should also be told that B and D have been successfully finished.

**Comment by derekchiang** [comment]
Also, if there are more than one cancelled commits in the fan-out case, we should report all the cancelled commits.

**Comment by brendanacassidy** [comment]
Also, it should block until all consequences have finished: in the event of a combination of some successful commits and some errors leading to cancelled commits, it should not return immediately upon encountering an error but should block until everything has flushed.

**Comment by jdoliner** [comment]
Definitely understand the use case here and think it's a good thing to address.
I have some questions about the implementation though, afaik it's not possible to return an error and a response from a grpc call. It'll only serialize one of those things. So it seems like the only way to get `FlushCommit` to behave like this would be to make it never error. That would definitely cause problems with some of the ways we're using `FlushCommit` internally and also seems like it might be a slightly weird set of semantics. I'm wondering if maybe this issue should be about introducing a different API call that does what we want rather than about extending `FlushCommit`. Or maybe we can just add a flag to `FlushCommit` that does what we want. Interested to hear what others think.

**Comment by brendanacassidy** [comment]
For FlushCommit to error when there's a downstream error seems to make sense. However, if it's not a fatal error with regards to executing the flush (like a network error), then it shouldn't return with the error until all downstream consequencies have terminated, whether they are successful or not. In other words, if it can flush, it should flush.

As far as how to discover the failure(s), that could be through the same API (maybe with a flag that lets you either return only successful commits, or return all commits in order look through them to discover their statuses) or could be through a different API.

**Comment by jdoliner** [comment]
@brendanacassidy thanks for clarifying, very helpful. I think what you've said totally makes sense. Flush returning should indicate that everything that's going to run due to the commit set has. That fits well with the semantics we already have and shouldn't be too hard to incorporate.

**Comment by JonathanFraser** [comment]
I'm going to jump in here and say that it might make sense to separate errors which occur in the pipeline from errors that occur during the flush. Leave the error value for GRPC for cases when the flush call itself fails due to network issues or the commit not existing....etc. Have the actual response contain two sets of data one of successful commits and another of failed commits and their associated errors.  This allows for differentiated errors with pipeline and other errors as well as provides a mechanism for displaying more that one error in the pipelines.

**Comment by sjezewski** [comment]
I believe this is solved w the upcoming 1.7 model. `flush-commit` blocks until commits are finished, and even failed jobs will finish commits.
